const en = {
  app_name: 'Super Customer App',
  greeting: 'Good Morning 👋',
  greeting_morning: 'Good Morning 👋',
  greeting_afternoon: 'Good Afternoon 👋',
  greeting_evening: 'Good Evening 👋',
  home_question: 'What are you looking for Today?',
  home_title: 'Home',
  home_subtitle: 'How can I help you today?',
  special_offer_label: '10% off',
  special_title: "Today's Special",
  special_description: 'Get a discount for every service order!',
  special_note: 'Only valid for today!',
  special_percent: '30%',
  services_title: 'Our Services',
  open_button: 'Open',
  service_type_title: 'Service Type',
  recommended_title: 'Recommended For You',
  recommended_name: 'Premium Cleaning',
  recommended_name_secondary: 'Fast Electrician',
  recommended_rating: '4.8 | 1,500+ reviews',
  service_deliveries: 'Deliveries',
  service_home_visit: 'Home-Visit Appointment',
  home_visits_section_title: 'Home Visits',
  home_visits_section_card_title: 'Home-Visit Appointment',
  home_visits_section_description: 'Book trusted professionals for your home services.',
  service_general_appointment: 'General Appointment',
  service_ride_sharing: 'Ride Sharing',
  recommended_price: '${{price}}/hr',
  recommended_reviews: '{{count}}+ reviews',
  splash_title: 'Food Delivery',
  loading: 'Loading...',
  splash_progress: '{{value}}%',
  developer_mode: 'Dev Mode',
  developer_mode_subtitle: 'System tools & diagnostics',
  developer_mode_welcome: 'Welcome to Developer Mode. Additional diagnostic tools will be available here soon.',
  driver_profile_button: 'Driver profile',
  auth_flow_button: 'Auth flow',
  rider_chat_button: 'Rider chat',
  dev_auth_title: 'Auth Sandbox',
  dev_auth_description: 'Temporary signup + session tools for development.',
  dev_auth_mode_signup: 'Signup',
  dev_auth_mode_login: 'Login',
  dev_auth_phone_label: 'Phone',
  dev_auth_phone_placeholder: '+923001234567',
  dev_auth_otp_label: 'OTP',
  dev_auth_otp_placeholder: '123456',
  dev_auth_name_label: 'Name',
  dev_auth_name_placeholder: 'John Doe',
  dev_auth_password_label: 'Password',
  dev_auth_password_placeholder: 'password123',
  dev_auth_push_token_label: 'Device Push Token',
  dev_auth_push_token_placeholder: 'fcm-token-here',
  dev_auth_referral_label: 'Referral Code',
  dev_auth_referral_placeholder: 'REF123',
  dev_auth_send_otp_button: 'Send OTP',
  dev_auth_send_login_otp_button: 'Send Login OTP',
  dev_auth_verify_button: 'Verify OTP & Create User',
  dev_auth_login_button: 'Verify OTP & Login',
  dev_auth_logout_button: 'Logout',
  dev_auth_status_label: 'Session Status',
  dev_auth_status_user: 'User: {{name}}',
  dev_auth_status_working: 'Working on request...',
  dev_auth_status_otp_sent: 'OTP sent. Verify to complete signup.',
  dev_auth_status_verified: 'Signup verified. Session stored.',
  dev_auth_status_failed: 'Request failed. Check the error below.',
  dev_auth_status_signed_in: 'Session active.',
  dev_auth_status_signed_out: 'No active session.',
  login_to_continue: 'Login to Continue',
  login_to_continue_desc: 'Please log in to save your delivery details and ensure a smooth, secure checkout experience.',
  continue_with_phone: 'Continue with Phone',
  continue_with_apple: 'Continue with Apple',
  continue_with_google: 'Continue with Google',
  continue_with_email: 'Continue with Email',
  or: 'or',
  dont_have_an_account: 'Don’t have an account?',
  signup: 'Sign Up',
  continue: 'Continue',
  enter_your_phone: 'Log in easily by entering your phone!',
  login_desc: 'We’ll check if you have an account',
  verify_your_phone_number: 'Verify Your Phone Number',
  verify_otp: 'Verify OTP',
  enter_otp_sent_to: 'Enter OTP sent to {{contact}}',
  didnt_receive_the_code: 'Didn’t receive the code?',
  resend_in: 'Resend in',
  try_another_way: 'Try another way',
  resend: 'Resend',
  incorrect_code: 'The code you entered is incorrect.',
  get_started: 'Let’s get you started',
  get_started_desc: 'First, let create your account',
  create_account: 'Create account',
  name: "Name",
  email: "Email",
  password: "Password",
  sms_verification: "Send code by SMS",
  call_verification: "Send code by Call",
  email_verification: "Send code by Mail",
  too_many_attempts: "Too many attempts",
  too_many_attempts_desc: "We’ve temporarily locked further attempts to protect your account. Try again in 5 minutes.",
  ok: "Ok",
  enter_your_email: 'Log in easily by entering your email!',
  enter_your_password: 'Enter your password',
  email_already_exist: 'Your email already exist.',
  remember_me: 'Remember me',
  forget_password: 'Forget Password?',
  invalid_password: 'Invalid password',
  enter_correct_password: 'Please enter the correct password.',
  forget_password_desc: 'Enter your email and we’ll send an OTP to reset your password.',
  create_new_password: 'Create your new password',
  create_password_desc: 'Set a new password and confirm it.',
  enter_new_password: 'Enter new passsword',
  confirm_new_password: 'Confirm new passsword',
  set_new_password: 'Set new password',
  verify_your_email: 'Verify Your Email',
  enter_strong_password: 'Please enter strong password.',
  password_not_matched: 'Make sure your passwords match',
  something_went_wrong: 'Something went wrong.',
  location_popup_title: 'Location Access',
  location_popup_description:
    'Use device location to show nearby stores, delivery availability, and relevant offers.',
  location_popup_denied_title: 'Location Permission Denied',
  location_popup_denied_description:
    'Location access is still off. Allow it to show nearby stores and accurate delivery availability.',
  location_popup_blocked_title: 'Enable Location in Settings',
  location_popup_blocked_description:
    'Location access is turned off for this app. Open settings to allow location access on your device.',
  location_popup_enable: 'Enable Location',
  location_popup_try_again: 'Try Again',
  location_popup_open_settings: 'Open Settings',
  location_popup_later: 'Maybe Later',
  address_list_title: 'My addresses',
  address_add_title: 'Add address',
  address_edit_title: 'Edit address',
  address_search_placeholder: 'Search for an address',
  address_choose_on_map: 'Choose on map',
  address_recent_searches: 'Recent searches',
  address_no_results: 'No results found',
  address_confirm_location: 'Confirm location',
  address_locating: 'Locating…',
  address_selected_location: 'Selected location',
  address_location_name_placeholder: 'Location name (e.g. My home)',
  address_details_label: 'Address Details',
  address_location_type_label: 'Location Type',
  address_location_details_label: 'Location Details',
  address_home_details_title: 'Home Details',
  address_apartment_details_title: 'Apartment Details',
  address_office_details_title: 'Office Details',
  address_field_house_flat_number: 'House / Flat Number',
  address_field_apartment_flat: 'Apartment / Flat',
  address_field_area_street: 'Area / Street',
  address_field_society_building_name: 'Society / Building Name',
  address_field_company_building_name: 'Company / Building Name',
  address_field_floor_tower_optional: 'Floor / Tower (Optional)',
  address_field_floor_suite_unit_optional: 'Floor / Suite / Unit (Optional)',
  address_field_department_optional: 'Department (Optional)',
  address_field_landmark_optional: 'Landmark (Optional)',
  address_detail_house_placeholder: 'House',
  address_detail_apartment_placeholder: 'Apartment / Flat',
  address_detail_office_placeholder: 'Office / Building',
  address_detail_company_building_placeholder: 'e.g. ABC Technologies',
  address_detail_floor_suite_unit_placeholder: 'e.g. 2nd Floor, Suite 201',
  address_detail_place_placeholder: 'Place',
  address_detail_society_placeholder: 'Society',
  address_detail_floor_placeholder: 'Floor / Tower',
  address_detail_department_placeholder: 'Department / Floor',
  address_detail_area_placeholder: 'Area / Street',
  address_detail_landmark_placeholder: 'Landmark',
  address_optional_suffix: '(optional)',
  address_set_as_default: 'Set as default address',
  address_type_home: 'Home',
  address_type_apartment: 'Apartment',
  address_type_office: 'Office',
  address_type_other: 'Other',
  address_save: 'Save address',
  address_update: 'Update address',
  address_delete: 'Delete',
  address_delete_confirm_title: 'Delete address',
  address_delete_confirm_message: 'Are you sure you want to delete this address?',
  address_delete_cancel: 'Cancel',
  address_delete_confirm: 'Delete',
  address_save_error: 'Could not save address.',
  address_select_error: 'Could not select address.',
  address_delete_error: 'Could not delete address.',
  address_delete_linked_orders_error:
    'This address cannot be deleted because it is linked to existing orders.',
  address_save_success: 'Address saved successfully.',
  address_update_success: 'Address updated successfully.',
  address_delete_success: 'Address deleted successfully.',
  address_selector_title: 'Location',
  address_selector_close: 'Close location picker',
  address_selector_use_current_location: 'Use my current location',
  address_selector_add_new: 'Add new address',
  profile_personal_account: 'Personal account',
  profile_wallet_balance: 'Wallet Balance',
  profile_view_wallet: 'View wallet',
  profile_menu_profile: 'Profile',
  profile_menu_notifications: 'Notifications',
  profile_menu_favorites: 'Favorites',
  profile_menu_coupons: 'Coupons',
  profile_menu_settings: 'Settings',
  profile_menu_support: 'Support',
  profile_menu_color_mode: 'App color mode',
  profile_menu_language: 'Language',
  profile_menu_logout: 'Log out',
  notifications_title: 'Notifications',
  notifications_section_today: 'Today',
  notifications_section_past: 'Past',
  notifications_show_more: 'Show More',
  notifications_empty_title: 'No notifications yet',
  notifications_empty_description: 'You will see your latest updates here once they arrive.',
  notifications_today_appointment_title: 'Your appointment at Style Haven is confirmed and ready for you.',
  notifications_today_appointment_subtitle: 'Just a moment ago.',
  notifications_today_location_title: 'Your home clean is confirmed: Visit us at Style Haven.',
  notifications_today_location_subtitle: 'A few hours back.',
  notifications_today_payment_title: 'Payment received: QR 65.00 for your home clean at Style Haven.',
  notifications_today_payment_subtitle: "It's 8:19 PM, perfect time for a night out!",
  notifications_past_offer_title: 'Special offer: Enjoy 15% off your next two visits!',
  notifications_past_offer_subtitle: 'On Sep 12 at 8:19 PM, your appointment was scheduled.',
  notifications_past_rating_title: "Don't forget to rate your recent home clean at Style Haven!",
  notifications_past_rating_subtitle: 'On Aug 24 at 8:19 PM, you had a great home clean.',
  notifications_past_receipt_title: 'Your receipt for home clean #2957 is now available.',
  notifications_past_receipt_subtitle: 'On Aug 04 at 8:19 PM, you enjoyed a fresh cut.',
  my_profile_title: 'My profile',
  my_profile_edit: 'Edit',
  my_profile_full_name: 'Full name',
  my_profile_date_of_birth: 'Date of birth',
  my_profile_mobile_number: 'Mobile number',
  my_profile_email: 'Email',
  my_profile_my_addresses: 'My addresses',
  my_profile_add_address: 'Add address',
  my_profile_address_home: 'Home',
  my_profile_address_apartment: 'Apartment',
  my_profile_address_work: 'Work',
  my_profile_address_other: 'Other',
  photo_modal_title: 'Profile Photo',
  photo_modal_description: 'Choose how you want to update your profile photo',
  photo_take_photo: 'Take Photo',
  photo_choose_gallery: 'Choose from Gallery',
  photo_cancel: 'Cancel',
  photo_permission_title: 'Permission required',
  photo_permission_camera: 'Camera access is needed so you can take a profile photo or attach a photo in support and chat.',
  photo_permission_gallery: 'Photo library access is needed so you can choose a profile photo or attach an existing photo in support and chat.',
  photo_upload_error_title: 'Upload Failed',
  photo_upload_failed: 'Could not update profile photo.',
  edit_profile_title: 'Edit profile',
  edit_profile_name: 'Name',
  edit_profile_date_of_birth: 'Date of birth',
  edit_profile_day: 'Day',
  edit_profile_month: 'Month',
  edit_profile_year: 'Year',
  edit_profile_gender: 'Gender',
  edit_profile_gender_placeholder: 'Select option',
  edit_profile_save: 'Save',
  edit_profile_success: 'Success',
  edit_profile_success_message: 'Profile updated successfully.',
  edit_profile_error: 'Error',
  edit_profile_name_required: 'Name is required.',
  edit_profile_failed: 'Could not update profile.',
  settings_title: 'Settings',
  settings_notifications: 'Notification Settings',
  settings_change_password: 'Change Password',
  settings_privacy_policy: 'Privacy Policy',
  settings_terms_of_service: 'Terms of Service',
  settings_terms_of_use: 'Terms of Use',
  settings_delete_account: 'Delete Account',
  settings_app_version: 'App Version 1.0.0',
  // Notification settings screen
  notif_settings_title: 'Notification Settings',
  notif_settings_food_delivery: 'Food Delivery',
  notif_settings_marketing: 'Marketing',
  notif_settings_email: 'Email',
  notif_settings_sms: 'SMS',
  notif_settings_whatsapp: 'WhatsApp',
  notif_settings_success_title: 'Saved',
  notif_settings_success_message: 'Notification preference updated.',
  notif_settings_error_title: 'Error',
  // Privacy Policy screen
  privacy_title: 'Privacy Policy',
  privacy_last_updated: 'Last updated 2 months ago',
  privacy_intro:
    'This privacy policy explains how we handle your personal information while using the food delivery app. By registering or accessing the app, you consent to the practices described in this policy.',
  privacy_section_app_title: 'Privacy policy for the app',
  privacy_section_app_body:
    'The food delivery app is committed to protecting and managing your personal data and orders securely. You are authorized to use the app for personal and business purposes, subject to compliance with this policy and all applicable laws.',
  privacy_section_responsibilities_title: 'User responsibilities',
  privacy_section_responsibilities_body:
    'Users are responsible for keeping their delivery addresses and payment information accurate. It is important to keep this information up to date to avoid issues during the ordering process.',
  privacy_section_data_title: 'Data collection',
  privacy_section_data_body:
    'The food delivery app collects essential data to improve your experience, including your location, order history, and preferences.',
  privacy_section_modifications_title: 'Order modifications',
  privacy_section_modifications_body:
    'You may modify or cancel your orders through the app before they are processed. Once an order is confirmed, changes may no longer be possible.',
  privacy_section_payment_title: 'Payment security',
  privacy_section_payment_body:
    'We prioritize the security of your payment information. All transactions made through the app are processed using standard encryption technology.',
  privacy_section_contact_title: 'Contact us',
  privacy_section_contact_body:
    'If you have any questions about these terms, please feel free to contact us:',
  privacy_contact_email: 'Email: contact@fooddelivery.com',
  privacy_contact_address: 'Address: Doha, Qatar',
  // Terms of Service screen
  tos_title: 'Terms of Service',
  tos_last_updated: 'Last updated 2 months ago',
  tos_intro:
    'These terms of service define your access to and use of the food delivery app.',
  tos_section_usage_title: 'Use of the service',
  tos_section_usage_body:
    'The food delivery app provides a reliable platform for placing orders and managing your meal deliveries.',
  tos_section_orders_title: 'Order management',
  tos_section_orders_body:
    'The app allows you to track your orders easily, modify details, or cancel them within the allowed timeframe.',
  tos_section_payment_title: 'Payment security',
  tos_section_payment_body:
    'Payments made through the app are processed securely using encryption technology.',
  tos_section_delivery_title: 'Delivery policies',
  tos_section_delivery_body:
    'Users are encouraged to provide accurate delivery addresses to support fast and efficient service.',
  tos_section_support_title: 'Customer support',
  tos_section_support_body:
    'The app provides a robust support system to address any questions or issues.',
  tos_section_contact_title: 'Contact us',
  tos_section_contact_body:
    'If you have any questions about these terms, please feel free to contact us:',
  tos_contact_email: 'Email: contact@fooddelivery.com',
  tos_contact_address: 'Address: Doha, Qatar',
  // Terms of Use screen
  tou_title: 'Terms of Use',
  tou_last_updated: 'Updated 2 months ago',
  tou_intro:
    'These terms of use define your rights and responsibilities when using the app.',
  tou_section_guidelines_title: 'Usage guidelines',
  tou_section_guidelines_body:
    'The app provides secure management of your orders and customer data.',
  tou_section_etiquette_title: 'Delivery etiquette',
  tou_section_etiquette_body:
    'Users should remain respectful and courteous toward delivery staff.',
  tou_section_payment_title: 'Payment methods',
  tou_section_payment_body:
    'The app supports multiple payment methods, including credit cards and digital wallets.',
  tou_section_cancellation_title: 'Cancellation policy',
  tou_section_cancellation_body:
    'Orders may be cancelled within 10 minutes after being placed.',
  tou_section_feedback_title: 'Feedback and ratings',
  tou_section_feedback_body:
    'Users are encouraged to share feedback about their delivery experience.',
  tou_section_promotions_title: 'Promotions and offers',
  tou_section_promotions_body:
    'The app may offer promotions and discounts that are subject to specific conditions.',
  tou_section_contact_title: 'Contact us',
  tou_section_contact_body:
    'If you have any questions, please feel free to contact us:',
  tou_contact_email: 'Email: contact@fooddelivery.com',
  tou_contact_address: 'Address: Doha, Qatar',
  // Change password flow
  change_password_title: 'Change Password',
  change_password_new_title: 'New Password',
  change_password_email_heading: 'Change password?',
  change_password_email_description: 'Enter your email address and we\'ll send you a verification code.',
  change_password_email_placeholder: 'your@email.com',
  change_password_continue: 'Continue',
  change_password_verify_heading: 'Verify Your Email',
  change_password_verify_description: 'Enter the 4-digit code sent to {{email}}',
  change_password_verify_button: 'Verify OTP',
  change_password_new_heading: 'Create your new password',
  change_password_new_description: 'Your new password must be different from your previous password.',
  change_password_new_placeholder: 'New password',
  change_password_confirm_placeholder: 'Confirm new password',
  change_password_set_new: 'Set new password',
  change_password_mismatch: 'Passwords do not match.',
  change_password_error_title: 'Error',
  change_password_send_otp_error: 'Failed to send verification code.',
  change_password_verify_otp_error: 'Invalid or expired code.',
  change_password_update_error: 'Failed to update password.',
  change_password_success_title: 'Success',
  change_password_success_message: 'Your password has been updated.',
  change_password_otp_resent_title: 'Code sent',
  change_password_otp_resent_message: 'A new verification code has been sent.',
  // Delete account flow
  delete_account_step_label: 'Delete my account',
  delete_account_sorry_heading: "We'll be sorry to see you go",
  delete_account_sorry_subtext: 'Can we change your mind? Drop a line at',
  delete_account_contact_email: 'hello@enategadelivery.com',
  delete_account_reason_heading: 'Why do you wish to leave Food delivery?',
  delete_account_reason_subtext: 'Please let us know the reason for deleting your account:',
  delete_account_reason_mistake: 'I created this account by mistake',
  delete_account_reason_no_longer: 'I do not want to use Food delivery anymore',
  delete_account_reason_no_venues: "I can't find the venues or services I want",
  delete_account_reason_other: 'Other',
  delete_account_confirm_heading: 'Delete your Food delivery account',
  delete_account_confirm_description: 'This action will delete your account and you won\'t be able to retrieve it. Please confirm you understand by ticking the below statements:',
  delete_account_confirm_item_orders: 'I know I won\'t be able to access my orders.',
  delete_account_confirm_item_marketplace: 'I know I will no longer be able to book orders via Food delivery marketplace.',
  delete_account_final_heading: 'Confirm you are happy to proceed',
  delete_account_final_description: 'Please note this is permanent and can\'t be undone. To confirm deleting your account, please review your email below:',
  delete_account_email_label: 'Email',
  delete_account_email_placeholder: 'your@email.com',
  delete_account_cta_continue: 'Continue',
  delete_account_cta_delete: 'Delete account',
  delete_account_close: 'Close',
  delete_account_alert_title: 'Delete account',
  delete_account_alert_message: 'Are you sure you want to permanently delete your account? This action cannot be undone.',
  delete_account_alert_cancel: 'Cancel',
  delete_account_alert_confirm: 'Delete',
  delete_account_error_title: 'Error',
  delete_account_error: 'Failed to delete account. Please try again.',
  color_mode_title: 'App color mode',
  color_mode_section_label: 'Select app color mode',
  color_mode_system: 'Default System',
  color_mode_light: 'Light',
  color_mode_dark: 'Dark',
  language_title: 'App languages',
  language_section_label: 'Select language',
  language_english: 'English',
  language_french: 'French',
  offline_notice_title: "You're offline",
  offline_notice_description: 'Reconnect to refresh routes, fares, and live app data.',
  clear_all: 'Clear all',
  filter_title: 'Filter',
  filter_close_label: 'Close filters',
  filter_apply_results: 'Apply filters',
  generic_list_error_title: 'Unable to load results',
  generic_list_error_description: 'Pull to refresh or try again.',
  generic_list_retry: 'Retry',
  generic_list_empty_title: 'No results found',
  generic_list_empty_description: 'Try a different search or adjust your filters.',
  generic_list_search_placeholder: 'Search',
  see_all_map_loading_title: 'Finding {{title}}',
  see_all_map_loading_description: 'This may take a few moments. Please stay on this screen.',
  see_all_map_sheet_title: 'Restaurant',
  see_all_map_cta: 'View Restaurant',
  see_all_back_label: 'Back',
  see_all_open_filters_label: 'Open filters',
  see_all_map_view_label: 'Map view',
  // Search components translations
  no_results_found: 'No results found',
  recent_searches: 'Recent searches',
  searching_near: 'Searching near',
  multi_vendor_address_label: 'Select address',
  // Search filter translations
  search_filter_title: 'Search Filters',
  search_filter_sort_by: 'Sort by',
  search_filter_sort_best_match: 'Best match',
  search_filter_sort_top_rated: 'Top rated',
  search_filter_sort_nearest: 'Nearest',
  search_filter_ratings: 'Minimum rating',
  search_filter_availability: 'Availability',
  search_filter_availability_standard: 'Standard',
  search_filter_availability_emergency: 'Emergency',
  search_filter_stars: 'stars',
  filter_button_label: 'Filter options',
  search_input_placeholder: 'Search anything',
  Recommended_restaurants: 'Recommended restaurants',
  home_drive_banners_title: 'Drive Offers',
};

export default en;
