const en = {
  app_name: 'Super Customer App',
  greeting: 'Good Morning 👋',
  greeting_morning: 'Good Morning 👋',
  greeting_afternoon: 'Good Afternoon 👋',
  greeting_evening: 'Good Evening 👋',
  home_question: 'What are you looking for Today?',
  home_title: 'Home',
  home_subtitle: 'How can I help you today?',
  special_offer_label: '10% off',
  special_title: "Today's Special",
  special_description: 'Get a discount for every service order!',
  special_note: 'Only valid for today!',
  special_percent: '30%',
  services_title: 'Our Services',
  open_button: 'Open',
  service_type_title: 'Service Type',
  recommended_title: 'Recommended For You',
  recommended_name: 'Premium Cleaning',
  recommended_name_secondary: 'Fast Electrician',
  recommended_rating: '4.8 | 1,500+ reviews',
  service_deliveries: 'Deliveries',
  service_home_visit: 'Home-Visit Appointment',
  home_visits_section_title: 'Home Visits',
  home_visits_section_card_title: 'Home-Visit Appointment',
  home_visits_section_description: 'Book trusted professionals for your home services.',
  service_general_appointment: 'General Appointment',
  service_ride_sharing: 'Ride Sharing',
  recommended_price: '${{price}}/hr',
  recommended_reviews: '{{count}}+ reviews',
  splash_title: 'Food Delivery',
  loading: 'Loading...',
  splash_progress: '{{value}}%',
  developer_mode: 'Dev Mode',
  developer_mode_subtitle: 'System tools & diagnostics',
  developer_mode_welcome: 'Welcome to Developer Mode. Additional diagnostic tools will be available here soon.',
  driver_profile_button: 'Driver profile',
  auth_flow_button: 'Auth flow',
  rider_chat_button: 'Rider chat',
  dev_auth_title: 'Auth Sandbox',
  dev_auth_description: 'Temporary signup + session tools for development.',
  dev_auth_mode_signup: 'Signup',
  dev_auth_mode_login: 'Login',
  dev_auth_phone_label: 'Phone',
  dev_auth_phone_placeholder: '+923001234567',
  dev_auth_otp_label: 'OTP',
  dev_auth_otp_placeholder: '123456',
  dev_auth_name_label: 'Name',
  dev_auth_name_placeholder: 'John Doe',
  dev_auth_password_label: 'Password',
  dev_auth_password_placeholder: 'password123',
  dev_auth_push_token_label: 'Device Push Token',
  dev_auth_push_token_placeholder: 'fcm-token-here',
  dev_auth_referral_label: 'Referral Code',
  dev_auth_referral_placeholder: 'REF123',
  dev_auth_send_otp_button: 'Send OTP',
  dev_auth_send_login_otp_button: 'Send Login OTP',
  dev_auth_verify_button: 'Verify OTP & Create User',
  dev_auth_login_button: 'Verify OTP & Login',
  dev_auth_logout_button: 'Logout',
  dev_auth_status_label: 'Session Status',
  dev_auth_status_user: 'User: {{name}}',
  dev_auth_status_working: 'Working on request...',
  dev_auth_status_otp_sent: 'OTP sent. Verify to complete signup.',
  dev_auth_status_verified: 'Signup verified. Session stored.',
  dev_auth_status_failed: 'Request failed. Check the error below.',
  dev_auth_status_signed_in: 'Session active.',
  dev_auth_status_signed_out: 'No active session.',
  login_to_continue: 'Login to Continue',
  login_to_continue_desc: 'Please log in to save your delivery details and ensure a smooth, secure checkout experience.',
  continue_with_phone: 'Continue with Phone',
  continue_with_apple: 'Continue with Apple',
  continue_with_google: 'Continue with Google',
  continue_with_email: 'Continue with Email',
  or: 'or',
  dont_have_an_account: 'Don’t have an account?',
  signup: 'Sign Up',
  continue: 'Continue',
  enter_your_phone: 'Log in easily by entering your phone!',
  login_desc: 'We’ll check if you have an account',
  verify_your_phone_number: 'Verify Your Phone Number',
  verify_otp: 'Verify OTP',
  enter_otp_sent_to: 'Enter OTP sent to {{contact}}',
  didnt_receive_the_code: 'Didn’t receive the code?',
  resend_in: 'Resend in',
  try_another_way: 'Try another way',
  resend: 'Resend',
  incorrect_code: 'The code you entered is incorrect.',
  get_started: 'Let’s get you started',
  get_started_desc: 'First, let create your account',
  create_account: 'Create account',
  name: "Name",
  email: "Email",
  password: "Password",
  sms_verification: "Send code by SMS",
  call_verification: "Send code by Call",
  email_verification: "Send code by Mail",
  too_many_attempts: "Too many attempts",
  too_many_attempts_desc: "We’ve temporarily locked further attempts to protect your account. Try again in 5 minutes.",
  ok: "Ok",
  enter_your_email: 'Log in easily by entering your email!',
  enter_your_password: 'Enter your password',
  email_already_exist: 'Your email already exist.',
  remember_me: 'Remember me',
  forget_password: 'Forget Password?',
  invalid_password: 'Invalid password',
  enter_correct_password: 'Please enter the correct password.',
  forget_password_desc: 'Enter your email and we’ll send an OTP to reset your password.',
  create_new_password: 'Create your new password',
  create_password_desc: 'Set a new password and confirm it.',
  enter_new_password: 'Enter new passsword',
  confirm_new_password: 'Confirm new passsword',
  set_new_password: 'Set new password',
  verify_your_email: 'Verify Your Email',
  enter_strong_password: 'Please enter strong password.',
  password_not_matched: 'Make sure your passwords match',
  something_went_wrong: 'Something went wrong.',
  location_popup_title: 'Location Access',
  location_popup_description:
    'Use device location to show nearby stores, delivery availability, and relevant offers.',
  location_popup_denied_title: 'Location Permission Denied',
  location_popup_denied_description:
    'Location access is still off. Allow it to show nearby stores and accurate delivery availability.',
  location_popup_blocked_title: 'Enable Location in Settings',
  location_popup_blocked_description:
    'Location access is turned off for this app. Open settings to allow location access on your device.',
  location_popup_enable: 'Enable Location',
  location_popup_try_again: 'Try Again',
  location_popup_open_settings: 'Open Settings',
  location_popup_later: 'Maybe Later',
  address_list_title: 'My addresses',
  address_add_title: 'Add address',
  address_edit_title: 'Edit address',
  address_search_placeholder: 'Search for an address',
  address_choose_on_map: 'Choose on map',
  address_popular_places: 'Popular places',
  address_recent_searches: 'Recent searches',
  address_no_results: 'No results found',
  address_confirm_location: 'Confirm location',
  address_locating: 'Locating…',
  address_selected_location: 'Selected location',
  address_location_name_placeholder: 'Location name (e.g. My home)',
  address_details_label: 'Address Details',
  address_location_type_label: 'Location Type',
  address_location_details_label: 'Location Details',
  address_home_details_title: 'Home Details',
  address_apartment_details_title: 'Apartment Details',
  address_office_details_title: 'Office Details',
  address_field_house_flat_number: 'House / Flat Number',
  address_field_apartment_flat: 'Apartment / Flat',
  address_field_area_street: 'Area / Street',
  address_field_society_building_name: 'Society / Building Name',
  address_field_company_building_name: 'Company / Building Name',
  address_field_floor_tower_optional: 'Floor / Tower (Optional)',
  address_field_floor_suite_unit_optional: 'Floor / Suite / Unit (Optional)',
  address_field_department_optional: 'Department (Optional)',
  address_field_landmark_optional: 'Landmark (Optional)',
  address_detail_house_placeholder: 'House',
  address_detail_apartment_placeholder: 'Apartment / Flat',
  address_detail_office_placeholder: 'Office / Building',
  address_detail_company_building_placeholder: 'e.g. ABC Technologies',
  address_detail_floor_suite_unit_placeholder: 'e.g. 2nd Floor, Suite 201',
  address_detail_place_placeholder: 'Place',
  address_detail_society_placeholder: 'Society',
  address_detail_floor_placeholder: 'Floor / Tower',
  address_detail_department_placeholder: 'Department / Floor',
  address_detail_area_placeholder: 'Area / Street',
  address_detail_landmark_placeholder: 'Landmark',
  address_optional_suffix: '(optional)',
  address_set_as_default: 'Set as default address',
  address_type_home: 'Home',
  address_type_apartment: 'Apartment',
  address_type_office: 'Office',
  address_type_other: 'Other',
  address_choose_title: 'Choose delivery location',
  address_save: 'Save address',
  address_update: 'Update address',
  address_delete: 'Delete',
  address_delete_confirm_title: 'Delete address',
  address_delete_confirm_message: 'Are you sure you want to delete this address?',
  address_delete_cancel: 'Cancel',
  address_delete_confirm: 'Delete',
  address_save_error: 'Could not save address.',
  address_select_error: 'Could not select address.',
  address_delete_error: 'Could not delete address.',
  address_delete_linked_orders_error:
    'This address cannot be deleted because it is linked to existing orders.',
  address_save_success: 'Address saved successfully.',
  address_update_success: 'Address updated successfully.',
  address_delete_success: 'Address deleted successfully.',
  address_selector_title: 'Location',
  address_selector_close: 'Close location picker',
  address_selector_use_current_location: 'Use my current location',
  address_selector_add_new: 'Add new address',
  address_selector_search_address: 'Search for an address',
  profile_personal_account: 'Personal account',
  profile_wallet_balance: 'Wallet Balance',
  profile_view_wallet: 'View wallet',
  profile_section_essentials: 'Your essentials',
  profile_section_preferences: 'Preferences',
  profile_section_more: 'More',
  profile_menu_orders: 'Orders',
  profile_menu_orders_subtitle: 'Track current and past deliveries',
  profile_menu_addresses: 'Addresses',
  profile_menu_addresses_subtitle: 'Choose where your orders arrive',
  profile_menu_favorites_subtitle: 'Return to stores you love',
  profile_menu_profile: 'Profile',
  profile_menu_notifications: 'Notifications',
  profile_menu_favorites: 'Favorites',
  profile_menu_coupons: 'Coupons',
  profile_menu_settings: 'Settings',
  profile_menu_support: 'Support',
  profile_menu_color_mode: 'App color mode',
  profile_menu_language: 'Language',
  profile_menu_logout: 'Log out',
  profile_logout_confirm_title: 'Log out?',
  profile_logout_confirm_description: 'You’ll need to sign in again to place orders, view your profile, or manage deliveries.',
  profile_logout_confirm_action: 'Yes, log out',
  profile_logout_confirm_cancel: 'Stay signed in',
  profile_logout_confirm_error: 'We couldn’t log you out. Check your connection and try again.',
  notifications_title: 'Notifications',
  notifications_section_today: 'Today',
  notifications_section_past: 'Past',
  notifications_show_more: 'Show More',
  notifications_empty_title: 'No notifications yet',
  notifications_empty_description: 'You will see your latest updates here once they arrive.',
  notifications_today_appointment_title: 'Your appointment at Style Haven is confirmed and ready for you.',
  notifications_today_appointment_subtitle: 'Just a moment ago.',
  notifications_today_location_title: 'Your home clean is confirmed: Visit us at Style Haven.',
  notifications_today_location_subtitle: 'A few hours back.',
  notifications_today_payment_title: 'Payment received: QR 65.00 for your home clean at Style Haven.',
  notifications_today_payment_subtitle: "It's 8:19 PM, perfect time for a night out!",
  notifications_past_offer_title: 'Special offer: Enjoy 15% off your next two visits!',
  notifications_past_offer_subtitle: 'On Sep 12 at 8:19 PM, your appointment was scheduled.',
  notifications_past_rating_title: "Don't forget to rate your recent home clean at Style Haven!",
  notifications_past_rating_subtitle: 'On Aug 24 at 8:19 PM, you had a great home clean.',
  notifications_past_receipt_title: 'Your receipt for home clean #2957 is now available.',
  notifications_past_receipt_subtitle: 'On Aug 04 at 8:19 PM, you enjoyed a fresh cut.',
  my_profile_title: 'My profile',
  my_profile_edit: 'Edit',
  my_profile_full_name: 'Full name',
  my_profile_date_of_birth: 'Date of birth',
  my_profile_mobile_number: 'Mobile number',
  my_profile_email: 'Email',
  my_profile_my_addresses: 'My addresses',
  my_profile_add_address: 'Add address',
  my_profile_address_home: 'Home',
  my_profile_address_apartment: 'Apartment',
  my_profile_address_work: 'Work',
  my_profile_address_other: 'Other',
  photo_modal_title: 'Profile Photo',
  photo_modal_description: 'Choose how you want to update your profile photo',
  photo_take_photo: 'Take Photo',
  photo_choose_gallery: 'Choose from Gallery',
  photo_cancel: 'Cancel',
  photo_permission_title: 'Permission required',
  photo_permission_camera: 'Camera access is needed so you can take a profile photo or attach a photo in support and chat.',
  photo_permission_gallery: 'Photo library access is needed so you can choose a profile photo or attach an existing photo in support and chat.',
  photo_upload_error_title: 'Upload Failed',
  photo_upload_failed: 'Could not update profile photo.',
  edit_profile_title: 'Edit profile',
  edit_profile_name: 'Name',
  edit_profile_date_of_birth: 'Date of birth',
  edit_profile_day: 'Day',
  edit_profile_month: 'Month',
  edit_profile_year: 'Year',
  edit_profile_gender: 'Gender',
  edit_profile_gender_placeholder: 'Select option',
  edit_profile_save: 'Save',
  edit_profile_success: 'Success',
  edit_profile_success_message: 'Profile updated successfully.',
  edit_profile_error: 'Error',
  edit_profile_name_required: 'Name is required.',
  edit_profile_failed: 'Could not update profile.',
  settings_title: 'Settings',
  settings_notifications: 'Notification Settings',
  settings_change_password: 'Change Password',
  settings_privacy_policy: 'Privacy Policy',
  settings_terms_of_service: 'Terms of Service',
  settings_terms_of_use: 'Terms of Use',
  settings_about_us: 'About Us',
  settings_how_it_works: 'How It Works',
  settings_contact_us: 'Contact Us',
  settings_delete_account: 'Delete Account',
  settings_app_version: 'App Version 1.0.0',
  // Notification settings screen
  notif_settings_title: 'Notification Settings',
  notif_settings_food_delivery: 'Food Delivery',
  notif_settings_marketing: 'Marketing',
  notif_settings_email: 'Email',
  notif_settings_sms: 'SMS',
  notif_settings_whatsapp: 'WhatsApp',
  notif_settings_success_title: 'Saved',
  notif_settings_success_message: 'Notification preference updated.',
  notif_settings_error_title: 'Error',
  // Privacy Policy screen
  privacy_title: 'Privacy Policy',
  privacy_last_updated: 'Last updated 2 months ago',
  privacy_intro:
    'This privacy policy explains how we handle your personal information while using the food delivery app. By registering or accessing the app, you consent to the practices described in this policy.',
  privacy_section_app_title: 'Privacy policy for the app',
  privacy_section_app_body:
    'The food delivery app is committed to protecting and managing your personal data and orders securely. You are authorized to use the app for personal and business purposes, subject to compliance with this policy and all applicable laws.',
  privacy_section_responsibilities_title: 'User responsibilities',
  privacy_section_responsibilities_body:
    'Users are responsible for keeping their delivery addresses and payment information accurate. It is important to keep this information up to date to avoid issues during the ordering process.',
  privacy_section_data_title: 'Data collection',
  privacy_section_data_body:
    'The food delivery app collects essential data to improve your experience, including your location, order history, and preferences.',
  privacy_section_modifications_title: 'Order modifications',
  privacy_section_modifications_body:
    'You may modify or cancel your orders through the app before they are processed. Once an order is confirmed, changes may no longer be possible.',
  privacy_section_payment_title: 'Payment security',
  privacy_section_payment_body:
    'We prioritize the security of your payment information. All transactions made through the app are processed using standard encryption technology.',
  privacy_section_contact_title: 'Contact us',
  privacy_section_contact_body:
    'If you have any questions about these terms, please feel free to contact us:',
  privacy_contact_email: 'Email: contact@fooddelivery.com',
  privacy_contact_address: 'Address: Doha, Qatar',
  // Terms and Conditions screen — mirrors sipp-web's /terms page verbatim.
  // Kept in English only: per the source document's own "Controlling
  // Language" clause, Spanish/English govern regardless of UI locale.
  tos_title: 'Terms and Conditions',
  tos_subtitle:
    'Costa Rica — Applicable to Users, Restaurant Partners and Delivery Partners.',
  tos_last_updated: 'Last updated: July 14, 2026',
  tos_preamble_title: 'Preamble and Parties',
  tos_preamble_paragraphs: [
    'These Terms and Conditions (the "Terms") govern access to and use of the SIPP Delivery mobile application and website (the "Application" or the "Platform") by any person who registers for or interacts with it in any of the following capacities: (a) a customer requesting Delivery Services ("User"); (b) a commercial establishment listed on the Application ("Restaurant Partner"); or (c) a person providing Delivery Services through the Application ("Delivery Partner"). Collectively, "You."',
    'The Platform is locally operated by SIPP Delivery S.A., a corporation (sociedad anónima) organized under the laws of the Republic of Costa Rica, cédula jurídica 3-101-954829 ("SIPP CR," "SIPP," "we"), acting as local operating agent and under license from SIPP Delivery LLC, a limited liability company organized under the laws of the State of Delaware, United States of America, EIN 36-5182139, with registered agent office at 8 The Green, Suite B, Dover, Delaware 19901 ("SIPP US"), the global owner of the "SIPP Delivery" brand, the Application, the software, the databases and other intellectual property associated with the Platform.',
    'These Terms are entered into solely between You and SIPP CR. SIPP US is not a party to these Terms and assumes no obligation to You hereunder; however, SIPP US may directly enforce Sections 18 (Intellectual Property), 22 (Confidentiality) and 23 (Limitation of Liability) as a third-party beneficiary.',
  ],
  tos_definitions_title: '1. Definitions',
  tos_definitions: [
    { term: 'Application or Platform', description: 'the SIPP Delivery mobile application and website and related systems and support.' },
    { term: 'User', description: 'a person who requests Delivery Services through the Application as an end consumer.' },
    { term: 'Restaurant Partner', description: 'an establishment listed on the Application offering products for purchase by Users.' },
    { term: 'Delivery Partner', description: 'a person who, as an independent contractor, provides Delivery Services through the Application.' },
    { term: 'Delivery Services', description: 'the collection, transport and delivery of goods requested by Users through the Application.' },
    { term: 'Restaurant Partner Agreement', description: 'the bilateral agreement executed between a Restaurant Partner and SIPP CR governing the specific commercial terms of that relationship.' },
    { term: 'Delivery Partner Agreement', description: 'the bilateral agreement executed between a Delivery Partner and SIPP CR governing the specific terms of that independent-contractor relationship.' },
    { term: 'Content', description: 'text, images, ratings, comments and other material You post or upload to the Application.' },
    { term: 'Account', description: 'the registration profile You create to access the Application.' },
  ],
  tos_sections: [
    { heading: '2. Acceptance of the Terms', paragraphs: ['By creating an Account, or by downloading, accessing or using the Application in any capacity, You represent that You have read, understood and accepted these Terms and that You have legal capacity to contract under Costa Rican law. If You act on behalf of a legal entity (for example, a Restaurant Partner), You represent that You have sufficient authority to bind it. If You do not accept these Terms, You must refrain from using the Application.'] },
    { heading: '3. Description of the Platform and Roles', paragraphs: ['SIPP CR operates a digital marketplace connecting Users, Restaurant Partners and Delivery Partners. SIPP CR does not prepare or sell food, is not a carrier, and is not the employer of Delivery Partners. SIPP CR acts as a technology intermediary and, in the cases described in these Terms, as a limited collection and payment agent on behalf of Restaurant Partners and Delivery Partners.'] },
    { heading: '4. Eligibility and Registration', paragraphs: ['To use the Application, You must: (a) be at least eighteen (18) years old; (b) provide truthful, complete and up-to-date information upon registration; (c) maintain only one active Account per person, unless expressly authorized by SIPP; and (d) comply with the additional eligibility requirements applicable to Your role, described below. SIPP CR may perform reasonable identity and documentation verifications.'] },
    { heading: '5. Account', paragraphs: ['You are responsible for maintaining the confidentiality of your access credentials and for all activity under Your Account. You must notify SIPP immediately of any unauthorized use. SIPP will not be liable for losses arising from unauthorized use of Your Account where such use results from Your negligence in safeguarding your credentials.'] },
    { heading: 'Part A — Terms Applicable to Users (Customers)', paragraphs: [] },
    { heading: '6. Order Formation', paragraphs: ['An order placed by a User through the Application constitutes an offer to purchase directed to the relevant Restaurant Partner. The sales contract for the products is formed directly between the User and the Restaurant Partner upon the latter\'s acceptance of the order. SIPP CR is not a party to that sales contract and does not warrant the availability, quality, safety or conformity of products offered by Restaurant Partners.'] },
    { heading: '7. Prices, Delivery Fees and Payments', paragraphs: ['Product prices are set by each Restaurant Partner. The applicable delivery fee is displayed on the Application before order confirmation. All amounts are expressed in Costa Rican colones (₡), unless another currency is expressly indicated. All payments are processed exclusively by electronic means through the Application; cash payments are not accepted. You designate SIPP CR as a limited collection agent, solely to receive on your behalf, and remit to the relevant Restaurant Partners and Delivery Partners, the amounts due to them.'] },
    { heading: '8. Cancellations, Refunds and Disputes', paragraphs: ["You may cancel an order free of charge before the Restaurant Partner accepts it. Once accepted, cancellation may be subject to a charge reflecting costs already incurred. For incorrect, damaged, incomplete or undelivered orders, You may submit a claim through the Application's support channel within a reasonable period; SIPP CR will evaluate the claim in good faith and, where warranted, process the corresponding full or partial refund, without prejudice to the direct liability that may lie with the responsible Restaurant Partner or Delivery Partner."] },
    { heading: '9. Delivery and Risk', paragraphs: ['Delivery is performed by independent Delivery Partners who are not employees of SIPP CR or SIPP US. Risk of loss or damage to products transfers to the User upon delivery, or upon completion of a contactless delivery instruction ("leave at door") specified by the User. You must provide an accurate, accessible and safe delivery address.'] },
    { heading: '10. Ratings and User-Generated Content', paragraphs: ['You may rate and comment on Delivery Services and products received. SIPP CR may moderate, hide or remove Content that is defamatory, false, discriminatory, or that infringes third-party rights. You grant SIPP CR a non-exclusive, worldwide, royalty-free license to use such Content within the Platform for purposes of operating, improving and promoting the service.'] },
    { heading: '11. Consumer Protection', paragraphs: ['Nothing in these Terms limits the non-waivable rights that Law No. 7472, Law for the Promotion of Competition and Effective Consumer Protection, and its Regulations, grant You as a consumer. In the event of a conflict between a provision of these Terms and such regulations, the consumer protection regulations shall prevail.'] },
    { heading: 'Part B — Terms Applicable to Restaurant Partners', paragraphs: [] },
    { heading: '12. Contractual Relationship and Precedence', paragraphs: ["A commercial establishment's access to the Platform as a Restaurant Partner requires execution of a separate Restaurant Partner Agreement with SIPP CR, which governs the applicable commission, settlement schedule and other commercial terms specific to that relationship. In the event of a conflict between the executed Restaurant Partner Agreement and these Terms regarding individually negotiated commercial terms (including, without limitation, commission, the duration of founding-partner terms, and the form and frequency of payment), the Restaurant Partner Agreement shall prevail. These Terms govern, on a complementary and general basis, all matters relating to use of the Application, conduct on the Platform, intellectual property, data protection and the other general provisions applicable to all Platform users."] },
    { heading: '13. Menu Content and Conduct', paragraphs: ['The Restaurant Partner is responsible for the accuracy of prices, product availability, allergen disclosure, and compliance with applicable health regulations. SIPP CR may suspend listings that violate the law, contain false information, or harm the reputation or operation of the Platform, upon notice where circumstances permit.'] },
    { heading: '14. Payments to Restaurant Partners', paragraphs: ['Commission, applicable deductions and the settlement schedule are governed by the executed Restaurant Partner Agreement. SIPP CR acts as a limited collection agent with respect to amounts paid by Users that are due to the Restaurant Partner.'] },
    { heading: 'Part C — Terms Applicable to Delivery Partners', paragraphs: [] },
    { heading: '15. Contractual Relationship and Precedence', paragraphs: ['Access to the Application as a Delivery Partner requires execution of a separate Delivery Partner Agreement, which confirms the independent-contractor relationship between the Delivery Partner and SIPP CR (no subordination, no exclusivity, no employment benefits) and governs the Delivery Fee, the Subscription Cost, and the settlement schedule. In the event of a conflict between the executed Delivery Partner Agreement and these Terms regarding such economic terms or the nature of the relationship, the Delivery Partner Agreement shall prevail.'] },
    { heading: '16. Delivery Partner Conduct', paragraphs: ['The Delivery Partner must perform Delivery Services in a professional and diligent manner, comply with applicable traffic regulations, refrain from soliciting or accepting cash payments, and use the Application solely for the purposes authorized under the Delivery Partner Agreement.'] },
    { heading: '17. Payments to Delivery Partners', paragraphs: ['The Delivery Fee, tips, the Subscription Cost and the settlement schedule are governed by the executed Delivery Partner Agreement.'] },
    { heading: 'General Provisions (Applicable to All Roles)', paragraphs: [] },
    { heading: '18. Intellectual Property', paragraphs: ['The Application, the software, the databases, the design, the "SIPP Delivery" trademarks, and all Platform content (excluding Content generated by You) are the exclusive property of SIPP US or its licensors, and are protected by Costa Rican and international intellectual property law. Nothing in these Terms transfers any ownership right in such assets to any User, Restaurant Partner or Delivery Partner.'] },
    { heading: '19. Limited License to Use', paragraphs: ['Subject to Your compliance with these Terms, SIPP CR grants You a limited, non-exclusive, non-transferable, non-sublicensable and revocable license to use the Application in accordance with Your role. You may not copy, modify, reverse engineer, sublicense, resell, use automated means to access the Application ("scraping"), or use it to develop a competing product or service.'] },
    { heading: '20. Prohibited Conduct', paragraphs: ['The following are prohibited: (a) fraud or rating manipulation; (b) creating or using unauthorized multiple accounts; (c) posting illegal or defamatory content, or content that infringes third-party rights; (d) harassing other Platform users; and (e) breaching, overloading or interfering with the security or operation of the Application.'] },
    { heading: '21. Personal Data Protection', paragraphs: ["SIPP CR processes the personal data of Users, Restaurant Partners and Delivery Partners in accordance with Law No. 8968, Law on the Protection of Individuals with regard to the Processing of their Personal Data, and SIPP's Privacy Policy available on the Application. You consent to the collection, use and, where applicable, disclosure of Your personal data (including Your location while using the Application) to operate the Platform, facilitate Delivery Services, ensure security, and comply with legal obligations. You may exercise Your rights of access, rectification, cancellation and objection under that Policy."] },
    { heading: '22. Confidentiality', paragraphs: ['Non-public information that SIPP CR shares with Restaurant Partners or Delivery Partners through support channels, administrative dashboards or other means (for example, operational or commercial Platform data) must be kept confidential and used solely for the purposes of the relationship with SIPP CR.'] },
    { heading: '23. Limitation of Liability', paragraphs: ["Without prejudice to Section 11, and to the maximum extent permitted by applicable law: neither SIPP CR nor SIPP US shall be liable for indirect, incidental, special, punitive or consequential damages, or for loss of profits, revenue, business or data. SIPP CR does not warrant uninterrupted or error-free availability of the Application. SIPP CR's aggregate liability to a Restaurant Partner or Delivery Partner shall be governed by the limit set forth in the applicable bilateral Agreement; to a User, it shall not exceed the amount of service fees paid by that User through the Application in the three (3) months preceding the event giving rise to the claim, except where consumer protection law provides otherwise."] },
    { heading: '24. Indemnification', paragraphs: ["Each User, Restaurant Partner and Delivery Partner shall indemnify, defend and hold harmless SIPP CR and SIPP US, and their respective officers, directors, employees and agents, from any claim, liability, damage, loss or expense (including reasonable attorneys' fees) arising from: (a) their breach of these Terms or of the applicable bilateral Agreement; (b) their negligent or willful acts or omissions; or (c) any third-party claim arising from their interaction with the Platform."] },
    { heading: '25. Account Suspension and Termination', paragraphs: ['SIPP CR may suspend or deactivate access to the Application for any Account that breaches these Terms, engages in fraud or unsafe conduct, or poses a risk to the Platform or third parties, with notice where circumstances permit. The foregoing is without prejudice to the specific suspension and termination rights and procedures set out in the applicable Restaurant Partner Agreement or Delivery Partner Agreement, which shall prevail as to those Partners.'] },
    { heading: '26. Modifications to these Terms', paragraphs: ['SIPP CR may modify these general Terms from time to time, with reasonable notice through the Application or by email. Continued use of the Application after a modification takes effect constitutes acceptance of it.', 'No modification to these general Terms may, by itself, alter the specific, individually negotiated commercial terms of an existing Restaurant Partner Agreement or Delivery Partner Agreement (including, without limitation, commissions or fees fixed for a set period). Such Agreements may only be modified in accordance with their own terms.'] },
    { heading: '27. Force Majeure', paragraphs: ['Neither party shall be liable for any failure or delay resulting from causes beyond its reasonable control, including natural disasters, government actions, labor disputes, or telecommunications or internet infrastructure failures.'] },
    { heading: '28. Governing Law and Dispute Resolution', paragraphs: ['These Terms are governed by the laws of the Republic of Costa Rica.', 'Disputes between SIPP CR and a Restaurant Partner or a Delivery Partner: shall first be addressed in good faith through the Application\'s support channel and, if unresolved, submitted to binding arbitration before the Arbitration and Conciliation Center of the Costa Rican Chamber of Commerce (CICA), seated in San José, as set out in the applicable bilateral Agreement.', 'Disputes with Users (consumers): shall first be addressed in good faith through the Application\'s support channel. If unresolved, the User may bring the matter before the National Consumer Commission or the ordinary courts of the Republic of Costa Rica.'] },
    { heading: '29. General Provisions', paragraphs: ["Assignment: You may not assign or transfer these Terms without SIPP CR's prior written consent; SIPP CR may freely assign or transfer them, including in connection with a merger, acquisition or sale of assets.", 'Severability: if any provision is found illegal, void or unenforceable, it shall be severed without affecting the validity of the remainder.', 'Electronic acceptance: these Terms may be accepted by electronic means, including by clicking "I Accept" in the Application, with the same legal validity as a handwritten signature, in accordance with Costa Rican legislation on digital signatures and electronic documents.', 'Entire agreement: these Terms, together with the Privacy Policy and, where applicable, the Restaurant Partner Agreement or Delivery Partner Agreement in effect, constitute the entire understanding between You and SIPP CR regarding their subject matter.', 'Notices: SIPP CR may notify You through the Application or the email address registered to Your Account.'] },
    { heading: '30. Controlling Language', paragraphs: ['These Terms have been drafted in Spanish and in English. In the event of any discrepancy or conflict between the two versions, the Spanish version shall prevail, as it is the version directed to the Costa Rican market and the one required under Costa Rican consumer protection legislation.'] },
  ],
  // Terms of Use screen
  tou_title: 'Terms of Use',
  tou_last_updated: 'Updated 2 months ago',
  tou_intro:
    'These terms of use define your rights and responsibilities when using the app.',
  tou_section_guidelines_title: 'Usage guidelines',
  tou_section_guidelines_body:
    'The app provides secure management of your orders and customer data.',
  tou_section_etiquette_title: 'Delivery etiquette',
  tou_section_etiquette_body:
    'Users should remain respectful and courteous toward delivery staff.',
  tou_section_payment_title: 'Payment methods',
  tou_section_payment_body:
    'The app supports multiple payment methods, including credit cards and digital wallets.',
  tou_section_cancellation_title: 'Cancellation policy',
  tou_section_cancellation_body:
    'Orders may be cancelled within 10 minutes after being placed.',
  tou_section_feedback_title: 'Feedback and ratings',
  tou_section_feedback_body:
    'Users are encouraged to share feedback about their delivery experience.',
  tou_section_promotions_title: 'Promotions and offers',
  tou_section_promotions_body:
    'The app may offer promotions and discounts that are subject to specific conditions.',
  tou_section_contact_title: 'Contact us',
  tou_section_contact_body:
    'If you have any questions, please feel free to contact us:',
  tou_contact_email: 'Email: contact@fooddelivery.com',
  tou_contact_address: 'Address: Doha, Qatar',
  // Change password flow
  change_password_title: 'Change Password',
  change_password_new_title: 'New Password',
  change_password_email_heading: 'Change password?',
  change_password_email_description: 'Enter your email address and we\'ll send you a verification code.',
  change_password_email_placeholder: 'your@email.com',
  change_password_continue: 'Continue',
  change_password_verify_heading: 'Verify Your Email',
  change_password_verify_description: 'Enter the 4-digit code sent to {{email}}',
  change_password_verify_button: 'Verify OTP',
  change_password_new_heading: 'Create your new password',
  change_password_new_description: 'Your new password must be different from your previous password.',
  change_password_new_placeholder: 'New password',
  change_password_confirm_placeholder: 'Confirm new password',
  change_password_set_new: 'Set new password',
  change_password_mismatch: 'Passwords do not match.',
  change_password_error_title: 'Error',
  change_password_send_otp_error: 'Failed to send verification code.',
  change_password_verify_otp_error: 'Invalid or expired code.',
  change_password_update_error: 'Failed to update password.',
  change_password_success_title: 'Success',
  change_password_success_message: 'Your password has been updated.',
  change_password_otp_resent_title: 'Code sent',
  change_password_otp_resent_message: 'A new verification code has been sent.',
  // Delete account flow
  delete_account_step_label: 'Delete my account',
  delete_account_sorry_heading: "We'll be sorry to see you go",
  delete_account_sorry_subtext: 'Can we change your mind? Drop a line at',
  delete_account_contact_email: 'hello@enategadelivery.com',
  delete_account_reason_heading: 'Why do you wish to leave Food delivery?',
  delete_account_reason_subtext: 'Please let us know the reason for deleting your account:',
  delete_account_reason_mistake: 'I created this account by mistake',
  delete_account_reason_no_longer: 'I do not want to use Food delivery anymore',
  delete_account_reason_no_venues: "I can't find the venues or services I want",
  delete_account_reason_other: 'Other',
  delete_account_confirm_heading: 'Delete your Food delivery account',
  delete_account_confirm_description: 'This action will delete your account and you won\'t be able to retrieve it. Please confirm you understand by ticking the below statements:',
  delete_account_confirm_item_orders: 'I know I won\'t be able to access my orders.',
  delete_account_confirm_item_marketplace: 'I know I will no longer be able to book orders via Food delivery marketplace.',
  delete_account_final_heading: 'Confirm you are happy to proceed',
  delete_account_final_description: 'Please note this is permanent and can\'t be undone. To confirm deleting your account, please review your email below:',
  delete_account_email_label: 'Email',
  delete_account_email_placeholder: 'your@email.com',
  delete_account_cta_continue: 'Continue',
  delete_account_cta_delete: 'Delete account',
  delete_account_close: 'Close',
  delete_account_alert_title: 'Delete account',
  delete_account_alert_message: 'Are you sure you want to permanently delete your account? This action cannot be undone.',
  delete_account_alert_cancel: 'Cancel',
  delete_account_alert_confirm: 'Delete',
  delete_account_error_title: 'Error',
  delete_account_error: 'Failed to delete account. Please try again.',
  color_mode_title: 'App color mode',
  color_mode_section_label: 'Select app color mode',
  color_mode_system: 'Default System',
  color_mode_light: 'Light',
  color_mode_dark: 'Dark',
  language_title: 'App languages',
  language_section_label: 'Select language',
  language_english: 'English',
  language_french: 'French',
  offline_notice_title: "You're offline",
  offline_notice_description: 'Reconnect to refresh routes, fares, and live app data.',
  clear_all: 'Clear all',
  filter_title: 'Filter',
  filter_close_label: 'Close filters',
  filter_apply_results: 'Apply filters',
  generic_list_error_title: 'Unable to load results',
  generic_list_error_description: 'Pull to refresh or try again.',
  generic_list_retry: 'Retry',
  generic_list_empty_title: 'No results found',
  generic_list_empty_description: 'Try a different search or adjust your filters.',
  generic_list_results_count: '{{count}} result',
  generic_list_results_count_plural: '{{count}} results',
  generic_list_search_placeholder: 'Search',
  search_clear_label: 'Clear search',
  search_screen_title: 'Find exactly what you need',
  search_screen_subtitle: 'Search nearby stores, meals and everyday essentials.',
  search_screen_input_placeholder: 'Search stores, meals and essentials',
  search_suggestions_title: 'Popular near you',
  search_delete_recent_label: 'Remove {{term}} from recent searches',
  see_all_map_loading_title: 'Finding {{title}}',
  see_all_map_loading_description: 'This may take a few moments. Please stay on this screen.',
  see_all_map_sheet_title: 'Restaurant',
  see_all_map_cta: 'View Restaurant',
  see_all_back_label: 'Back',
  navigation_back: 'Go back',
  see_all_open_filters_label: 'Open filters',
  see_all_map_view_label: 'Map view',
  // Search components translations
  no_results_found: 'No results found',
  recent_searches: 'Recent searches',
  searching_near: 'Searching near',
  multi_vendor_address_label: 'Select address',
  // Search filter translations
  search_filter_title: 'Search Filters',
  search_filter_sort_by: 'Sort by',
  search_filter_sort_best_match: 'Best match',
  search_filter_sort_top_rated: 'Top rated',
  search_filter_sort_nearest: 'Nearest',
  search_filter_ratings: 'Minimum rating',
  search_filter_availability: 'Availability',
  search_filter_availability_standard: 'Standard',
  search_filter_availability_emergency: 'Emergency',
  search_filter_stars: 'stars',
  filter_button_label: 'Filter options',
  search_input_placeholder: 'Search anything',
  Recommended_restaurants: 'Recommended restaurants',
  home_drive_banners_title: 'Drive Offers',
  // About Us screen
  about_title: "Building the delivery infrastructure of Costa Rica's coast.",
  about_subtitle: 'So many options. Zero effort.',
  about_origin_title: 'Why we started',
  about_origin_paragraphs: [
    "SIPP is a local delivery platform built for one simple reason: to make ordering food, groceries, and essentials effortless — in places where traditional delivery never really worked.",
    "We started in Santa Teresa, Costa Rica, where tourists, locals, villas, and restaurants all face the same problem: great food, great places — but fragmented, unreliable, and outdated delivery systems.",
    "SIPP changes that.",
    "We connect restaurants, grocery suppliers, and local businesses into one intelligent platform that allows customers to order everything they need in one place — from meals and snacks to drinks, groceries, and daily essentials — with fast, organized, and trackable delivery.",
  ],
  about_different_title: 'What makes SIPP different',
  about_different_intro:
    'SIPP is not just a food delivery app. It is a local commerce and logistics platform designed specifically for coastal and high-tourism regions.',
  about_different_focus_label: 'We focus on',
  about_different_items: [
    'A wide selection of restaurants and local partners',
    'Grocery and essentials delivery alongside prepared food',
    'Reliable late-night operations',
    'Clear, user-friendly ordering',
    'Secure card payments',
    'Fast, coordinated local logistics',
    'Strong support for restaurants and partners',
  ],
  about_different_outro:
    'Instead of forcing global delivery models into small markets, we built SIPP around how these towns actually work — seasonality, tourism peaks, local suppliers, and short-distance logistics.',
  about_different_result:
    'The result is a platform that benefits everyone: customers get convenience and variety, restaurants get more orders and visibility, and local communities get modern delivery infrastructure.',
  about_local_title: 'Built locally. Designed to scale.',
  about_local_paragraphs: [
    'SIPP was founded and is operated in Costa Rica. Our team works on the ground with restaurants, couriers, supermarkets, and villas every day.',
    'That local presence allows us to control quality, delivery times, onboarding, and customer experience — while continuously improving the platform.',
    'At the same time, SIPP is built with scale in mind. Our technology, logistics model, and partner structure are designed to expand across coastal regions, tourism hubs, and emerging delivery markets.',
  ],
  about_mission_title: 'Our mission',
  about_mission_statement:
    "To become the leading delivery and local commerce platform across Costa Rica's coastal areas — and a long-term regional player in high-tourism markets.",
  about_mission_paragraphs: [
    'We are building more than an app.',
    'We are building the system that powers everyday life: food, groceries, restaurants, and local businesses — all in one place.',
  ],
  about_tagline_label: 'SIPP in one sentence',
  about_tagline_value: 'So many options. Zero effort.',
  // How It Works screen
  how_it_works_title: 'How it works?',
  how_it_works_subtitle:
    "SIPP is an online delivery platform that brings your town's favorite spots straight to your doorstep. We connect customers with local businesses – restaurants, cafés, bars, grocery stores – and handle delivery through our logistics crew to get you what you need, when you need it.",
  how_it_works_steps_title: "Here's how SIPP works in four easy steps",
  how_it_works_steps: [
    {
      title: '1. Browse & Order',
      description:
        'Pop into our platform from any device (phone, tablet, or computer) and see what tickles your fancy. Browse by category or search for a specific restaurant, store, dish or product. Sign in, add items to your cart and place your order with a few clicks. You can pay securely with your credit card – easy, fast, and cash-free.',
    },
    {
      title: '2. We Confirm & Prep',
      description:
        "The moment you order, we automatically send the request over to the chosen restaurant or shop. They'll give it a thumbs up and start prepping your items with love and care. Whether it's a hot meal being cooked or groceries being packed, we keep things moving quickly. That's when your order status will change from Pending, to Accepted and then, to Preparing.",
    },
    {
      title: '3. Out for Delivery',
      description:
        "As soon as your order is ready to roll, one of our SIPP couriers springs into action. They'll pick up your order and head straight to your location. You can track your delivery in real time on our platform. Feel free to do a little happy dance; your goods are on the way!",
    },
    {
      title: '4. Delivered & Enjoy',
      description:
        'Ding-dong! Delivery has arrived. Our courier will hand off your order at your door. Now all that\'s left is to dig in and enjoy.',
    },
  ],
  how_it_works_delivery_area_title: 'Where do we deliver?',
  how_it_works_delivery_area_body:
    "Currently, SIPP operates in and around Santa Teresa, Costa Rica, covering the nearby locations – from Manzanillo to Santiago, Playa Hermosa, Playa Carmen, and Mal País. We're a local service, so we know these roads like the back of our hand (yes, that shortcut past the surf shop? We know it). Good news: we're expanding soon! SIPP will be coming to Nosara next, so stay tuned.",
  how_it_works_closing_body:
    "In short, SIPP works just like those big delivery apps – but with extra Pura Vida flair. We pride ourselves on being fast, reliable, and just a bit awesome (if we do say so ourselves). Hungry? Thirsty? Out of toothpaste? Whatever you need – just SIPP it.",
  // Contact Us screen
  contact_title: '📬 Contact Us',
  contact_tagline: 'Got questions? Cravings? Ideas?',
  contact_body:
    "We're all ears — and all delivery wheels. Whether you're a hungry guest, a curious concierge, or a restaurant ready to join the ride, we'd love to hear from you.",
  contact_whatsapp_title: '📱 WhatsApp or Call Us',
  contact_whatsapp_subtitle: 'Fastest way to reach us — like our delivery.',
  contact_phone_display: '📞 +506 7044 5484 — Tap to chat or call!',
  contact_email_title: '📩 Email Us',
  contact_email_subtitle: 'Prefer typing it all out?',
  contact_email_address: 'support@sippdelivery.com',
  contact_support_title: '🎫 Need Help With An Order?',
  contact_support_subtitle:
    'Got an issue or a question about your account or an order? Open a support ticket and our team will sort it out.',
  contact_support_cta: 'Create a ticket',
  contact_address: 'Santa Teresa, Provincia de Puntarenas, Puntarenas, Costa Rica',
  contact_social_title: 'Follow us',
  contact_error_generic: 'We could not complete that action. Please try again.',
};

export default en;
