const fr = {
  app_name: 'Application Super Client',
  greeting: 'Bonjour 👋',
  greeting_morning: 'Bonjour 👋',
  greeting_afternoon: 'Bon après-midi 👋',
  greeting_evening: 'Bonsoir 👋',
  home_question: 'Que recherchez-vous aujourd’hui ?',
  home_title: 'Accueil',
  home_subtitle: 'Comment puis-je vous aider aujourd\'hui ?',
  special_offer_label: '10% de réduction',
  special_title: 'Offre du jour',
  special_description: 'Obtenez une réduction pour chaque commande de service !',
  special_note: 'Valable uniquement aujourd’hui !',
  special_percent: '30%',
  services_title: 'Nos Services',
  open_button: 'Ouvrir',
  service_type_title: 'Type de Service',
  recommended_title: 'Recommandé Pour Vous',
  recommended_name: 'Nettoyage Premium',
  recommended_name_secondary: 'Électricien Express',
  recommended_rating: '4,8 | 1 500+ avis',
  service_deliveries: 'Livraisons',
  service_home_visit: 'Rendez-vous à Domicile',
  home_visits_section_title: 'Rendez-vous à Domicile',
  home_visits_section_card_title: 'Rendez-vous a Domicile',
  home_visits_section_description: 'Reservez des professionnels de confiance pour vos services a domicile.',
  service_general_appointment: 'Rendez-vous Général',
  service_ride_sharing: 'Covoiturage',
  recommended_price: '${{price}}/h',
  recommended_reviews: '{{count}}+ avis',
  splash_title: 'Livraison de Nourriture',
  loading: 'Chargement...',
  splash_progress: '{{value}}%',
  developer_mode: 'Dev Mode',
  developer_mode_subtitle: 'Outils système et diagnostics',
  developer_mode_welcome: 'Bienvenue en mode développeur. D’autres outils de diagnostic seront bientôt disponibles.',
  driver_profile_button: 'Profil conducteur',
  auth_flow_button: 'Parcours auth',
  rider_chat_button: 'Chat livreur',
  dev_auth_title: 'Espace Auth',
  dev_auth_description: 'Outils temporaires pour inscription et session.',
  dev_auth_mode_signup: 'Inscription',
  dev_auth_mode_login: 'Connexion',
  dev_auth_phone_label: 'Téléphone',
  dev_auth_phone_placeholder: '+923001234567',
  dev_auth_otp_label: 'OTP',
  dev_auth_otp_placeholder: '123456',
  dev_auth_name_label: 'Nom',
  dev_auth_name_placeholder: 'John Doe',
  dev_auth_password_label: 'Mot de passe',
  dev_auth_password_placeholder: 'password123',
  dev_auth_push_token_label: 'Jeton Push',
  dev_auth_push_token_placeholder: 'fcm-token-here',
  dev_auth_referral_label: 'Code de parrainage',
  dev_auth_referral_placeholder: 'REF123',
  dev_auth_send_otp_button: 'Envoyer OTP',
  dev_auth_send_login_otp_button: 'Envoyer OTP Connexion',
  dev_auth_verify_button: 'Vérifier OTP et créer',
  dev_auth_login_button: 'Vérifier OTP et se connecter',
  dev_auth_logout_button: 'Se déconnecter',
  dev_auth_status_label: 'Statut de session',
  dev_auth_status_user: 'Utilisateur : {{name}}',
  dev_auth_status_working: 'Traitement de la requête...',
  dev_auth_status_otp_sent: 'OTP envoyé. Vérifiez pour terminer.',
  dev_auth_status_verified: 'Inscription vérifiée. Session enregistrée.',
  dev_auth_status_failed: 'Échec de la requête. Voir l’erreur ci-dessous.',
  dev_auth_status_signed_in: 'Session active.',
  dev_auth_status_signed_out: 'Aucune session active.',
  login_to_continue: 'Connectez-vous pour continuer',
  login_to_continue_desc: 'Veuillez vous connecter pour enregistrer vos informations de livraison et garantir un paiement fluide et sécurisé.',
  continue_with_phone: 'Continuer avec le téléphone',
  continue_with_apple: 'Continuer avec Apple',
  continue_with_google: 'Continuer avec Google',
  continue_with_email: 'Continuer avec l’e-mail',
  or: 'ou',
  dont_have_an_account: 'Vous n’avez pas de compte ?',
  signup: 'Créer un compte',
  continue: 'Continuer',
  enter_your_phone: 'Connectez-vous facilement en entrant votre téléphone !',
  login_desc: 'Nous allons vérifier si vous avez déjà un compte',
  verify_your_phone_number: 'Vérifiez votre numéro de téléphone',
  verify_otp: 'Vérifier le code',
  enter_otp_sent_to: 'Entrez le code envoyé à {{contact}}',
  didnt_receive_the_code: 'Vous n’avez pas reçu le code ?',
  resend_in: 'Renvoyer dans',
  try_another_way: 'Essayer une autre méthode',
  resend: 'Renvoyer',
  incorrect_code: 'Le code saisi est incorrect.',
  get_started: 'Commençons',
  get_started_desc: 'Créons d’abord votre compte',
  create_account: 'Créer un compte',
  name: 'Nom',
  email: 'E-mail',
  password: 'Mot de passe',
  sms_verification: 'Envoyer le code par SMS',
  call_verification: 'Envoyer le code par appel',
  email_verification: 'Envoyer le code par e-mail',
  too_many_attempts: 'Trop de tentatives',
  too_many_attempts_desc: 'Nous avons temporairement bloqué les nouvelles tentatives pour protéger votre compte. Réessayez dans 5 minutes.',
  ok: 'OK',
  enter_your_email: 'Connectez-vous facilement en entrant votre e-mail !',
  enter_your_password: 'Entrez votre mot de passe',
  email_already_exist: 'Votre e-mail existe déjà.',
  remember_me: 'Se souvenir de moi',
  forget_password: 'Mot de passe oublié ?',
  invalid_password: 'Mot de passe invalide',
  enter_correct_password: 'Veuillez saisir le bon mot de passe.',
  forget_password_desc: 'Saisissez votre e-mail et nous vous enverrons un code pour réinitialiser votre mot de passe.',
  create_new_password: 'Créez votre nouveau mot de passe',
  create_password_desc: 'Définissez un nouveau mot de passe et confirmez-le.',
  enter_new_password: 'Entrez le nouveau mot de passe',
  confirm_new_password: 'Confirmez le nouveau mot de passe',
  set_new_password: 'Définir le nouveau mot de passe',
  verify_your_email: 'Vérifiez votre e-mail',
  enter_strong_password: 'Veuillez saisir un mot de passe fort.',
  password_not_matched: 'Assurez-vous que vos mots de passe correspondent',
  something_went_wrong: 'Un problème est survenu.',
  location_popup_title: 'Accès à la localisation',
  location_popup_description:
    'Utilisez la localisation de l’appareil pour afficher les magasins proches, la disponibilité de livraison et les offres pertinentes.',
  location_popup_denied_title: 'Autorisation refusée',
  location_popup_denied_description:
    'L’accès à la localisation est toujours désactivé. Autorisez-le pour afficher les magasins proches et la disponibilité exacte de livraison.',
  location_popup_blocked_title: 'Activez la localisation dans les réglages',
  location_popup_blocked_description:
    'L’accès à la localisation est désactivé pour cette application. Ouvrez les réglages pour autoriser la localisation sur votre appareil.',
  location_popup_enable: 'Activer la localisation',
  location_popup_try_again: 'Réessayer',
  location_popup_open_settings: 'Ouvrir les réglages',
  location_popup_later: 'Plus tard',
  address_list_title: 'Mes adresses',
  address_add_title: 'Ajouter une adresse',
  address_edit_title: "Modifier l'adresse",
  address_search_placeholder: 'Rechercher une adresse',
  address_choose_on_map: 'Choisir sur la carte',
  address_popular_places: 'Lieux populaires',
  address_recent_searches: 'Recherches récentes',
  address_no_results: 'Aucun résultat trouvé',
  address_confirm_location: "Confirmer l'emplacement",
  address_locating: 'Localisation…',
  address_selected_location: 'Emplacement sélectionné',
  address_location_name_placeholder: 'Nom du lieu (ex. Ma maison)',
  address_details_label: "Détails de l'adresse",
  address_location_type_label: 'Type de lieu',
  address_location_details_label: 'Détails du lieu',
  address_home_details_title: 'Détails du domicile',
  address_apartment_details_title: "Détails de l'appartement",
  address_office_details_title: 'Détails du bureau',
  address_field_house_flat_number: 'Maison / Numéro d’appartement',
  address_field_apartment_flat: 'Appartement / Flat',
  address_field_area_street: 'Zone / Rue',
  address_field_society_building_name: 'Résidence / Nom du bâtiment',
  address_field_company_building_name: 'Entreprise / Nom du bâtiment',
  address_field_floor_tower_optional: 'Étage / Tour (Facultatif)',
  address_field_floor_suite_unit_optional: 'Étage / Suite / Unité (Facultatif)',
  address_field_department_optional: 'Service (Facultatif)',
  address_field_landmark_optional: 'Repère (Facultatif)',
  address_detail_house_placeholder: 'Maison',
  address_detail_apartment_placeholder: 'Appartement / Flat',
  address_detail_office_placeholder: 'Bureau / Immeuble',
  address_detail_company_building_placeholder: 'ex. ABC Technologies',
  address_detail_floor_suite_unit_placeholder: 'ex. 2e étage, Suite 201',
  address_detail_place_placeholder: 'Lieu',
  address_detail_society_placeholder: 'Société / Résidence',
  address_detail_floor_placeholder: 'Étage / Tour',
  address_detail_department_placeholder: 'Service / Étage',
  address_detail_area_placeholder: 'Zone / Rue',
  address_detail_landmark_placeholder: 'Repère',
  address_optional_suffix: '(facultatif)',
  address_set_as_default: 'Définir comme adresse par défaut',
  address_type_home: 'Domicile',
  address_type_apartment: 'Appartement',
  address_type_office: 'Bureau',
  address_type_other: 'Autre',
  address_choose_title: 'Choisir le lieu de livraison',
  address_save: "Enregistrer l'adresse",
  address_update: "Mettre à jour l'adresse",
  address_delete: 'Supprimer',
  address_delete_confirm_title: "Supprimer l'adresse",
  address_delete_confirm_message: 'Êtes-vous sûr de vouloir supprimer cette adresse ?',
  address_delete_cancel: 'Annuler',
  address_delete_confirm: 'Supprimer',
  address_save_error: "Impossible d'enregistrer l'adresse.",
  address_select_error: "Impossible de sélectionner l'adresse.",
  address_delete_error: "Impossible de supprimer l'adresse.",
  address_delete_linked_orders_error:
    "Cette adresse ne peut pas être supprimée car elle est liée à des commandes existantes.",
  address_save_success: 'Adresse enregistrée avec succès.',
  address_update_success: 'Adresse mise à jour avec succès.',
  address_delete_success: 'Adresse supprimée avec succès.',
  address_selector_title: 'Emplacement',
  address_selector_close: "Fermer le sélecteur d'emplacement",
  address_selector_use_current_location: 'Utiliser ma position actuelle',
  address_selector_add_new: 'Ajouter une nouvelle adresse',
  address_selector_search_address: 'Rechercher une adresse',
  profile_personal_account: 'Compte personnel',
  profile_wallet_balance: 'Solde du portefeuille',
  profile_view_wallet: 'Voir le portefeuille',
  profile_section_essentials: 'Vos essentiels',
  profile_section_preferences: 'Préférences',
  profile_section_more: 'Plus',
  profile_menu_orders: 'Commandes',
  profile_menu_orders_subtitle: 'Suivez vos livraisons actuelles et passées',
  profile_menu_addresses: 'Adresses',
  profile_menu_addresses_subtitle: 'Choisissez où recevoir vos commandes',
  profile_menu_favorites_subtitle: 'Retrouvez les magasins que vous aimez',
  profile_menu_profile: 'Profil',
  profile_menu_notifications: 'Notifications',
  profile_menu_favorites: 'Favoris',
  profile_menu_coupons: 'Coupons',
  profile_menu_settings: 'Paramètres',
  profile_menu_support: 'Assistance',
  profile_menu_color_mode: 'Mode couleur',
  profile_menu_language: 'Langue',
  profile_menu_logout: 'Se déconnecter',
  profile_logout_confirm_title: 'Se déconnecter ?',
  profile_logout_confirm_description: 'Vous devrez vous reconnecter pour commander, consulter votre profil ou gérer vos livraisons.',
  profile_logout_confirm_action: 'Oui, me déconnecter',
  profile_logout_confirm_cancel: 'Rester connecté',
  profile_logout_confirm_error: 'Impossible de vous déconnecter. Vérifiez votre connexion et réessayez.',
  notifications_title: 'Notifications',
  notifications_section_today: "Aujourd'hui",
  notifications_section_past: 'Passées',
  notifications_show_more: 'Afficher plus',
  notifications_empty_title: 'Aucune notification pour le moment',
  notifications_empty_description: 'Vos dernières mises à jour apparaîtront ici dès leur arrivée.',
  notifications_today_appointment_title: 'Votre rendez-vous chez Style Haven est confirmé.',
  notifications_today_appointment_subtitle: "À l'instant.",
  notifications_today_location_title: 'Votre nettoyage à domicile est confirmé : rendez-vous chez Style Haven.',
  notifications_today_location_subtitle: 'Il y a quelques heures.',
  notifications_today_payment_title: 'Paiement reçu : 65,00 QR pour votre nettoyage à domicile chez Style Haven.',
  notifications_today_payment_subtitle: "Il est 20:19, parfait pour une sortie du soir !",
  notifications_past_offer_title: 'Offre spéciale : profitez de 15 % de réduction sur vos deux prochaines visites !',
  notifications_past_offer_subtitle: 'Le 12 sept. à 20:19, votre rendez-vous a été planifié.',
  notifications_past_rating_title: "N'oubliez pas d'évaluer votre récent nettoyage à domicile chez Style Haven !",
  notifications_past_rating_subtitle: 'Le 24 août à 20:19, vous avez eu un excellent nettoyage à domicile.',
  notifications_past_receipt_title: 'Votre reçu pour le nettoyage à domicile #2957 est maintenant disponible.',
  notifications_past_receipt_subtitle: 'Le 04 août à 20:19, vous avez apprécié une coupe fraîche.',
  my_profile_title: 'Mon profil',
  my_profile_edit: 'Modifier',
  my_profile_full_name: 'Nom complet',
  my_profile_date_of_birth: 'Date de naissance',
  my_profile_mobile_number: 'Numéro de téléphone',
  my_profile_email: 'E-mail',
  my_profile_my_addresses: 'Mes adresses',
  my_profile_add_address: 'Ajouter une adresse',
  my_profile_address_home: 'Domicile',
  my_profile_address_apartment: 'Appartement',
  my_profile_address_work: 'Travail',
  my_profile_address_other: 'Autre',
  photo_modal_title: 'Photo de profil',
  photo_modal_description: 'Choisissez comment mettre à jour votre photo de profil',
  photo_take_photo: 'Prendre une photo',
  photo_choose_gallery: 'Choisir dans la galerie',
  photo_cancel: 'Annuler',
  photo_permission_title: 'Autorisation requise',
  photo_permission_camera: "L'accès à la caméra est nécessaire pour prendre une photo de profil ou joindre une photo dans l'assistance et le chat.",
  photo_permission_gallery: "L'accès à la photothèque est nécessaire pour choisir une photo de profil ou joindre une photo existante dans l'assistance et le chat.",
  photo_upload_error_title: 'Échec du téléchargement',
  photo_upload_failed: 'Impossible de mettre à jour la photo de profil.',
  edit_profile_title: 'Modifier le profil',
  edit_profile_name: 'Nom',
  edit_profile_date_of_birth: 'Date de naissance',
  edit_profile_day: 'Jour',
  edit_profile_month: 'Mois',
  edit_profile_year: 'Année',
  edit_profile_gender: 'Genre',
  edit_profile_gender_placeholder: 'Sélectionner une option',
  edit_profile_save: 'Enregistrer',
  edit_profile_success: 'Succès',
  edit_profile_success_message: 'Profil mis à jour avec succès.',
  edit_profile_error: 'Erreur',
  edit_profile_name_required: 'Le nom est requis.',
  edit_profile_failed: 'Impossible de mettre à jour le profil.',
  settings_title: 'Paramètres',
  settings_notifications: 'Paramètres de notifications',
  settings_change_password: 'Changer le mot de passe',
  settings_privacy_policy: 'Politique de confidentialité',
  settings_terms_of_service: "Conditions d'utilisation",
  settings_terms_of_use: "Conditions d'usage",
  settings_about_us: 'À propos de nous',
  settings_how_it_works: 'Comment ça marche',
  settings_contact_us: 'Nous contacter',
  settings_delete_account: 'Supprimer le compte',
  settings_app_version: "Version de l'application 1.0.0",
  // Notification settings screen
  notif_settings_title: 'Paramètres de notifications',
  notif_settings_food_delivery: 'Livraison de nourriture',
  notif_settings_marketing: 'Marketing',
  notif_settings_email: 'E-mail',
  notif_settings_sms: 'SMS',
  notif_settings_whatsapp: 'WhatsApp',
  notif_settings_success_title: 'Enregistré',
  notif_settings_success_message: 'Préférence de notification mise à jour.',
  notif_settings_error_title: 'Erreur',
  // Privacy Policy screen
  privacy_title: 'Politique de confidentialité',
  privacy_last_updated: 'Dernière mise à jour il y a 2 mois',
  privacy_intro:
    "Cette politique de confidentialité explique comment nous traitons vos informations personnelles lors de l'utilisation de l'application de livraison de nourriture. En vous inscrivant ou en accédant à l'application, vous consentez aux pratiques décrites dans cette politique.",
  privacy_section_app_title: "Politique de confidentialité pour l'application",
  privacy_section_app_body:
    "L'application de livraison de nourriture s'engage à protéger et gérer vos données personnelles et commandes en toute sécurité. Vous êtes autorisé à utiliser l'application à des fins personnelles et commerciales, sous réserve de respecter cette politique et toutes les lois applicables.",
  privacy_section_responsibilities_title: 'Responsabilités des utilisateurs',
  privacy_section_responsibilities_body:
    "Les utilisateurs sont responsables de l'exactitude de leurs adresses de livraison et de leurs informations de paiement. Il est important de maintenir ces informations à jour pour éviter tout problème lors du processus de commande.",
  privacy_section_data_title: 'Collecte de données',
  privacy_section_data_body:
    "L'application de livraison de nourriture collecte des données essentielles pour améliorer votre expérience, notamment votre localisation, l'historique de vos commandes et vos préférences.",
  privacy_section_modifications_title: 'Modifications de commande',
  privacy_section_modifications_body:
    "Vous pouvez modifier ou annuler vos commandes via l'application avant qu'elles ne soient traitées. Une fois une commande confirmée, les modifications peuvent ne pas être possibles.",
  privacy_section_payment_title: 'Sécurité des paiements',
  privacy_section_payment_body:
    "Nous accordons la priorité à la sécurité de vos informations de paiement. Toutes les transactions effectuées via l'application sont traitées à l'aide d'une technologie de chiffrement standard.",
  privacy_section_contact_title: 'Nous contacter',
  privacy_section_contact_body: 'Si vous avez des questions sur ces conditions, n\'hésitez pas à nous contacter :',
  privacy_contact_email: 'E-mail : contact@fooddelivery.com',
  privacy_contact_address: 'Adresse : Doha, Qatar',
  // Terms and Conditions screen — mirrors sipp-web's /terms page verbatim.
  // Kept in English only: per the source document's own "Controlling
  // Language" clause, Spanish/English govern regardless of UI locale
  // (sipp-web's own French/German build keeps this page in English too).
  tos_title: 'Terms and Conditions',
  tos_subtitle:
    'Costa Rica — Applicable to Users, Restaurant Partners and Delivery Partners.',
  tos_last_updated: 'Last updated: July 14, 2026',
  tos_preamble_title: 'Preamble and Parties',
  tos_preamble_paragraphs: [
    'These Terms and Conditions (the "Terms") govern access to and use of the SIPP Delivery mobile application and website (the "Application" or the "Platform") by any person who registers for or interacts with it in any of the following capacities: (a) a customer requesting Delivery Services ("User"); (b) a commercial establishment listed on the Application ("Restaurant Partner"); or (c) a person providing Delivery Services through the Application ("Delivery Partner"). Collectively, "You."',
    'The Platform is locally operated by SIPP Delivery S.A., a corporation (sociedad anónima) organized under the laws of the Republic of Costa Rica, cédula jurídica 3-101-954829 ("SIPP CR," "SIPP," "we"), acting as local operating agent and under license from SIPP Delivery LLC, a limited liability company organized under the laws of the State of Delaware, United States of America, EIN 36-5182139, with registered agent office at 8 The Green, Suite B, Dover, Delaware 19901 ("SIPP US"), the global owner of the "SIPP Delivery" brand, the Application, the software, the databases and other intellectual property associated with the Platform.',
    'These Terms are entered into solely between You and SIPP CR. SIPP US is not a party to these Terms and assumes no obligation to You hereunder; however, SIPP US may directly enforce Sections 18 (Intellectual Property), 22 (Confidentiality) and 23 (Limitation of Liability) as a third-party beneficiary.',
  ],
  tos_definitions_title: '1. Definitions',
  tos_definitions: [
    { term: 'Application or Platform', description: 'the SIPP Delivery mobile application and website and related systems and support.' },
    { term: 'User', description: 'a person who requests Delivery Services through the Application as an end consumer.' },
    { term: 'Restaurant Partner', description: 'an establishment listed on the Application offering products for purchase by Users.' },
    { term: 'Delivery Partner', description: 'a person who, as an independent contractor, provides Delivery Services through the Application.' },
    { term: 'Delivery Services', description: 'the collection, transport and delivery of goods requested by Users through the Application.' },
    { term: 'Restaurant Partner Agreement', description: 'the bilateral agreement executed between a Restaurant Partner and SIPP CR governing the specific commercial terms of that relationship.' },
    { term: 'Delivery Partner Agreement', description: 'the bilateral agreement executed between a Delivery Partner and SIPP CR governing the specific terms of that independent-contractor relationship.' },
    { term: 'Content', description: 'text, images, ratings, comments and other material You post or upload to the Application.' },
    { term: 'Account', description: 'the registration profile You create to access the Application.' },
  ],
  tos_sections: [
    { heading: '2. Acceptance of the Terms', paragraphs: ['By creating an Account, or by downloading, accessing or using the Application in any capacity, You represent that You have read, understood and accepted these Terms and that You have legal capacity to contract under Costa Rican law. If You act on behalf of a legal entity (for example, a Restaurant Partner), You represent that You have sufficient authority to bind it. If You do not accept these Terms, You must refrain from using the Application.'] },
    { heading: '3. Description of the Platform and Roles', paragraphs: ['SIPP CR operates a digital marketplace connecting Users, Restaurant Partners and Delivery Partners. SIPP CR does not prepare or sell food, is not a carrier, and is not the employer of Delivery Partners. SIPP CR acts as a technology intermediary and, in the cases described in these Terms, as a limited collection and payment agent on behalf of Restaurant Partners and Delivery Partners.'] },
    { heading: '4. Eligibility and Registration', paragraphs: ['To use the Application, You must: (a) be at least eighteen (18) years old; (b) provide truthful, complete and up-to-date information upon registration; (c) maintain only one active Account per person, unless expressly authorized by SIPP; and (d) comply with the additional eligibility requirements applicable to Your role, described below. SIPP CR may perform reasonable identity and documentation verifications.'] },
    { heading: '5. Account', paragraphs: ['You are responsible for maintaining the confidentiality of your access credentials and for all activity under Your Account. You must notify SIPP immediately of any unauthorized use. SIPP will not be liable for losses arising from unauthorized use of Your Account where such use results from Your negligence in safeguarding your credentials.'] },
    { heading: 'Part A — Terms Applicable to Users (Customers)', paragraphs: [] },
    { heading: '6. Order Formation', paragraphs: ['An order placed by a User through the Application constitutes an offer to purchase directed to the relevant Restaurant Partner. The sales contract for the products is formed directly between the User and the Restaurant Partner upon the latter\'s acceptance of the order. SIPP CR is not a party to that sales contract and does not warrant the availability, quality, safety or conformity of products offered by Restaurant Partners.'] },
    { heading: '7. Prices, Delivery Fees and Payments', paragraphs: ['Product prices are set by each Restaurant Partner. The applicable delivery fee is displayed on the Application before order confirmation. All amounts are expressed in Costa Rican colones (₡), unless another currency is expressly indicated. All payments are processed exclusively by electronic means through the Application; cash payments are not accepted. You designate SIPP CR as a limited collection agent, solely to receive on your behalf, and remit to the relevant Restaurant Partners and Delivery Partners, the amounts due to them.'] },
    { heading: '8. Cancellations, Refunds and Disputes', paragraphs: ["You may cancel an order free of charge before the Restaurant Partner accepts it. Once accepted, cancellation may be subject to a charge reflecting costs already incurred. For incorrect, damaged, incomplete or undelivered orders, You may submit a claim through the Application's support channel within a reasonable period; SIPP CR will evaluate the claim in good faith and, where warranted, process the corresponding full or partial refund, without prejudice to the direct liability that may lie with the responsible Restaurant Partner or Delivery Partner."] },
    { heading: '9. Delivery and Risk', paragraphs: ['Delivery is performed by independent Delivery Partners who are not employees of SIPP CR or SIPP US. Risk of loss or damage to products transfers to the User upon delivery, or upon completion of a contactless delivery instruction ("leave at door") specified by the User. You must provide an accurate, accessible and safe delivery address.'] },
    { heading: '10. Ratings and User-Generated Content', paragraphs: ['You may rate and comment on Delivery Services and products received. SIPP CR may moderate, hide or remove Content that is defamatory, false, discriminatory, or that infringes third-party rights. You grant SIPP CR a non-exclusive, worldwide, royalty-free license to use such Content within the Platform for purposes of operating, improving and promoting the service.'] },
    { heading: '11. Consumer Protection', paragraphs: ['Nothing in these Terms limits the non-waivable rights that Law No. 7472, Law for the Promotion of Competition and Effective Consumer Protection, and its Regulations, grant You as a consumer. In the event of a conflict between a provision of these Terms and such regulations, the consumer protection regulations shall prevail.'] },
    { heading: 'Part B — Terms Applicable to Restaurant Partners', paragraphs: [] },
    { heading: '12. Contractual Relationship and Precedence', paragraphs: ["A commercial establishment's access to the Platform as a Restaurant Partner requires execution of a separate Restaurant Partner Agreement with SIPP CR, which governs the applicable commission, settlement schedule and other commercial terms specific to that relationship. In the event of a conflict between the executed Restaurant Partner Agreement and these Terms regarding individually negotiated commercial terms (including, without limitation, commission, the duration of founding-partner terms, and the form and frequency of payment), the Restaurant Partner Agreement shall prevail. These Terms govern, on a complementary and general basis, all matters relating to use of the Application, conduct on the Platform, intellectual property, data protection and the other general provisions applicable to all Platform users."] },
    { heading: '13. Menu Content and Conduct', paragraphs: ['The Restaurant Partner is responsible for the accuracy of prices, product availability, allergen disclosure, and compliance with applicable health regulations. SIPP CR may suspend listings that violate the law, contain false information, or harm the reputation or operation of the Platform, upon notice where circumstances permit.'] },
    { heading: '14. Payments to Restaurant Partners', paragraphs: ['Commission, applicable deductions and the settlement schedule are governed by the executed Restaurant Partner Agreement. SIPP CR acts as a limited collection agent with respect to amounts paid by Users that are due to the Restaurant Partner.'] },
    { heading: 'Part C — Terms Applicable to Delivery Partners', paragraphs: [] },
    { heading: '15. Contractual Relationship and Precedence', paragraphs: ['Access to the Application as a Delivery Partner requires execution of a separate Delivery Partner Agreement, which confirms the independent-contractor relationship between the Delivery Partner and SIPP CR (no subordination, no exclusivity, no employment benefits) and governs the Delivery Fee, the Subscription Cost, and the settlement schedule. In the event of a conflict between the executed Delivery Partner Agreement and these Terms regarding such economic terms or the nature of the relationship, the Delivery Partner Agreement shall prevail.'] },
    { heading: '16. Delivery Partner Conduct', paragraphs: ['The Delivery Partner must perform Delivery Services in a professional and diligent manner, comply with applicable traffic regulations, refrain from soliciting or accepting cash payments, and use the Application solely for the purposes authorized under the Delivery Partner Agreement.'] },
    { heading: '17. Payments to Delivery Partners', paragraphs: ['The Delivery Fee, tips, the Subscription Cost and the settlement schedule are governed by the executed Delivery Partner Agreement.'] },
    { heading: 'General Provisions (Applicable to All Roles)', paragraphs: [] },
    { heading: '18. Intellectual Property', paragraphs: ['The Application, the software, the databases, the design, the "SIPP Delivery" trademarks, and all Platform content (excluding Content generated by You) are the exclusive property of SIPP US or its licensors, and are protected by Costa Rican and international intellectual property law. Nothing in these Terms transfers any ownership right in such assets to any User, Restaurant Partner or Delivery Partner.'] },
    { heading: '19. Limited License to Use', paragraphs: ['Subject to Your compliance with these Terms, SIPP CR grants You a limited, non-exclusive, non-transferable, non-sublicensable and revocable license to use the Application in accordance with Your role. You may not copy, modify, reverse engineer, sublicense, resell, use automated means to access the Application ("scraping"), or use it to develop a competing product or service.'] },
    { heading: '20. Prohibited Conduct', paragraphs: ['The following are prohibited: (a) fraud or rating manipulation; (b) creating or using unauthorized multiple accounts; (c) posting illegal or defamatory content, or content that infringes third-party rights; (d) harassing other Platform users; and (e) breaching, overloading or interfering with the security or operation of the Application.'] },
    { heading: '21. Personal Data Protection', paragraphs: ["SIPP CR processes the personal data of Users, Restaurant Partners and Delivery Partners in accordance with Law No. 8968, Law on the Protection of Individuals with regard to the Processing of their Personal Data, and SIPP's Privacy Policy available on the Application. You consent to the collection, use and, where applicable, disclosure of Your personal data (including Your location while using the Application) to operate the Platform, facilitate Delivery Services, ensure security, and comply with legal obligations. You may exercise Your rights of access, rectification, cancellation and objection under that Policy."] },
    { heading: '22. Confidentiality', paragraphs: ['Non-public information that SIPP CR shares with Restaurant Partners or Delivery Partners through support channels, administrative dashboards or other means (for example, operational or commercial Platform data) must be kept confidential and used solely for the purposes of the relationship with SIPP CR.'] },
    { heading: '23. Limitation of Liability', paragraphs: ["Without prejudice to Section 11, and to the maximum extent permitted by applicable law: neither SIPP CR nor SIPP US shall be liable for indirect, incidental, special, punitive or consequential damages, or for loss of profits, revenue, business or data. SIPP CR does not warrant uninterrupted or error-free availability of the Application. SIPP CR's aggregate liability to a Restaurant Partner or Delivery Partner shall be governed by the limit set forth in the applicable bilateral Agreement; to a User, it shall not exceed the amount of service fees paid by that User through the Application in the three (3) months preceding the event giving rise to the claim, except where consumer protection law provides otherwise."] },
    { heading: '24. Indemnification', paragraphs: ["Each User, Restaurant Partner and Delivery Partner shall indemnify, defend and hold harmless SIPP CR and SIPP US, and their respective officers, directors, employees and agents, from any claim, liability, damage, loss or expense (including reasonable attorneys' fees) arising from: (a) their breach of these Terms or of the applicable bilateral Agreement; (b) their negligent or willful acts or omissions; or (c) any third-party claim arising from their interaction with the Platform."] },
    { heading: '25. Account Suspension and Termination', paragraphs: ['SIPP CR may suspend or deactivate access to the Application for any Account that breaches these Terms, engages in fraud or unsafe conduct, or poses a risk to the Platform or third parties, with notice where circumstances permit. The foregoing is without prejudice to the specific suspension and termination rights and procedures set out in the applicable Restaurant Partner Agreement or Delivery Partner Agreement, which shall prevail as to those Partners.'] },
    { heading: '26. Modifications to these Terms', paragraphs: ['SIPP CR may modify these general Terms from time to time, with reasonable notice through the Application or by email. Continued use of the Application after a modification takes effect constitutes acceptance of it.', 'No modification to these general Terms may, by itself, alter the specific, individually negotiated commercial terms of an existing Restaurant Partner Agreement or Delivery Partner Agreement (including, without limitation, commissions or fees fixed for a set period). Such Agreements may only be modified in accordance with their own terms.'] },
    { heading: '27. Force Majeure', paragraphs: ['Neither party shall be liable for any failure or delay resulting from causes beyond its reasonable control, including natural disasters, government actions, labor disputes, or telecommunications or internet infrastructure failures.'] },
    { heading: '28. Governing Law and Dispute Resolution', paragraphs: ['These Terms are governed by the laws of the Republic of Costa Rica.', 'Disputes between SIPP CR and a Restaurant Partner or a Delivery Partner: shall first be addressed in good faith through the Application\'s support channel and, if unresolved, submitted to binding arbitration before the Arbitration and Conciliation Center of the Costa Rican Chamber of Commerce (CICA), seated in San José, as set out in the applicable bilateral Agreement.', 'Disputes with Users (consumers): shall first be addressed in good faith through the Application\'s support channel. If unresolved, the User may bring the matter before the National Consumer Commission or the ordinary courts of the Republic of Costa Rica.'] },
    { heading: '29. General Provisions', paragraphs: ["Assignment: You may not assign or transfer these Terms without SIPP CR's prior written consent; SIPP CR may freely assign or transfer them, including in connection with a merger, acquisition or sale of assets.", 'Severability: if any provision is found illegal, void or unenforceable, it shall be severed without affecting the validity of the remainder.', 'Electronic acceptance: these Terms may be accepted by electronic means, including by clicking "I Accept" in the Application, with the same legal validity as a handwritten signature, in accordance with Costa Rican legislation on digital signatures and electronic documents.', 'Entire agreement: these Terms, together with the Privacy Policy and, where applicable, the Restaurant Partner Agreement or Delivery Partner Agreement in effect, constitute the entire understanding between You and SIPP CR regarding their subject matter.', 'Notices: SIPP CR may notify You through the Application or the email address registered to Your Account.'] },
    { heading: '30. Controlling Language', paragraphs: ['These Terms have been drafted in Spanish and in English. In the event of any discrepancy or conflict between the two versions, the Spanish version shall prevail, as it is the version directed to the Costa Rican market and the one required under Costa Rican consumer protection legislation.'] },
  ],
  // Terms of Use screen
  tou_title: "Conditions d'usage",
  tou_last_updated: 'mise à jour il y a 2 mois',
  tou_intro:
    "Ces conditions d'utilisation définissent vos droits et responsabilités lors de l'utilisation de l'application.",
  tou_section_guidelines_title: "Directives d'utilisation",
  tou_section_guidelines_body:
    "L'application fournit une gestion sécurisée de vos commandes et données client.",
  tou_section_etiquette_title: 'Étiquette de livraison',
  tou_section_etiquette_body:
    'Les utilisateurs doivent maintenir le respect et la courtoisie envers le personnel de livraison.',
  tou_section_payment_title: 'Méthodes de paiement',
  tou_section_payment_body:
    "L'application prend en charge plusieurs méthodes de paiement, notamment les cartes de crédit et les portefeuilles numériques.",
  tou_section_cancellation_title: "Politique d'annulation",
  tou_section_cancellation_body:
    'Les commandes peuvent être annulées dans un délai de 10 minutes après leur passation.',
  tou_section_feedback_title: 'Commentaires et évaluations',
  tou_section_feedback_body:
    "Les utilisateurs sont encouragés à donner leur avis sur leur expérience de livraison.",
  tou_section_promotions_title: 'Promotions et offres',
  tou_section_promotions_body:
    "L'application peut proposer des promotions et des réductions soumises à des conditions spécifiques.",
  tou_section_contact_title: 'Nous contacter',
  tou_section_contact_body: 'Si vous avez des questions, n\'hésitez pas à nous contacter :',
  tou_contact_email: 'E-mail : contact@fooddelivery.com',
  tou_contact_address: 'Adresse : Doha, Qatar',
  // Change password flow
  change_password_title: 'Changer le mot de passe',
  change_password_new_title: 'Nouveau mot de passe',
  change_password_email_heading: 'Changer le mot de passe ?',
  change_password_email_description:
    'Entrez votre adresse e-mail et nous vous enverrons un code de vérification.',
  change_password_email_placeholder: 'votre@email.com',
  change_password_continue: 'Continuer',
  change_password_verify_heading: 'Vérifiez votre e-mail',
  change_password_verify_description: 'Entrez le code à 4 chiffres envoyé à {{email}}',
  change_password_verify_button: 'Vérifier le code',
  change_password_new_heading: 'Créez votre nouveau mot de passe',
  change_password_new_description: "Votre nouveau mot de passe doit être différent de l'ancien.",
  change_password_new_placeholder: 'Nouveau mot de passe',
  change_password_confirm_placeholder: 'Confirmer le mot de passe',
  change_password_set_new: 'Définir le nouveau mot de passe',
  change_password_mismatch: 'Les mots de passe ne correspondent pas.',
  change_password_error_title: 'Erreur',
  change_password_send_otp_error: "Échec de l'envoi du code de vérification.",
  change_password_verify_otp_error: 'Code invalide ou expiré.',
  change_password_update_error: 'Échec de la mise à jour du mot de passe.',
  change_password_success_title: 'Succès',
  change_password_success_message: 'Votre mot de passe a été mis à jour.',
  change_password_otp_resent_title: 'Code envoyé',
  change_password_otp_resent_message: 'Un nouveau code de vérification a été envoyé.',
  // Delete account flow
  delete_account_step_label: 'Supprimer mon compte',
  delete_account_sorry_heading: 'Nous serons désolés de vous voir partir',
  delete_account_sorry_subtext: 'Pouvons-nous vous faire changer d\'avis ? Contactez-nous à',
  delete_account_contact_email: 'hello@enategadelivery.com',
  delete_account_reason_heading: 'Pourquoi souhaitez-vous quitter Food delivery ?',
  delete_account_reason_subtext: 'Veuillez nous indiquer la raison de la suppression de votre compte :',
  delete_account_reason_mistake: 'J\'ai créé ce compte par erreur',
  delete_account_reason_no_longer: 'Je ne veux plus utiliser Food delivery',
  delete_account_reason_no_venues: 'Je ne trouve pas les établissements ou services que je veux',
  delete_account_reason_other: 'Autre',
  delete_account_confirm_heading: 'Supprimer votre compte Food delivery',
  delete_account_confirm_description: 'Cette action supprimera votre compte et vous ne pourrez pas le récupérer. Veuillez confirmer que vous comprenez en cochant les déclarations ci-dessous :',
  delete_account_confirm_item_orders: 'Je sais que je ne pourrai plus accéder à mes commandes.',
  delete_account_confirm_item_marketplace: 'Je sais que je ne pourrai plus passer de commandes via la marketplace Food delivery.',
  delete_account_final_heading: 'Confirmez que vous souhaitez continuer',
  delete_account_final_description: 'Veuillez noter que cette action est permanente et ne peut pas être annulée. Pour confirmer la suppression de votre compte, veuillez vérifier votre e-mail ci-dessous :',
  delete_account_email_label: 'E-mail',
  delete_account_email_placeholder: 'votre@email.com',
  delete_account_cta_continue: 'Continuer',
  delete_account_cta_delete: 'Supprimer le compte',
  delete_account_close: 'Fermer',
  delete_account_alert_title: 'Supprimer le compte',
  delete_account_alert_message: 'Êtes-vous sûr de vouloir supprimer définitivement votre compte ? Cette action est irréversible.',
  delete_account_alert_cancel: 'Annuler',
  delete_account_alert_confirm: 'Supprimer',
  delete_account_error_title: 'Erreur',
  delete_account_error: 'Échec de la suppression du compte. Veuillez réessayer.',
  color_mode_title: 'Mode couleur',
  color_mode_section_label: 'Sélectionner le mode couleur',
  color_mode_system: 'Système par défaut',
  color_mode_light: 'Clair',
  color_mode_dark: 'Sombre',
  language_title: "Langues de l'application",
  language_section_label: 'Sélectionner la langue',
  language_english: 'Anglais',
  language_french: 'Français',
  offline_notice_title: 'Vous êtes hors ligne',
  offline_notice_description: 'Reconnectez-vous pour actualiser les trajets, tarifs et données en direct.',
  clear_all: 'Tout effacer',
  filter_title: 'Filtrer',
  filter_close_label: 'Fermer les filtres',
  filter_apply_results: 'Appliquer les filtres',
  generic_list_error_title: 'Impossible de charger les résultats',
  generic_list_error_description: 'Actualisez ou réessayez.',
  generic_list_retry: 'Réessayer',
  generic_list_empty_title: 'Aucun résultat trouvé',
  generic_list_empty_description: 'Essayez une autre recherche ou modifiez vos filtres.',
  generic_list_results_count: '{{count}} résultat',
  generic_list_results_count_plural: '{{count}} résultats',
  generic_list_search_placeholder: 'Recherche',
  search_clear_label: 'Effacer la recherche',
  search_screen_title: 'Trouvez exactement ce qu’il vous faut',
  search_screen_subtitle: 'Recherchez les commerces, plats et essentiels à proximité.',
  search_screen_input_placeholder: 'Rechercher commerces, plats et essentiels',
  search_suggestions_title: 'Populaire près de chez vous',
  search_delete_recent_label: 'Supprimer {{term}} des recherches récentes',
  see_all_map_loading_title: 'Recherche de {{title}}',
  see_all_map_loading_description: 'Cela peut prendre quelques instants. Veuillez rester sur cet écran.',
  see_all_map_sheet_title: 'Restaurant',
  see_all_map_cta: 'Voir le restaurant',
  see_all_back_label: 'Retour',
  navigation_back: 'Retour',
  see_all_open_filters_label: 'Ouvrir les filtres',
  see_all_map_view_label: 'Vue carte',
  // Search components translations
  no_results_found: 'Aucun résultat trouvé',
  recent_searches: 'Recherches récentes',
  searching_near: 'Recherche près de',
  multi_vendor_address_label: 'Sélectionner une adresse',
  // Search filter translations
  search_filter_title: 'Filtres de recherche',
  search_filter_sort_by: 'Trier par',
  search_filter_sort_best_match: 'Meilleure correspondance',
  search_filter_sort_top_rated: 'Mieux notés',
  search_filter_sort_nearest: 'Plus proches',
  search_filter_ratings: 'Note minimum',
  search_filter_availability: 'Disponibilité',
  search_filter_availability_standard: 'Standard',
  search_filter_availability_emergency: 'Urgence',
  search_filter_stars: 'étoiles',
  filter_button_label: 'Options de filtre',
  search_input_placeholder: "Rechercher n'importe quoi",
  Recommended_restaurants: 'Restaurants recommandés',
  home_drive_banners_title: 'Offres Drive',
  // About Us screen
  about_title: "Nous construisons l'infrastructure de livraison de la côte du Costa Rica.",
  about_subtitle: 'Tant d\'options. Zéro effort.',
  about_origin_title: 'Pourquoi nous avons commencé',
  about_origin_paragraphs: [
    "SIPP est une plateforme de livraison locale créée pour une raison simple : rendre la commande de repas, d'épicerie et de produits essentiels facile — là où la livraison traditionnelle n'a jamais vraiment fonctionné.",
    "Nous avons commencé à Santa Teresa, au Costa Rica, où touristes, habitants, villas et restaurants font tous face au même problème : d'excellents plats, d'excellents lieux — mais des systèmes de livraison fragmentés, peu fiables et dépassés.",
    'SIPP change cela.',
    "Nous connectons restaurants, fournisseurs d'épicerie et commerces locaux au sein d'une seule plateforme intelligente qui permet aux clients de commander tout ce dont ils ont besoin au même endroit — des repas et snacks aux boissons, à l'épicerie et aux produits du quotidien — avec une livraison rapide, organisée et traçable.",
  ],
  about_different_title: 'Ce qui rend SIPP différent',
  about_different_intro:
    "SIPP n'est pas qu'une simple application de livraison de repas. C'est une plateforme de commerce local et de logistique conçue spécifiquement pour les régions côtières et à forte affluence touristique.",
  about_different_focus_label: 'Nous nous concentrons sur',
  about_different_items: [
    'Un large choix de restaurants et de partenaires locaux',
    "La livraison d'épicerie et de produits essentiels en plus des plats préparés",
    'Un service fiable, même tard le soir',
    'Une commande claire et facile à utiliser',
    'Des paiements par carte sécurisés',
    'Une logistique locale rapide et coordonnée',
    'Un fort accompagnement des restaurants et partenaires',
  ],
  about_different_outro:
    "Plutôt que d'imposer des modèles de livraison mondiaux à de petits marchés, nous avons conçu SIPP autour du fonctionnement réel de ces villes — saisonnalité, pics touristiques, fournisseurs locaux et logistique de courte distance.",
  about_different_result:
    "Le résultat est une plateforme qui profite à tous : les clients gagnent en commodité et en choix, les restaurants obtiennent plus de commandes et de visibilité, et les communautés locales bénéficient d'une infrastructure de livraison moderne.",
  about_local_title: 'Ancrés localement. Conçus pour grandir.',
  about_local_paragraphs: [
    'SIPP a été fondée et opère au Costa Rica. Notre équipe travaille chaque jour sur le terrain avec les restaurants, les livreurs, les supermarchés et les villas.',
    "Cette présence locale nous permet de maîtriser la qualité, les délais de livraison, l'intégration des partenaires et l'expérience client — tout en améliorant continuellement la plateforme.",
    "Dans le même temps, SIPP est conçue pour évoluer. Notre technologie, notre modèle logistique et notre structure de partenariat sont pensés pour s'étendre aux régions côtières, aux pôles touristiques et aux marchés de livraison émergents.",
  ],
  about_mission_title: 'Notre mission',
  about_mission_statement:
    'Devenir la principale plateforme de livraison et de commerce local sur le littoral du Costa Rica — et un acteur régional durable dans les marchés à forte affluence touristique.',
  about_mission_paragraphs: [
    "Nous construisons bien plus qu'une application.",
    'Nous construisons le système qui fait tourner le quotidien : repas, épicerie, restaurants et commerces locaux — tous réunis au même endroit.',
  ],
  about_tagline_label: 'SIPP en une phrase',
  about_tagline_value: 'Tant d\'options. Zéro effort.',
  // How It Works screen
  how_it_works_title: 'Comment ça marche ?',
  how_it_works_subtitle:
    "SIPP est une plateforme de livraison en ligne qui apporte les meilleures adresses de votre ville directement à votre porte. Nous connectons les clients aux commerces locaux – restaurants, cafés, bars, épiceries – et gérons la livraison grâce à notre équipe logistique pour vous apporter ce dont vous avez besoin, quand vous en avez besoin.",
  how_it_works_steps_title: 'Voici comment SIPP fonctionne en quatre étapes simples',
  how_it_works_steps: [
    {
      title: '1. Parcourir & Commander',
      description:
        "Rendez-vous sur notre plateforme depuis n'importe quel appareil (téléphone, tablette ou ordinateur) et voyez ce qui vous tente. Parcourez par catégorie ou recherchez un restaurant, une boutique, un plat ou un produit précis. Connectez-vous, ajoutez des articles à votre panier et passez commande en quelques clics. Vous pouvez payer en toute sécurité par carte bancaire – simple, rapide et sans espèces.",
    },
    {
      title: '2. Confirmation & Préparation',
      description:
        "Dès que vous commandez, nous transmettons automatiquement la demande au restaurant ou commerce choisi. Il donnera son accord et commencera à préparer vos articles avec soin. Qu'il s'agisse d'un plat chaud en cuisine ou de courses en cours d'emballage, nous veillons à ce que tout avance rapidement. C'est à ce moment que le statut de votre commande passera de En attente, à Acceptée puis à En préparation.",
    },
    {
      title: '3. En cours de livraison',
      description:
        'Dès que votre commande est prête, l\'un de nos livreurs SIPP entre en action. Il récupère votre commande et se dirige directement vers votre adresse. Vous pouvez suivre votre livraison en temps réel sur notre plateforme. N\'hésitez pas à célébrer un peu : vos articles sont en route !',
    },
    {
      title: '4. Livré & Bon appétit',
      description:
        "Ding-dong ! Votre livraison est arrivée. Notre livreur vous remettra votre commande à la porte. Il ne vous reste plus qu'à en profiter.",
    },
  ],
  how_it_works_delivery_area_title: 'Où livrons-nous ?',
  how_it_works_delivery_area_body:
    "Actuellement, SIPP opère à Santa Teresa, au Costa Rica, et dans les environs – de Manzanillo à Santiago, Playa Hermosa, Playa Carmen et Mal País. Nous sommes un service local, nous connaissons donc ces routes comme notre poche (oui, ce raccourci derrière le surf shop ? On le connaît). Bonne nouvelle : nous nous étendons bientôt ! SIPP arrivera prochainement à Nosara, restez à l'écoute.",
  how_it_works_closing_body:
    "En résumé, SIPP fonctionne comme les grandes applications de livraison – avec un supplément d'esprit Pura Vida. Nous sommes fiers d'être rapides, fiables et un peu géniaux (on peut bien le dire nous-mêmes). Faim ? Soif ? Plus de dentifrice ? Quoi qu'il vous faille – SIPP it.",
  // Contact Us screen
  contact_title: '📬 Nous contacter',
  contact_tagline: 'Des questions ? Une envie ? Une idée ?',
  contact_body:
    "Nous sommes à votre écoute — et sur la route pour vous. Que vous soyez un client affamé, un concierge curieux ou un restaurant prêt à nous rejoindre, nous serions ravis de vous entendre.",
  contact_whatsapp_title: '📱 WhatsApp ou appelez-nous',
  contact_whatsapp_subtitle: 'Le moyen le plus rapide de nous joindre — comme notre livraison.',
  contact_phone_display: '📞 +506 7044 5484 — Appuyez pour discuter ou appeler !',
  contact_email_title: '📩 Envoyez-nous un e-mail',
  contact_email_subtitle: 'Vous préférez tout écrire ?',
  contact_email_address: 'support@sippdelivery.com',
  contact_support_title: "🎫 Besoin d'aide avec une commande ?",
  contact_support_subtitle:
    'Un souci ou une question sur votre compte ou une commande ? Ouvrez un ticket et notre équipe s\'en occupera.',
  contact_support_cta: 'Créer un ticket',
  contact_address: 'Santa Teresa, Provincia de Puntarenas, Puntarenas, Costa Rica',
  contact_social_title: 'Suivez-nous',
  contact_error_generic: "Nous n'avons pas pu terminer cette action. Veuillez réessayer.",
};

export default fr;
