const fr = {
  app_name: 'Application Super Client',
  greeting: 'Bonjour 👋',
  greeting_morning: 'Bonjour 👋',
  greeting_afternoon: 'Bon après-midi 👋',
  greeting_evening: 'Bonsoir 👋',
  home_question: 'Que recherchez-vous aujourd’hui ?',
  home_title: 'Accueil',
  home_subtitle: 'Comment puis-je vous aider aujourd\'hui ?',
  special_offer_label: '10% de réduction',
  special_title: 'Offre du jour',
  special_description: 'Obtenez une réduction pour chaque commande de service !',
  special_note: 'Valable uniquement aujourd’hui !',
  special_percent: '30%',
  services_title: 'Nos Services',
  open_button: 'Ouvrir',
  service_type_title: 'Type de Service',
  recommended_title: 'Recommandé Pour Vous',
  recommended_name: 'Nettoyage Premium',
  recommended_name_secondary: 'Électricien Express',
  recommended_rating: '4,8 | 1 500+ avis',
  service_deliveries: 'Livraisons',
  service_home_visit: 'Rendez-vous à Domicile',
  home_visits_section_title: 'Rendez-vous à Domicile',
  home_visits_section_card_title: 'Rendez-vous a Domicile',
  home_visits_section_description: 'Reservez des professionnels de confiance pour vos services a domicile.',
  service_general_appointment: 'Rendez-vous Général',
  service_ride_sharing: 'Covoiturage',
  recommended_price: '${{price}}/h',
  recommended_reviews: '{{count}}+ avis',
  splash_title: 'Livraison de Nourriture',
  loading: 'Chargement...',
  splash_progress: '{{value}}%',
  developer_mode: 'Dev Mode',
  developer_mode_subtitle: 'Outils système et diagnostics',
  developer_mode_welcome: 'Bienvenue en mode développeur. D’autres outils de diagnostic seront bientôt disponibles.',
  driver_profile_button: 'Profil conducteur',
  auth_flow_button: 'Parcours auth',
  rider_chat_button: 'Chat livreur',
  dev_auth_title: 'Espace Auth',
  dev_auth_description: 'Outils temporaires pour inscription et session.',
  dev_auth_mode_signup: 'Inscription',
  dev_auth_mode_login: 'Connexion',
  dev_auth_phone_label: 'Téléphone',
  dev_auth_phone_placeholder: '+923001234567',
  dev_auth_otp_label: 'OTP',
  dev_auth_otp_placeholder: '123456',
  dev_auth_name_label: 'Nom',
  dev_auth_name_placeholder: 'John Doe',
  dev_auth_password_label: 'Mot de passe',
  dev_auth_password_placeholder: 'password123',
  dev_auth_push_token_label: 'Jeton Push',
  dev_auth_push_token_placeholder: 'fcm-token-here',
  dev_auth_referral_label: 'Code de parrainage',
  dev_auth_referral_placeholder: 'REF123',
  dev_auth_send_otp_button: 'Envoyer OTP',
  dev_auth_send_login_otp_button: 'Envoyer OTP Connexion',
  dev_auth_verify_button: 'Vérifier OTP et créer',
  dev_auth_login_button: 'Vérifier OTP et se connecter',
  dev_auth_logout_button: 'Se déconnecter',
  dev_auth_status_label: 'Statut de session',
  dev_auth_status_user: 'Utilisateur : {{name}}',
  dev_auth_status_working: 'Traitement de la requête...',
  dev_auth_status_otp_sent: 'OTP envoyé. Vérifiez pour terminer.',
  dev_auth_status_verified: 'Inscription vérifiée. Session enregistrée.',
  dev_auth_status_failed: 'Échec de la requête. Voir l’erreur ci-dessous.',
  dev_auth_status_signed_in: 'Session active.',
  dev_auth_status_signed_out: 'Aucune session active.',
  login_to_continue: 'Connectez-vous pour continuer',
  login_to_continue_desc: 'Veuillez vous connecter pour enregistrer vos informations de livraison et garantir un paiement fluide et sécurisé.',
  continue_with_phone: 'Continuer avec le téléphone',
  continue_with_apple: 'Continuer avec Apple',
  continue_with_google: 'Continuer avec Google',
  continue_with_email: 'Continuer avec l’e-mail',
  or: 'ou',
  dont_have_an_account: 'Vous n’avez pas de compte ?',
  signup: 'Créer un compte',
  continue: 'Continuer',
  enter_your_phone: 'Connectez-vous facilement en entrant votre téléphone !',
  login_desc: 'Nous allons vérifier si vous avez déjà un compte',
  verify_your_phone_number: 'Vérifiez votre numéro de téléphone',
  verify_otp: 'Vérifier le code',
  enter_otp_sent_to: 'Entrez le code envoyé à {{contact}}',
  didnt_receive_the_code: 'Vous n’avez pas reçu le code ?',
  resend_in: 'Renvoyer dans',
  try_another_way: 'Essayer une autre méthode',
  resend: 'Renvoyer',
  incorrect_code: 'Le code saisi est incorrect.',
  get_started: 'Commençons',
  get_started_desc: 'Créons d’abord votre compte',
  create_account: 'Créer un compte',
  name: 'Nom',
  email: 'E-mail',
  password: 'Mot de passe',
  sms_verification: 'Envoyer le code par SMS',
  call_verification: 'Envoyer le code par appel',
  email_verification: 'Envoyer le code par e-mail',
  too_many_attempts: 'Trop de tentatives',
  too_many_attempts_desc: 'Nous avons temporairement bloqué les nouvelles tentatives pour protéger votre compte. Réessayez dans 5 minutes.',
  ok: 'OK',
  enter_your_email: 'Connectez-vous facilement en entrant votre e-mail !',
  enter_your_password: 'Entrez votre mot de passe',
  email_already_exist: 'Votre e-mail existe déjà.',
  remember_me: 'Se souvenir de moi',
  forget_password: 'Mot de passe oublié ?',
  invalid_password: 'Mot de passe invalide',
  enter_correct_password: 'Veuillez saisir le bon mot de passe.',
  forget_password_desc: 'Saisissez votre e-mail et nous vous enverrons un code pour réinitialiser votre mot de passe.',
  create_new_password: 'Créez votre nouveau mot de passe',
  create_password_desc: 'Définissez un nouveau mot de passe et confirmez-le.',
  enter_new_password: 'Entrez le nouveau mot de passe',
  confirm_new_password: 'Confirmez le nouveau mot de passe',
  set_new_password: 'Définir le nouveau mot de passe',
  verify_your_email: 'Vérifiez votre e-mail',
  enter_strong_password: 'Veuillez saisir un mot de passe fort.',
  password_not_matched: 'Assurez-vous que vos mots de passe correspondent',
  something_went_wrong: 'Un problème est survenu.',
  location_popup_title: 'Accès à la localisation',
  location_popup_description:
    'Utilisez la localisation de l’appareil pour afficher les magasins proches, la disponibilité de livraison et les offres pertinentes.',
  location_popup_denied_title: 'Autorisation refusée',
  location_popup_denied_description:
    'L’accès à la localisation est toujours désactivé. Autorisez-le pour afficher les magasins proches et la disponibilité exacte de livraison.',
  location_popup_blocked_title: 'Activez la localisation dans les réglages',
  location_popup_blocked_description:
    'L’accès à la localisation est désactivé pour cette application. Ouvrez les réglages pour autoriser la localisation sur votre appareil.',
  location_popup_enable: 'Activer la localisation',
  location_popup_try_again: 'Réessayer',
  location_popup_open_settings: 'Ouvrir les réglages',
  location_popup_later: 'Plus tard',
  address_list_title: 'Mes adresses',
  address_add_title: 'Ajouter une adresse',
  address_edit_title: "Modifier l'adresse",
  address_search_placeholder: 'Rechercher une adresse',
  address_choose_on_map: 'Choisir sur la carte',
  address_recent_searches: 'Recherches récentes',
  address_no_results: 'Aucun résultat trouvé',
  address_confirm_location: "Confirmer l'emplacement",
  address_locating: 'Localisation…',
  address_selected_location: 'Emplacement sélectionné',
  address_location_name_placeholder: 'Nom du lieu (ex. Ma maison)',
  address_details_label: "Détails de l'adresse",
  address_location_type_label: 'Type de lieu',
  address_location_details_label: 'Détails du lieu',
  address_home_details_title: 'Détails du domicile',
  address_apartment_details_title: "Détails de l'appartement",
  address_office_details_title: 'Détails du bureau',
  address_field_house_flat_number: 'Maison / Numéro d’appartement',
  address_field_apartment_flat: 'Appartement / Flat',
  address_field_area_street: 'Zone / Rue',
  address_field_society_building_name: 'Résidence / Nom du bâtiment',
  address_field_company_building_name: 'Entreprise / Nom du bâtiment',
  address_field_floor_tower_optional: 'Étage / Tour (Facultatif)',
  address_field_floor_suite_unit_optional: 'Étage / Suite / Unité (Facultatif)',
  address_field_department_optional: 'Service (Facultatif)',
  address_field_landmark_optional: 'Repère (Facultatif)',
  address_detail_house_placeholder: 'Maison',
  address_detail_apartment_placeholder: 'Appartement / Flat',
  address_detail_office_placeholder: 'Bureau / Immeuble',
  address_detail_company_building_placeholder: 'ex. ABC Technologies',
  address_detail_floor_suite_unit_placeholder: 'ex. 2e étage, Suite 201',
  address_detail_place_placeholder: 'Lieu',
  address_detail_society_placeholder: 'Société / Résidence',
  address_detail_floor_placeholder: 'Étage / Tour',
  address_detail_department_placeholder: 'Service / Étage',
  address_detail_area_placeholder: 'Zone / Rue',
  address_detail_landmark_placeholder: 'Repère',
  address_optional_suffix: '(facultatif)',
  address_set_as_default: 'Définir comme adresse par défaut',
  address_type_home: 'Domicile',
  address_type_apartment: 'Appartement',
  address_type_office: 'Bureau',
  address_type_other: 'Autre',
  address_save: "Enregistrer l'adresse",
  address_update: "Mettre à jour l'adresse",
  address_delete: 'Supprimer',
  address_delete_confirm_title: "Supprimer l'adresse",
  address_delete_confirm_message: 'Êtes-vous sûr de vouloir supprimer cette adresse ?',
  address_delete_cancel: 'Annuler',
  address_delete_confirm: 'Supprimer',
  address_save_error: "Impossible d'enregistrer l'adresse.",
  address_select_error: "Impossible de sélectionner l'adresse.",
  address_delete_error: "Impossible de supprimer l'adresse.",
  address_delete_linked_orders_error:
    "Cette adresse ne peut pas être supprimée car elle est liée à des commandes existantes.",
  address_save_success: 'Adresse enregistrée avec succès.',
  address_update_success: 'Adresse mise à jour avec succès.',
  address_delete_success: 'Adresse supprimée avec succès.',
  address_selector_title: 'Emplacement',
  address_selector_close: "Fermer le sélecteur d'emplacement",
  address_selector_use_current_location: 'Utiliser ma position actuelle',
  address_selector_add_new: 'Ajouter une nouvelle adresse',
  profile_personal_account: 'Compte personnel',
  profile_wallet_balance: 'Solde du portefeuille',
  profile_view_wallet: 'Voir le portefeuille',
  profile_menu_profile: 'Profil',
  profile_menu_notifications: 'Notifications',
  profile_menu_favorites: 'Favoris',
  profile_menu_coupons: 'Coupons',
  profile_menu_settings: 'Paramètres',
  profile_menu_support: 'Assistance',
  profile_menu_color_mode: 'Mode couleur',
  profile_menu_language: 'Langue',
  profile_menu_logout: 'Se déconnecter',
  notifications_title: 'Notifications',
  notifications_section_today: "Aujourd'hui",
  notifications_section_past: 'Passées',
  notifications_show_more: 'Afficher plus',
  notifications_empty_title: 'Aucune notification pour le moment',
  notifications_empty_description: 'Vos dernières mises à jour apparaîtront ici dès leur arrivée.',
  notifications_today_appointment_title: 'Votre rendez-vous chez Style Haven est confirmé.',
  notifications_today_appointment_subtitle: "À l'instant.",
  notifications_today_location_title: 'Votre nettoyage à domicile est confirmé : rendez-vous chez Style Haven.',
  notifications_today_location_subtitle: 'Il y a quelques heures.',
  notifications_today_payment_title: 'Paiement reçu : 65,00 QR pour votre nettoyage à domicile chez Style Haven.',
  notifications_today_payment_subtitle: "Il est 20:19, parfait pour une sortie du soir !",
  notifications_past_offer_title: 'Offre spéciale : profitez de 15 % de réduction sur vos deux prochaines visites !',
  notifications_past_offer_subtitle: 'Le 12 sept. à 20:19, votre rendez-vous a été planifié.',
  notifications_past_rating_title: "N'oubliez pas d'évaluer votre récent nettoyage à domicile chez Style Haven !",
  notifications_past_rating_subtitle: 'Le 24 août à 20:19, vous avez eu un excellent nettoyage à domicile.',
  notifications_past_receipt_title: 'Votre reçu pour le nettoyage à domicile #2957 est maintenant disponible.',
  notifications_past_receipt_subtitle: 'Le 04 août à 20:19, vous avez apprécié une coupe fraîche.',
  my_profile_title: 'Mon profil',
  my_profile_edit: 'Modifier',
  my_profile_full_name: 'Nom complet',
  my_profile_date_of_birth: 'Date de naissance',
  my_profile_mobile_number: 'Numéro de téléphone',
  my_profile_email: 'E-mail',
  my_profile_my_addresses: 'Mes adresses',
  my_profile_add_address: 'Ajouter une adresse',
  my_profile_address_home: 'Domicile',
  my_profile_address_apartment: 'Appartement',
  my_profile_address_work: 'Travail',
  my_profile_address_other: 'Autre',
  photo_modal_title: 'Photo de profil',
  photo_modal_description: 'Choisissez comment mettre à jour votre photo de profil',
  photo_take_photo: 'Prendre une photo',
  photo_choose_gallery: 'Choisir dans la galerie',
  photo_cancel: 'Annuler',
  photo_permission_title: 'Autorisation requise',
  photo_permission_camera: "L'accès à la caméra est nécessaire pour prendre une photo de profil ou joindre une photo dans l'assistance et le chat.",
  photo_permission_gallery: "L'accès à la photothèque est nécessaire pour choisir une photo de profil ou joindre une photo existante dans l'assistance et le chat.",
  photo_upload_error_title: 'Échec du téléchargement',
  photo_upload_failed: 'Impossible de mettre à jour la photo de profil.',
  edit_profile_title: 'Modifier le profil',
  edit_profile_name: 'Nom',
  edit_profile_date_of_birth: 'Date de naissance',
  edit_profile_day: 'Jour',
  edit_profile_month: 'Mois',
  edit_profile_year: 'Année',
  edit_profile_gender: 'Genre',
  edit_profile_gender_placeholder: 'Sélectionner une option',
  edit_profile_save: 'Enregistrer',
  edit_profile_success: 'Succès',
  edit_profile_success_message: 'Profil mis à jour avec succès.',
  edit_profile_error: 'Erreur',
  edit_profile_name_required: 'Le nom est requis.',
  edit_profile_failed: 'Impossible de mettre à jour le profil.',
  settings_title: 'Paramètres',
  settings_notifications: 'Paramètres de notifications',
  settings_change_password: 'Changer le mot de passe',
  settings_privacy_policy: 'Politique de confidentialité',
  settings_terms_of_service: "Conditions d'utilisation",
  settings_terms_of_use: "Conditions d'usage",
  settings_delete_account: 'Supprimer le compte',
  settings_app_version: "Version de l'application 1.0.0",
  // Notification settings screen
  notif_settings_title: 'Paramètres de notifications',
  notif_settings_food_delivery: 'Livraison de nourriture',
  notif_settings_marketing: 'Marketing',
  notif_settings_email: 'E-mail',
  notif_settings_sms: 'SMS',
  notif_settings_whatsapp: 'WhatsApp',
  notif_settings_success_title: 'Enregistré',
  notif_settings_success_message: 'Préférence de notification mise à jour.',
  notif_settings_error_title: 'Erreur',
  // Privacy Policy screen
  privacy_title: 'Politique de confidentialité',
  privacy_last_updated: 'Dernière mise à jour il y a 2 mois',
  privacy_intro:
    "Cette politique de confidentialité explique comment nous traitons vos informations personnelles lors de l'utilisation de l'application de livraison de nourriture. En vous inscrivant ou en accédant à l'application, vous consentez aux pratiques décrites dans cette politique.",
  privacy_section_app_title: "Politique de confidentialité pour l'application",
  privacy_section_app_body:
    "L'application de livraison de nourriture s'engage à protéger et gérer vos données personnelles et commandes en toute sécurité. Vous êtes autorisé à utiliser l'application à des fins personnelles et commerciales, sous réserve de respecter cette politique et toutes les lois applicables.",
  privacy_section_responsibilities_title: 'Responsabilités des utilisateurs',
  privacy_section_responsibilities_body:
    "Les utilisateurs sont responsables de l'exactitude de leurs adresses de livraison et de leurs informations de paiement. Il est important de maintenir ces informations à jour pour éviter tout problème lors du processus de commande.",
  privacy_section_data_title: 'Collecte de données',
  privacy_section_data_body:
    "L'application de livraison de nourriture collecte des données essentielles pour améliorer votre expérience, notamment votre localisation, l'historique de vos commandes et vos préférences.",
  privacy_section_modifications_title: 'Modifications de commande',
  privacy_section_modifications_body:
    "Vous pouvez modifier ou annuler vos commandes via l'application avant qu'elles ne soient traitées. Une fois une commande confirmée, les modifications peuvent ne pas être possibles.",
  privacy_section_payment_title: 'Sécurité des paiements',
  privacy_section_payment_body:
    "Nous accordons la priorité à la sécurité de vos informations de paiement. Toutes les transactions effectuées via l'application sont traitées à l'aide d'une technologie de chiffrement standard.",
  privacy_section_contact_title: 'Nous contacter',
  privacy_section_contact_body: 'Si vous avez des questions sur ces conditions, n\'hésitez pas à nous contacter :',
  privacy_contact_email: 'E-mail : contact@fooddelivery.com',
  privacy_contact_address: 'Adresse : Doha, Qatar',
  // Terms of Service screen
  tos_title: "Conditions d'utilisation",
  tos_last_updated: 'dernière mise à jour il y a 2 mois',
  tos_intro:
    "Ces conditions d'utilisation définissent votre accès et votre utilisation de l'application de livraison de nourriture.",
  tos_section_usage_title: 'Utilisation du service',
  tos_section_usage_body:
    "L'application de livraison de nourriture fournit une plateforme fiable pour commander et gérer vos livraisons de repas.",
  tos_section_orders_title: 'Gestion des commandes',
  tos_section_orders_body:
    "L'application vous permet de suivre facilement vos commandes, de modifier les détails ou de les annuler dans le délai imparti.",
  tos_section_payment_title: 'Sécurité des paiements',
  tos_section_payment_body:
    "Les paiements via l'application sont traités de manière sécurisée avec une technologie de chiffrement.",
  tos_section_delivery_title: 'Politiques de livraison',
  tos_section_delivery_body:
    'Les utilisateurs sont encouragés à fournir des adresses de livraison précises pour faciliter un service rapide et efficace.',
  tos_section_support_title: 'Service client',
  tos_section_support_body:
    "L'application fournit un système d'assistance robuste pour répondre à toutes les questions ou problèmes.",
  tos_section_contact_title: 'Nous contacter',
  tos_section_contact_body: 'Si vous avez des questions sur ces conditions, n\'hésitez pas à nous contacter :',
  tos_contact_email: 'E-mail : contact@fooddelivery.com',
  tos_contact_address: 'Adresse : Doha, Qatar',
  // Terms of Use screen
  tou_title: "Conditions d'usage",
  tou_last_updated: 'mise à jour il y a 2 mois',
  tou_intro:
    "Ces conditions d'utilisation définissent vos droits et responsabilités lors de l'utilisation de l'application.",
  tou_section_guidelines_title: "Directives d'utilisation",
  tou_section_guidelines_body:
    "L'application fournit une gestion sécurisée de vos commandes et données client.",
  tou_section_etiquette_title: 'Étiquette de livraison',
  tou_section_etiquette_body:
    'Les utilisateurs doivent maintenir le respect et la courtoisie envers le personnel de livraison.',
  tou_section_payment_title: 'Méthodes de paiement',
  tou_section_payment_body:
    "L'application prend en charge plusieurs méthodes de paiement, notamment les cartes de crédit et les portefeuilles numériques.",
  tou_section_cancellation_title: "Politique d'annulation",
  tou_section_cancellation_body:
    'Les commandes peuvent être annulées dans un délai de 10 minutes après leur passation.',
  tou_section_feedback_title: 'Commentaires et évaluations',
  tou_section_feedback_body:
    "Les utilisateurs sont encouragés à donner leur avis sur leur expérience de livraison.",
  tou_section_promotions_title: 'Promotions et offres',
  tou_section_promotions_body:
    "L'application peut proposer des promotions et des réductions soumises à des conditions spécifiques.",
  tou_section_contact_title: 'Nous contacter',
  tou_section_contact_body: 'Si vous avez des questions, n\'hésitez pas à nous contacter :',
  tou_contact_email: 'E-mail : contact@fooddelivery.com',
  tou_contact_address: 'Adresse : Doha, Qatar',
  // Change password flow
  change_password_title: 'Changer le mot de passe',
  change_password_new_title: 'Nouveau mot de passe',
  change_password_email_heading: 'Changer le mot de passe ?',
  change_password_email_description:
    'Entrez votre adresse e-mail et nous vous enverrons un code de vérification.',
  change_password_email_placeholder: 'votre@email.com',
  change_password_continue: 'Continuer',
  change_password_verify_heading: 'Vérifiez votre e-mail',
  change_password_verify_description: 'Entrez le code à 4 chiffres envoyé à {{email}}',
  change_password_verify_button: 'Vérifier le code',
  change_password_new_heading: 'Créez votre nouveau mot de passe',
  change_password_new_description: "Votre nouveau mot de passe doit être différent de l'ancien.",
  change_password_new_placeholder: 'Nouveau mot de passe',
  change_password_confirm_placeholder: 'Confirmer le mot de passe',
  change_password_set_new: 'Définir le nouveau mot de passe',
  change_password_mismatch: 'Les mots de passe ne correspondent pas.',
  change_password_error_title: 'Erreur',
  change_password_send_otp_error: "Échec de l'envoi du code de vérification.",
  change_password_verify_otp_error: 'Code invalide ou expiré.',
  change_password_update_error: 'Échec de la mise à jour du mot de passe.',
  change_password_success_title: 'Succès',
  change_password_success_message: 'Votre mot de passe a été mis à jour.',
  change_password_otp_resent_title: 'Code envoyé',
  change_password_otp_resent_message: 'Un nouveau code de vérification a été envoyé.',
  // Delete account flow
  delete_account_step_label: 'Supprimer mon compte',
  delete_account_sorry_heading: 'Nous serons désolés de vous voir partir',
  delete_account_sorry_subtext: 'Pouvons-nous vous faire changer d\'avis ? Contactez-nous à',
  delete_account_contact_email: 'hello@enategadelivery.com',
  delete_account_reason_heading: 'Pourquoi souhaitez-vous quitter Food delivery ?',
  delete_account_reason_subtext: 'Veuillez nous indiquer la raison de la suppression de votre compte :',
  delete_account_reason_mistake: 'J\'ai créé ce compte par erreur',
  delete_account_reason_no_longer: 'Je ne veux plus utiliser Food delivery',
  delete_account_reason_no_venues: 'Je ne trouve pas les établissements ou services que je veux',
  delete_account_reason_other: 'Autre',
  delete_account_confirm_heading: 'Supprimer votre compte Food delivery',
  delete_account_confirm_description: 'Cette action supprimera votre compte et vous ne pourrez pas le récupérer. Veuillez confirmer que vous comprenez en cochant les déclarations ci-dessous :',
  delete_account_confirm_item_orders: 'Je sais que je ne pourrai plus accéder à mes commandes.',
  delete_account_confirm_item_marketplace: 'Je sais que je ne pourrai plus passer de commandes via la marketplace Food delivery.',
  delete_account_final_heading: 'Confirmez que vous souhaitez continuer',
  delete_account_final_description: 'Veuillez noter que cette action est permanente et ne peut pas être annulée. Pour confirmer la suppression de votre compte, veuillez vérifier votre e-mail ci-dessous :',
  delete_account_email_label: 'E-mail',
  delete_account_email_placeholder: 'votre@email.com',
  delete_account_cta_continue: 'Continuer',
  delete_account_cta_delete: 'Supprimer le compte',
  delete_account_close: 'Fermer',
  delete_account_alert_title: 'Supprimer le compte',
  delete_account_alert_message: 'Êtes-vous sûr de vouloir supprimer définitivement votre compte ? Cette action est irréversible.',
  delete_account_alert_cancel: 'Annuler',
  delete_account_alert_confirm: 'Supprimer',
  delete_account_error_title: 'Erreur',
  delete_account_error: 'Échec de la suppression du compte. Veuillez réessayer.',
  color_mode_title: 'Mode couleur',
  color_mode_section_label: 'Sélectionner le mode couleur',
  color_mode_system: 'Système par défaut',
  color_mode_light: 'Clair',
  color_mode_dark: 'Sombre',
  language_title: "Langues de l'application",
  language_section_label: 'Sélectionner la langue',
  language_english: 'Anglais',
  language_french: 'Français',
  offline_notice_title: 'Vous êtes hors ligne',
  offline_notice_description: 'Reconnectez-vous pour actualiser les trajets, tarifs et données en direct.',
  clear_all: 'Tout effacer',
  filter_title: 'Filtrer',
  filter_close_label: 'Fermer les filtres',
  filter_apply_results: 'Appliquer les filtres',
  generic_list_error_title: 'Impossible de charger les résultats',
  generic_list_error_description: 'Actualisez ou réessayez.',
  generic_list_retry: 'Réessayer',
  generic_list_empty_title: 'Aucun résultat trouvé',
  generic_list_empty_description: 'Essayez une autre recherche ou modifiez vos filtres.',
  generic_list_search_placeholder: 'Recherche',
  see_all_map_loading_title: 'Recherche de {{title}}',
  see_all_map_loading_description: 'Cela peut prendre quelques instants. Veuillez rester sur cet écran.',
  see_all_map_sheet_title: 'Restaurant',
  see_all_map_cta: 'Voir le restaurant',
  see_all_back_label: 'Retour',
  see_all_open_filters_label: 'Ouvrir les filtres',
  see_all_map_view_label: 'Vue carte',
  // Search components translations
  no_results_found: 'Aucun résultat trouvé',
  recent_searches: 'Recherches récentes',
  searching_near: 'Recherche près de',
  multi_vendor_address_label: 'Sélectionner une adresse',
  // Search filter translations
  search_filter_title: 'Filtres de recherche',
  search_filter_sort_by: 'Trier par',
  search_filter_sort_best_match: 'Meilleure correspondance',
  search_filter_sort_top_rated: 'Mieux notés',
  search_filter_sort_nearest: 'Plus proches',
  search_filter_ratings: 'Note minimum',
  search_filter_availability: 'Disponibilité',
  search_filter_availability_standard: 'Standard',
  search_filter_availability_emergency: 'Urgence',
  search_filter_stars: 'étoiles',
  filter_button_label: 'Options de filtre',
  search_input_placeholder: "Rechercher n'importe quoi",
  Recommended_restaurants: 'Restaurants recommandés',
  home_drive_banners_title: 'Offres Drive',
};

export default fr;
