const ar = {
  "shop_type_grocery": "بقالة",
  "shop_type_restaurant": "مطعم",
  "promotional_banner": "الدعاية",
  "store_menu_all_categories": "جميع الفئات",
  "store_menu_page_error": "لا يمكن تحميل هذه المواد. تحقق من اتصالك وحاول مرة أخرى",
  "store_menu_refresh_error": "لم أستطع إعادة فتح القائمة أغراضك الحالية لا تزال متاحة",
  "store_menu_search_hint": "صنف شخصين على الأقل لتفتيش هذا المطعم",
  "store_menu_search_loading": "أبحث عن هذا المطعم",
  "store_menu_search_empty": "لا تطابق الأشياء جرب اسم مختلف أو عنصر مختلف",
  "store_menu_search_error": "البحث لا يمكن تحميل. تحقق من اتصالك وحاول مرة أخرى",
  "store_menu_no_section_items": "ولا توجد حاليا أي بنود في هذا الفرع.",
  "label": "التوصيلات",
  "description": "أوامر من المتاجر أو البائعين.",
  "header_title": "التوصيلات",
  "header_subtitle": "اختيار نوع التسليم",
  "hero_badge": "تجربة ديمو",
  "hero_subtitle": "التبديل بين نماذج التوصيل والتجربة الكاملة بشكل جميل",
  "hero_pill_fast": "التحول السريع",
  "hero_pill_flexible": "محاولة كل تدفقات التسليم",
  "section_title": "اختر أسلوبك",
  "single_vendor_title": "الزهرة الوحيدة",
  "single_vendor_desc": "طلب من متجرك المفضل",
  "single_vendor_chip": "المخزن المتداول",
  "single_vendor_stat": "محل مركز واحد",
  "multi_vendor_title": "متعدد المتاجر",
  "multi_vendor_desc": "الحشد والطلب من متاجر متعددة",
  "multi_vendor_chip": "السوق",
  "multi_vendor_stat": "العديد من البائعين في مكان واحد",
  "chain_title": "السلاسل",
  "chain_desc": "طلب من سلاسلك المفضلة",
  "chain_chip": "شبكة براند",
  "chain_stat": "الطحالب والمواقع",
  "explore_button": "استكشف",
  "details_title": "التفاصيل",
  "single_vendor_categories_title": "الفئات",
  "single_vendor_category_products_empty": "لم يتم العثور على منتجات في هذه الفئة.",
  "single_vendor_home_subtitle": "متجرك المفضل",
  "single_vendor_home_body": "استكشاف البائعين والخدمات هنا.",
  "single_vendor_tab_home": "البيت",
  "single_vendor_tab_search": "البحث",
  "single_vendor_tab_orders": "الأوامر",
  "single_vendor_tab_profile": "الملف الشخصي",
  "single_vendor_tab_search_placeholder": "ستظهر نتائج البحث وأدوات الاكتشاف هنا قريباً",
  "single_vendor_tab_orders_placeholder": "أوامرك الوحيدة ستظهر هنا قريباً",
  "single_vendor_logout_error_title": "خطأ",
  "single_vendor_logout_error_message": "غير قادر على الدخول الآن",
  "multi_vendor_home_subtitle": "مخازن متعددة",
  "multi_vendor_home_body": "كشف أمر من بائعين متعددين",
  "multi_vendor_home_greeting_morning": "صباح الخير",
  "multi_vendor_home_greeting_afternoon": "مساء الخير",
  "multi_vendor_home_greeting_evening": "مساء الخير",
  "delivery_home_greeting_morning": "صباح الخير",
  "delivery_home_greeting_afternoon": "مساء الخير",
  "delivery_home_greeting_evening": "مساء الخير",
  "delivery_home_title": "كل ما تحتاجه، تسليم.",
  "delivery_home_subtitle": "استكشاف المتاجر المجاورة ووجبات جديدة ووجبات ضرورية كل يوم",
  "delivery_home_search_placeholder": "مخازن البحث والوجبات والمواد الأساسية",
  "multi_vendor_tab_home": "البيت",
  "multi_vendor_tab_search": "البحث",
  "multi_vendor_tab_orders": "الأوامر",
  "multi_vendor_tab_profile": "الملف الشخصي",
  "chain_tab_home": "البيت",
  "chain_tab_search": "البحث",
  "chain_tab_orders": "الأوامر",
  "chain_tab_profile": "الملف الشخصي",
  "chain_logout_error_title": "خطأ",
  "chain_logout_error_message": "غير قادر على الدخول الآن",
  "chain_categories_title": "الفئات",
  "chain_category_products_empty": "لم يتم العثور على منتجات في هذه الفئة.",
  "chain_menu_template_selector_label": "قائمة بالسلاسل المختارة",
  "chain_menu_template_loading": "التعبئة",
  "chain_menu_template_empty": "لا رجال",
  "chain_menu_template_unavailable": "منو غير متاح",
  "delivery_address_title": "عنوان التسليم",
  "delivery_address_empty_state": "أضف عنواناً ليبدأ الطلب من هذا المتجر",
  "logout": "لوج",
  "multi_vendor_address_label": "العنوان الصحيح",
  "delivery_header_deliver_to": "تسليم إلى",
  "multi_vendor_shop_types_title": "أنواع المتاجر",
  "home_all_stores": "جميع المخازن",
  "home_store_count": "مخازن {{count}} لاستكشاف",
  "home_store_count_one": "متجر {{count}} لاستكشاف",
  "home_store_count_other": "مخازن {{count}} لاستكشاف",
  "home_store_list_subtitle": "ابحث عن شيء جيد قريب",
  "home_no_nearby_stores_title": "حيك ينمو",
  "home_no_nearby_stores_message": "نستكشف جميع المتاجر بينما نجد المزيد بالقرب من هذا العنوان",
  "home_no_deals_title": "العروض الجديدة في الطريق",
  "home_no_deals_message": "تحقق قريبا من شيء يستحق الاكتشاف.",
  "home_no_shop_type_stores_title": "لا متاجر في هذه المجموعة بعد",
  "deals_page_title": "إيجاد جيد، أسعار أفضل.",
  "deals_page_description": "استكشاف العروض على الأشياء التي تحبها",
  "deals_page_empty_title": "لا عروض هنا",
  "deals_page_empty_description": "حاول بحثاً آخر أو تفقده قريباً من أجل صفقات جديدة",
  "multi_vendor_main_shop_types_title": "مجموعات التوصيل",
  "multi_vendor_categories_title": "الفئات",
  "multi_vendor_top_brands_title": "براندات كبيرة",
  "multi_vendor_all_brands_title": "جميع العلامات التجارية",
  "multi_vendor_search_brands_placeholder": "علامات البحث",
  "multi_vendor_nearby_store_title": "مخازن قريبة",
  "multi_vendor_home_quick_browse": "جميع المخازن",
  "multi_vendor_home_quick_deals": "الصفقات",
  "multi_vendor_home_quick_orders": "مرة أخرى",
  "multi_vendor_home_quick_favourites": "المفضلة",
  "multi_vendor_deals_title": "الصفقات",
  "multi_vendor_recommended_restaurants_title": "المطاعم الموصى بها",
  "deals_see_all_tab_all": "كل شيء",
  "deals_see_all_tab_limited": "محدودية الوقت",
  "deals_see_all_tab_weekly": "الصفقات الأسبوعية",
  "deals_see_all_ends_in": "تنتهي",
  "deals_see_all_section_title": "استكشاف جميع العروض",
  "deals_see_all_section_title_limited": "سينتهي قريباً",
  "deals_see_all_section_title_weekly": "عروض هذا الأسبوع",
  "deals_see_all_badge_percentage": "{{value}}",
  "deals_see_all_badge_fixed": "{{value}}",
  "multi_vendor_order_again_title": "مرة أخرى",
  "main see all": "انظر الى الجميع",
  "multi_vendor_see_all": "شاهد كل شيء",
  "multi_vendor_order_again_add_item": "البند",
  "multi_vendor_order_again_price_unavailable": "السعر غير المتاح",
  "multi_vendor_nearby_store_name_hardees": "هاردي - ز بلوك",
  "multi_vendor_nearby_store_name_subway": "Subway - Z Block",
  "multi_vendor_nearby_store_category_fast_food": "الغذاء السريع",
  "multi_vendor_nearby_store_category_pure_veg": "نباتي بالكامل",
  "multi_vendor_nearby_store_review_count": "(5000+)",
  "multi_vendor_nearby_store_delivery_fee": "دولار",
  "multi_vendor_nearby_store_delivery_time": "30 دقيقة",
  "multi_vendor_nearby_store_distance": "1.7 km",
  "multi_vendor_sponsored_label": "الرعاة",
  "multi_vendor_cart_label": "السلة",
  "multi_vendor_shop_type_gift": "تسليم الهدايا",
  "multi_vendor_shop_type_milk": "توصيل الحليب",
  "multi_vendor_shop_type_flower": "تسليم الزهور",
  "multi_vendor_shop_type_liquor": "تسليم المشروبات",
  "multi_vendor_shop_type_products_empty": "لا توجد منتجات لهذا النوع من المتاجر",
  "multi_vendor_shop_type_stores_empty": "لا يوجد متاجر لهذا النوع من المتاجر",
  "multi_vendor_shop_types_empty": "لا توجد أنواع من محلات التسليم متاحة الآن.",
  "multi_vendor_location_stores_empty": "لا توجد مخازن متاحة لهذا الموقع.",
  "multi_vendor_shop_type_products_error": "غير قادر على تحميل المنتجات الآن",
  "multi_vendor_shop_type_stores_error": "غير قادر على تحميل المتاجر الآن",
  "multi_vendor_home_section_empty_title": "لا تطابق الآن",
  "multi_vendor_home_section_empty_message": "وسيظهر هنا في أقرب وقت ممكن الاختيارات الجديدة والعروض المحدودة الوقت.",
  "multi_vendor_home_section_error_title": "المواد غير القادرة على تحميلها",
  "multi_vendor_home_section_error_message": "حاول مرة أخرى في لحظة",
  "multi_vendor_home_section_empty_order_again": "إختياراتك الأخيرة ستظهر هنا بعد طلبك الأول",
  "multi_vendor_home_empty_order_again_title": "مستعدّة لمُفضّل جديد؟",
  "multi_vendor_home_empty_explore_action": "مخازن المتفجرات",
  "multi_vendor_home_empty_order_action": "تفجير الآن",
  "store_details_search_placeholder": "قائمة البحث...",
  "store_details_hero_title": "اصنع هو\nوجبة.",
  "store_details_store_name": "Subway @ Old Town, New Mexico",
  "store_details_store_phone": "555-0123",
  "store_details_store_email": "support@subway.com",
  "store_details_store_hours": "9 AM to 6 PM",
  "store_details_call_label": "اتصل بنا",
  "store_details_email_label": "أو البريد الإلكتروني",
  "store_details_tab_pizza": "البيتزا",
  "store_details_tab_burgers": "البرغرات",
  "store_details_tab_pasta": "المعكرونة",
  "store_details_tab_sushi": "سوشي",
  "store_details_subcategory_italian_classic": "الإيطالية الكلاسيكية",
  "store_details_subcategory_american_style": "على الطريقة الأمريكية",
  "store_details_subcategory_pepperoni": "بيبروني",
  "store_details_subcategory_bbq_chicken": "دجاج باربكيو",
  "store_details_subcategory_thin_crust": "عجينة رقيقة",
  "store_details_all_offered_items": "جميع البنود المعروضة",
  "store_details_no_items": "لا يوجد تطابق مع هذا المرشح بعد",
  "store_details_load_error": "غير قادر على تحميل تفاصيل المتجر الآن",
  "store_details_hours_unavailable": "ساعات غير متاحة",
  "store_details_store_missing": "ولا تتوافر تفاصيل مسروقة.",
  "store_details_action_info": "معلومات مسروقة",
  "store_details_action_favorite": "إضافة مخزن للمفضلين",
  "store_details_action_remove_favorite": "نقل متجر من المفضّلين",
  "store_details_action_share": "مخزن الحصاد",
  "store_details_action_back": "العودة",
  "store_details_about_title": "بشأننا",
  "store_details_about_fallback": "الوصف المخزني غير متاح الآن",
  "store_details_closed_store_title": "متجر {{storeName}} مغلق حاليًا",
  "store_details_closed_store_description": "{{storeName}} is currently not open. حاول مرة أخرى لاحقاً",
  "store_details_closed_store_fallback_name": "هذا المتجر",
  "store_closed_modal_title": "متجر {{storeName}} مغلق حاليًا",
  "store_closed_see_menu": "انظر قائمة الطعام",
  "store_status_closed": "مغلق",
  "store_status_open": "مفتوح",
  "store_details_delivery_minutes": "{{minutes}} دقيقة",
  "store_details_minimum_order": "الحد الأدنى {{amount}}",
  "store_details_close": "اقترب",
  "store_details_info_address": "العنوان: {{address}}",
  "store_details_info_phone": "الهاتف: {{phone}}",
  "store_details_info_email": "البريد الإلكتروني: {{email}}",
  "store_details_view_cart": "عربة فيو",
  "store_details_cart_summary": "{{count}} items {{amount}}",
  "store_details_add_product": "إضافة {{item}}",
  "store_details_badge_deal": "اتفقنا",
  "store_details_badge_ten_percent_off": "10%",
  "store_details_item_chicken_fajita": "دجاج فاجيتا",
  "store_details_item_chicken_teriyaki": "دجاج تيرياكي",
  "store_details_item_burger": "البرغر",
  "store_details_item_sushi": "سوشي",
  "store_details_item_alfredo_pasta": "ألفريدو باستا",
  "store_details_item_veggie_delight": "وجبة نباتية شهية",
  "chain_home_subtitle": "السلاسل المفضلة",
  "chain_home_body": "طلب من متاجر السلاسل المفضلة لديك.",
  "type_single_vendor_title": "مخزن منفرد",
  "type_single_vendor_desc": "بائعو أقساط مجهزة باليد فقط",
  "type_marketplace_title": "السوق",
  "type_marketplace_desc": "مقدمي الخدمات المجتمعية المحلية",
  "type_chain_title": "Stores Chain",
  "type_chain_desc": "اقطع سلاسلك المفضلة",
  "profile_personal_account": "الحساب الشخصي",
  "profile_wallet_balance": "الرصيد الجداري",
  "profile_view_wallet": "محفظة الرؤية",
  "profile_menu_profile": "الملف الشخصي",
  "profile_menu_notifications": "الإخطارات",
  "profile_menu_favorites": "المفضلة",
  "profile_menu_coupons": "القسائم",
  "profile_menu_settings": "التركيبات",
  "profile_menu_support": "الدعم",
  "profile_menu_color_mode": "نمط الألوان",
  "profile_menu_language": "الإنكليزية",
  "profile_menu_logout": "لوج",
  "coupon_title": "القسائم",
  "coupon_active": "النشاط",
  "coupon_claim_label": "إضافة رمز برومو",
  "coupon_description": "إذا كان لديك رمز تسليم الأغذية، رمز الإحالة أو بطاقة الهدايا، أدخله هنا للمطالبة بفوائدك.",
  "coupon_input_placeholder": "رمز الدخول",
  "coupon_use": "الاستخدام",
  "coupon_off": "قبالة",
  "coupon_valid_until": "صالح حتى: {{date}}",
  "coupon_claim": "المطالبة",
  "coupon_claim_success_title": "تمت إضافة القسيمة",
  "coupon_claim_error_title": "تعذر إضافة القسيمة",
  "coupon_claim_error_fallback": "من فضلك أدخل رمز صالح وحاول مرة أخرى",
  "coupon_list_error_fallback": "غير قادر على تحميل القسائم المطالب بها الآن",
  "coupon_used": "مستخدم",
  "coupon_use_success_title": "تم تشغيل كوبون",
  "coupon_use_success_message": "الآن يمكنك استخدام هذا.",
  "coupon_use_error_title": "غير قادر على تفعيل القسطرة",
  "coupon_use_error_fallback": "حاول مرة أخرى",
  "coupon_deactivate": "التطهير",
  "coupon_deactivate_success_title": "تم تعطيلها",
  "coupon_deactivate_success_message": "هذه الحفلة لم تعد نشطة",
  "coupon_deactivate_error_title": "عدم القدرة على تعطيل الانقلاب",
  "coupon_deactivate_error_fallback": "حاول مرة أخرى",
  "coupon_status_expired": "منتهية الصلاحية",
  "coupon_min_order": "الحد الأدنى للطلب {{currency}} {{value}}",
  "coupon_store_fallback": "الشريك المخزن",
  "coupon_store_with_more": "{{store}} و{{count}} أخرى",
  "coupon_claimed_state_title": "أنت فقط حصلت على كوبون!",
  "coupon_claimed_state_body_line_one": "مرحى! تم تطبيق شفرة البرموزين الخاصة بك.",
  "coupon_claimed_state_body_line_two": "وسيظهر الخصم تلقائيا عند المغادرة.",
  "coupon_empty_title": "لا قوارب بعد",
  "coupon_empty_description": "ليس لديك أي كوبونات الآن أدخل رمز برومو فوق لإيجاد العروض",
  "my_profile_title": "ملفي الشخصي",
  "my_profile_edit": "تعديل",
  "my_profile_full_name": "الاسم الكامل",
  "my_profile_date_of_birth": "تاريخ الميلاد",
  "my_profile_mobile_number": "رقم الهاتف",
  "my_profile_email": "البريد الإلكتروني",
  "my_profile_my_addresses": "عناوينى",
  "my_profile_add_address": "العنوان",
  "my_profile_address_home": "البيت",
  "my_profile_address_apartment": "الشقة",
  "my_profile_address_work": "العمل",
  "my_profile_address_other": "أخرى",
  "photo_modal_title": "الصورة",
  "photo_modal_description": "اختر كيف تريد تحديث صورة ملفك",
  "photo_take_photo": "خذ الصورة",
  "photo_choose_gallery": "اختر من الجاليري",
  "photo_cancel": "إلغاء",
  "photo_permission_title": "الإذن المطلوب",
  "photo_permission_camera": "الكاميرا مطلوبة للحصول على صورة",
  "photo_permission_gallery": "هناك حاجة للوصول إلى المعرض لاختيار صورة.",
  "photo_upload_error_title": "حمولة خفيفة",
  "photo_upload_failed": "لا يمكن تحديث الصورة.",
  "edit_profile_title": "تعديل الملف الشخصي",
  "edit_profile_name": "الاسم",
  "edit_profile_date_of_birth": "تاريخ الميلاد",
  "edit_profile_day": "اليوم",
  "edit_profile_month": "الشهر",
  "edit_profile_year": "السنة",
  "edit_profile_gender": "نوع الجنس",
  "edit_profile_gender_placeholder": "الخيار الانتقائي",
  "edit_profile_save": "أنقذني",
  "edit_profile_success": "النجاح",
  "edit_profile_success_message": "تم تحديث الصورة بنجاح.",
  "edit_profile_error": "خطأ",
  "edit_profile_name_required": "الاسم مطلوب",
  "edit_profile_failed": "لا يمكن تحديث الملف",
  "address_list_title": "عناوينى",
  "address_add_title": "العنوان",
  "address_edit_title": "عنوان إديت",
  "address_search_placeholder": "ابحث عن عنوان",
  "address_choose_on_map": "اختر الخريطة",
  "address_recent_searches": "عمليات البحث الأخيرة",
  "address_no_results": "لا توجد نتائج",
  "address_confirm_location": "الموقع",
  "address_locating": "مكان...",
  "address_selected_location": "موقع مختار",
  "address_location_name_placeholder": "اسم الموقع (مثل منزلي)",
  "address_details_label": "التفاصيل",
  "address_location_type_label": "نوع الموقع",
  "address_location_details_label": "تفاصيل الموقع",
  "address_detail_house_placeholder": "البيت",
  "address_detail_apartment_placeholder": "الشقة/الشعلة",
  "address_detail_office_placeholder": "المكتب/المبنى",
  "address_detail_place_placeholder": "المكان",
  "address_detail_society_placeholder": "المجتمع",
  "address_detail_floor_placeholder": "الزهور/البرج",
  "address_detail_department_placeholder": "الإدارة/الطابق",
  "address_detail_area_placeholder": "المنطقة/الشارع",
  "address_detail_landmark_placeholder": "علامة",
  "address_optional_suffix": "(اختياري)",
  "address_type_home": "البيت",
  "address_type_apartment": "الشقة",
  "address_type_office": "المكتب",
  "address_type_other": "أخرى",
  "address_save": "عنوان إنقاذ",
  "address_update": "آخر عنوان",
  "address_delete": "تحذف",
  "address_delete_confirm_title": "العنوان المحذف",
  "address_delete_confirm_message": "هل أنت متأكد أنك تريد حذف هذا العنوان؟",
  "address_delete_cancel": "إلغاء",
  "address_delete_confirm": "تحذف",
  "address_save_error": "لا يمكن إنقاذ العنوان",
  "address_select_error": "لم أستطع اختيار العنوان",
  "address_delete_error": "لا يمكن حذف العنوان.",
  "address_save_success": "تم إنقاذ العنوان بنجاح",
  "address_update_success": "استكملت بنجاح.",
  "address_delete_success": "حذف العنوان بنجاح.",
  "address_selector_title": "الموقع",
  "address_selector_close": "موقع قريب",
  "address_selector_use_current_location": "استخدم موقعي الحالي",
  "address_selector_add_new": "إضافة عنوان جديد",
  "favourites_title": "ففوري",
  "favourites_subtitle": "متاجركم المنقذة جاهزة عندما تكونون",
  "favourites_empty_title": "لا محاباة بعد",
  "favourites_empty_subtitle": "حطم قلب أي متجر ليبقيه قريباً من المرة القادمة",
  "favourites_error_title": "لا يمكن تحميل المفضّلات",
  "favourites_error": "تحقق من اتصالك وحاول مرة أخرى",
  "favourites_retry": "حاول مرة أخرى",
  "favourites_free_delivery": "التسليم المجاني",
  "favourites_remove": "نقل من المفضّلين",
  "favourites_add": "إضافة إلى المفضّلين",
  "favourites_toggle_added": "مضافة إلى المحاباة",
  "favourites_toggle_removed": "نقل من المفضّلين",
  "favourites_toggle_error": "فشل في تحديث المفضّلين",
  "rate_order_title": "معدل طلبك",
  "rate_order_heading": "كيف كانت وجبتك؟",
  "rate_order_subheading": "تعليقاتك تساعدنا على تحسين توصيلنا",
  "rate_order_comment_placeholder": "أكتب خبرتك هنا",
  "rate_order_submit": "إرسال",
  "rate_order_submitted_heading": "شكراً على تقديرك",
  "rate_order_submitted_subheading": "لقد قمت بالفعل بتقييم هذا الأمر تعليقاتك تساعدنا على تحسين توصيلنا",
  "rate_order_submitted_no_comment": "ولم يُضاف تعليق بهذا التقييم.",
  "rate_order_success_title": "شكراً لك",
  "rate_order_success_message": "لقد تم تقديم استعراضك",
  "rate_order_error_title": "فشل العرض",
  "settings_title": "التركيبات",
  "settings_notifications": "مجموعة الإخطارات",
  "settings_change_password": "تغيير كلمة السر",
  "settings_privacy_policy": "سياسة الخصوصية",
  "settings_terms_of_service": "مدة الخدمة",
  "settings_terms_of_use": "مدة الاستخدام",
  "settings_delete_account": "يحذف الحساب",
  "settings_app_version": "إصدار التطبيق 1.0.0",
  "notif_settings_title": "مجموعة الإخطارات",
  "notif_settings_food_delivery": "تسليم الأغذية",
  "notif_settings_marketing": "التسويق",
  "notif_settings_email": "البريد الإلكتروني",
  "notif_settings_sms": "SMS",
  "notif_settings_whatsapp": "WhatsApp",
  "notif_settings_success_title": "منقذة",
  "notif_settings_success_message": "تحديث أفضلية الإخطار.",
  "notif_settings_error_title": "خطأ",
  "privacy_title": "سياسة الخصوصية",
  "privacy_last_updated": "آخر تحديث قبل شهرين",
  "privacy_intro": "سياسة الخصوصية هذه توضح كيف نتعامل مع معلوماتك الشخصية بينما نستخدم تطبيق تقديم الطعام عن طريق تسجيل التطبيق أو الوصول إليه، توافق على الممارسات الموصوفة في هذه السياسة.",
  "privacy_section_app_title": "سياسة الخصوصية للتطبيق",
  "privacy_section_app_body": "تطبيق تسليم الطعام ملتزم بحماية وإدارة بياناتك وأوامرك الشخصية بأمان يحق لك استخدام التطبيق للأغراض الشخصية والتجارية، رهنا بالامتثال لهذه السياسة وجميع القوانين المنطبقة.",
  "privacy_section_responsibilities_title": "مسؤوليات المستعملين",
  "privacy_section_responsibilities_body": "والمستعملون مسؤولون عن إبقاء عناوين تسليمهم ومعلومات الدفع دقيقة. ومن المهم استكمال هذه المعلومات حتى الآن لتجنب المسائل خلال عملية الترتيب.",
  "privacy_section_data_title": "جمع البيانات",
  "privacy_section_data_body": "برنامج تقديم الطعام يجمع البيانات الأساسية لتحسين خبرتك، بما في ذلك موقعك، ترتيب التاريخ والأفضليات.",
  "privacy_section_modifications_title": "تعديلات النظام",
  "privacy_section_modifications_body": "يمكنك تعديل أو إلغاء أوامرك من خلال التطبيق قبل تجهيزها. وبمجرد تأكيد أمر ما، قد لا تكون التغييرات ممكنة.",
  "privacy_section_payment_title": "أمن المدفوعات",
  "privacy_section_payment_body": "نعطي الأولوية لأمن معلومات الدفع الخاصة بك. ويتم تجهيز جميع المعاملات التي تتم عن طريق التطبيق باستخدام تكنولوجيا التشفير الموحدة.",
  "privacy_section_contact_title": "اتصل بنا",
  "privacy_section_contact_body": "إذا كان لديك أي أسئلة حول هذه الشروط، يرجى أن تشعر بحرية للاتصال بنا:",
  "privacy_contact_email": "البريد الإلكتروني: contact@fooddelivery.com",
  "privacy_contact_address": "العنوان: الدوحة، قطر",
  "tos_title": "مدة الخدمة",
  "tos_last_updated": "آخر تحديث قبل شهرين",
  "tos_intro": "وتحدد شروط الخدمة هذه إمكانية وصولك إلى تطبيق تقديم الأغذية واستخدامها.",
  "tos_section_usage_title": "استخدام الخدمة",
  "tos_section_usage_body": "تطبيق تسليم الطعام يوفر منبراً موثوقاً به لوضع الأوامر وإدارة تسليم وجباتك",
  "tos_section_orders_title": "إدارة النظام",
  "tos_section_orders_body": "التطبيق يسمح لك بتتبع أوامرك بسهولة تعديل التفاصيل أو إلغائها ضمن الإطار الزمني المسموح به",
  "tos_section_payment_title": "أمن المدفوعات",
  "tos_section_payment_body": "ويتم تجهيز المدفوعات من خلال التطبيق بطريقة آمنة باستخدام تكنولوجيا التشفير.",
  "tos_section_delivery_title": "سياسات التنفيذ",
  "tos_section_delivery_body": "ويُشجَّع المستعملون على توفير عناوين دقيقة لتقديم الخدمات لدعم الخدمات السريعة والفعالة.",
  "tos_section_support_title": "دعم العملاء",
  "tos_section_support_body": "ويوفر التطبيق نظام دعم قوي لمعالجة أي مسائل أو مسائل.",
  "tos_section_contact_title": "اتصل بنا",
  "tos_section_contact_body": "إذا كان لديك أي أسئلة حول هذه الشروط، يرجى أن تشعر بحرية للاتصال بنا:",
  "tos_contact_email": "البريد الإلكتروني: contact@fooddelivery.com",
  "tos_contact_address": "العنوان: الدوحة، قطر",
  "tou_title": "مدة الاستخدام",
  "tou_last_updated": "أحدث قبل شهرين",
  "tou_intro": "وتحدد شروط الاستخدام هذه حقوقك ومسؤولياتك عند استخدام التطبيق.",
  "tou_section_guidelines_title": "المبادئ التوجيهية المتعلقة بالنقل",
  "tou_section_guidelines_body": "التطبيق يوفر إدارة آمنة لأوامرك وبيانات العملاء",
  "tou_section_etiquette_title": "التوصيل",
  "tou_section_etiquette_body": "وينبغي أن يظل المستعملون محترمين ومحترمين بالنسبة لموظفي التسليم.",
  "tou_section_payment_title": "أساليب الدفع",
  "tou_section_payment_body": "ويدعم التطبيق أساليب الدفع المتعددة، بما في ذلك بطاقات الائتمان والمحافظات الرقمية.",
  "tou_section_cancellation_title": "سياسة الإلغاء",
  "tou_section_cancellation_body": "ويجوز إلغاء الأوامر في غضون 10 دقائق من وضعها.",
  "tou_section_feedback_title": "التغذية والتقديرات",
  "tou_section_feedback_body": "ويُشجَّع المستعملون على تبادل الآراء بشأن خبرتهم في مجال التسليم.",
  "tou_section_promotions_title": "الترقيات والعروض",
  "tou_section_promotions_body": "ويمكن أن يقدم هذا التطبيق ترقيات وخصمات تخضع لشروط محددة.",
  "tou_section_contact_title": "اتصل بنا",
  "tou_section_contact_body": "إذا كان لديك أي أسئلة، يرجى الحصول على حرية الاتصال بنا:",
  "tou_contact_email": "البريد الإلكتروني: contact@fooddelivery.com",
  "tou_contact_address": "العنوان: الدوحة، قطر",
  "rider_chat_title": "تشات مع ريدر",
  "rider_chat_subtitle": "تحديثات البث المباشر",
  "rider_chat_status_online": "على الإنترنت الآن",
  "rider_chat_eta_label": "{{minutes}}",
  "rider_chat_order_label": "الأمر {{orderCode}}",
  "rider_chat_help_text": "نتشارك الملاحظات أو نطلب اتصالاً",
  "rider_chat_message_rider_intro": "مرحبا! أنا في طريق طلبك",
  "rider_chat_message_user_reply": "رائع أرجوك اتصل بي عندما تصل إلى البوابة",
  "rider_chat_message_rider_eta": "بالتأكيد سأتصل بك أراك في حوالي الدقائق {{minutes}}.",
  "rider_chat_quick_reply_gate": "نداء عند البوابة",
  "rider_chat_quick_reply_thanks": "شكراً",
  "rider_chat_quick_reply_here": "أنا هنا",
  "rider_chat_quick_reply_hello": "مرحبا",
  "rider_chat_quick_reply_call_arrive": "اتصل بي عندما تصل",
  "rider_chat_quick_reply_where": "أين أنت؟",
  "rider_chat_quick_reply_eta": "كم من الوقت ستأخذ؟",
  "rider_chat_input_placeholder": "أدخل قلقك",
  "rider_chat_auto_message": "كيف يمكننا مساعدتك؟",
  "rider_chat_auto_time": "8:29 pm",
  "rider_chat_send": "أرسل",
  "rider_chat_send_error": "لم أستطع إرسال رسالة",
  "rider_chat_missing_session_error": "يرجى الدخول قبل إرسال رسالة.",
  "rider_chat_missing_receiver_error": "الإستقبال مفقود لهذه الدردشة",
  "rider_chat_attachment_permission_title": "الإذن اللازم",
  "rider_chat_attachment_permission_message": "يرجى السماح لمكتبة الصور الدخول لإضافة الملحق.",
  "rider_chat_attachment_selected_title": "ملحق مختار",
  "rider_chat_attachment_selected_message": "{{fileName}} على استعداد لربط.",
  "rider_chat_add_attachment": "ملحق",
  "rider_chat_send_message": "رسالة",
  "rider_chat_call_action": "راكب اتصالات",
  "support_title": "الدعم",
  "support_active_order_eyebrow": "النظام الحي",
  "support_active_order_track": "التعقب والحصول على المساعدة",
  "support_active_order_accessibility": "{{store}}, {{status}}. طلب المسار والحصول على المساعدة.",
  "support_topic_faq": "الأسئلة المتكررة",
  "support_topic_faq_description": "ابحثوا عن إجابات سريعة عن الأوامر والتوصيل وحسابكم",
  "support_issue_prompt": "ألم تجد ما تحتاجه؟",
  "support_issue_select_title": "رجاءً إخترْ خيارَ.",
  "support_issue_placeholder": "اختيار نوع من القضايا",
  "support_retry": "حاول مرة أخرى",
  "support_error_title": "لم نتمكن من تحميل هذا الآن",
  "support_error_description": "تحقق من اتصالك وحاول مرة أخرى تاريخ دعمك آمن",
  "support_tickets_empty_title": "عدم الإبلاغ عن أي مسائل",
  "support_tickets_empty_description": "وعندما تُبلغون عن مسألة ما، سيظهر هنا التقدم المحرز والردود.",
  "support_chat_closed_title": "هذه المحادثة مغلقة",
  "support_chat_closed_description": "يمكنك مراجعة الرسائل أعلاه أو بدء طلب دعم جديد.",
  "support_issue_order": "لدي حساب عمل بالفعل و أحتاج للدعم",
  "support_issue_payment": "إنني مهتم بالانضمام إلى تقديم الأغذية كعمل تجاري",
  "support_issue_delivery": "حجزتُ أمرًا مع عمل في مجال تسليم الطعام",
  "support_issue_account": "أحتاج مساعدة في شيء آخر",
  "support_issue_business_support": "لدي حساب عمل بالفعل و أحتاج للدعم",
  "support_issue_joining_as_a_business": "إنني مهتم بالانضمام إلى تقديم الأغذية كعمل تجاري",
  "support_issue_appointment_support": "حجزتُ أمرًا مع عمل في مجال تسليم الطعام",
  "support_call_action": "دعم المكالمات",
  "support_back_action": "العودة",
  "support_header_action": "الإجراءات الرئيسية",
  "support_close_action": "شكل الدعم الوثيق",
  "support_tickets_search_action": "تذاكر البحث",
  "support_tickets_search_placeholder": "تذاكر البحث",
  "support_tickets_no_results_title": "لا تذاكر مطابقة",
  "support_tickets_no_results_description": "جرب رقم ترتيب مختلف أو وضع أو كلمة مفتاح",
  "support_form_how_help_label": "كيف يمكننا المساعدة؟",
  "support_form_email_label": "البريد الإلكتروني",
  "support_form_email_helper": "إذا كان لديك حساب تسليم الطعام، أدخل عنوان البريد الإلكتروني الذي تسجل فيه",
  "support_form_full_name_label": "الاسم الكامل",
  "support_form_full_name_placeholder": "أدخل اسمك",
  "support_form_country_region_label": "البلد/الإقليم",
  "support_form_country_region_placeholder": "الرجاء اختيار",
  "support_form_mobile_number_label": "رقم الهاتف",
  "support_form_mobile_number_placeholder": "+61 333 000 0000",
  "support_form_business_name_label": "اسم تجاري",
  "support_form_business_type_label": "نوع الأعمال",
  "support_form_business_type_placeholder": "الرجاء اختيار",
  "support_form_team_size_label": "حجم الفريق",
  "support_form_team_size_placeholder": "الرجاء اختيار",
  "support_form_business_description_label": "هل هناك أي شيء على وجه الخصوص تريد أن تعرف عن تسليم الطعام؟",
  "support_form_reason_label": "سبب الاتصال",
  "support_form_reason_placeholder": "الرجاء اختيار",
  "support_form_reason_account_setup": "إنشاء حساب",
  "support_form_reason_add_on_integrations": "الإضافات والإدماجات",
  "support_form_reason_addons_integrations": "الإضافات والإدماجات",
  "support_form_reason_using_the_app": "استخدام التطبيق",
  "support_form_reason_payments_and_payouts": "المدفوعات والمدفوعات",
  "support_form_reason_technical_issues": "المسائل التقنية",
  "support_form_reason_my_orders": "أوامري",
  "support_form_reason_payments_and_purchases": "المدفوعات والمشتريات",
  "support_form_reason_reviews": "الاستعراضات",
  "support_form_reason_emails_and_notifications": "الإيميلات والإخطارات",
  "support_form_reason_delete_my_account": "تحذف حسابي",
  "support_form_reason_billing_fees": "الفواتير والرسوم",
  "support_form_reason_payments_payouts": "المدفوعات والمدفوعات",
  "support_form_reason_technical_support": "الدعم التقني",
  "support_form_reason_other": "أخرى",
  "support_form_country_united_states": "الولايات المتحدة",
  "support_form_country_canada": "كندا",
  "support_form_country_united_kingdom": "المملكة المتحدة",
  "support_form_country_australia": "أستراليا",
  "support_form_country_france": "فرنسا",
  "support_form_business_type_burger_joint": "مطعم برغر",
  "support_form_business_type_pizza_place": "مطعم بيتزا",
  "support_form_business_type_taco_stand": "متجر تاكو",
  "support_form_business_type_sandwich_shop": "متجر شطائر",
  "support_form_business_type_ice_cream_parlor": "متجر آيس كريم",
  "support_form_business_type_fried_chicken_spot": "قشرة الدجاج",
  "support_form_business_type_food_truck": "شاحنة غذائية",
  "support_form_business_type_hot_dog_stand": "متجر هوت دوغ",
  "support_form_business_type_other_fast_food": "الأغذية السريعة الأخرى",
  "support_form_team_size_just_me": "أنا فقط",
  "support_form_team_size_2_5": "2 - 5",
  "support_form_team_size_6_10": "6 - 10",
  "support_form_team_size_11_plus": "11+",
  "support_form_description_label": "صف ما تحتاج للمساعدة",
  "support_form_description_placeholder": "أدخل وصفاً...",
  "support_form_attach_title": "طلقات نارية",
  "support_form_attach_description": "ضع ملفاتك هنا",
  "support_form_attach_cta": "اختر الملف",
  "support_form_send_email": "إرسال البريد الإلكتروني",
  "support_form_submit_success_title": "تم إنشاء التذكرة",
  "support_form_submit_success_message": "تذكرة دعمك تم تقديمها بنجاح",
  "support_form_submit_error_title": "التذاكر فشلت",
  "support_form_submit_error_message": "لا يمكننا تقديم تذكرة دعمك تحقق من اتصالك وحاول مرة أخرى",
  "support_form_attachment_upload_error": "ولا يمكن تحميل ملحق واحد أو أكثر. تحقق من اتصالك وحاول مرة أخرى",
  "support_chat_attachment_invalid_title": "ملحق غير مضاف",
  "support_chat_attachment_too_large_message": "ويجب أن يكون كل مرفق 5 ميغابايت أو أقل.",
  "support_chat_auto_message": "كيف يمكننا مساعدتك؟",
  "support_chat_auto_time": "8:29 pm",
  "support_chat_quick_reply_here": "أنا هنا",
  "support_chat_quick_reply_hello": "مرحبا",
  "support_chat_quick_reply_call_arrive": "اتصل بي عندما تصل",
  "support_chat_quick_reply_where": "أين أنت؟",
  "support_chat_quick_reply_eta": "كم من الوقت ستأخذ؟",
  "support_chat_input_placeholder": "أدخل قلقك",
  "support_chat_add_attachment": "ملحق",
  "support_chat_send_message": "رسالة",
  "support_chat_send_error_title": "الرسالة فشلت",
  "support_chat_send_error_message": "لم أستطع إرسال رسالة دعمك",
  "support_chat_missing_session_error": "يرجى الدخول قبل إرسال رسالة.",
  "support_chat_missing_receiver_error": "دردشة الدعم ليست جاهزة بعد من فضلك افتح محادثة قائمة أولاً",
  "support_chat_loading": "...محادثة لعب",
  "support_chat_attachment_permission_title": "الإذن اللازم",
  "support_chat_attachment_permission_message": "يرجى السماح لمكتبة الصور الدخول لإضافة الملحق.",
  "support_chat_attachment_selected_title": "ملحق مختار",
  "support_chat_attachment_selected_message": "{{fileName}} على استعداد لربط.",
  "support_tickets_title": "تذكرتي",
  "support_new_ticket": "تذكرة جديدة",
  "support_tickets_subtitle": "تتبع طلباتك وتتابع مع فريقنا على كل واحد",
  "support_tickets_filter_all": "كل شيء",
  "support_tickets_filter_active": "النشاط",
  "support_tickets_filter_closed": "تم حلها/إغلاقها",
  "support_tickets_search_clear": "البحث الواضح",
  "support_tickets_empty": "لم نجد تذاكر بعد",
  "support_tickets_order_id": "بطاقة الهوية: {{orderId}}",
  "support_faq_title": "مسائل النظام العام",
  "support_faq_header_title": "مواد المساعدة",
  "support_faq_subtitle": "إجابات واضحة على الأسئلة الأكثر شيوعاً",
  "support_faq_place_order": "كيف وضع أمر",
  "support_faq_schedule_delivery": "كيف تحدد موعد تسليمك مقدما",
  "support_faq_change_delivery": "تغيير توصيلاتك",
  "support_faq_order_history": "كيف ترى تاريخ طلبك",
  "support_faq_ordering_for_others": "ترتيب الآخرين وإرسال تأكيدات إلى عناوين مختلفة",
  "support_faq_still_need_help": "ما زلت بحاجة لبعض المساعدة؟",
  "support_faq_feedback_prompt": "هل كان هذا مفيداً؟",
  "support_faq_feedback_yes": "نعم",
  "support_faq_feedback_no": "لا",
  "support_faq_feedback_thanks": "شكرا - تعليقاتكم تساعدنا على تحسين الدعم.",
  "support_faq_place_order_body_1": "وضع أمر سريع وبسيط افتحي تطبيقات التوصيلات ومسح المطاعم القريبة أو المتاجر أو الفئات التي تتطابق مع ما تحتاجين",
  "support_faq_place_order_body_2": "جهزوا متجراً لتستكشف قائمة الطعام ثم أضيفوا الأشياء التي تريدونها إلى عربتكم يمكنك مراجعة الكميات وإضافات الملاحظات وإزالة أي شيء قبل المغادرة",
  "support_faq_place_order_body_3": "عندما تكون مستعداً، تابع التحقق لتأكيد عنوان تسليمك، وتطبيق أي رموز برومو، واختيار طريقة الدفع المفضلة لديك.",
  "support_faq_place_order_body_4": "بعد أن تضعي الأمر، يمكنكِ تعقب تقدمه في الوقت الحقيقي وإبقائه مستكملاً حتى يصل إلى بابكِ.",
  "support_faq_schedule_delivery_body_1": "إذا كان المخزن يدعم الأوامر المقررة، يمكنك اختيار وقت التسليم قبل أن تكمل عملية التفتيش.",
  "support_faq_schedule_delivery_body_2": "أضف أغراضك إلى العربة و إبدأ بالمغادرة ابحث عن قسم توقيت التسليم قبل تأكيد طلبك",
  "support_faq_schedule_delivery_body_3": "نختار موعداً ووقتاً يعمل لديك ثم نراجع تفاصيل الطلب للتأكد من أن كل شيء يبدو صحيحاً",
  "support_faq_schedule_delivery_body_4": "مرة واحدة تأكدت، ونحن سوف تبقي تسليمك في جدول أوامرك حتى تتمكن من استعراضه مرة أخرى في وقت لاحق.",
  "support_faq_change_delivery_body_1": "قد تكون قادراً على تحديث أجزاء من طلبك قبل أن يبدأ المتجر بإعداده",
  "support_faq_change_delivery_body_2": "افتحوا أوامركم وتأكدوا من أن التحرير مازال متاحاً وتسمح بعض المخازن بتحديثات صغيرة بينما يمكن للآخرين أن يغلقوا التغييرات عندما يبدأ الإعداد.",
  "support_faq_change_delivery_body_3": "وإذا كان التحرير غير متاح، فإن الخيار الأسرع يتمثل عادة في الاتصال بالدعم من قسم المساعدة أو بدء محادثة مع شخص ما.",
  "support_faq_change_delivery_body_4": "نوصي بفحص عربتك بعناية قبل وضع الطلب حتى تتمكن من تجنب التغييرات في اللحظة الأخيرة",
  "support_faq_order_history_body_1": "شحناتك السابقة والنشطة متاحة من قسم الطلبات في التطبيق",
  "support_faq_order_history_body_2": "افتحي الأمر الذي تريدين أن تعيدي النظر في بنوده، تفاصيل الدفع، عنوان التسليم، الوضع الحالي أو الماضي.",
  "support_faq_order_history_body_3": "هذا أفضل مكان لإعادة ترتيب الأشياء بسرعة عندما تريد نفس التسليم مرة أخرى",
  "support_faq_ordering_for_others_body_1": "يمكنك وضع أمر لشخص آخر باختيار أو دخول عنوان التسليم الصحيح قبل الخروج",
  "support_faq_ordering_for_others_body_2": "تأكد من أن اسم المتلقي ورقم الهاتف وأي تعليمات تسليم دقيقة حتى يتمكن حامل البريد من الوصول إلى الشخص المناسب",
  "support_faq_ordering_for_others_body_3": "إذا كنت بحاجة إلى إرسال آخر المستجدات إلى اتصال مختلف، استعراض تفاصيل الاتصال المتاحة خلال عملية التفتيش وقبل تأكيد الأمر.",
  "support_faq_ordering_for_others_body_4": "لأفضل تجربة، دع المتلقي يعرف أن التسليم في طريقه إلى هنا و يتشارك في أي تفاصيل توقيت معهم.",
  "support_faq_still_need_help_body_1": "إذا كان سؤالك غير مشمول هنا، فتح خيار الدردشة في أسفل الشاشة والتواصل مع فريق الدعم لدينا.",
  "support_faq_still_need_help_body_2": "إدراج تفاصيل رئيسية مثل اسم المتجر، ورقم الطلب، وشرح قصير للمسألة حتى نتمكن من المساعدة بشكل أسرع.",
  "support_faq_still_need_help_body_3": "وسيرشدكم فريقنا خلال الخطوات التالية ويساعد على حل الشواغل المتعلقة بالتوصيل أو الدفع أو الحسابات.",
  "searching_near": "البحث بالقرب",
  "products": "المنتجات",
  "stores": "المتاجر",
  "see_all": "انظر",
  "filter_title": "فيلم",
  "filter_close_label": "أقتربوا من التصفية",
  "filter_apply_results": "مرشحات التطبيق",
  "filter_category_title": "الفئة",
  "filter_price_title": "السعر",
  "filter_address_title": "عنوان قريب",
  "filter_stock_title": "المخزون",
  "filter_sort_title": "نوعا ما",
  "generic_list_error_title": "عدم القدرة على تحميل النتائج",
  "generic_list_error_description": "اسحب لتنعش أو حاول مرة أخرى",
  "generic_list_retry": "إعادة المحاولة",
  "generic_list_empty_title": "لا توجد نتائج",
  "generic_list_empty_description": "حاول البحث أو تعديل مرشحيك",
  "generic_list_search_placeholder": "البحث",
  "see_all_map_loading_title": "جارٍ البحث عن {{title}}",
  "see_all_map_loading_description": "هذا قد يستغرق بضع لحظات. من فضلك ابقى على هذه الشاشة",
  "see_all_map_sheet_title": "المطعم",
  "see_all_map_cta": "مطعم فيو",
  "change_password_title": "تغيير كلمة السر",
  "change_password_new_title": "كلمة سر جديدة",
  "change_password_email_heading": "تغيير كلمة السر؟",
  "change_password_email_description": "أدخل عنوان بريدك الإلكتروني وسنرسل لك رمز التحقق",
  "change_password_email_placeholder": "your@email.com",
  "change_password_continue": "استمر",
  "change_password_verify_heading": "تحقق من بريدك الإلكتروني",
  "change_password_verify_description": "أدخل الرمز المكون من 4 أرقام المرسل إلى {{email}}",
  "change_password_verify_button": "تصديق مكتب المدعي العام",
  "change_password_new_heading": "خلق كلمة مرور جديدة",
  "change_password_new_description": "كلمة السر الجديدة يجب أن تكون مختلفة عن كلمة السر السابقة",
  "change_password_new_placeholder": "كلمة سر جديدة",
  "change_password_confirm_placeholder": "تأكيد كلمة سر جديدة",
  "change_password_set_new": "وضع كلمة سر جديدة",
  "change_password_mismatch": "كلمات السر لا تتطابق",
  "change_password_error_title": "خطأ",
  "change_password_send_otp_error": "فشل في إرسال رمز التحقق.",
  "change_password_verify_otp_error": "شفرة غير صالحة أو انتهت",
  "change_password_update_error": "فشلت في تحديث كلمة السر",
  "change_password_success_title": "النجاح",
  "change_password_success_message": "تم تحديث كلمة السر الخاصة بك.",
  "change_password_otp_resent_title": "تم إرسالها",
  "change_password_otp_resent_message": "وأرسلت مدونة جديدة للتحقق.",
  "delete_account_step_label": "تحذف حسابي",
  "delete_account_sorry_heading": "سنأسف لرؤيتك تذهب",
  "delete_account_sorry_subtext": "هل يمكننا تغيير رأيك؟ اسقط الخط",
  "delete_account_contact_email": "hello@enategadelivery.com",
  "delete_account_reason_heading": "لماذا تريد أن تترك توصيلة الطعام؟",
  "delete_account_reason_subtext": "رجاءً أخبرنا سبب حذف حسابك:",
  "delete_account_reason_mistake": "صنعت هذا الحساب بالخطأ",
  "delete_account_reason_no_longer": "أنا لا أريد استخدام تسليم الطعام بعد الآن",
  "delete_account_reason_no_venues": "لا أستطيع إيجاد الأماكن أو الخدمات التي أريدها",
  "delete_account_reason_other": "أخرى",
  "delete_account_confirm_heading": "تحذف حساب تسليم الطعام",
  "delete_account_confirm_description": "هذا العمل سيحذف حسابك ولن تستطيع إسترجاعه يرجى تأكيد فهمك بدقة البيانات التالية:",
  "delete_account_confirm_item_orders": "أعلم أنني لن أكون قادراً على الوصول لأوامري",
  "delete_account_confirm_item_marketplace": "أعلم أنني لن أكون قادراً على كتابة الطلبات عبر سوق تسليم الأغذية",
  "delete_account_final_heading": "تأكد من أنك سعيد للمضي قدما",
  "delete_account_final_description": "الرجاء ملاحظة أن هذا دائم ولا يمكن أن يكون غير مقصود. لتأكيد حذف حسابك، يرجى مراجعة بريدك الإلكتروني أدناه:",
  "delete_account_email_label": "البريد الإلكتروني",
  "delete_account_email_placeholder": "your@email.com",
  "delete_account_cta_continue": "استمر",
  "delete_account_cta_delete": "الحساب",
  "delete_account_close": "اقترب",
  "delete_account_alert_title": "الحساب",
  "delete_account_alert_message": "هل أنت متأكد أنك تريد حذف حسابك بشكل دائم؟ هذا العمل لا يمكن أن يزول.",
  "delete_account_alert_cancel": "إلغاء",
  "delete_account_alert_confirm": "تحذف",
  "delete_account_error_title": "خطأ",
  "delete_account_error": "فشل في حذف الحساب حاول مرة أخرى",
  "color_mode_title": "نمط الألوان",
  "color_mode_section_label": "نمط لون التطبيقات المختارة",
  "color_mode_system": "نظام التقصير",
  "color_mode_light": "الضوء",
  "color_mode_dark": "الظلام",
  "language_title": "لغات التطبيق",
  "language_section_label": "اختر اللغة",
  "language_english": "الإنجليزية",
  "language_german": "الألمانية",
  "language_spanish": "الإسبانية",
  "language_arabic": "العربية",
  "language_french": "الفرنسية",
  "popular": "الشعبية",
  "ingredients": "المكونات",
  "usage": "الاستخدام",
  "nutrition_facts": "حقائق التغذية",
  "amount_per": "المبلغ الواحد",
  "energy": "الطاقة",
  "fat": "فاتن",
  "carbohydrates": "الكربوهيدرات",
  "protein": "البروتين",
  "sugar": "السكر",
  "choose_size": "Size",
  "choose_variation": "اختصار الفرق",
  "select_one": "اختيار واحد",
  "required_label": "المطلوب",
  "optional_label": "الاختياري",
  "product_option_choose_at_least": "اختر {{count}} على الأقل",
  "product_option_choose_range": "Choose {{min}}-{{max}}",
  "product_option_choose_up_to": "اختر حتى {{count}}",
  "product_option_required_error": "اختيار الخيارات المطلوبة لمواصلة العمل.",
  "small": "صغيرة",
  "medium": "متوسطة",
  "large": "رقيب",
  "choose_your_flavour": "اختر سلافك",
  "choose_your_addons": "اختر أظافرك",
  "add_to_cart": "مضافا إليها",
  "cart_title": "السلة",
  "cart_store_fallback": "متجرك",
  "cart_return_to_store": "العودة إلى {{store}}",
  "cart_delivery_time": "{{time}}",
  "cart_items_title": "بنودك",
  "cart_add_more": "إضافة المزيد",
  "cart_recommended_title": "أوصي لك",
  "cart_checkout": "الذهاب إلى المراقبة",
  "cart_checkout_short": "التحقق",
  "cart_order_summary": "موجز",
  "cart_promo_title": "رمز الخصم",
  "cart_promo_subtitle": "اختر رمز لهذا الأمر",
  "cart_promo_applied": "مختارون للمغادرة",
  "cart_promo_add": "مضاف",
  "cart_promo_change": "التغيير",
  "cart_fees_at_checkout": "تم تأكيد رسوم التسليم والخدمات عند المغادرة",
  "cart_minimum_remaining": "متبقي {{amount}} للوصول إلى الحد الأدنى للطلب",
  "cart_minimum_reached": "الحد الأدنى من النظام",
  "cart_minimum_progress_accessibility": "{{current}} من الحد الأدنى {{minimum}} للطلب",
  "cart_item_unavailable": "غير متاح",
  "cart_recommendation_accessibility": "عرض {{product}}",
  "cart_fee_modal_current_subtotal": "المجموع الفرعي الحالي",
  "cart_fee_modal_minimum_order": "الحد الأدنى من النظام",
  "cart_fee_modal_base_delivery": "رسوم تسليم القاعدة",
  "cart_fee_modal_checkout_notice": "رسوم التوصيل والخدمة النهائية محسوبة على عنوانك عند المغادرة",
  "checkout_title": "التحقق",
  "checkout_order_from": "الأمر من",
  "checkout_item_count": "{{count}}",
  "checkout_fulfillment_title": "ما رأيك؟",
  "checkout_fulfillment_delivery": "التسليم",
  "checkout_fulfillment_pickup": "بيبي",
  "checkout_delivery_details_title": "تفاصيل التنفيذ",
  "checkout_pickup_details_title": "التفاصيل",
  "checkout_address_title": "اختر عنوان التسليم",
  "checkout_address_subtitle": "تاب هنا لمواصلة",
  "checkout_address_selected_subtitle": "تاب هنا للتغيير",
  "checkout_pickup_title": "الموقع",
  "checkout_pickup_subtitle": "اجمع طلبك من المتجر",
  "checkout_leave_at_door_title": "اترك الباب",
  "checkout_leave_at_door_subtitle": "تسليم خال من الاتصال",
  "checkout_notes_title": "مذكرات أوامر",
  "checkout_message_restaurant_title": "أضف رسالة للمطعم",
  "checkout_message_restaurant_subtitle": "طلبات خاصة، حساسية، قيود غذائية؟",
  "checkout_message_restaurant_editor_title": "تعليمات للمطعم",
  "checkout_message_restaurant_editor_description": "طلبات خاصة، حساسية، قيود غذائية؟",
  "checkout_message_restaurant_placeholder": "إضافة طلبات خاصة (اختيارية)",
  "checkout_message_courier_title": "أضف رسالة للسعاة",
  "checkout_message_courier_subtitle": "يضاف أي تعليمات هامة أو علامات أو طلبات خاصة.",
  "checkout_message_courier_editor_title": "تعليمات لحاملي البريد",
  "checkout_message_courier_editor_description": "يضاف أي تعليمات هامة أو علامات أو طلبات خاصة.",
  "checkout_message_courier_placeholder": "إضافة تعليمات التسليم (اختياريا)",
  "checkout_message_done": "تم",
  "checkout_delivery_time_title": "وقت التنفيذ",
  "checkout_collection_time_title": "وقت التحصيل",
  "checkout_delivery_time_standard": "المعيار",
  "checkout_delivery_time_standard_eta": "10-20 دقيقة",
  "checkout_delivery_time_schedule": "الجدول الزمني",
  "checkout_delivery_time_schedule_hint": "اختر وقت التسليم",
  "checkout_schedule_title": "الجدول الزمني",
  "checkout_schedule_heading": "اختر الوقت الذي يناسبك",
  "checkout_schedule_description": "الوقت المتاح في هذا المتجر",
  "checkout_schedule_available_times": "الأوقات المتاحة",
  "checkout_schedule_today": "اليوم",
  "checkout_schedule_tomorrow": "غداً",
  "checkout_schedule_asap": "بأسرع ما يمكن",
  "checkout_schedule_confirm": "تأكيد",
  "checkout_schedule_empty_title": "لا توجد جداول زمنية متاحة",
  "checkout_schedule_empty_message": "حاولي يوم آخر أو استمري في التسليم",
  "checkout_schedule_error_title": "غير قادر على تحميل الجداول الزمنية",
  "checkout_schedule_error_message": "من فضلك حاول مرة أخرى أن تحضر الوقت المتاح",
  "checkout_schedule_slot_expired": "ذلك الوقت لم يعد متاحاً أرجوك إختر واحدة أخرى",
  "checkout_schedule_unavailable_note": "ما قبل الدورة غير متاحة في أيام الأحد.",
  "checkout_payment_title": "المدفوعات",
  "checkout_payment_selector_title": "طريقة الدفع",
  "checkout_payment_close": "طرق السداد",
  "checkout_payment_selector_heading": "اختيار طريقة الدفع",
  "checkout_payment_selector_description": "اختيار كيف تريد أن تدفع لهذا الطلب.",
  "checkout_payment_selector_confirm": "طريقة الدفع",
  "checkout_payment_cash_title": "النقدية",
  "checkout_payment_cash_subtitle": "تدفع نقداً عندما تصل أوامرك",
  "checkout_payment_card_title": "بطاقة",
  "checkout_payment_card_subtitle": "ادفع بطاقتك",
  "checkout_payment_card_saved_subtitle": "{{brand}} ( •---------- {{last4}})",
  "checkout_payment_option_cash_description": "ادفع عند التوصيل أو التقاط",
  "checkout_payment_option_card_description": "سوف تُكمل الدفع في مُراقبة (ستري) آمنة.",
  "checkout_payment_add_card_required": "أضف بطاقة في المحفظة لاستخدام بطاقة الدفع.",
  "checkout_payment_cash_unavailable": "النقدية عند التسليم غير متاحة لهذا المتجر",
  "checkout_payment_card_unavailable": "مدفوعات البطاقات غير متاحة لهذا المتجر",
  "checkout_payment_cod_unavailable_error": "هذا المتجر لا يسمح بالمال عند التسليم",
  "checkout_payment_card_unavailable_error": "هذا المتجر لا يسمح بدفع البطاقات",
  "checkout_payment_webview_title": "مجموع المدفوعات",
  "checkout_payment_processing_title": "تأكيد دفعك",
  "checkout_payment_processing_message": "رجاءً إنتظرْ بينما نَتأكّدُ مِنْ دفعِكَ ويَجْعلُ طلبَكَ.",
  "checkout_payment_processing_error": "مازلنا نتفقد دفعك انتظر لحظة من فضلك",
  "checkout_payment_cancelled": "وألغيت المدفوعات.",
  "checkout_payment_failed": "فشل الدفع حاول مرة أخرى بطريقة أخرى",
  "checkout_payment_confirmation_delayed": "دفع بطاقتك قد لا يزال تجهيز. تحقق من أوامرك قبل المحاولة مرة أخرى",
  "checkout_payment_card_redirecting": "أكملي دفعك في المسبح لإنهاء هذا الأمر",
  "checkout_payment_card_redirect_error": "غير قادر على فتح مراقبة آمنة الآن",
  "checkout_leave_at_door_card_required": "الإجازة عند الباب تتطلب دفع البطاقة الرجاء التحول إلى البطاقة لمواصلة.",
  "checkout_leave_at_door_switched_to_card": "تحولت طريقة الدفع إلى البطاقة من أجل الإجازات في الهواء",
  "checkout_promo_title": "رمز الخصم",
  "checkout_promo_subtitle": "تاب هنا لمواصلة",
  "checkout_promo_tap_to_change": "تاب هنا للتغيير",
  "checkout_promo_remove": "إزالة الألغام",
  "checkout_promo_removed": "مسح الرمز",
  "checkout_tip_title": "تلاعب بساعتك",
  "checkout_tip_description": "سيدفع البقشيش بالكامل إلى الساعي",
  "checkout_tip_custom": "العرف",
  "checkout_tip_none": "لا معلومة",
  "checkout_tip_custom_title": "إضافة بقشيش",
  "checkout_tip_custom_placeholder": "0.00",
  "checkout_tip_custom_done": "تم",
  "checkout_summary_title": "موجز",
  "checkout_summary_hint": "مجموع الضرائب (إذا انطبق)",
  "checkout_summary_subtotal": "المجموع الفرعي",
  "checkout_summary_discount": "الخصم",
  "checkout_summary_delivery_fee": "رسوم التسليم",
  "checkout_summary_packing_charges": "رسوم التعبئة",
  "checkout_summary_tax": "الضرائب",
  "checkout_summary_tip": "معلومة حامل الحقيبة",
  "checkout_summary_total": "المجموع",
  "checkout_summary_free": "مجانا",
  "checkout_place_order": "أمر المكان",
  "checkout_place_order_pending": "وسيتاح أمر المكان في الخطوة التالية.",
  "checkout_place_order_success": "وضع النظام بنجاح.",
  "checkout_place_order_error": "غير قادر على وضع طلبك الآن",
  "order_confirmation_title": "تم تأكيد الأمر",
  "order_confirmation_number": "الأمر رقم {{number}}",
  "order_confirmation_message": "{{store}} قد تلقى طلبك. وسنطلعكم على آخر المستجدات أثناء تحركاتنا.",
  "order_confirmation_store_fallback": "متجرك",
  "order_confirmation_step_confirmed": "تم تأكيدها",
  "order_confirmation_step_store": "مع المتجر",
  "order_confirmation_step_preparing": "الإعداد",
  "order_confirmation_step_scheduled": "الجدول الزمني",
  "order_confirmation_step_delivery": "التسليم",
  "order_confirmation_step_pickup": "الاستلام",
  "order_confirmation_eta_label": "تقديرات الوصول",
  "order_confirmation_ready_label": "الوقت الجاهز المقدر",
  "order_confirmation_eta_pending": "يستكمل قريبا",
  "order_confirmation_minutes": "{{estimate}} دقيقة",
  "order_confirmation_order_from": "الأمر من",
  "order_confirmation_track": "ترتيب المسار",
  "order_confirmation_receipt": "إيصال الرؤية",
  "order_confirmation_help": "مساعدة",
  "order_confirmation_done": "تأكيد",
  "checkout_address_required": "الرجاء اختيار عنوان التسليم أولا.",
  "checkout_promo_pending": "وسيضاف الدعم الرمزي للبرومو في الخطوة التالية.",
  "checkout_preview_error_title": "غير قادر على التحميل",
  "checkout_preview_error_message": "حاول مرة أخرى في لحظة",
  "checkout_preview_updating": "تحديث مجموعتك...",
  "checkout_store_closed_title": "المخزن مغلق",
  "checkout_store_closed_message": "هذا المتجر مغلق حالياً حاول مرة أخرى خلال ساعات الافتتاح",
  "checkout_address_outside_delivery_area_title": "منطقة التسليم الخارجي",
  "checkout_address_outside_delivery_area_message": "هذا المتجر لا يمكنه تسليمه إلى العنوان المختار الرجاء اختيار عنوان تسليم مختلف.",
  "checkout_change_address": "عنوان التغيير",
  "checkout_insufficient_wallet_balance_title": "عدم كفاية رصيد المحفظة",
  "checkout_insufficient_wallet_balance_message": "رصيد محفظتك ({{balance}}) لا يغطي إجمالي هذا الطلب ({{total}}). أضف أموالًا أو اختر طريقة دفع أخرى.",
  "checkout_insufficient_wallet_balance_add_funds": "إضافة أموال للمحفظة",
  "checkout_insufficient_wallet_balance_choose_payment": "اختيار طريقة دفع أخرى",
  "checkout_payment_wallet_title": "الجدار",
  "checkout_payment_wallet_subtitle": "إدفعي بإستخدام رصيد محفظتك",
  "checkout_payment_option_wallet_description": "ادفعوا بأمان باستخدام رصيد محفظتكم",
  "checkout_payment_wallet_insufficient_balance": "عدم كفاية رصيد المحفظة لهذا الطلب",
  "checkout_payment_wallet_balance": "الرصيد الجداري: {{currency}} {{amount}}",
  "cart_empty_title": "عربتك فارغة",
  "cart_empty_message": "عندما تضيف أشياء من متجر، سيكون طلبك هنا حتى تتمكن من إجراء تغييرات كلما أردت.",
  "cart_start_shopping": "بدء التسوق",
  "cart_error_title": "لا يمكن تحميل عربتك",
  "cart_error_message": "حاول مرة أخرى في لحظة",
  "cart_remove_item": "بند إزالة الألغام",
  "cart_decrement_item": "انخفاض الكمية",
  "cart_increment_item": "الزيادة في الكمية",
  "cart_info_label": "رسوم الطلب والحد الأدنى من الإنفاق",
  "cart_low_order_fee_applies_prefix": "ألف",
  "cart_low_order_fee_applies_suffix": "رسوم منخفضة السعر",
  "cart_fee_modal_title": "الحد الأدنى للنفقة",
  "cart_fee_modal_description_prefix": "الحد الأدنى للنفقة هو",
  "cart_fee_modal_description_suffix": "مجموع قيمة العربات",
  "cart_fee_modal_total_cart_value": "مجموع قيمة العربات",
  "cart_fee_modal_service_fee": "رسوم الخدمات",
  "cart_fee_modal_above": "&quot; أعلاه",
  "cart_fee_modal_no_fee": "No Fee",
  "cart_fee_modal_note_prefix": "* للأوامر أقل من",
  "cart_fee_modal_note_middle": "رسم طلب صغير",
  "cart_fee_modal_note_suffix": "ينطبق",
  "cart_store_conflict_title": "أستبدل عربتك الحالية؟",
  "cart_store_conflict_message": "عربتك لديها أصناف من متجر آخر يستعاض عنها بإضافة بنود من {{incomingStore}}.",
  "cart_store_conflict_message_with_product": "عربتك لديها أصناف من متجر آخر يستعاض عنها بإضافة {{product}} من {{incomingStore}}.",
  "cart_store_conflict_keep_cart": "حافظ على العربة الحالية",
  "cart_store_conflict_replace_cart": "استبدال العربة",
  "cart_store_conflict_store_fallback": "هذا المتجر",
  "cart_action_loading_options_title": "خيارات الإعداد",
  "cart_action_loading_options_message": "يرجى الانتظار بينما نحمل التكييفات المتاحة لهذا البند.",
  "cart_action_customization_required_title": "اختر خياراتك أولاً",
  "cart_action_customization_required_message": "يرجى استعراض خيارات المنتج قبل إضافة هذا البند إلى عربتك.",
  "cart_action_out_of_stock_title": "البند غير متاح",
  "cart_action_out_of_stock_message": "هذا البند غير موجود حالياً. رجاءً جربي بنداً آخر",
  "cart_network_error_title": "مسألة العلاقة",
  "cart_network_error_message": "أرجوك تحقق من اتصالك بالإنترنت وحاول مرة أخرى",
  "cart_add_success_title": "مضافة إلى العربة",
  "cart_add_success_message": "{{quantity}} × {{product}} جاهز في سلة التسوق.",
  "cart_add_success_go_to_cart": "الذهاب إلى العربة",
  "cart_add_success_continue_shopping": "استمر بالتسوق",
  "cart_add_error_title": "لا يمكن إضافة بند",
  "cart_add_error_message": "حاول مرة أخرى في لحظة",
  "cart_store_closed_title": "{{storeName}} مغلقة",
  "cart_store_closed_description": "هذا المتجر لا يقبل الأوامر الآن من فضلك تحقق مرة واحدة إعادة فتح.",
  "cart_update_success_title": "تحديث السيارة",
  "cart_update_success_message": "كمية العربات الخاصة بك تم تحديثها.",
  "cart_update_error_title": "لا يمكن تحديث العربة",
  "cart_update_error_message": "أرجوك حاول تحديث عربتك مرة أخرى",
  "cart_remove_success_title": "البند المزال",
  "cart_remove_success_message": "تم إزالة البند من عربتك",
  "cart_remove_error_title": "لا يمكن إزالة البند",
  "cart_remove_error_message": "رجاء حاول إزالة البند مرة أخرى",
  "cart_clear_action": "عربة آمنة",
  "cart_clear_popup_title": "أخلي عربتك؟",
  "cart_clear_popup_message": "هذا سيزيل كل الأشياء من عربتك الحالية لكي تبدأ من جديد",
  "cart_clear_popup_confirm": "عربة آمنة",
  "cart_clear_popup_cancel": "إلغاء",
  "cart_clear_error_title": "لا يمكن استبدال العربة",
  "cart_clear_error_message": "حاول مرة أخرى في لحظة",
  "free": "مجانا",
  "store_card_new": "جديدة",
  "store_card_delivery_fee_unavailable": "{{currency}}",
  "store_card_delivery_time_unavailable": "ETA —",
  "store_card_distance_unavailable": "- كيلومترات",
  "product_info_back": "العودة",
  "product_info_share": "حصة المنتجات",
  "product_info_unavailable": "في الوقت الراهن غير متاح",
  "product_info_error_title": "لا يمكن تحميل المنتج",
  "orders_tab_active": "النشاط",
  "orders_tab_history": "الماضي",
  "orders_tab_scheduled": "الجدول الزمني",
  "orders_history_active_heading": "الأوامر الفعلية",
  "orders_empty_active_title": "لم تصدر أوامر نشطة بعد",
  "orders_empty_active_subtitle": "أوامرك النشطة ستظهر هنا بمجرد أن تضع واحدة",
  "orders_empty_history_title": "لا أوامر بعد",
  "orders_empty_history_subtitle": "لم تصدروا أي أمر. سوف تظهر هنا عندما تصنع واحدة",
  "orders_empty_history_cta": "بدء التسوق",
  "orders_empty_scheduled_title": "لا تسليم الجدول بعد",
  "orders_empty_scheduled_subtitle": "لم تحددوا أي أمر.",
  "orders_history_ongoing_heading": "النظام الجاري",
  "orders_history_past_heading": "الأوامر السابقة",
  "orders_history_scheduled_heading": "الأوامر المقررة",
  "orders_list_load_more": "المزيد",
  "orders_list_no_more_items": "لا مزيد من البنود",
  "orders_list_error": "غير قادر على تحميل التوصيلات المقررة الآن",
  "orders_list_retry": "حاول مرة أخرى",
  "orders_status_upcoming": "قادم",
  "orders_status_ongoing": "جارية",
  "orders_status_scheduled": "الجدول الزمني",
  "orders_status_received": "الأمر الوارد",
  "orders_status_confirmed": "تم تأكيدها",
  "orders_status_preparing": "إعداد طلبك",
  "orders_status_ready": "جاهز للإلتقاط",
  "orders_status_courier_assigned": "حامل الحقيبة",
  "orders_status_on_the_way": "في الطريق",
  "orders_status_arrived": "وصل الساعي",
  "orders_status_delayed": "تأخر التنفيذ",
  "orders_status_delivered": "النظام المنفذ",
  "orders_status_cancelled": "الأمر الملغى",
  "orders_status_rejected": "رفض الأمر",
  "orders_status_failed": "لم يكن من الممكن إتمام الأمر",
  "orders_screen_title": "الأوامر",
  "orders_screen_subtitle": "اتبع ما يجري أو إعادة النظر في التسليم الماضي.",
  "orders_view_details": "تفاصيل الرؤية",
  "order_cancel_title": "أمر إلغاء؟",
  "order_cancel_message": "أوامر الدفع سترد لمحفظتك",
  "order_cancel_keep": "اطلب",
  "order_cancel_confirm": "طلب إلغاء",
  "order_cancel_failed": "غير قادر على إلغاء الأمر",
  "order_details_title": "تفاصيل النظام",
  "order_details_error_title": "غير قادر على حمل هذا الطلب الآن",
  "order_details_status": "الوضع النظامي",
  "order_details_progress": "التقدم المحرز في التنفيذ",
  "order_details_scheduled_for": "الجدول الزمني",
  "order_details_items": "بنود النظام",
  "order_details_summary": "موجز",
  "order_details_payment_details": "تفاصيل المدفوعات",
  "order_details_payment_method": "طريقة الدفع",
  "order_details_paid": "دفع",
  "order_details_unavailable": "غير متاح",
  "order_details_reference": "الأمر رقم {{number}}",
  "order_details_get_help": "مساعدة",
  "order_details_order_number": "رقم النظام",
  "order_details_delivery_address": "عنوان التسليم",
  "order_details_item_subtotal": "البند الفرعي",
  "order_details_discount": "الخصم",
  "order_details_tax": "الضرائب",
  "order_details_packing_charges": "رسوم التعبئة",
  "order_details_delivery_fee": "التسليم",
  "order_details_courier_tip": "معلومة حامل الحقيبة",
  "order_details_total_amount": "مجموع المبلغ",
  "order_details_rate_order": "معدل الطلب",
  "order_details_view_rating": "شاهد تقديرك",
  "order_details_increase_tip": "زيادة البقشيش",
  "order_details_track_progress": "التقدم المحرز",
  "order_details_order_again": "مرة أخرى",
  "order_details_notes": "الحواشي",
  "order_details_restaurant_note": "مذكرة احتياطية",
  "order_details_courier_note": "مذكرة حامل الحقيبة",
  "order_again_error_title": "لا يمكن إعادة ترتيب البنود",
  "order_again_error_message": "أرجوك حاول طلب هذه الأشياء مرة أخرى في لحظة",
  "order_again_partial_title": "بعض البنود تحتاج إلى اهتمام",
  "order_details_tip_done": "تم",
  "order_details_tip_placeholder": "0.00",
  "order_details_empty_items": "لا بنود",
  "order_details_quantity_one": "الكمية {{count}}",
  "order_tracking_title": "أمرك",
  "order_tracking_help": "مساعدة تتبع النظام",
  "order_tracking_eta_label": "وقت التسليم التقديري",
  "order_tracking_eta_pending": "يستكمل قريبا",
  "order_tracking_eta_short_confirming": "تأكيد",
  "order_tracking_eta_short_preparing": "تحضير",
  "order_tracking_eta_short_on_way": "في الطريق",
  "order_tracking_eta_short_nearby": "قريبة",
  "order_tracking_eta_short_delivered": "تم",
  "order_tracking_eta_short_ended": "انتهت",
  "order_tracking_eta_short_updating": "قريبا",
  "order_tracking_until_delivered": "حتى يتم تسليمها",
  "order_tracking_eta_remaining": "المتبقية",
  "order_tracking_estimated_arrival": "الوصول المتوقع {{time}}",
  "order_tracking_close": "تتبع النظام",
  "order_tracking_recenter_map": "خريطة حديثة",
  "order_tracking_route_loading": "إيجاد أفضل طريق...",
  "order_tracking_route_unavailable": "الطريق الحي غير متاح",
  "order_tracking_route_unavailable_description": "وتظل المواقع الحية مرئية بينما تستكمل طرق الطرق.",
  "order_tracking_route_pending": "تحديث الطريق سيظهر هنا",
  "order_tracking_route_pending_description": "وسيرسم الطريق بمجرد توافر الموقعين.",
  "order_tracking_location_unavailable": "خريطة حية غير متاحة",
  "order_tracking_location_unavailable_description": "تحديثات طلبك لا تزال متاحة أدناه",
  "order_tracking_progress": "التقدم المحرز في التنفيذ",
  "order_tracking_next_step": "التالي: {{step}}",
  "order_tracking_no_next_step": "لا مزيد من الخطوات",
  "order_tracking_delay_next": "سنطلعكم على آخر المستجدات",
  "order_tracking_order_items": "بنود النظام",
  "order_tracking_courier_role": "ساعتك",
  "order_tracking_courier_pending": "تفاصيل المراسلين تستكمل",
  "order_tracking_message_courier": "حامل رسالة",
  "order_tracking_delivered_title": "المبلغ",
  "order_tracking_delivered_message_line_one": "لقد تم تسليم طلبك",
  "order_tracking_delivered_message_line_two": "استمتع بوجبتك",
  "order_tracking_error_title": "غير قادر على التعقب الآن",
  "order_tracking_delivery_details": "تفاصيل التنفيذ",
  "order_tracking_collection_details": "تفاصيل التجميع",
  "order_tracking_contact_title": "اتصل بساعتك",
  "order_tracking_contact_subtitle": "طلب التسليم بدون اتصال",
  "order_tracking_courier_fallback": "حامل الحقيبة",
  "order_tracking_summary": "موجز",
  "order_tracking_summary_note": "مجموع الضرائب (إذا انطبق)",
  "order_tracking_unavailable_title": "أمر غير مؤكد",
  "order_tracking_unavailable_description": "المتجر لم يتمكن من تأكيد طلبك لذا تم إلغاؤه يمكنك وضعه مرة أخرى أو اختيار متجر آخر قريب.",
  "order_tracking_unavailable_cancelled_description": "تم إلغاء هذا الأمر لذا لم يتبقى شيء لتتبعه يمكنك وضعه مرة أخرى أو اختيار متجر آخر قريب.",
  "order_tracking_unavailable_action": "العودة إلى المنزل",
  "wallet_title": "الجدار",
  "wallet_balance_label": "الرصيد الجداري",
  "wallet_hide_balance": "رصيد المحفظة",
  "wallet_show_balance": "رصيد حافظة العرض",
  "wallet_action_convert": "النقاط المنحرفة",
  "wallet_action_cards": "بطاقات إدارة",
  "wallet_loyalty_available_points": "النقاط المتاحة",
  "wallet_loyalty_zero_state": "لا نقاط تحول بعد نقاطك ستظهر هنا عندما تكسبهم",
  "wallet_loyalty_receive_label": "سوف تستقبل",
  "wallet_loyalty_details": "تفاصيل الولاء",
  "wallet_loyalty_hide_details": "إخفاء تفاصيل الولاء",
  "wallet_points_max": "ماكس",
  "wallet_convert_sheet_description": "تحويل نقاط الولاء الخاص بك إلى رصيد المحفظة.",
  "wallet_loyalty_total_points": "مجموع نقاط الولاء المكتسبة",
  "wallet_loyalty_rate": "{{points}} نقطة = {{currency}} 1",
  "wallet_loyalty_amount": "الرصيد الجداري المكتسب من الولاء",
  "wallet_convert_points_title": "نقاط الولاء",
  "wallet_points_available": "{{points}}",
  "wallet_points_input": "نقاط التحول",
  "wallet_points_receive": "سوف تحصل على {{currency}} {{amount}}",
  "wallet_convert_points_action": "إضافة إلى المحفظة",
  "wallet_points_converted_title": "النقاط المحولة",
  "wallet_points_converted_message": "{{currency}} {{amount}} أضيف إلى محفظتك",
  "wallet_points_convert_error": "عدم القدرة على تحويل النقاط",
  "wallet_cards_title": "البطاقات",
  "wallet_payment_methods_title": "أساليب الدفع",
  "wallet_cards_sheet_description": "إدارة بطاقاتك المحفوظة.",
  "wallet_cards_secure_note": "تفاصيل البطاقة يتم التعامل معها بأمان من قبل (روي).",
  "wallet_saved_card_accessibility": "بطاقة {{brand}} باسم {{name}}، {{last4}}",
  "wallet_done": "تم",
  "wallet_close": "اقترب",
  "wallet_view_transactions": "معاملات اليقظة",
  "wallet_secure": "الضمان",
  "wallet_default_card": "التقصير",
  "wallet_add_card": "مطروحة/بطاقة ائتمان",
  "wallet_topup_title": "المال",
  "wallet_topup_sheet_description": "ارفعي محفظتك من أجل دفعات أسرع وأسهل",
  "wallet_select_payment_method": "طريقة السداد المختارة",
  "wallet_choose_payment_method": "طريقة الاختيار للدفع",
  "wallet_clear_amount": "المبلغ الإجمالي",
  "wallet_topup_amount": "المبلغ المستخدم",
  "wallet_topup_action": "إضافة إلى المحفظة",
  "wallet_topup_action_amount": "أضف {{amount}} إلى المحفظة",
  "wallet_cover_order": "أعلى {{amount}} لهذا الأمر",
  "wallet_topup_minimum": "الحد الأدنى للزيادة: {{amount}}",
  "wallet_add_card_continue": "إضافة بطاقة لمواصلة",
  "wallet_topup_card_required": "أضف بطاقة قبل أن أصعد",
  "wallet_topup_success": "المدفوعات الناجحة",
  "wallet_topup_success_title": "تم تأكيد الدفع",
  "wallet_topup_success_message": "ودفعت شركة {{amount}} بنجاح. رصيد محفظتك سيستكمل قريباً",
  "wallet_topup_processing": "تجهيز المدفوعات",
  "wallet_topup_pending": "رصيد محفظتك سيستكمل بعد تأكيد الدفع",
  "wallet_topup_error": "غير قادر على إضافة المال",
  "wallet_recent_transactions": "المعاملات الأخيرة",
  "wallet_balance_load_error": "لا يمكن تحميل توازنك. قفزة إلى العودة.",
  "wallet_statement_today": "اليوم",
  "wallet_statement_yesterday": "أمس",
  "wallet_statement_title": "بيان الجدارة",
  "wallet_statement_balance": "الرصيد الحالي",
  "wallet_statement_all": "جميع الأنشطة",
  "wallet_statement_money_in": "المال في",
  "wallet_statement_money_out": "المال",
  "wallet_statement_no_filtered_activity": "لا يوجد نشاط في هذه الفئة حتى الآن",
  "wallet_statement_details": "تفاصيل المعاملات",
  "wallet_statement_reason": "السبب",
  "wallet_statement_direction": "التوجيه",
  "wallet_statement_date": "التاريخ والوقت",
  "wallet_statement_status": "الحالة",
  "wallet_statement_reference": "المدفوعات أو الأمر",
  "wallet_statement_transaction_id": "هوية المعاملات الجدارية",
  "wallet_statement_view_order": "طلب المراقبة",
  "wallet_statement_completed": "مكتملة",
  "wallet_statement_approved": "الوظائف المعتمدة",
  "wallet_statement_pending": "تنتهي",
  "wallet_statement_rejected": "مرفوضة",
  "wallet_statement_unknown_status": "المسجلة",
  "wallet_statement_unknown_direction": "التوجيه غير متاح",
  "wallet_statement_card_topup": "أموال مضافة للمحفظة",
  "wallet_statement_card_topup_description": "دفع ببطاقة منقذة",
  "wallet_statement_order_payment": "دفعة لطلب",
  "wallet_statement_order_payment_description": "دفعة من محفظتك",
  "wallet_statement_order_refund": "رد الأمر",
  "wallet_statement_order_refund_description": "المال عاد إلى محفظتك",
  "wallet_statement_loyalty_conversion": "نقاط الولاء المحولة",
  "wallet_statement_loyalty_conversion_description": "مضاف من نقاط الولاء الخاصة بك",
  "wallet_statement_opening_balance": "الرصيد المبدئي",
  "wallet_statement_opening_balance_description": "محفظتك السابقة",
  "wallet_statement_credit": "الأموال المضافة إلى المحفظة",
  "wallet_statement_credit_description": "المصدر لم يسجل",
  "wallet_statement_debit": "المال المأخوذ من المحفظة",
  "wallet_statement_debit_description": "السبب لم يسجل",
  "wallet_statement_withdrawal": "سحب الجدار",
  "wallet_statement_withdrawal_description": "الأموال المسحوبة من محفظتك",
  "wallet_statement_unknown": "المعاملات الجدارية",
  "wallet_statement_unknown_description": "لم تسجل تفاصيل المعاملات",
  "wallet_transactions_empty_title": "لا معاملات بعد",
  "wallet_transactions_empty_description": "نشاط محفظتك سيظهر هنا بمجرد أن تدفع أو تسترد",
  "wallet_transactions_error": "لا يمكننا تحميل نشاط محفظتك حاول مرة أخرى",
  "wallet_see_all": "شاهد كل شيء",
  "wallet_view_details": "تفاصيل الرؤية",
  "wallet_add_card_title": "بطاقة",
  "wallet_name_on_card": "الاسم على البطاقة",
  "wallet_name_placeholder": "أضف اسم حامل البطاقة",
  "wallet_card_number_label": "رقم البطاقة",
  "wallet_card_secure_title": "تفاصيل بطاقتك تبقى محمية",
  "wallet_card_secure_description": "تفاصيل المدفوعات مشفرة ومعالجتها بأمان من قبل (روي).",
  "wallet_card_number_placeholder": "رقم بطاقة الائتمان أو الديون",
  "wallet_expiry_label": "تاريخ انتهاء الخدمة",
  "wallet_security_code_label": "رمز الأمن",
  "wallet_pay_securely": "الدفع بأمان",
  "wallet_save_card": "أنقذني",
  "wallet_no_saved_cards": "لا توجد بطاقات منقذة",
  "wallet_cards_error": "غير قادر على حمل البطاقات الموفرة حاول مرة أخرى",
  "wallet_add_card_error": "غير قادر على حفظ البطاقة",
  "wallet_setup_intent_success_title": "بدأ إعداد البطاقات",
  "wallet_setup_intent_success_message": "خلقت النية أكملوا تدفق تأكيد البطاقة مع (ري دي كي)",
  "wallet_stripe_publishable_key_missing": "مفتاح النشر المتعرّي مفقود",
  "wallet_card_incomplete": "من فضلك أكمل تفاصيل البطاقات",
  "wallet_card_saved_success_title": "Card save",
  "wallet_card_saved_success_message": "بطاقتك أضيفت بنجاح",
  "off": "قبالة"
};

export default ar;
