const de = {
  "shop_type_grocery": "Lebensmittelgeschäft",
  "shop_type_restaurant": "Restaurant",
  "promotional_banner": "Werbebanner",
  "store_menu_all_categories": "Alle Kategorien",
  "store_menu_page_error": "Konnte diese Gegenstände nicht laden. Überprüfen Sie Ihre Verbindung und versuchen Sie es erneut.",
  "store_menu_refresh_error": "Ich konnte das Menü nicht auffrischen. Ihre aktuellen Artikel sind noch verfügbar.",
  "store_menu_search_hint": "Geben Sie mindestens 2 Zeichen ein, um dieses Restaurant zu durchsuchen.",
  "store_menu_search_loading": "Durchsuchen dieses Restaurants...",
  "store_menu_search_empty": "Keine übereinstimmenden Positionen. Versuchen Sie einen anderen Namen oder eine andere Zutat.",
  "store_menu_search_error": "Die Suche konnte nicht geladen werden. Überprüfen Sie Ihre Verbindung und versuchen Sie es erneut.",
  "store_menu_no_section_items": "In diesem Abschnitt sind derzeit keine Artikel verfügbar.",
  "label": "Lieferungen",
  "description": "Bestellung von Geschäften oder Verkäufern.",
  "header_title": "Lieferungen",
  "header_subtitle": "Wählen Sie einen Liefertyp",
  "hero_badge": "Demo-Erfahrung",
  "hero_subtitle": "Wechseln Sie zwischen Liefermodellen und sehen Sie sich das volle Erlebnis wunderschön an.",
  "hero_pill_fast": "Schnellmodusschaltung",
  "hero_pill_flexible": "Probieren Sie alle Lieferströme",
  "section_title": "Wählen Sie Ihren Modus",
  "single_vendor_title": "Einzelverkäufer",
  "single_vendor_desc": "Bestellen Sie aus Ihrem bevorzugten Shop.",
  "single_vendor_chip": "Kuratiertes Lager",
  "single_vendor_stat": "Eine fokussierte Storefront",
  "multi_vendor_title": "Mehrfachverkäufer",
  "multi_vendor_desc": "Browsen und bestellen Sie aus mehreren Geschäften.",
  "multi_vendor_chip": "Marktplatz",
  "multi_vendor_stat": "Viele Anbieter an einem Ort",
  "chain_title": "Kette",
  "chain_desc": "Bestellen Sie von Ihren Lieblingsketten.",
  "chain_chip": "Markennetzwerk",
  "chain_stat": "Kettenmenüs und Standorte",
  "explore_button": "Entdecken",
  "details_title": "Lieferangaben",
  "single_vendor_categories_title": "Kategorien",
  "single_vendor_category_products_empty": "Keine Produkte für diese Kategorie gefunden.",
  "single_vendor_home_subtitle": "Dein bevorzugtes Geschäft",
  "single_vendor_home_body": "Entdecken Sie hier Anbieter und Dienstleistungen.",
  "single_vendor_tab_home": "Zuhause",
  "single_vendor_tab_search": "Suche",
  "single_vendor_tab_orders": "Bestellungen",
  "single_vendor_tab_profile": "Profil",
  "single_vendor_tab_search_placeholder": "Suchergebnisse und Discovery-Tools werden hier in Kürze erscheinen.",
  "single_vendor_tab_orders_placeholder": "Ihre Single-Vendor-Bestellungen werden bald hier erscheinen.",
  "single_vendor_logout_error_title": "Fehler",
  "single_vendor_logout_error_message": "Unfähig, sich jetzt abzumelden.",
  "multi_vendor_home_subtitle": "Durchsuchen mehrerer Stores",
  "multi_vendor_home_body": "Entdecken und bestellen Sie bei mehreren Anbietern.",
  "multi_vendor_home_greeting_morning": "Guten Morgen 👋",
  "multi_vendor_home_greeting_afternoon": "Guten Nachmittag 👋",
  "multi_vendor_home_greeting_evening": "Guten Abend 👋",
  "delivery_home_greeting_morning": "Guten Morgen",
  "delivery_home_greeting_afternoon": "Guten Abend",
  "delivery_home_greeting_evening": "Guten Abend",
  "delivery_home_title": "Alles, was Sie brauchen, geliefert.",
  "delivery_home_subtitle": "Entdecken Sie nahe gelegene Geschäfte, frische Mahlzeiten und alltägliche Dinge.",
  "delivery_home_search_placeholder": "Läden oder Essen suchen",
  "multi_vendor_tab_home": "Zuhause",
  "multi_vendor_tab_search": "Suche",
  "multi_vendor_tab_orders": "Bestellungen",
  "multi_vendor_tab_profile": "Profil",
  "chain_tab_home": "Zuhause",
  "chain_tab_search": "Suche",
  "chain_tab_orders": "Bestellungen",
  "chain_tab_profile": "Profil",
  "chain_logout_error_title": "Fehler",
  "chain_logout_error_message": "Unfähig, sich jetzt abzumelden.",
  "chain_categories_title": "Kategorien",
  "chain_category_products_empty": "Keine Produkte für diese Kategorie gefunden.",
  "chain_menu_template_selector_label": "Kettenmenü auswählen",
  "chain_menu_template_loading": "Lademenüs",
  "chain_menu_template_empty": "Keine Menüs",
  "chain_menu_template_unavailable": "Menü nicht verfügbar",
  "delivery_address_title": "Lieferanschrift",
  "delivery_address_empty_state": "Fügen Sie eine Adresse hinzu, um mit der Bestellung in diesem Shop zu beginnen.",
  "logout": "Abmelden",
  "multi_vendor_address_label": "Ausgewählte Adresse",
  "delivery_header_deliver_to": "Lieferung an",
  "multi_vendor_shop_types_title": "Shop-Typen",
  "home_all_stores": "Alle Geschäfte",
  "home_store_count": "{{count}} speichert zu erkunden",
  "home_store_count_one": "{{count}} Store zum Erkunden",
  "home_store_count_other": "{{count}} speichert zu erkunden",
  "home_store_list_subtitle": "Finde etwas Gutes in der Nähe.",
  "home_no_nearby_stores_title": "Ihre Nachbarschaft wächst",
  "home_no_nearby_stores_message": "Entdecken Sie alle Geschäfte, während wir mehr in der Nähe dieser Adresse finden.",
  "home_no_deals_title": "Frische Angebote sind unterwegs",
  "home_no_deals_message": "Überprüfen Sie bald zurück für etwas, das es wert ist, entdeckt zu werden.",
  "home_no_shop_type_stores_title": "Noch keine Stores in dieser Kollektion",
  "deals_page_title": "Gute Funde, bessere Preise.",
  "deals_page_description": "Entdecken Sie Angebote zu den Dingen, die Sie lieben.",
  "deals_page_empty_title": "Keine Angebote hier noch",
  "deals_page_empty_description": "Versuchen Sie eine andere Suche oder überprüfen Sie bald wieder für neue Angebote.",
  "multi_vendor_main_shop_types_title": "Lieferkategorien",
  "multi_vendor_categories_title": "Kategorien",
  "multi_vendor_top_brands_title": "Top-Marken",
  "multi_vendor_all_brands_title": "Alle Marken",
  "multi_vendor_search_brands_placeholder": "Suchmarken",
  "multi_vendor_nearby_store_title": "Geschäfte in der Nähe",
  "multi_vendor_home_quick_browse": "Alle Geschäfte",
  "multi_vendor_home_quick_deals": "Geschäfte",
  "multi_vendor_home_quick_orders": "Bestellung erneut",
  "multi_vendor_home_quick_favourites": "Favoriten",
  "multi_vendor_deals_title": "Geschäfte",
  "multi_vendor_recommended_restaurants_title": "Empfohlene Restaurants",
  "deals_see_all_tab_all": "alle",
  "deals_see_all_tab_limited": "Zeitlich begrenzte Geschäfte",
  "deals_see_all_tab_weekly": "Wöchentliche Angebote",
  "deals_see_all_ends_in": "Enden in",
  "deals_see_all_section_title": "Entdecken Sie alle Angebote",
  "deals_see_all_section_title_limited": "Bald enden",
  "deals_see_all_section_title_weekly": "Die Angebote dieser Woche",
  "deals_see_all_badge_percentage": "{{value}} % Rabatt",
  "deals_see_all_badge_fixed": "{{value}} aus",
  "multi_vendor_order_again_title": "Wieder bestellen 😋",
  "main see all": "Main sehen alle",
  "multi_vendor_see_all": "Sehen Sie alle",
  "multi_vendor_order_again_add_item": "Artikel hinzufügen",
  "multi_vendor_order_again_price_unavailable": "Preis nicht verfügbar",
  "multi_vendor_nearby_store_name_hardees": "Hardee — Z Block",
  "multi_vendor_nearby_store_name_subway": "U-Bahn - Z Block",
  "multi_vendor_nearby_store_category_fast_food": "Fast Food",
  "multi_vendor_nearby_store_category_pure_veg": "Reines Gemüse",
  "multi_vendor_nearby_store_review_count": "(5000+)",
  "multi_vendor_nearby_store_delivery_fee": "2 USD",
  "multi_vendor_nearby_store_delivery_time": "30 Minuten",
  "multi_vendor_nearby_store_distance": "1,7 km",
  "multi_vendor_sponsored_label": "Gesponsert",
  "multi_vendor_cart_label": "Warenkorb",
  "multi_vendor_shop_type_gift": "Geschenklieferung",
  "multi_vendor_shop_type_milk": "Milchlieferung",
  "multi_vendor_shop_type_flower": "Blumenlieferung",
  "multi_vendor_shop_type_liquor": "Flüssigkeitsabgabe",
  "multi_vendor_shop_type_products_empty": "Keine Produkte für diesen Shop-Typ gefunden.",
  "multi_vendor_shop_type_stores_empty": "Keine Läden für diesen Shop-Typ gefunden.",
  "multi_vendor_shop_types_empty": "Derzeit sind keine Liefershop-Typen verfügbar.",
  "multi_vendor_location_stores_empty": "Für diesen Standort sind keine Geschäfte verfügbar.",
  "multi_vendor_shop_type_products_error": "Produkte können derzeit nicht geladen werden.",
  "multi_vendor_shop_type_stores_error": "Speicher können derzeit nicht geladen werden.",
  "multi_vendor_home_section_empty_title": "Derzeit keine Matches",
  "multi_vendor_home_section_empty_message": "Frische Picks und zeitlich begrenzte Angebote werden hier erscheinen, sobald sie verfügbar sind.",
  "multi_vendor_home_section_error_title": "Unfähig, Gegenstände zu laden",
  "multi_vendor_home_section_error_message": "Bitte versuchen Sie es gleich noch einmal.",
  "multi_vendor_home_section_empty_order_again": "Ihre letzten Picks werden hier nach Ihrer ersten Bestellung erscheinen.",
  "multi_vendor_home_empty_order_again_title": "Bereit für einen neuen Favoriten?",
  "multi_vendor_home_empty_explore_action": "Entdecken Sie Geschäfte",
  "multi_vendor_home_empty_order_action": "Jetzt erkunden",
  "store_details_search_placeholder": "Suchmenü ...",
  "store_details_hero_title": "Fabrikat I A\nMahlzeit.",
  "store_details_store_name": "Subway @ Old Town, New Mexico",
  "store_details_store_phone": "555-0123",
  "store_details_store_email": "support@subway.com",
  "store_details_store_hours": "9 Uhr morgens bis 6 Uhr morgens",
  "store_details_call_label": "Rufen Sie uns an",
  "store_details_email_label": "oder E-Mail an",
  "store_details_tab_pizza": "Pizza",
  "store_details_tab_burgers": "Burger",
  "store_details_tab_pasta": "Teigwaren",
  "store_details_tab_sushi": "Sushi",
  "store_details_subcategory_italian_classic": "Italienischer Klassiker",
  "store_details_subcategory_american_style": "Amerikanischer Stil",
  "store_details_subcategory_pepperoni": "Pfeffer",
  "store_details_subcategory_bbq_chicken": "BBQ Huhn",
  "store_details_subcategory_thin_crust": "Dünne Krusten",
  "store_details_all_offered_items": "Alle angebotenen Artikel",
  "store_details_no_items": "Es gibt noch keine Elemente, die mit diesem Filter übereinstimmen.",
  "store_details_load_error": "Speicherdetails können derzeit nicht geladen werden.",
  "store_details_hours_unavailable": "Stunden nicht verfügbar",
  "store_details_store_missing": "Store Details sind nicht verfügbar.",
  "store_details_action_info": "Speichern Sie Informationen",
  "store_details_action_favorite": "Laden zu Favoriten hinzufügen",
  "store_details_action_remove_favorite": "Laden von Favoriten entfernen",
  "store_details_action_share": "Aktienlager",
  "store_details_action_back": "Gehen Sie zurück",
  "store_details_about_title": "Über uns",
  "store_details_about_fallback": "Die Shop-Beschreibung ist derzeit nicht verfügbar.",
  "store_details_closed_store_title": "{{storeName}} ist derzeit geschlossen",
  "store_details_closed_store_description": "{{storeName}} ist derzeit nicht geöffnet. Bitte versuchen Sie es später noch einmal.",
  "store_details_closed_store_fallback_name": "Dieser Laden",
  "store_closed_modal_title": "{{storeName}} ist derzeit geschlossen",
  "store_closed_see_menu": "Siehe Menü",
  "store_status_closed": "Geschlossen",
  "store_status_open": "Offen",
  "store_details_delivery_minutes": "{{minutes}} min",
  "store_details_minimum_order": "Mindestens {{amount}}",
  "store_details_close": "Schließen",
  "store_details_info_address": "Anschrift: {{address}}",
  "store_details_info_phone": "Telefon: {{phone}}",
  "store_details_info_email": "E-Mail: {{email}}",
  "store_details_view_cart": "Ansichtswagen",
  "store_details_cart_summary": "{{count}}-Artikel · {{amount}}",
  "store_details_add_product": "{{item}} hinzufügen",
  "store_details_badge_deal": "Angebot",
  "store_details_badge_ten_percent_off": "10% Abschlag",
  "store_details_item_chicken_fajita": "Huhn Fajita",
  "store_details_item_chicken_teriyaki": "Huhn Teriyaki",
  "store_details_item_burger": "Burger",
  "store_details_item_sushi": "Sushi",
  "store_details_item_alfredo_pasta": "Alfredo Pasta",
  "store_details_item_veggie_delight": "Veggie Delight",
  "chain_home_subtitle": "Lieblingsketten",
  "chain_home_body": "Bestellen Sie bei Ihren Lieblingsgeschäften.",
  "type_single_vendor_title": "Einzelanbieter-Shop",
  "type_single_vendor_desc": "Nur handverlesene Premium-Anbieter",
  "type_marketplace_title": "Marktplatz",
  "type_marketplace_desc": "Große Anbieter in der lokalen Gemeinschaft",
  "type_chain_title": "Kettenspeicher",
  "type_chain_desc": "Shoppen Sie Ihre Lieblingsketten",
  "profile_personal_account": "Persönliches Konto",
  "profile_wallet_balance": "Wallet-Guthaben",
  "profile_view_wallet": "View Wallet",
  "profile_menu_profile": "Profil",
  "profile_menu_notifications": "Meldungen",
  "profile_menu_favorites": "Favoriten",
  "profile_menu_coupons": "Gutscheine",
  "profile_menu_settings": "Einstellungen",
  "profile_menu_support": "Unterstützung",
  "profile_menu_color_mode": "App-Farbmodus",
  "profile_menu_language": "Englisch",
  "profile_menu_logout": "Abmelden",
  "coupon_title": "Gutscheine",
  "coupon_active": "Aktiv",
  "coupon_claim_label": "Hinzufügen eines Promo-Codes",
  "coupon_description": "Wenn Sie einen Food Delivery Promo-Code, einen Empfehlungscode oder eine Geschenkkarte haben, geben Sie diesen hier ein, um Ihre Vorteile in Anspruch zu nehmen.",
  "coupon_input_placeholder": "Angabecode",
  "coupon_use": "Verwendung",
  "coupon_off": "Ausgeschaltet",
  "coupon_valid_until": "Gültig: {{date}}",
  "coupon_claim": "Forderung",
  "coupon_claim_success_title": "Coupon beantragt",
  "coupon_claim_error_title": "Kupon nicht beanspruchen können",
  "coupon_claim_error_fallback": "Bitte geben Sie einen gültigen Code ein und versuchen Sie es erneut.",
  "coupon_list_error_fallback": "Unfähig, beanspruchte Coupons jetzt zu laden.",
  "coupon_used": "Verwendet",
  "coupon_use_success_title": "Coupon aktiviert",
  "coupon_use_success_message": "Jetzt können Sie dies verwenden.",
  "coupon_use_error_title": "Kupon kann nicht aktiviert werden",
  "coupon_use_error_fallback": "Bitte versuchen Sie es noch einmal.",
  "coupon_deactivate": "Deaktivieren",
  "coupon_deactivate_success_title": "Coupon deaktiviert",
  "coupon_deactivate_success_message": "Diese Promo ist nicht mehr aktiv.",
  "coupon_deactivate_error_title": "Coupon nicht deaktivieren",
  "coupon_deactivate_error_fallback": "Bitte versuchen Sie es noch einmal.",
  "coupon_status_expired": "Abgelaufen",
  "coupon_min_order": "Min. Ordnung {{currency}} {{value}}",
  "coupon_store_fallback": "Partnergeschäft",
  "coupon_store_with_more": "{{store}} und {{count}} mehr",
  "coupon_claimed_state_title": "Du hast gerade den Coupon bekommen!",
  "coupon_claimed_state_body_line_one": "Hooray! Ihr Promo-Code wurde angewendet.",
  "coupon_claimed_state_body_line_two": "Der Rabatt erscheint automatisch beim Checkout.",
  "coupon_empty_title": "Noch keine Coupons",
  "coupon_empty_description": "Sie haben derzeit keine Coupons. Geben Sie oben einen Promo-Code ein, um Angebote zu finden.",
  "my_profile_title": "Mein Profil",
  "my_profile_edit": "Bearbeiten",
  "my_profile_full_name": "Vollständiger Name",
  "my_profile_date_of_birth": "Geburtsdatum",
  "my_profile_mobile_number": "Mobilfunknummer",
  "my_profile_email": "E-Mail",
  "my_profile_my_addresses": "Meine Anschriften",
  "my_profile_add_address": "Adresse hinzufügen",
  "my_profile_address_home": "Zuhause",
  "my_profile_address_apartment": "Wohnung",
  "my_profile_address_work": "Arbeit",
  "my_profile_address_other": "andere",
  "photo_modal_title": "Profilfoto",
  "photo_modal_description": "Wählen Sie aus, wie Sie Ihr Profilfoto aktualisieren möchten",
  "photo_take_photo": "Nehmen Sie Foto",
  "photo_choose_gallery": "Wählen Sie aus Galerie",
  "photo_cancel": "Stornierung",
  "photo_permission_title": "Genehmigung erforderlich",
  "photo_permission_camera": "Kamerazugriff ist erforderlich, um ein Foto zu machen.",
  "photo_permission_gallery": "Der Zugang zur Galerie ist erforderlich, um ein Foto auszuwählen.",
  "photo_upload_error_title": "Upload fehlgeschlagen",
  "photo_upload_failed": "Das Profilfoto konnte nicht aktualisiert werden.",
  "edit_profile_title": "Profil bearbeiten",
  "edit_profile_name": "Name",
  "edit_profile_date_of_birth": "Geburtsdatum",
  "edit_profile_day": "Tag",
  "edit_profile_month": "Monat",
  "edit_profile_year": "Jahr",
  "edit_profile_gender": "Geschlecht",
  "edit_profile_gender_placeholder": "Option auswählen",
  "edit_profile_save": "Sparen",
  "edit_profile_success": "Erfolgreich",
  "edit_profile_success_message": "Profil erfolgreich aktualisiert.",
  "edit_profile_error": "Fehler",
  "edit_profile_name_required": "Name ist erforderlich.",
  "edit_profile_failed": "Profil konnte nicht aktualisiert werden.",
  "address_list_title": "Meine Anschriften",
  "address_add_title": "Adresse hinzufügen",
  "address_edit_title": "Adresse der Bearbeitung",
  "address_search_placeholder": "Suche nach einer Adresse",
  "address_choose_on_map": "Wählen Sie auf der Karte",
  "address_recent_searches": "Jüngste Suchanfragen",
  "address_no_results": "Keine Ergebnisse gefunden",
  "address_confirm_location": "Standort bestätigen",
  "address_locating": "Ortung ...",
  "address_selected_location": "Ausgewählter Standort",
  "address_location_name_placeholder": "Standortname (z. B. Mein Zuhause)",
  "address_details_label": "Adressdaten",
  "address_location_type_label": "Ortstyp",
  "address_location_details_label": "Angaben zum Standort",
  "address_detail_house_placeholder": "Haus",
  "address_detail_apartment_placeholder": "Wohnung/Wohnung",
  "address_detail_office_placeholder": "Büro / Gebäude",
  "address_detail_place_placeholder": "Ort",
  "address_detail_society_placeholder": "Gesellschaft",
  "address_detail_floor_placeholder": "Boden/Turm",
  "address_detail_department_placeholder": "Abteilung / Etage",
  "address_detail_area_placeholder": "Bereich/Straße",
  "address_detail_landmark_placeholder": "Orientierungspunkt",
  "address_optional_suffix": "(fakultativ)",
  "address_type_home": "Zuhause",
  "address_type_apartment": "Wohnung",
  "address_type_office": "Büro",
  "address_type_other": "andere",
  "address_save": "Speicheradresse",
  "address_update": "Aktualisierungsadresse",
  "address_delete": "Löschung",
  "address_delete_confirm_title": "Anschrift löschen",
  "address_delete_confirm_message": "Sind Sie sicher, dass Sie diese Adresse löschen möchten?",
  "address_delete_cancel": "Stornierung",
  "address_delete_confirm": "Löschung",
  "address_save_error": "Die Adresse konnte nicht gespeichert werden.",
  "address_select_error": "Adresse konnte nicht ausgewählt werden.",
  "address_delete_error": "Adresse nicht löschen konnte.",
  "address_save_success": "Adresse erfolgreich gespeichert.",
  "address_update_success": "Adresse erfolgreich aktualisiert.",
  "address_delete_success": "Adresse erfolgreich gelöscht.",
  "address_selector_title": "Standort",
  "address_selector_close": "Nahabnehmer",
  "address_selector_use_current_location": "Verwenden Sie meinen aktuellen Standort",
  "address_selector_add_new": "Neue Adresse hinzufügen",
  "favourites_title": "Ihre Favoriten",
  "favourites_subtitle": "Ihre gespeicherten Speicher, bereit, wenn Sie sind.",
  "favourites_empty_title": "Noch keine Favoriten",
  "favourites_empty_subtitle": "Tippen Sie auf das Herz in einem Geschäft, um es für das nächste Mal in der Nähe zu halten.",
  "favourites_error_title": "Favoriten konnten nicht geladen werden",
  "favourites_error": "Überprüfen Sie Ihre Verbindung und versuchen Sie es erneut.",
  "favourites_retry": "Versuchen Sie es noch einmal",
  "favourites_free_delivery": "Kostenlose Lieferung",
  "favourites_remove": "Aus Favoriten entfernen",
  "favourites_add": "Zu den Favoriten hinzufügen",
  "favourites_toggle_added": "Zu den Favoriten hinzugefügt",
  "favourites_toggle_removed": "Aus Favoriten entfernt",
  "favourites_toggle_error": "Nicht aktualisierte Favoriten",
  "rate_order_title": "Bewerten Sie Ihre Bestellung",
  "rate_order_heading": "Wie war dein Essen?",
  "rate_order_subheading": "Ihr Feedback hilft uns, unsere Lieferung zu verbessern.",
  "rate_order_comment_placeholder": "Schreiben Sie Ihre Erfahrungen hier...",
  "rate_order_submit": "Einreichung",
  "rate_order_submitted_heading": "Vielen Dank für Ihre Bewertung!",
  "rate_order_submitted_subheading": "Sie haben diese Bestellung bereits bewertet. Ihr Feedback hilft uns, unsere Lieferung zu verbessern.",
  "rate_order_submitted_no_comment": "Mit diesem Rating wurde kein Kommentar hinzugefügt.",
  "rate_order_success_title": "Vielen Dank!",
  "rate_order_success_message": "Ihre Bewertung wurde eingereicht.",
  "rate_order_error_title": "Einreichung fehlgeschlagen",
  "settings_title": "Einstellungen",
  "settings_notifications": "Benachrichtigungseinstellungen",
  "settings_change_password": "Passwort ändern",
  "settings_privacy_policy": "Datenschutzpolitik",
  "settings_terms_of_service": "Nutzungsbedingungen",
  "settings_terms_of_use": "Nutzungsbedingungen",
  "settings_delete_account": "Konto löschen",
  "settings_app_version": "App-Version 1.0.0",
  "notif_settings_title": "Benachrichtigungseinstellungen",
  "notif_settings_food_delivery": "Lebensmittellieferung",
  "notif_settings_marketing": "Marketing",
  "notif_settings_email": "E-Mail",
  "notif_settings_sms": "SMS",
  "notif_settings_whatsapp": "WhatsApp",
  "notif_settings_success_title": "Gerettet",
  "notif_settings_success_message": "Mitteilungspräferenz aktualisiert.",
  "notif_settings_error_title": "Fehler",
  "privacy_title": "Datenschutzpolitik",
  "privacy_last_updated": "Zuletzt aktualisiert vor 2 Monaten",
  "privacy_intro": "In dieser Datenschutzerklärung wird erläutert, wie wir mit Ihren persönlichen Daten umgehen, während wir die Lebensmittelliefer-App verwenden. Durch die Registrierung oder den Zugriff auf die App stimmen Sie den in dieser Richtlinie beschriebenen Praktiken zu.",
  "privacy_section_app_title": "Datenschutzerklärung für die App",
  "privacy_section_app_body": "Die Food Delivery App verpflichtet sich, Ihre persönlichen Daten und Bestellungen sicher zu schützen und zu verwalten. Sie sind berechtigt, die App für persönliche und geschäftliche Zwecke zu verwenden, vorbehaltlich der Einhaltung dieser Richtlinie und aller geltenden Gesetze.",
  "privacy_section_responsibilities_title": "Verantwortlichkeiten der Nutzer",
  "privacy_section_responsibilities_body": "Benutzer sind dafür verantwortlich, ihre Lieferadressen und Zahlungsinformationen korrekt zu halten. Es ist wichtig, diese Informationen auf dem neuesten Stand zu halten, um Probleme während des Bestellvorgangs zu vermeiden.",
  "privacy_section_data_title": "Datenerhebung",
  "privacy_section_data_body": "Die App für Lebensmittellieferungen sammelt wichtige Daten, um Ihre Erfahrung zu verbessern, einschließlich Ihres Standorts, Ihrer Bestellhistorie und Ihrer Präferenzen.",
  "privacy_section_modifications_title": "Auftragsänderungen",
  "privacy_section_modifications_body": "Sie können Ihre Bestellungen über die App ändern oder stornieren, bevor sie verarbeitet werden. Sobald eine Bestellung bestätigt wurde, sind Änderungen möglicherweise nicht mehr möglich.",
  "privacy_section_payment_title": "Zahlungssicherheit",
  "privacy_section_payment_body": "Wir priorisieren die Sicherheit Ihrer Zahlungsinformationen. Alle über die App getätigten Transaktionen werden mit Standard-Verschlüsselungstechnologie verarbeitet.",
  "privacy_section_contact_title": "Kontaktieren Sie uns",
  "privacy_section_contact_body": "Wenn Sie Fragen zu diesen Bedingungen haben, kontaktieren Sie uns bitte gerne:",
  "privacy_contact_email": "E-Mail: contact@fooddelivery.com",
  "privacy_contact_address": "Anschrift: Doha, Katar",
  "tos_title": "Nutzungsbedingungen",
  "tos_last_updated": "Zuletzt aktualisiert vor 2 Monaten",
  "tos_intro": "Diese Nutzungsbedingungen definieren Ihren Zugriff auf und die Nutzung der Lebensmittelliefer-App.",
  "tos_section_usage_title": "Nutzung des Dienstes",
  "tos_section_usage_body": "Die Food Delivery App bietet eine zuverlässige Plattform für die Bestellung und Verwaltung Ihrer Mahlzeitenlieferungen.",
  "tos_section_orders_title": "Auftragsverwaltung",
  "tos_section_orders_body": "Die App ermöglicht es Ihnen, Ihre Bestellungen einfach zu verfolgen, Details zu ändern oder innerhalb des zulässigen Zeitrahmens zu stornieren.",
  "tos_section_payment_title": "Zahlungssicherheit",
  "tos_section_payment_body": "Zahlungen über die App werden sicher mit Verschlüsselungstechnologie verarbeitet.",
  "tos_section_delivery_title": "Lieferrichtlinien",
  "tos_section_delivery_body": "Benutzer werden aufgefordert, genaue Lieferadressen anzugeben, um einen schnellen und effizienten Service zu unterstützen.",
  "tos_section_support_title": "Kundensupport",
  "tos_section_support_body": "Die app bietet ein robustes support-system, um alle fragen oder probleme zu lösen.",
  "tos_section_contact_title": "Kontaktieren Sie uns",
  "tos_section_contact_body": "Wenn Sie Fragen zu diesen Bedingungen haben, kontaktieren Sie uns bitte gerne:",
  "tos_contact_email": "E-Mail: contact@fooddelivery.com",
  "tos_contact_address": "Anschrift: Doha, Katar",
  "tou_title": "Nutzungsbedingungen",
  "tou_last_updated": "Aktualisiert vor 2 Monaten",
  "tou_intro": "Diese Nutzungsbedingungen definieren Ihre Rechte und Pflichten bei der Nutzung der App.",
  "tou_section_guidelines_title": "Nutzungsleitlinien",
  "tou_section_guidelines_body": "Die App bietet eine sichere Verwaltung Ihrer Bestellungen und Kundendaten.",
  "tou_section_etiquette_title": "Lieferetikette",
  "tou_section_etiquette_body": "Benutzer sollten respektvoll und höflich gegenüber dem Lieferpersonal bleiben.",
  "tou_section_payment_title": "Zahlungsmethoden",
  "tou_section_payment_body": "Die App unterstützt mehrere Zahlungsmethoden, darunter Kreditkarten und digitale Geldbörsen.",
  "tou_section_cancellation_title": "Stornierungspolitik",
  "tou_section_cancellation_body": "Bestellungen können innerhalb von 10 Minuten nach der Platzierung storniert werden.",
  "tou_section_feedback_title": "Feedback und Ratings",
  "tou_section_feedback_body": "Benutzer werden ermutigt, Feedback über ihre Liefererfahrung zu teilen.",
  "tou_section_promotions_title": "Promotions und Angebote",
  "tou_section_promotions_body": "Die App kann Promotions und Rabatte anbieten, die bestimmten Bedingungen unterliegen.",
  "tou_section_contact_title": "Kontaktieren Sie uns",
  "tou_section_contact_body": "Wenn Sie Fragen haben, kontaktieren Sie uns bitte:",
  "tou_contact_email": "E-Mail: contact@fooddelivery.com",
  "tou_contact_address": "Anschrift: Doha, Katar",
  "rider_chat_title": "Chat mit Rider",
  "rider_chat_subtitle": "Live Delivery Updates",
  "rider_chat_status_online": "Jetzt online",
  "rider_chat_eta_label": "{{minutes}} min entfernt",
  "rider_chat_order_label": "Auftrag {{orderCode}}",
  "rider_chat_help_text": "Teilen Sie Pickup-Notizen oder fragen Sie nach einem Ankunftsanruf.",
  "rider_chat_message_rider_intro": "Hi! Ich bin mit Ihrer Bestellung unterwegs.",
  "rider_chat_message_user_reply": "Perfekt. Bitte rufen Sie mich an, wenn Sie am Gate ankommen.",
  "rider_chat_message_rider_eta": "Klar, ich rufe dich an. Wir sehen uns in ungefähr {{minutes}} Minuten.",
  "rider_chat_quick_reply_gate": "Anruf am Gate",
  "rider_chat_quick_reply_thanks": "Danke!",
  "rider_chat_quick_reply_here": "Ich bin hier",
  "rider_chat_quick_reply_hello": "Hallo",
  "rider_chat_quick_reply_call_arrive": "Ruf mich an, wenn du ankommst",
  "rider_chat_quick_reply_where": "Wo bist du?",
  "rider_chat_quick_reply_eta": "Wie lange werden Sie brauchen?",
  "rider_chat_input_placeholder": "Geben Sie Ihre Sorge ein ...",
  "rider_chat_auto_message": "Wie können wir Ihnen helfen?",
  "rider_chat_auto_time": "8:29 Uhr",
  "rider_chat_send": "Senden",
  "rider_chat_send_error": "Konnte keine Nachricht senden.",
  "rider_chat_missing_session_error": "Bitte loggen Sie sich ein, bevor Sie eine Nachricht senden.",
  "rider_chat_missing_receiver_error": "Der Empfänger fehlt für diesen Chat.",
  "rider_chat_attachment_permission_title": "Genehmigung erforderlich",
  "rider_chat_attachment_permission_message": "Bitte erlauben Sie der Fotobibliothek den Zugriff, um einen Anhang hinzuzufügen.",
  "rider_chat_attachment_selected_title": "Anlage selected",
  "rider_chat_attachment_selected_message": "{{fileName}} ist bereit zu befestigen.",
  "rider_chat_add_attachment": "Add-Anhang",
  "rider_chat_send_message": "Sendenachricht",
  "rider_chat_call_action": "Rufreiter",
  "support_title": "Unterstützung",
  "support_active_order_eyebrow": "Lebendbestellung",
  "support_active_order_track": "Verfolgen und Hilfe bekommen",
  "support_active_order_accessibility": "{{store}}, {{status}}. Verfolgen Sie die Reihenfolge und holen Sie sich Hilfe.",
  "support_topic_faq": "Häufig gestellte Fragen",
  "support_topic_faq_description": "Finden Sie schnelle Antworten auf Bestellungen, Lieferung und Ihr Konto.",
  "support_issue_prompt": "Haben Sie nicht gefunden, was Sie brauchen?",
  "support_issue_select_title": "Bitte wählen Sie eine Option.",
  "support_issue_placeholder": "Wählen Sie einen Problemtyp",
  "support_retry": "Versuchen Sie es noch einmal",
  "support_error_title": "Wir konnten das jetzt nicht laden",
  "support_error_description": "Überprüfen Sie Ihre Verbindung und versuchen Sie es erneut. Ihre Support-Geschichte ist sicher.",
  "support_tickets_empty_title": "Keine gemeldeten Probleme",
  "support_tickets_empty_description": "Wenn Sie ein Problem melden, werden der Fortschritt und die Antworten hier angezeigt.",
  "support_chat_closed_title": "Dieses Gespräch ist geschlossen",
  "support_chat_closed_description": "Sie können die obigen Nachrichten überprüfen oder eine neue Supportanfrage starten.",
  "support_issue_order": "Ich habe bereits ein Geschäftskonto und brauche Unterstützung",
  "support_issue_payment": "Ich bin daran interessiert, Food Delivery als Unternehmen beizutreten",
  "support_issue_delivery": "Ich buchte eine Bestellung mit einem Geschäft auf Essen Lieferung",
  "support_issue_account": "Ich brauche Hilfe bei etwas anderem",
  "support_issue_business_support": "Ich habe bereits ein Geschäftskonto und brauche Unterstützung",
  "support_issue_joining_as_a_business": "Ich bin daran interessiert, Food Delivery als Unternehmen beizutreten",
  "support_issue_appointment_support": "Ich buchte eine Bestellung mit einem Geschäft auf Essen Lieferung",
  "support_call_action": "Call Support",
  "support_back_action": "Gehen Sie zurück",
  "support_header_action": "Header-Aktion",
  "support_close_action": "Enges Unterstützungsformular",
  "support_tickets_search_action": "Suchtickets",
  "support_tickets_search_placeholder": "Suchtickets",
  "support_tickets_no_results_title": "Keine Matching Tickets",
  "support_tickets_no_results_description": "Versuchen Sie eine andere Bestellnummer, einen anderen Status oder ein anderes Keyword.",
  "support_form_how_help_label": "Wie können wir helfen?",
  "support_form_email_label": "E-Mail",
  "support_form_email_helper": "Wenn Sie ein Lebensmittellieferkonto haben, geben Sie die E-Mail-Adresse ein, mit der Sie sich anmelden",
  "support_form_full_name_label": "Vollständiger Name",
  "support_form_full_name_placeholder": "Geben Sie Ihren Namen ein",
  "support_form_country_region_label": "Land/Region",
  "support_form_country_region_placeholder": "Bitte auswählen",
  "support_form_mobile_number_label": "Mobilfunknummer",
  "support_form_mobile_number_placeholder": "+61 333 000 0000",
  "support_form_business_name_label": "Firmenname",
  "support_form_business_type_label": "Unternehmenstyp",
  "support_form_business_type_placeholder": "Bitte auswählen",
  "support_form_team_size_label": "Größe des Teams",
  "support_form_team_size_placeholder": "Bitte auswählen",
  "support_form_business_description_label": "Gibt es etwas Besonderes, das Sie über die Lieferung von Lebensmitteln wissen möchten?",
  "support_form_reason_label": "Grund der Kontaktaufnahme",
  "support_form_reason_placeholder": "Bitte auswählen",
  "support_form_reason_account_setup": "Einrichtung eines Kontos",
  "support_form_reason_add_on_integrations": "Add-ons und Integrationen",
  "support_form_reason_addons_integrations": "Add-ons und Integrationen",
  "support_form_reason_using_the_app": "Mit der App",
  "support_form_reason_payments_and_payouts": "Zahlungen und Auszahlungen",
  "support_form_reason_technical_issues": "Technische Fragen",
  "support_form_reason_my_orders": "Meine Bestellungen",
  "support_form_reason_payments_and_purchases": "Zahlungen und Ankäufe",
  "support_form_reason_reviews": "Überprüfungen",
  "support_form_reason_emails_and_notifications": "E-Mails und Benachrichtigungen",
  "support_form_reason_delete_my_account": "Lösche meinen Account",
  "support_form_reason_billing_fees": "Abrechnung und Gebühren",
  "support_form_reason_payments_payouts": "Zahlungen und Auszahlungen",
  "support_form_reason_technical_support": "Technische Unterstützung",
  "support_form_reason_other": "andere",
  "support_form_country_united_states": "Vereinigte Staaten",
  "support_form_country_canada": "Kanada",
  "support_form_country_united_kingdom": "Vereinigtes Königreich",
  "support_form_country_australia": "Australien",
  "support_form_country_france": "Frankreich",
  "support_form_business_type_burger_joint": "Burgerrestaurant",
  "support_form_business_type_pizza_place": "Pizzaplatz",
  "support_form_business_type_taco_stand": "Taco-Stand",
  "support_form_business_type_sandwich_shop": "Sandwichladen",
  "support_form_business_type_ice_cream_parlor": "Eiscremesalon",
  "support_form_business_type_fried_chicken_spot": "Gebratener Hühnerfleck",
  "support_form_business_type_food_truck": "Foodtruck",
  "support_form_business_type_hot_dog_stand": "Hotdog-Stand",
  "support_form_business_type_other_fast_food": "Andere Fast Food",
  "support_form_team_size_just_me": "Nur ich",
  "support_form_team_size_2_5": "2 - 5",
  "support_form_team_size_6_10": "6 - 10",
  "support_form_team_size_11_plus": "11+",
  "support_form_description_label": "Beschreiben Sie, womit Sie Hilfe benötigen",
  "support_form_description_placeholder": "Geben Sie eine Beschreibung ein...",
  "support_form_attach_title": "Screenshots anfügen",
  "support_form_attach_description": "Lassen Sie Ihre Dateien hier",
  "support_form_attach_cta": "Wählen Sie eine Datei",
  "support_form_send_email": "E-Mail senden",
  "support_form_submit_success_title": "Ticket erstellt",
  "support_form_submit_success_message": "Ihr Support-Ticket wurde erfolgreich eingereicht.",
  "support_form_submit_error_title": "Ticket fehlgeschlagen",
  "support_form_submit_error_message": "Wir konnten Ihr Support-Ticket nicht einreichen. Überprüfen Sie Ihre Verbindung und versuchen Sie es erneut.",
  "support_form_attachment_upload_error": "Ein oder mehrere Anhänge konnten nicht hochgeladen werden. Überprüfen Sie Ihre Verbindung und versuchen Sie es erneut.",
  "support_chat_attachment_invalid_title": "Anlage nicht hinzugefügt",
  "support_chat_attachment_too_large_message": "Jede Befestigung muss 5 MB oder kleiner sein.",
  "support_chat_auto_message": "Wie können wir Ihnen helfen?",
  "support_chat_auto_time": "8:29 Uhr",
  "support_chat_quick_reply_here": "Ich bin hier",
  "support_chat_quick_reply_hello": "Hallo",
  "support_chat_quick_reply_call_arrive": "Ruf mich an, wenn du ankommst",
  "support_chat_quick_reply_where": "Wo bist du?",
  "support_chat_quick_reply_eta": "Wie lange werden Sie brauchen?",
  "support_chat_input_placeholder": "Geben Sie Ihre Sorge ein ...",
  "support_chat_add_attachment": "Add-Anhang",
  "support_chat_send_message": "Sendenachricht",
  "support_chat_send_error_title": "Nachricht fehlgeschlagen",
  "support_chat_send_error_message": "Konnte ihre support-nachricht nicht senden.",
  "support_chat_missing_session_error": "Bitte loggen Sie sich ein, bevor Sie eine Nachricht senden.",
  "support_chat_missing_receiver_error": "Der Support-Chat ist noch nicht fertig. Bitte öffnen Sie zuerst ein bestehendes Gespräch.",
  "support_chat_loading": "Gespräch laden...",
  "support_chat_attachment_permission_title": "Genehmigung erforderlich",
  "support_chat_attachment_permission_message": "Bitte erlauben Sie der Fotobibliothek den Zugriff, um einen Anhang hinzuzufügen.",
  "support_chat_attachment_selected_title": "Anlage selected",
  "support_chat_attachment_selected_message": "{{fileName}} ist bereit zu befestigen.",
  "support_tickets_title": "Meine Tickets",
  "support_new_ticket": "Neues Ticket",
  "support_tickets_subtitle": "Verfolgen Sie Ihre Anfragen und folgen Sie mit unserem Team zu jedem einzelnen.",
  "support_tickets_filter_all": "alle",
  "support_tickets_filter_active": "Aktiv",
  "support_tickets_filter_closed": "Aufgelöst / geschlossen",
  "support_tickets_search_clear": "Klare Suche",
  "support_tickets_empty": "Noch keine Tickets gefunden.",
  "support_tickets_order_id": "Bestellnummer: {{orderId}}",
  "support_faq_title": "Fragen zur allgemeinen Reihenfolge",
  "support_faq_header_title": "Hilfeartikel",
  "support_faq_subtitle": "Klare Antworten auf die häufigsten Bestell- und Lieferfragen.",
  "support_faq_place_order": "Wie man eine Bestellung aufgibt",
  "support_faq_schedule_delivery": "Wie Sie Ihre Lieferungen im Voraus planen",
  "support_faq_change_delivery": "Ändern Ihrer Lieferungen",
  "support_faq_order_history": "Wie Sie Ihre Bestellhistorie anzeigen",
  "support_faq_ordering_for_others": "Bestellung für andere und Versenden von Bestätigungen an verschiedene Adressen",
  "support_faq_still_need_help": "Brauchen Sie noch Hilfe?",
  "support_faq_feedback_prompt": "War das hilfreich?",
  "support_faq_feedback_yes": "Ja",
  "support_faq_feedback_no": "Nein",
  "support_faq_feedback_thanks": "Danke - Ihr Feedback hilft uns, den Support zu verbessern.",
  "support_faq_place_order_body_1": "Die Bestellung ist schnell und einfach. Öffnen Sie die Liefer-App und durchsuchen Sie Restaurants, Geschäfte oder Kategorien in der Nähe, die Ihren Bedürfnissen entsprechen.",
  "support_faq_place_order_body_2": "Tippen Sie auf ein Geschäft, um das Menü zu erkunden, und fügen Sie dann die gewünschten Artikel zu Ihrem Warenkorb hinzu. Sie können Mengen überprüfen, Notizen hinzufügen und alles vor dem Checkout entfernen.",
  "support_faq_place_order_body_3": "Wenn Sie bereit sind, gehen Sie weiter zum Checkout, um Ihre Lieferadresse zu bestätigen, alle Promo-Codes anzuwenden und Ihre bevorzugte Zahlungsmethode auszuwählen.",
  "support_faq_place_order_body_4": "Nachdem Sie die Bestellung aufgegeben haben, können Sie den Fortschritt in Echtzeit verfolgen und auf dem neuesten Stand bleiben, bis er an Ihrer Tür ankommt.",
  "support_faq_schedule_delivery_body_1": "Wenn ein Geschäft geplante Bestellungen unterstützt, können Sie eine Lieferzeit auswählen, bevor Sie den Checkout abschließen.",
  "support_faq_schedule_delivery_body_2": "Fügen Sie Ihre Artikel in den Warenkorb und gehen Sie zur Kasse. Suchen Sie nach dem Lieferzeitabschnitt, bevor Sie Ihre Bestellung bestätigen.",
  "support_faq_schedule_delivery_body_3": "Wählen Sie ein Datum und Zeitfenster, das für Sie funktioniert, und überprüfen Sie dann die Bestelldetails, um sicherzustellen, dass alles richtig aussieht.",
  "support_faq_schedule_delivery_body_4": "Nach der Bestätigung behalten wir Ihre geplante Lieferung in Ihrer Bestellung, damit Sie sie später erneut überprüfen können.",
  "support_faq_change_delivery_body_1": "Möglicherweise können Sie Teile Ihrer Bestellung aktualisieren, bevor der Shop mit der Vorbereitung beginnt.",
  "support_faq_change_delivery_body_2": "Öffnen Sie Ihre aktive Bestellung und prüfen Sie, ob die Bearbeitung noch verfügbar ist. Einige Geschäfte erlauben kleine Updates, während andere Änderungen sperren können, sobald die Vorbereitung beginnt.",
  "support_faq_change_delivery_body_3": "Wenn die bearbeitung nicht verfügbar ist, ist die schnellste option in der regel, den support aus dem hilfebereich zu kontaktieren oder einen chat mit einer person zu starten.",
  "support_faq_change_delivery_body_4": "Wir empfehlen, Ihren Warenkorb sorgfältig zu überprüfen, bevor Sie die Bestellung aufgeben, damit Sie Änderungen in letzter Minute vermeiden können.",
  "support_faq_order_history_body_1": "Ihre vorherigen und aktiven Lieferungen sind im Abschnitt Bestellungen in der App verfügbar.",
  "support_faq_order_history_body_2": "Öffnen Sie die Bestellung, die Sie überprüfen möchten, um die Artikel, Zahlungsdetails, Lieferadresse und den aktuellen oder früheren Status zu sehen.",
  "support_faq_order_history_body_3": "Dies ist auch der beste Ort, um Artikel schnell neu zu bestellen, wenn Sie die gleiche Lieferung wieder wünschen.",
  "support_faq_ordering_for_others_body_1": "Sie können eine Bestellung für eine andere Person aufgeben, indem Sie vor dem Checkout die richtige Lieferadresse auswählen oder eingeben.",
  "support_faq_ordering_for_others_body_2": "Stellen Sie sicher, dass der Empfängername, die Telefonnummer und alle Lieferanweisungen korrekt sind, damit der Kurier die richtige Person erreichen kann.",
  "support_faq_ordering_for_others_body_3": "Wenn Sie Updates an einen anderen Kontakt senden müssen, überprüfen Sie die verfügbaren Kontaktdaten während des Checkouts und bevor Sie die Bestellung bestätigen.",
  "support_faq_ordering_for_others_body_4": "Für die reibungsloseste Erfahrung, lassen Sie den Empfänger wissen, dass eine Lieferung unterwegs ist und teilen Sie alle Timing-Details mit ihnen.",
  "support_faq_still_need_help_body_1": "Wenn ihre frage hier nicht behandelt wird, öffnen sie die chat-option am unteren bildschirmrand und wenden sie sich an unser support-team.",
  "support_faq_still_need_help_body_2": "Fügen Sie wichtige Details wie den Ladennamen, die Bestellnummer und eine kurze Erklärung des Problems hinzu, damit wir schneller helfen können.",
  "support_faq_still_need_help_body_3": "Unser Team führt Sie durch die nächsten Schritte und hilft bei der Lösung von Liefer-, Zahlungs- oder Kontoproblemen.",
  "searching_near": "Suche in der Nähe",
  "products": "Produkte",
  "stores": "Lagerräume",
  "see_all": "Sehen Sie alle",
  "filter_title": "Filter",
  "filter_close_label": "Schließfilter",
  "filter_apply_results": "Filter anwenden",
  "filter_category_title": "Kategorie",
  "filter_price_title": "Preis",
  "filter_address_title": "Nähere Anschrift",
  "filter_stock_title": "Bestand",
  "filter_sort_title": "Sortieren nach",
  "generic_list_error_title": "Ergebnisse nicht laden können",
  "generic_list_error_description": "Ziehen Sie zum Erfrischen oder versuchen Sie es erneut.",
  "generic_list_retry": "Versuch",
  "generic_list_empty_title": "Keine Ergebnisse gefunden",
  "generic_list_empty_description": "Versuchen Sie eine andere Suche oder passen Sie Ihre Filter an.",
  "generic_list_search_placeholder": "Suche",
  "see_all_map_loading_title": "Suche nach {{title}}",
  "see_all_map_loading_description": "Das kann einige Augenblicke dauern. Bitte bleiben Sie auf diesem Bildschirm.",
  "see_all_map_sheet_title": "Restaurant",
  "see_all_map_cta": "Restaurant ansehen",
  "change_password_title": "Passwort ändern",
  "change_password_new_title": "Neues Passwort",
  "change_password_email_heading": "Passwort ändern?",
  "change_password_email_description": "Geben Sie Ihre E-Mail-Adresse ein und wir senden Ihnen einen Bestätigungscode.",
  "change_password_email_placeholder": "your@email.com",
  "change_password_continue": "Weiterfahren",
  "change_password_verify_heading": "Überprüfen Sie Ihre E-Mail",
  "change_password_verify_description": "Geben Sie den 4-stelligen Code an {{email}}",
  "change_password_verify_button": "OTP überprüfen",
  "change_password_new_heading": "Erstellen Sie Ihr neues Passwort",
  "change_password_new_description": "Ihr neues Passwort muss sich von Ihrem vorherigen Passwort unterscheiden.",
  "change_password_new_placeholder": "Neues Passwort",
  "change_password_confirm_placeholder": "Neues Passwort bestätigen",
  "change_password_set_new": "Setzen Sie ein neues Passwort",
  "change_password_mismatch": "Passwörter passen nicht zusammen.",
  "change_password_error_title": "Fehler",
  "change_password_send_otp_error": "Es ist nicht gelungen, den Bestätigungscode zu senden.",
  "change_password_verify_otp_error": "Ungültiger oder abgelaufener Code.",
  "change_password_update_error": "Das Passwort konnte nicht aktualisiert werden.",
  "change_password_success_title": "Erfolgreich",
  "change_password_success_message": "Ihr Passwort wurde aktualisiert.",
  "change_password_otp_resent_title": "Versandcode",
  "change_password_otp_resent_message": "Es wurde ein neuer Verifizierungscode übermittelt.",
  "delete_account_step_label": "Lösche meinen Account",
  "delete_account_sorry_heading": "Es tut uns leid, dass Sie gehen",
  "delete_account_sorry_subtext": "Können wir Ihre Meinung ändern? Drop a line bei",
  "delete_account_contact_email": "hello@enategadelivery.com",
  "delete_account_reason_heading": "Warum möchten Sie die Lieferung von Lebensmitteln verlassen?",
  "delete_account_reason_subtext": "Bitte teilen Sie uns den Grund für die Löschung Ihres Kontos mit:",
  "delete_account_reason_mistake": "Ich habe diesen Account aus Versehen erstellt",
  "delete_account_reason_no_longer": "Ich möchte keine Lebensmittellieferung mehr verwenden",
  "delete_account_reason_no_venues": "Ich kann die Veranstaltungsorte oder Dienste, die ich möchte, nicht finden",
  "delete_account_reason_other": "andere",
  "delete_account_confirm_heading": "Löschen Sie Ihren Food Delivery Account",
  "delete_account_confirm_description": "Diese Aktion löscht Ihr Konto und Sie können es nicht abrufen. Bitte bestätigen Sie, dass Sie verstehen, indem Sie die folgenden Aussagen ankreuzen:",
  "delete_account_confirm_item_orders": "Ich weiß, dass ich nicht auf meine Bestellungen zugreifen kann.",
  "delete_account_confirm_item_marketplace": "Ich weiß, dass ich Bestellungen nicht mehr über den Food Delivery Marketplace buchen kann.",
  "delete_account_final_heading": "Bestätigen Sie, dass Sie gerne fortfahren",
  "delete_account_final_description": "Bitte beachten Sie, dass dies dauerhaft ist und nicht rückgängig gemacht werden kann. Um das Löschen Ihres Kontos zu bestätigen, lesen Sie bitte Ihre E-Mail unten:",
  "delete_account_email_label": "E-Mail",
  "delete_account_email_placeholder": "your@email.com",
  "delete_account_cta_continue": "Weiterfahren",
  "delete_account_cta_delete": "Konto löschen",
  "delete_account_close": "Schließen",
  "delete_account_alert_title": "Konto löschen",
  "delete_account_alert_message": "Sind Sie sicher, dass Sie Ihr Konto dauerhaft löschen möchten? Diese Aktion kann nicht rückgängig gemacht werden.",
  "delete_account_alert_cancel": "Stornierung",
  "delete_account_alert_confirm": "Löschung",
  "delete_account_error_title": "Fehler",
  "delete_account_error": "Konto nicht löschen. Bitte versuchen Sie es noch einmal.",
  "color_mode_title": "App-Farbmodus",
  "color_mode_section_label": "App-Farbmodus auswählen",
  "color_mode_system": "Standardsystem",
  "color_mode_light": "Licht",
  "color_mode_dark": "Dunkel",
  "language_title": "App-Sprachen",
  "language_section_label": "Sprache auswählen",
  "language_english": "Englisch",
  "language_german": "Deutsch",
  "language_spanish": "Spanisch",
  "language_arabic": "Arabisch",
  "language_french": "Französisch",
  "popular": "Populär",
  "ingredients": "Zutaten",
  "usage": "Verwendung",
  "nutrition_facts": "Nährwert",
  "amount_per": "Betrag je",
  "energy": "Energie",
  "fat": "Fett",
  "carbohydrates": "Kohlenhydrate",
  "protein": "Protein",
  "sugar": "Zucker",
  "choose_size": "Größe auswählen",
  "choose_variation": "Wählen Sie Variation",
  "select_one": "Wählen Sie eine",
  "required_label": "erforderlich",
  "optional_label": "Fakultativ",
  "product_option_choose_at_least": "Wählen Sie mindestens {{count}}",
  "product_option_choose_range": "Wählen Sie {{min}}-{{max}}",
  "product_option_choose_up_to": "Wählen Sie bis zu {{count}}",
  "product_option_required_error": "Wählen Sie die erforderlichen Optionen, um fortzufahren.",
  "small": "Klein",
  "medium": "Medium",
  "large": "Groß",
  "choose_your_flavour": "Wählen Sie Ihren Geschmack",
  "choose_your_addons": "Wählen Sie Ihre Addons",
  "add_to_cart": "Hinzufügen zum Warenkorb",
  "cart_title": "Warenkorb",
  "cart_store_fallback": "Dein Shop",
  "cart_return_to_store": "Zurück zu {{store}}",
  "cart_delivery_time": "{{time}} min Lieferung",
  "cart_items_title": "Ihre Artikel",
  "cart_add_more": "Mehr hinzufügen",
  "cart_recommended_title": "Empfohlen für Sie",
  "cart_checkout": "Gehen Sie zum Checkout",
  "cart_checkout_short": "Kasse",
  "cart_order_summary": "Bestellzusammenfassung",
  "cart_promo_title": "Promo-Code",
  "cart_promo_subtitle": "Wählen Sie einen Code für diese Bestellung",
  "cart_promo_applied": "Ausgewählt zum Checkout",
  "cart_promo_add": "Addition",
  "cart_promo_change": "Änderung",
  "cart_fees_at_checkout": "Liefer- und Servicegebühren werden an der Kasse bestätigt",
  "cart_minimum_remaining": "{{amount}} weg von der minimalen Ordnung",
  "cart_minimum_reached": "Mindestauftrag erreicht",
  "cart_minimum_progress_accessibility": "{{current}} von {{minimum}} Mindestauftrag",
  "cart_item_unavailable": "Nicht verfügbar",
  "cart_recommendation_accessibility": "Ansicht {{product}}",
  "cart_fee_modal_current_subtotal": "Aktuelle Teilsumme",
  "cart_fee_modal_minimum_order": "Mindestanforderungen",
  "cart_fee_modal_base_delivery": "Grundliefergebühr",
  "cart_fee_modal_checkout_notice": "Endgültige Liefer- und Servicegebühren werden für Ihre Adresse an der Kasse berechnet.",
  "checkout_title": "Kasse",
  "checkout_order_from": "Bestellung von",
  "checkout_item_count": "{{count}}-Artikel",
  "checkout_fulfillment_title": "Wie würde es dir gefallen?",
  "checkout_fulfillment_delivery": "Lieferung",
  "checkout_fulfillment_pickup": "Abholung",
  "checkout_delivery_details_title": "Lieferdetails",
  "checkout_pickup_details_title": "Angaben zur Abholung",
  "checkout_address_title": "Wählen Sie eine Lieferadresse",
  "checkout_address_subtitle": "Tippen Sie hier, um fortzufahren",
  "checkout_address_selected_subtitle": "Tippen Sie hier, um zu ändern",
  "checkout_pickup_title": "Abholort",
  "checkout_pickup_subtitle": "Sammeln Sie Ihre Bestellung aus dem Laden",
  "checkout_leave_at_door_title": "Lassen Sie an der Tür",
  "checkout_leave_at_door_subtitle": "Eine kontaktlose Übergabe",
  "checkout_notes_title": "Reihenfolge",
  "checkout_message_restaurant_title": "Eine Nachricht für das Restaurant hinzufügen",
  "checkout_message_restaurant_subtitle": "Sonderwünsche, Allergien, diätetische Einschränkungen?",
  "checkout_message_restaurant_editor_title": "Anweisungen für das Restaurant",
  "checkout_message_restaurant_editor_description": "Sonderwünsche, Allergien, diätetische Einschränkungen?",
  "checkout_message_restaurant_placeholder": "Sonderwünsche hinzufügen (optional)",
  "checkout_message_courier_title": "Hinzufügen einer Nachricht für den Kurier",
  "checkout_message_courier_subtitle": "Fügen Sie wichtige Anweisungen, Landmarken oder Sonderanfragen hinzu.",
  "checkout_message_courier_editor_title": "Anweisungen für den Kurier",
  "checkout_message_courier_editor_description": "Fügen Sie wichtige Anweisungen, Landmarken oder Sonderanfragen hinzu.",
  "checkout_message_courier_placeholder": "Lieferanweisungen hinzufügen (optional)",
  "checkout_message_done": "Geschehen",
  "checkout_delivery_time_title": "Lieferzeit",
  "checkout_collection_time_title": "Sammelzeit",
  "checkout_delivery_time_standard": "Standard",
  "checkout_delivery_time_standard_eta": "10-20 min",
  "checkout_delivery_time_schedule": "Zeitplan",
  "checkout_delivery_time_schedule_hint": "Wählen Sie eine Lieferzeit",
  "checkout_schedule_title": "Zeitplan Lieferzeit",
  "checkout_schedule_heading": "Wählen Sie eine Zeit, die für Sie arbeitet",
  "checkout_schedule_description": "Die verfügbaren Zeiten werden für diesen Shop aktuell gehalten.",
  "checkout_schedule_available_times": "Verfügbare Zeiten",
  "checkout_schedule_today": "Heute",
  "checkout_schedule_tomorrow": "Morgen",
  "checkout_schedule_asap": "So bald wie möglich",
  "checkout_schedule_confirm": "Bestätigung",
  "checkout_schedule_empty_title": "Keine Zeitplanslots verfügbar",
  "checkout_schedule_empty_message": "Versuchen Sie einen anderen Tag oder fahren Sie mit der Standardlieferung fort.",
  "checkout_schedule_error_title": "Fahrplanschlitze nicht laden können",
  "checkout_schedule_error_message": "Bitte versuchen Sie erneut, die verfügbaren Zeitfenster abzuholen.",
  "checkout_schedule_slot_expired": "Dieser Zeitschlitz ist nicht mehr verfügbar. Bitte wählen Sie eine andere.",
  "checkout_schedule_unavailable_note": "Vorbestellung nicht verfügbar an Sonntagen und Feiertagen.",
  "checkout_payment_title": "Zahlung",
  "checkout_payment_selector_title": "Zahlungsmethode",
  "checkout_payment_close": "Enge Zahlungsmethoden",
  "checkout_payment_selector_heading": "Wählen Sie eine Zahlungsmethode",
  "checkout_payment_selector_description": "Wählen Sie aus, wie Sie für diese Bestellung bezahlen möchten.",
  "checkout_payment_selector_confirm": "Zahlungsmethode bestätigen",
  "checkout_payment_cash_title": "Bargeld",
  "checkout_payment_cash_subtitle": "Bezahlen Sie mit Bargeld, wenn Ihre Bestellung eintrifft",
  "checkout_payment_card_title": "Karte",
  "checkout_payment_card_subtitle": "Bezahlen Sie sicher online mit Ihrer Karte",
  "checkout_payment_card_saved_subtitle": "{{brand}} (••••{{last4}})",
  "checkout_payment_option_cash_description": "Bezahlen bei Lieferung oder Abholung.",
  "checkout_payment_option_card_description": "Sie werden die zahlung im sicheren stripe checkout abschließen.",
  "checkout_payment_add_card_required": "Fügen Sie eine Karte in der Brieftasche hinzu, um die Kartenzahlung zu verwenden.",
  "checkout_payment_cash_unavailable": "Bargeld bei Lieferung ist für diesen Shop nicht verfügbar",
  "checkout_payment_card_unavailable": "Kartenzahlung ist für diesen Shop nicht verfügbar",
  "checkout_payment_cod_unavailable_error": "Dieser Laden erlaubt kein Bargeld bei Lieferung.",
  "checkout_payment_card_unavailable_error": "Dieser Shop erlaubt keine Kartenzahlungen.",
  "checkout_payment_webview_title": "Vollständige Zahlung",
  "checkout_payment_processing_title": "Bestätigung Ihrer Zahlung",
  "checkout_payment_processing_message": "Bitte warten Sie, während wir Ihre Zahlung überprüfen und Ihre Bestellung erstellen.",
  "checkout_payment_processing_error": "Wir überprüfen immer noch Ihre Zahlung. Bitte warten Sie einen Moment.",
  "checkout_payment_cancelled": "Die Zahlung wurde storniert.",
  "checkout_payment_failed": "Zahlung fehlgeschlagen. Bitte versuchen Sie es noch einmal mit einer anderen Methode.",
  "checkout_payment_confirmation_delayed": "Ihre Kartenzahlung kann immer noch verarbeitet werden. Überprüfen Sie Ihre Bestellungen, bevor Sie es erneut versuchen.",
  "checkout_payment_card_redirecting": "Füllen Sie Ihre Zahlung im Browser aus, um diese Bestellung abzuschließen.",
  "checkout_payment_card_redirect_error": "Unfähig, sichere Checkout jetzt zu öffnen.",
  "checkout_leave_at_door_card_required": "Lassen Sie an der Tür erfordert Kartenzahlung. Bitte wechseln Sie zur Karte, um fortzufahren.",
  "checkout_leave_at_door_switched_to_card": "Zahlungsmethode auf Karte für Leave-at-Door-Lieferung geschaltet.",
  "checkout_promo_title": "Promo-Code",
  "checkout_promo_subtitle": "Tippen Sie hier, um fortzufahren",
  "checkout_promo_tap_to_change": "Tippen Sie hier, um zu ändern",
  "checkout_promo_remove": "Entfernen",
  "checkout_promo_removed": "Promo-Code entfernt",
  "checkout_tip_title": "Tippen Sie Ihren Kurier",
  "checkout_tip_description": "Das Trinkgeld wird vollständig an den Kurier ausgezahlt.",
  "checkout_tip_custom": "Zoll",
  "checkout_tip_none": "Keine Spitze",
  "checkout_tip_custom_title": "Hinzufügen eines benutzerdefinierten Tipp",
  "checkout_tip_custom_placeholder": "0.00",
  "checkout_tip_custom_done": "Geschehen",
  "checkout_summary_title": "Zusammenfassung",
  "checkout_summary_hint": "inkl. Steuern (falls zutreffend)",
  "checkout_summary_subtotal": "Zwischensumme",
  "checkout_summary_discount": "Rabatt",
  "checkout_summary_delivery_fee": "Liefergebühr",
  "checkout_summary_packing_charges": "Verpackungsgebühren",
  "checkout_summary_tax": "Steuern",
  "checkout_summary_tip": "Kurierspitze",
  "checkout_summary_total": "Insgesamt",
  "checkout_summary_free": "frei",
  "checkout_place_order": "Bestellung",
  "checkout_place_order_pending": "Die Bestellung wird im nächsten Schritt verfügbar sein.",
  "checkout_place_order_success": "Bestellung erfolgreich platziert.",
  "checkout_place_order_error": "Sie können Ihre Bestellung jetzt nicht aufgeben.",
  "order_confirmation_title": "Bestellung bestätigt",
  "order_confirmation_number": "Ordnung #{{number}}",
  "order_confirmation_message": "{{store}} hat Ihre Bestellung erhalten. Wir halten Sie auf dem Laufenden, während es sich bewegt.",
  "order_confirmation_store_fallback": "Dein Shop",
  "order_confirmation_step_confirmed": "Bestätigt",
  "order_confirmation_step_store": "Mit dem Laden",
  "order_confirmation_step_preparing": "Vorbereitung",
  "order_confirmation_step_scheduled": "Geplant",
  "order_confirmation_step_delivery": "Lieferung",
  "order_confirmation_step_pickup": "Abholung",
  "order_confirmation_eta_label": "Geschätzte Ankunft",
  "order_confirmation_ready_label": "Geschätzte Bereitschaftszeit",
  "order_confirmation_eta_pending": "Updates in Kürze",
  "order_confirmation_minutes": "{{estimate}} min",
  "order_confirmation_order_from": "Bestellung aus",
  "order_confirmation_track": "Gleislage",
  "order_confirmation_receipt": "Sichteingang",
  "order_confirmation_help": "Hilfe bekommen",
  "order_confirmation_done": "Schließende Bestätigung",
  "checkout_address_required": "Bitte wählen Sie zuerst eine Lieferadresse aus.",
  "checkout_promo_pending": "Promo-Code-Unterstützung wird im nächsten Schritt hinzugefügt.",
  "checkout_preview_error_title": "Checkout nicht laden können",
  "checkout_preview_error_message": "Bitte versuchen Sie es gleich noch einmal.",
  "checkout_preview_updating": "Aktualisieren Sie Ihre gesamte...",
  "checkout_store_closed_title": "Der Laden ist geschlossen",
  "checkout_store_closed_message": "Dieser Laden ist derzeit geschlossen. Bitte versuchen Sie es noch einmal während der Öffnungszeiten.",
  "checkout_address_outside_delivery_area_title": "Außerhalb des Liefergebiets",
  "checkout_address_outside_delivery_area_message": "Dieser Speicher kann nicht an die ausgewählte Adresse liefern. Bitte wählen Sie eine andere Lieferadresse.",
  "checkout_change_address": "Änderungsadresse",
  "checkout_insufficient_wallet_balance_title": "Unzureichendes Wallet-Guthaben",
  "checkout_insufficient_wallet_balance_message": "Ihr Wallet-Guthaben von {{balance}} reicht nicht aus, um die Gesamtsumme dieser Bestellung von {{total}} abzudecken. Fügen Sie Geld zu Ihrer Brieftasche hinzu oder wählen Sie eine andere Zahlungsmethode.",
  "checkout_insufficient_wallet_balance_add_funds": "Fügen Sie Geld für Wallet hinzu",
  "checkout_insufficient_wallet_balance_choose_payment": "Wählen Sie eine andere Zahlungsmethode",
  "checkout_payment_wallet_title": "Wallet",
  "checkout_payment_wallet_subtitle": "Bezahlen Sie mit Ihrem Wallet-Guthaben",
  "checkout_payment_option_wallet_description": "Bezahlen Sie sicher mit Ihrem Wallet-Guthaben.",
  "checkout_payment_wallet_insufficient_balance": "Unzureichendes Wallet-Guthaben für diese Bestellung.",
  "checkout_payment_wallet_balance": "Wallet-Guthaben: {{currency}} {{amount}}",
  "cart_empty_title": "Ihr Wagen ist leer",
  "cart_empty_message": "Wenn Sie Artikel aus einem Geschäft hinzufügen, ist Ihre Bestellung hier, so dass Sie Änderungen vornehmen können, wann immer Sie möchten.",
  "cart_start_shopping": "Einkaufen beginnen",
  "cart_error_title": "Konnte Ihren Wagen nicht laden",
  "cart_error_message": "Bitte versuchen Sie es gleich noch einmal.",
  "cart_remove_item": "Artikel entfernen",
  "cart_decrement_item": "Verringerung der Menge",
  "cart_increment_item": "Erhöhung der Menge",
  "cart_info_label": "Bestellgebühren und Mindestausgaben",
  "cart_low_order_fee_applies_prefix": "A",
  "cart_low_order_fee_applies_suffix": "Low-Order-Gebühr gilt",
  "cart_fee_modal_title": "Bestellgebühren und Mindestausgaben",
  "cart_fee_modal_description_prefix": "Die Mindestausgaben sind",
  "cart_fee_modal_description_suffix": "Gesamtwagenwert.",
  "cart_fee_modal_total_cart_value": "Gesamtwagenwert",
  "cart_fee_modal_service_fee": "Servicegebühr",
  "cart_fee_modal_above": "& oben",
  "cart_fee_modal_no_fee": "Keine Gebühr",
  "cart_fee_modal_note_prefix": "* Für Bestellungen weniger als",
  "cart_fee_modal_note_middle": "eine geringe Auftragsgebühr von",
  "cart_fee_modal_note_suffix": "gilt",
  "cart_store_conflict_title": "Ersetzen Sie Ihren aktuellen Warenkorb?",
  "cart_store_conflict_message": "Ihr Warenkorb hat bereits Artikel aus einem anderen Geschäft. Ersetzen Sie es, um Elemente aus {{incomingStore}} hinzuzufügen.",
  "cart_store_conflict_message_with_product": "Ihr Warenkorb hat bereits Artikel aus einem anderen Geschäft. Ersetzen Sie es, um {{product}} aus {{incomingStore}} hinzuzufügen.",
  "cart_store_conflict_keep_cart": "Halten Sie den aktuellen Warenkorb",
  "cart_store_conflict_replace_cart": "Ersatzwagen",
  "cart_store_conflict_store_fallback": "Dieser Laden",
  "cart_action_loading_options_title": "Vorbereitungsoptionen",
  "cart_action_loading_options_message": "Bitte warten Sie, während wir die verfügbaren Anpassungen für diesen Artikel laden.",
  "cart_action_customization_required_title": "Wählen Sie zuerst Ihre Optionen",
  "cart_action_customization_required_message": "Bitte überprüfen Sie die Produktoptionen, bevor Sie diesen Artikel in Ihren Warenkorb legen.",
  "cart_action_out_of_stock_title": "Artikel nicht verfügbar",
  "cart_action_out_of_stock_message": "Dieser Artikel ist derzeit nicht vorrätig. Bitte versuchen Sie einen anderen Punkt.",
  "cart_network_error_title": "Verbindungsproblem",
  "cart_network_error_message": "Bitte überprüfen Sie Ihre Internetverbindung und versuchen Sie es erneut.",
  "cart_add_success_title": "Zum Warenkorb hinzugefügt",
  "cart_add_success_message": "{{quantity}} × {{product}} ist in Ihrem Warenkorb bereit.",
  "cart_add_success_go_to_cart": "Gehe zum Wagen",
  "cart_add_success_continue_shopping": "Weiter einkaufen",
  "cart_add_error_title": "Artikel konnte nicht hinzugefügt werden",
  "cart_add_error_message": "Bitte versuchen Sie es gleich noch einmal.",
  "cart_store_closed_title": "{{storeName}} ist geschlossen",
  "cart_store_closed_description": "Dieser Laden akzeptiert derzeit keine Bestellungen. Bitte schauen Sie zurück, sobald es wieder geöffnet ist.",
  "cart_update_success_title": "Warenkorb aktualisiert",
  "cart_update_success_message": "Ihre Warenkorbnummer wurde aktualisiert.",
  "cart_update_error_title": "Kann den Warenkorb nicht aktualisieren",
  "cart_update_error_message": "Bitte versuchen Sie, Ihren Warenkorb erneut zu aktualisieren.",
  "cart_remove_success_title": "Entfernter Gegenstand",
  "cart_remove_success_message": "Der Artikel wurde aus Ihrem Warenkorb entfernt.",
  "cart_remove_error_title": "Artikel konnte nicht entfernt werden",
  "cart_remove_error_message": "Bitte versuchen Sie, den Artikel erneut zu entfernen.",
  "cart_clear_action": "Klarer Warenkorb",
  "cart_clear_popup_title": "Löschen Sie Ihren Warenkorb?",
  "cart_clear_popup_message": "Dadurch werden alle Artikel aus Ihrem aktuellen Warenkorb entfernt, sodass Sie frisch beginnen können.",
  "cart_clear_popup_confirm": "Klarer Warenkorb",
  "cart_clear_popup_cancel": "Stornierung",
  "cart_clear_error_title": "Kann den Wagen nicht ersetzen",
  "cart_clear_error_message": "Bitte versuchen Sie es gleich noch einmal.",
  "free": "frei",
  "store_card_new": "Neu",
  "store_card_delivery_fee_unavailable": "{{currency}} —",
  "store_card_delivery_time_unavailable": "ETA —",
  "store_card_distance_unavailable": "— km",
  "product_info_back": "Rücken",
  "product_info_share": "Aktienprodukt",
  "product_info_unavailable": "Derzeit nicht verfügbar",
  "product_info_error_title": "Konnte Produkt nicht laden",
  "orders_tab_active": "Aktiv",
  "orders_tab_history": "Vergangenheit",
  "orders_tab_scheduled": "Geplant",
  "orders_history_active_heading": "Aktive Aufträge",
  "orders_empty_active_title": "Noch keine aktiven Bestellungen",
  "orders_empty_active_subtitle": "Ihre aktiven Bestellungen werden hier erscheinen, sobald Sie eine platzieren.",
  "orders_empty_history_title": "Noch keine Bestellungen",
  "orders_empty_history_subtitle": "Du hast keine Bestellung gemacht. Es wird sich hier zeigen, wenn du einen gemacht hast.",
  "orders_empty_history_cta": "Einkaufen beginnen",
  "orders_empty_scheduled_title": "Noch keine Terminlieferungen",
  "orders_empty_scheduled_subtitle": "Sie haben keine Bestellung geplant.",
  "orders_history_ongoing_heading": "Laufender Auftrag",
  "orders_history_past_heading": "Vergangene Aufträge",
  "orders_history_scheduled_heading": "Geplante Aufträge",
  "orders_list_load_more": "Mehr Ladung",
  "orders_list_no_more_items": "Keine weiteren Artikel mehr",
  "orders_list_error": "Unfähig, geplante Lieferungen jetzt zu laden.",
  "orders_list_retry": "Versuchen Sie es noch einmal",
  "orders_status_upcoming": "Kommend",
  "orders_status_ongoing": "Laufende",
  "orders_status_scheduled": "Geplant",
  "orders_status_received": "Auftragseingang",
  "orders_status_confirmed": "Bestätigt",
  "orders_status_preparing": "Vorbereiten Ihrer Bestellung",
  "orders_status_ready": "Bereit für Pickup",
  "orders_status_courier_assigned": "Zugeordneter Kurier",
  "orders_status_on_the_way": "Auf dem Weg",
  "orders_status_arrived": "Kurier angekommen",
  "orders_status_delayed": "Lieferverzögerung",
  "orders_status_delivered": "Zugestellter Auftrag",
  "orders_status_cancelled": "Bestellung storniert",
  "orders_status_rejected": "Bestellung abgelehnt",
  "orders_status_failed": "Bestellung konnte nicht abgeschlossen werden",
  "orders_screen_title": "Bestellungen",
  "orders_screen_subtitle": "Folgen Sie dem, was in Bewegung ist, oder besuchen Sie eine frühere Lieferung.",
  "orders_view_details": "Angaben zur Darstellung",
  "order_cancel_title": "Auftrag stornieren?",
  "order_cancel_message": "Bezahlte Bestellungen werden auf Ihre Brieftasche zurückerstattet.",
  "order_cancel_keep": "Reihenfolge beibehalten",
  "order_cancel_confirm": "Annullierung des Auftrags",
  "order_cancel_failed": "Unfähig, die Bestellung zu stornieren",
  "order_details_title": "Auftragsangaben",
  "order_details_error_title": "Diese Bestellung kann derzeit nicht geladen werden.",
  "order_details_status": "Auftragsstatus",
  "order_details_progress": "Lieferfortschritt",
  "order_details_scheduled_for": "Geplant für",
  "order_details_items": "Auftragspositionen",
  "order_details_summary": "Bestellzusammenfassung",
  "order_details_payment_details": "Zahlungsdaten",
  "order_details_payment_method": "Zahlungsmethode",
  "order_details_paid": "Bezahlt",
  "order_details_unavailable": "Nicht verfügbar",
  "order_details_reference": "Ordnung #{{number}}",
  "order_details_get_help": "Hilfe bekommen",
  "order_details_order_number": "Laufende Nummer",
  "order_details_delivery_address": "Lieferanschrift",
  "order_details_item_subtotal": "Position Zwischensumme",
  "order_details_discount": "Rabatt",
  "order_details_tax": "Steuersatz",
  "order_details_packing_charges": "Verpackungsgebühren",
  "order_details_delivery_fee": "Lieferung",
  "order_details_courier_tip": "Kurierspitze",
  "order_details_total_amount": "Gesamtbetrag",
  "order_details_rate_order": "Bewerten Sie den Auftrag",
  "order_details_view_rating": "Sehen Sie Ihre Bewertung",
  "order_details_increase_tip": "Erhöhen Sie die Spitze",
  "order_details_track_progress": "Spurweite Fortschritte",
  "order_details_order_again": "Bestellung erneut",
  "order_details_notes": "Anmerkungen",
  "order_details_restaurant_note": "Restaurantbeschreibung",
  "order_details_courier_note": "Kurierschein",
  "order_again_error_title": "Artikel konnten nicht neu bestellt werden",
  "order_again_error_message": "Bitte versuchen Sie, diese Artikel in einem Moment erneut zu bestellen.",
  "order_again_partial_title": "Einige Dinge brauchen Aufmerksamkeit",
  "order_details_tip_done": "Geschehen",
  "order_details_tip_placeholder": "0.00",
  "order_details_empty_items": "Keine Artikel",
  "order_details_quantity_one": "Anz. {{count}}",
  "order_tracking_title": "Ihre Bestellung",
  "order_tracking_help": "Order Tracking Hilfe",
  "order_tracking_eta_label": "Geschätzte Lieferzeit",
  "order_tracking_eta_pending": "Updates in Kürze",
  "order_tracking_eta_short_confirming": "Bestätigung",
  "order_tracking_eta_short_preparing": "Prep.",
  "order_tracking_eta_short_on_way": "Auf dem Weg",
  "order_tracking_eta_short_nearby": "Nahe",
  "order_tracking_eta_short_delivered": "Geschehen",
  "order_tracking_eta_short_ended": "Beendet",
  "order_tracking_eta_short_updating": "Bald",
  "order_tracking_until_delivered": "bis zur Lieferung",
  "order_tracking_eta_remaining": "verbleibend",
  "order_tracking_estimated_arrival": "Geschätzte Ankunft {{time}}",
  "order_tracking_close": "Close Order Tracking",
  "order_tracking_recenter_map": "Recenter-Karte",
  "order_tracking_route_loading": "Die beste Route finden...",
  "order_tracking_route_unavailable": "Live Route nicht verfügbar",
  "order_tracking_route_unavailable_description": "Live-Standorte bleiben sichtbar, während die Straßenroute aktualisiert wird.",
  "order_tracking_route_pending": "Routen-Updates erscheinen hier",
  "order_tracking_route_pending_description": "Die Route wird gezogen, sobald beide Standorte verfügbar sind.",
  "order_tracking_location_unavailable": "Live Map nicht verfügbar",
  "order_tracking_location_unavailable_description": "Ihre Bestellupdates sind unten noch verfügbar.",
  "order_tracking_progress": "Lieferfortschritt",
  "order_tracking_next_step": "Weiter: {{step}}",
  "order_tracking_no_next_step": "Keine weiteren Schritte",
  "order_tracking_delay_next": "Wir halten Sie auf dem Laufenden",
  "order_tracking_order_items": "Auftragspositionen",
  "order_tracking_courier_role": "Ihr Kurier",
  "order_tracking_courier_pending": "Kurier Details aktualisieren",
  "order_tracking_message_courier": "Nachrichtenkurierdienst",
  "order_tracking_delivered_title": "Geliefert",
  "order_tracking_delivered_message_line_one": "Ihre Bestellung wurde geliefert.",
  "order_tracking_delivered_message_line_two": "Genießen Sie Ihr Essen!",
  "order_tracking_error_title": "Das Tracking kann momentan nicht geladen werden.",
  "order_tracking_delivery_details": "Lieferdetails",
  "order_tracking_collection_details": "Angaben zur Sammlung",
  "order_tracking_contact_title": "Kontaktieren Sie Ihren Kurier",
  "order_tracking_contact_subtitle": "Bitten Sie um kontaktlose Lieferung",
  "order_tracking_courier_fallback": "Kurier",
  "order_tracking_summary": "Zusammenfassung",
  "order_tracking_summary_note": "inkl. Steuern (falls zutreffend)",
  "order_tracking_unavailable_title": "Bestellung nicht bestätigt",
  "order_tracking_unavailable_description": "Der Laden konnte Ihre Bestellung nicht bestätigen, daher wurde sie storniert. Sie können es wieder platzieren oder einen anderen Laden in der Nähe auswählen.",
  "order_tracking_unavailable_cancelled_description": "Diese Bestellung wurde storniert, so dass nichts mehr zu verfolgen ist. Sie können es wieder platzieren oder einen anderen Laden in der Nähe auswählen.",
  "order_tracking_unavailable_action": "Zurück nach Hause",
  "wallet_title": "Wallet",
  "wallet_balance_label": "Wallet Balance",
  "wallet_hide_balance": "Verstecken Wallet Balance",
  "wallet_show_balance": "Show Wallet Balance",
  "wallet_action_convert": "Umrechnungspunkte",
  "wallet_action_cards": "Verwalten von Karten",
  "wallet_loyalty_available_points": "verfügbare Punkte",
  "wallet_loyalty_zero_state": "Noch keine Punkte zu konvertieren. Ihre Punkte werden hier erscheinen, wenn Sie sie verdienen.",
  "wallet_loyalty_receive_label": "Sie erhalten",
  "wallet_loyalty_details": "Loyalitätsdetails anzeigen",
  "wallet_loyalty_hide_details": "Details zur Loyalität ausblenden",
  "wallet_points_max": "Max.",
  "wallet_convert_sheet_description": "Verwandeln Sie Ihre Loyalitätspunkte in Wallet Balance.",
  "wallet_loyalty_total_points": "Insgesamt verdiente Treuepunkte",
  "wallet_loyalty_rate": "{{points}} Punkte = {{currency}} 1",
  "wallet_loyalty_amount": "Wallet-Guthaben aus Loyalität verdient",
  "wallet_convert_points_title": "Loyalitätspunkte konvertieren",
  "wallet_points_available": "{{points}} Punkte verfügbar",
  "wallet_points_input": "Konvertierungspunkte",
  "wallet_points_receive": "Sie erhalten {{currency}} {{amount}}",
  "wallet_convert_points_action": "Hinzufügen zu Wallet",
  "wallet_points_converted_title": "Konvertierte Punkte",
  "wallet_points_converted_message": "{{currency}} {{amount}} wurde Ihrem Wallet hinzugefügt.",
  "wallet_points_convert_error": "Keine Konvertierung von Punkten möglich",
  "wallet_cards_title": "Karten",
  "wallet_payment_methods_title": "Zahlungsmethoden",
  "wallet_cards_sheet_description": "Verwalten Sie Ihre gespeicherten Karten.",
  "wallet_cards_secure_note": "Kartendetails werden von stripe sicher gehandhabt.",
  "wallet_saved_card_accessibility": "{{brand}} Karte {{name}}, {{last4}}",
  "wallet_done": "Geschehen",
  "wallet_close": "Schließen",
  "wallet_view_transactions": "Transaktionen ansehen",
  "wallet_secure": "sicher",
  "wallet_default_card": "Ausfall",
  "wallet_add_card": "Debit-/Kreditkarte hinzufügen",
  "wallet_topup_title": "Geld hinzufügen",
  "wallet_topup_sheet_description": "Füllen Sie Ihre Brieftasche für schnellere und einfachere Zahlungen auf.",
  "wallet_select_payment_method": "Wählen Sie die Zahlungsmethode",
  "wallet_choose_payment_method": "Wählen Sie die Zahlungsmethode",
  "wallet_clear_amount": "Klarer Betrag",
  "wallet_topup_amount": "Einstiegsbetrag",
  "wallet_topup_action": "Hinzufügen zu Wallet",
  "wallet_topup_action_amount": "{{amount}} zum Wallet hinzufügen",
  "wallet_cover_order": "{{amount}} für diesen Auftrag aufladen",
  "wallet_topup_minimum": "Mindestaufstockung: {{amount}}",
  "wallet_add_card_continue": "Eine Karte hinzufügen, um fortzufahren",
  "wallet_topup_card_required": "Fügen Sie eine Karte hinzu, bevor Sie auffüllen",
  "wallet_topup_success": "Zahlung erfolgreich",
  "wallet_topup_success_title": "Zahlung bestätigt",
  "wallet_topup_success_message": "{{amount}} wurde erfolgreich bezahlt. Ihr Wallet-Guthaben wird in Kürze aktualisiert.",
  "wallet_topup_processing": "Zahlungsabwicklung",
  "wallet_topup_pending": "Ihr Wallet-Guthaben wird nach der Zahlungsbestätigung aktualisiert.",
  "wallet_topup_error": "Unfähig, Geld hinzuzufügen",
  "wallet_recent_transactions": "Jüngste Transaktionen",
  "wallet_balance_load_error": "Konnte dein Gleichgewicht nicht belasten. Tippen Sie auf Retry.",
  "wallet_statement_today": "Heute",
  "wallet_statement_yesterday": "Gestern",
  "wallet_statement_title": "Wallet Statement",
  "wallet_statement_balance": "Leistungsbilanz",
  "wallet_statement_all": "Alle Tätigkeiten",
  "wallet_statement_money_in": "Geld in",
  "wallet_statement_money_out": "Geld raus",
  "wallet_statement_no_filtered_activity": "Noch keine Aktivität in dieser Kategorie",
  "wallet_statement_details": "Einzelheiten zu Transaktionen",
  "wallet_statement_reason": "Grund",
  "wallet_statement_direction": "Richtung",
  "wallet_statement_date": "Datum und Uhrzeit",
  "wallet_statement_status": "Status",
  "wallet_statement_reference": "Zahlungs- oder Bestellnummer",
  "wallet_statement_transaction_id": "Wallet Transaktions-ID",
  "wallet_statement_view_order": "Reihenfolge der Ansicht",
  "wallet_statement_completed": "Abgeschlossen",
  "wallet_statement_approved": "Zugelassen",
  "wallet_statement_pending": "Ausstehend",
  "wallet_statement_rejected": "abgelehnt",
  "wallet_statement_unknown_status": "Aufgezeichnet",
  "wallet_statement_unknown_direction": "Richtung nicht verfügbar",
  "wallet_statement_card_topup": "Geld zum Wallet hinzugefügt",
  "wallet_statement_card_topup_description": "Bezahlt mit einer gespeicherten Karte",
  "wallet_statement_order_payment": "Bezahlt für eine Bestellung",
  "wallet_statement_order_payment_description": "Bezahlt aus Ihrer Brieftasche",
  "wallet_statement_order_refund": "Auftragsrückerstattung",
  "wallet_statement_order_refund_description": "Geld zurück in Ihre Brieftasche",
  "wallet_statement_loyalty_conversion": "Konvertierte Loyalitätspunkte",
  "wallet_statement_loyalty_conversion_description": "Hinzugefügt aus Ihren Treuepunkten",
  "wallet_statement_opening_balance": "Ausgangssaldo",
  "wallet_statement_opening_balance_description": "Überbringen von Ihrer vorherigen Brieftasche",
  "wallet_statement_credit": "Geld hinzugefügt zu Wallet",
  "wallet_statement_credit_description": "Quelle wurde nicht erfasst",
  "wallet_statement_debit": "Geld aus der Brieftasche",
  "wallet_statement_debit_description": "Grund wurde nicht erfasst",
  "wallet_statement_withdrawal": "Wallet Rückzug",
  "wallet_statement_withdrawal_description": "Geld, das aus Ihrer Brieftasche abgezogen wurde",
  "wallet_statement_unknown": "Wallet-Transaktion",
  "wallet_statement_unknown_description": "Transaktionsdetails wurden nicht erfasst",
  "wallet_transactions_empty_title": "Noch keine Transaktionen",
  "wallet_transactions_empty_description": "Ihre Wallet-Aktivität wird hier angezeigt, sobald Sie eine Zahlung oder Rückerstattung vornehmen.",
  "wallet_transactions_error": "Wir konnten Ihre Wallet-Aktivität nicht laden. Tippen Sie, um es erneut zu versuchen.",
  "wallet_see_all": "Sehen Sie alle",
  "wallet_view_details": "Angaben zur Darstellung",
  "wallet_add_card_title": "Karte hinzufügen",
  "wallet_name_on_card": "Name auf der Karte",
  "wallet_name_placeholder": "Vollständiger Name des Karteninhabers",
  "wallet_card_number_label": "Kartennummer",
  "wallet_card_secure_title": "Ihre Kartendaten bleiben geschützt",
  "wallet_card_secure_description": "Zahlungsdetails werden von stripe verschlüsselt und sicher gehandhabt.",
  "wallet_card_number_placeholder": "Kredit- oder Debitkartennummer",
  "wallet_expiry_label": "Ablaufdatum",
  "wallet_security_code_label": "Sicherheitscode",
  "wallet_pay_securely": "Bezahlen Sie sicher mit",
  "wallet_save_card": "Sparen",
  "wallet_no_saved_cards": "Noch keine gespeicherten Karten",
  "wallet_cards_error": "Es können keine gespeicherten Karten geladen werden. Tippen Sie, um es erneut zu versuchen.",
  "wallet_add_card_error": "Karte nicht speichern können",
  "wallet_setup_intent_success_title": "Kartenaufbau gestartet",
  "wallet_setup_intent_success_message": "Setup Intention erstellt. Füllen Sie den Kartenbestätigungsfluss mit Stripe SDK aus.",
  "wallet_stripe_publishable_key_missing": "Stripe veröffentlichbarer Schlüssel fehlt.",
  "wallet_card_incomplete": "Bitte füllen Sie die Kartenangaben aus.",
  "wallet_card_saved_success_title": "Karte gespeichert",
  "wallet_card_saved_success_message": "Ihre Karte wurde erfolgreich hinzugefügt.",
  "off": "ausgeschaltet"
};

export default de;
