const en = {
  label: 'Deliveries',
  description: 'Order from stores or vendors.',
  header_title: 'Deliveries',
  header_subtitle: 'Choose a delivery type',
  hero_badge: 'Demo experience',
  hero_subtitle:
    'Switch between delivery models and preview the full experience beautifully.',
  hero_pill_fast: 'Quick mode switching',
  hero_pill_flexible: 'Try all delivery flows',
  section_title: 'Pick your mode',
  single_vendor_title: 'Single Vendor',
  single_vendor_desc: 'Order from your preferred store.',
  single_vendor_chip: 'Curated store',
  single_vendor_stat: 'One focused storefront',
  multi_vendor_title: 'Multi Vendor',
  multi_vendor_desc: 'Browse and order from multiple stores.',
  multi_vendor_chip: 'Marketplace',
  multi_vendor_stat: 'Many vendors in one place',
  chain_title: 'Chain',
  chain_desc: 'Order from your favorite chains.',
  chain_chip: 'Brand network',
  chain_stat: 'Chain menus and locations',
  explore_button: 'Explore',
  details_title: 'Delivery Details',
  single_vendor_categories_title: 'Categories',
  single_vendor_category_products_empty: 'No products found for this category.',
  single_vendor_home_subtitle: 'Your preferred store',
  single_vendor_home_body: 'Explore vendors and services here.',
  single_vendor_tab_home: 'Home',
  single_vendor_tab_search: 'Search',
  single_vendor_tab_orders: 'Orders',
  single_vendor_tab_profile: 'Profile',
  single_vendor_tab_search_placeholder: 'Search results and discovery tools will appear here soon.',
  single_vendor_tab_orders_placeholder: 'Your single-vendor orders will appear here soon.',
  single_vendor_logout_error_title: 'Error',
  single_vendor_logout_error_message: 'Unable to log out right now.',
  multi_vendor_home_subtitle: 'Browse multiple stores',
  multi_vendor_home_body: 'Discover and order from multiple vendors.',
  multi_vendor_home_greeting_morning: 'Good Morning 👋',
  multi_vendor_home_greeting_afternoon: 'Good Afternoon 👋',
  multi_vendor_home_greeting_evening: 'Good Evening 👋',
  delivery_home_greeting_morning: 'Good morning',
  delivery_home_greeting_afternoon: 'Good afternoon',
  delivery_home_greeting_evening: 'Good evening',
  delivery_home_title: 'Everything you need, delivered.',
  delivery_home_subtitle: 'Explore nearby stores, fresh meals and everyday essentials.',
  delivery_home_search_placeholder: 'Search stores, meals and essentials',
  multi_vendor_tab_home: 'Home',
  multi_vendor_tab_search: 'Search',
  multi_vendor_tab_orders: 'Orders',
  multi_vendor_tab_profile: 'Profile',
  chain_tab_home: 'Home',
  chain_tab_search: 'Search',
  chain_tab_orders: 'Orders',
  chain_tab_profile: 'Profile',
  chain_logout_error_title: 'Error',
  chain_logout_error_message: 'Unable to log out right now.',
  chain_categories_title: 'Categories',
  chain_category_products_empty: 'No products found for this category.',
  chain_menu_template_selector_label: 'Select chain menu',
  chain_menu_template_loading: 'Loading menus',
  chain_menu_template_empty: 'No menus',
  chain_menu_template_unavailable: 'Menu unavailable',
  delivery_address_title: 'Delivery address',
  delivery_address_empty_state:
    'Add an address to start ordering from this store.',
  logout: 'Log out',
  multi_vendor_address_label: 'Select address',
  delivery_header_deliver_to: 'Deliver to',
  multi_vendor_shop_types_title: 'Shop Types',
  multi_vendor_main_shop_types_title: 'Delivery Categories',
  multi_vendor_categories_title: 'Categories',
  multi_vendor_top_brands_title: 'Top Brands',
  multi_vendor_all_brands_title: 'All brands',
  multi_vendor_nearby_store_title: 'Nearby stores',
  multi_vendor_home_quick_browse: 'All stores',
  multi_vendor_home_quick_deals: 'Deals',
  multi_vendor_home_quick_orders: 'Order again',
  multi_vendor_home_quick_favourites: 'Favourites',
  multi_vendor_deals_title: 'Deals',
  multi_vendor_recommended_restaurants_title: 'Recommended restaurants',
  deals_see_all_tab_all: 'All',
  deals_see_all_tab_limited: 'Limited time deals',
  deals_see_all_tab_weekly: 'Weekly deals',
  deals_see_all_ends_in: 'Ends in',
  deals_see_all_section_title: 'All Offered Items',
  deals_see_all_section_title_limited: 'Limited Time Offers',
  deals_see_all_section_title_weekly: 'Weekly Offers',
  deals_see_all_badge_percentage: '{{value}}% off',
  deals_see_all_badge_fixed: '{{value}} off',
  multi_vendor_order_again_title: 'Order Again 😋',
  'main see all': 'Main see all',
  multi_vendor_see_all: 'See all',
  multi_vendor_order_again_add_item: 'Add item',
  multi_vendor_order_again_price_unavailable: 'Price unavailable',
  multi_vendor_nearby_store_name_hardees: 'Hardee’s - Z Block',
  multi_vendor_nearby_store_name_subway: 'Subway - Z Block',
  multi_vendor_nearby_store_category_fast_food: 'Fast Food',
  multi_vendor_nearby_store_category_pure_veg: 'Pure veg',
  multi_vendor_nearby_store_review_count: '(5000+)',
  multi_vendor_nearby_store_delivery_fee: '$2',
  multi_vendor_nearby_store_delivery_time: '30 mins',
  multi_vendor_nearby_store_distance: '1.7 km',
  multi_vendor_sponsored_label: 'Sponsored',
  multi_vendor_cart_label: 'Cart',
  multi_vendor_shop_type_gift: 'Gift Delivery',
  multi_vendor_shop_type_milk: 'Milk Delivery',
  multi_vendor_shop_type_flower: 'Flower Delivery',
  multi_vendor_shop_type_liquor: 'Liquor Delivery',
  multi_vendor_shop_type_products_empty: 'No products found for this shop type.',
  multi_vendor_shop_type_stores_empty: 'No stores found for this shop type.',
  multi_vendor_shop_types_empty: 'No delivery shop types are available right now.',
  multi_vendor_location_stores_empty: 'No stores available for this location.',
  multi_vendor_shop_type_products_error: 'Unable to load products right now.',
  multi_vendor_shop_type_stores_error: 'Unable to load stores right now.',
  multi_vendor_home_section_empty_title: 'No matches right now',
  multi_vendor_home_section_empty_message: 'Fresh picks and limited-time offers will appear here as soon as they are available.',
  multi_vendor_home_section_error_title: 'Unable to load items',
  multi_vendor_home_section_error_message: 'Please try again in a moment.',
  multi_vendor_home_section_empty_order_again: 'Your recent picks will appear here after your first order.',
  multi_vendor_home_empty_order_again_title: 'Ready for a new favourite?',
  multi_vendor_home_empty_explore_action: 'Explore stores',
  multi_vendor_home_empty_order_action: 'Explore now',
  store_details_search_placeholder: 'Search menu…',
  store_details_hero_title: 'Make It A\nMeal.',
  store_details_store_name: 'Subway @ Old Town, New Mexico',
  store_details_store_phone: '555-0123',
  store_details_store_email: 'support@subway.com',
  store_details_store_hours: '9 AM to 6 PM',
  store_details_call_label: 'Call us at',
  store_details_email_label: 'or email at',
  store_details_tab_offers: 'Offers',
  store_details_tab_pizza: 'Pizza',
  store_details_tab_burgers: 'Burgers',
  store_details_tab_pasta: 'Pasta',
  store_details_tab_sushi: 'Sushi',
  store_details_subcategory_italian_classic: 'Italian Classic',
  store_details_subcategory_american_style: 'American Style',
  store_details_subcategory_pepperoni: 'Pepperoni',
  store_details_subcategory_bbq_chicken: 'BBQ Chicken',
  store_details_subcategory_thin_crust: 'Thin Crust',
  store_details_all_offered_items: 'All Offered Items',
  store_details_no_items: 'No items match this filter yet.',
  store_details_load_error: 'Unable to load store details right now.',
  store_details_hours_unavailable: 'Hours unavailable',
  store_details_store_missing: 'Store details are not available.',
  store_details_action_info: 'Store info',
  store_details_action_favorite: 'Add store to favourites',
  store_details_action_remove_favorite: 'Remove store from favourites',
  store_details_action_share: 'Share store',
  store_details_action_back: 'Go back',
  store_details_about_title: 'About Us',
  store_details_about_fallback: 'Store description is not available right now.',
  store_details_closed_store_title: '{{storeName}} is currently closed',
  store_details_closed_store_description:
    '{{storeName}} is currently not open. Please try again later.',
  store_details_closed_store_fallback_name: 'This store',
  store_closed_modal_title: '{{storeName}} is currently closed',
  store_closed_see_menu: 'See menu',
  store_status_closed: 'Closed',
  store_status_open: 'Open',
  store_details_delivery_minutes: '{{minutes}} min',
  store_details_minimum_order: 'Min {{amount}}',
  store_details_close: 'Close',
  store_details_info_address: 'Address: {{address}}',
  store_details_info_phone: 'Phone: {{phone}}',
  store_details_info_email: 'Email: {{email}}',
  store_details_view_cart: 'View cart',
  store_details_cart_summary: '{{count}} items · {{amount}}',
  store_details_add_product: 'Add {{item}}',
  store_details_badge_deal: 'Deal',
  store_details_badge_ten_percent_off: '10% off',
  store_details_item_chicken_fajita: 'Chicken Fajita',
  store_details_item_chicken_teriyaki: 'Chicken Teriyaki',
  store_details_item_burger: 'Burger',
  store_details_item_sushi: 'Sushi',
  store_details_item_alfredo_pasta: 'Alfredo Pasta',
  store_details_item_veggie_delight: 'Veggie Delight',
  chain_home_subtitle: 'Favorite chains',
  chain_home_body: 'Order from your favorite chain stores.',
  type_single_vendor_title: 'Single Vendor Store',
  type_single_vendor_desc: 'Hand-picked premium vendors only',
  type_marketplace_title: 'Marketplace',
  type_marketplace_desc: 'Vast Local Community providers',
  type_chain_title: 'Chain Stores',
  type_chain_desc: 'Shop your favorite chains',
  // Profile screen
  profile_personal_account: 'Personal account',
  profile_wallet_balance: 'Wallet Balance',
  profile_view_wallet: 'View wallet',
  profile_menu_profile: 'Profile',
  profile_menu_notifications: 'Notifications',
  profile_menu_favorites: 'Favorites',
  profile_menu_coupons: 'Coupons',
  profile_menu_settings: 'Settings',
  profile_menu_support: 'Support',
  profile_menu_color_mode: 'App color mode',
  profile_menu_language: 'English',
  profile_menu_logout: 'Log out',
  // Coupons screen
  coupon_title: 'Coupons',
  coupon_active: 'Active',
  coupon_claim_label: 'Add a promo code',
  coupon_description:
    'If you have a Food Delivery promo code, referral code or gift card, enter it here to claim your benefits.',
  coupon_input_placeholder: 'Enter code',
  coupon_use: 'Use',
  coupon_off: 'Off',
  coupon_valid_until: 'Valid: {{date}}',
  coupon_claim: 'Claim',
  coupon_claim_success_title: 'Coupon claimed',
  coupon_claim_error_title: 'Unable to claim coupon',
  coupon_claim_error_fallback: 'Please enter a valid code and try again.',
  coupon_list_error_fallback: 'Unable to load claimed coupons right now.',
  coupon_used: 'Used',
  coupon_use_success_title: 'Coupon activated',
  coupon_use_success_message: 'Now you can use this.',
  coupon_use_error_title: 'Unable to activate coupon',
  coupon_use_error_fallback: 'Please try again.',
  coupon_deactivate: 'Deactivate',
  coupon_deactivate_success_title: 'Coupon deactivated',
  coupon_deactivate_success_message: 'This promo is no longer active.',
  coupon_deactivate_error_title: 'Unable to deactivate coupon',
  coupon_deactivate_error_fallback: 'Please try again.',
  coupon_status_expired: 'Expired',
  coupon_min_order: 'Min. order {{currency}} {{value}}',
  coupon_store_fallback: 'Partner Store',
  coupon_store_with_more: '{{store}} and {{count}} more',
  coupon_claimed_state_title: 'You just got the Coupon!',
  coupon_claimed_state_body_line_one: 'Hooray! Your promo code has been applied.',
  coupon_claimed_state_body_line_two: 'The discount will appear automatically at checkout.',
  coupon_empty_title: 'No coupons yet',
  coupon_empty_description:
    "You don't have any coupons right now. Enter a promo code above to find offers.",
  // My Profile screen
  my_profile_title: 'My profile',
  my_profile_edit: 'Edit',
  my_profile_full_name: 'Full name',
  my_profile_date_of_birth: 'Date of birth',
  my_profile_mobile_number: 'Mobile number',
  my_profile_email: 'Email',
  my_profile_my_addresses: 'My addresses',
  my_profile_add_address: 'Add address',
  my_profile_address_home: 'Home',
  my_profile_address_apartment: 'Apartment',
  my_profile_address_work: 'Work',
  my_profile_address_other: 'Other',
  // Profile photo modal
  photo_modal_title: 'Profile Photo',
  photo_modal_description: 'Choose how you want to update your profile photo',
  photo_take_photo: 'Take Photo',
  photo_choose_gallery: 'Choose from Gallery',
  photo_cancel: 'Cancel',
  photo_permission_title: 'Permission required',
  photo_permission_camera: 'Camera access is needed to take a photo.',
  photo_permission_gallery: 'Gallery access is needed to pick a photo.',
  photo_upload_error_title: 'Upload Failed',
  photo_upload_failed: 'Could not update profile photo.',
  // Edit Profile screen
  edit_profile_title: 'Edit profile',
  edit_profile_name: 'Name',
  edit_profile_date_of_birth: 'Date of birth',
  edit_profile_day: 'Day',
  edit_profile_month: 'Month',
  edit_profile_year: 'Year',
  edit_profile_gender: 'Gender',
  edit_profile_gender_placeholder: 'Select option',
  edit_profile_save: 'Save',
  edit_profile_success: 'Success',
  edit_profile_success_message: 'Profile updated successfully.',
  edit_profile_error: 'Error',
  edit_profile_name_required: 'Name is required.',
  edit_profile_failed: 'Could not update profile.',
  // Address screens
  address_list_title: 'My addresses',
  address_add_title: 'Add address',
  address_edit_title: 'Edit address',
  address_search_placeholder: 'Search for an address',
  address_choose_on_map: 'Choose on map',
  address_recent_searches: 'Recent searches',
  address_no_results: 'No results found',
  address_confirm_location: 'Confirm location',
  address_locating: 'Locating…',
  address_selected_location: 'Selected location',
  address_location_name_placeholder: 'Location name (e.g. My home)',
  address_details_label: 'Address Details',
  address_location_type_label: 'Location Type',
  address_location_details_label: 'Location Details',
  address_detail_house_placeholder: 'House',
  address_detail_apartment_placeholder: 'Apartment / Flat',
  address_detail_office_placeholder: 'Office / Building',
  address_detail_place_placeholder: 'Place',
  address_detail_society_placeholder: 'Society',
  address_detail_floor_placeholder: 'Floor / Tower',
  address_detail_department_placeholder: 'Department / Floor',
  address_detail_area_placeholder: 'Area / Street',
  address_detail_landmark_placeholder: 'Landmark',
  address_optional_suffix: '(optional)',
  address_type_home: 'Home',
  address_type_apartment: 'Apartment',
  address_type_office: 'Office',
  address_type_other: 'Other',
  address_save: 'Save address',
  address_update: 'Update address',
  address_delete: 'Delete',
  address_delete_confirm_title: 'Delete address',
  address_delete_confirm_message: 'Are you sure you want to delete this address?',
  address_delete_cancel: 'Cancel',
  address_delete_confirm: 'Delete',
  address_save_error: 'Could not save address.',
  address_select_error: 'Could not select address.',
  address_delete_error: 'Could not delete address.',
  address_save_success: 'Address saved successfully.',
  address_update_success: 'Address updated successfully.',
  address_delete_success: 'Address deleted successfully.',
  address_selector_title: 'Location',
  address_selector_close: 'Close location picker',
  address_selector_use_current_location: 'Use my current location',
  address_selector_add_new: 'Add new address',
  // Favourites screen
  favourites_title: 'Your Favourites',
  favourites_subtitle: 'Your saved stores, ready when you are.',
  favourites_empty_title: 'No favourites yet',
  favourites_empty_subtitle: 'Tap the heart on any store to keep it close for next time.',
  favourites_error_title: 'Could not load favourites',
  favourites_error: 'Check your connection and try again.',
  favourites_retry: 'Try again',
  favourites_free_delivery: 'Free delivery',
  favourites_remove: 'Remove from favourites',
  favourites_add: 'Add to favourites',
  favourites_toggle_added: 'Added to favourites',
  favourites_toggle_removed: 'Removed from favourites',
  favourites_toggle_error: 'Failed to update favourites',
  // Rate order screen
  rate_order_title: 'Rate Your Order',
  rate_order_heading: 'How was your meal?',
  rate_order_subheading: 'Your feedback helps us improve our delivery.',
  rate_order_comment_placeholder: 'Write your experience here...',
  rate_order_submit: 'Submit',
  rate_order_submitted_heading: 'Thanks for your rating!',
  rate_order_submitted_subheading:
    'You have already rated this order. Your feedback helps us improve our delivery.',
  rate_order_submitted_no_comment: 'No comment was added with this rating.',
  rate_order_success_title: 'Thank you!',
  rate_order_success_message: 'Your review has been submitted.',
  rate_order_error_title: 'Submission failed',
  // Settings screen
  settings_title: 'Settings',
  settings_notifications: 'Notification Settings',
  settings_change_password: 'Change Password',
  settings_privacy_policy: 'Privacy Policy',
  settings_terms_of_service: 'Terms of Service',
  settings_terms_of_use: 'Terms of Use',
  settings_delete_account: 'Delete Account',
  settings_app_version: 'App Version 1.0.0',
  // Notification settings screen
  notif_settings_title: 'Notification Settings',
  notif_settings_food_delivery: 'Food Delivery',
  notif_settings_marketing: 'Marketing',
  notif_settings_email: 'Email',
  notif_settings_sms: 'SMS',
  notif_settings_whatsapp: 'WhatsApp',
  notif_settings_success_title: 'Saved',
  notif_settings_success_message: 'Notification preference updated.',
  notif_settings_error_title: 'Error',
  // Privacy Policy screen
  privacy_title: 'Privacy Policy',
  privacy_last_updated: 'Last updated 2 months ago',
  privacy_intro:
    'This privacy policy explains how we handle your personal information while using the food delivery app. By registering or accessing the app, you consent to the practices described in this policy.',
  privacy_section_app_title: 'Privacy policy for the app',
  privacy_section_app_body:
    'The food delivery app is committed to protecting and managing your personal data and orders securely. You are authorized to use the app for personal and business purposes, subject to compliance with this policy and all applicable laws.',
  privacy_section_responsibilities_title: 'User responsibilities',
  privacy_section_responsibilities_body:
    'Users are responsible for keeping their delivery addresses and payment information accurate. It is important to keep this information up to date to avoid issues during the ordering process.',
  privacy_section_data_title: 'Data collection',
  privacy_section_data_body:
    'The food delivery app collects essential data to improve your experience, including your location, order history, and preferences.',
  privacy_section_modifications_title: 'Order modifications',
  privacy_section_modifications_body:
    'You may modify or cancel your orders through the app before they are processed. Once an order is confirmed, changes may no longer be possible.',
  privacy_section_payment_title: 'Payment security',
  privacy_section_payment_body:
    'We prioritize the security of your payment information. All transactions made through the app are processed using standard encryption technology.',
  privacy_section_contact_title: 'Contact us',
  privacy_section_contact_body:
    'If you have any questions about these terms, please feel free to contact us:',
  privacy_contact_email: 'Email: contact@fooddelivery.com',
  privacy_contact_address: 'Address: Doha, Qatar',
  // Terms of Service screen
  tos_title: 'Terms of Service',
  tos_last_updated: 'Last updated 2 months ago',
  tos_intro:
    'These terms of service define your access to and use of the food delivery app.',
  tos_section_usage_title: 'Use of the service',
  tos_section_usage_body:
    'The food delivery app provides a reliable platform for placing orders and managing your meal deliveries.',
  tos_section_orders_title: 'Order management',
  tos_section_orders_body:
    'The app allows you to track your orders easily, modify details, or cancel them within the allowed timeframe.',
  tos_section_payment_title: 'Payment security',
  tos_section_payment_body:
    'Payments made through the app are processed securely using encryption technology.',
  tos_section_delivery_title: 'Delivery policies',
  tos_section_delivery_body:
    'Users are encouraged to provide accurate delivery addresses to support fast and efficient service.',
  tos_section_support_title: 'Customer support',
  tos_section_support_body:
    'The app provides a robust support system to address any questions or issues.',
  tos_section_contact_title: 'Contact us',
  tos_section_contact_body:
    'If you have any questions about these terms, please feel free to contact us:',
  tos_contact_email: 'Email: contact@fooddelivery.com',
  tos_contact_address: 'Address: Doha, Qatar',
  // Terms of Use screen
  tou_title: 'Terms of Use',
  tou_last_updated: 'Updated 2 months ago',
  tou_intro:
    'These terms of use define your rights and responsibilities when using the app.',
  tou_section_guidelines_title: 'Usage guidelines',
  tou_section_guidelines_body:
    'The app provides secure management of your orders and customer data.',
  tou_section_etiquette_title: 'Delivery etiquette',
  tou_section_etiquette_body:
    'Users should remain respectful and courteous toward delivery staff.',
  tou_section_payment_title: 'Payment methods',
  tou_section_payment_body:
    'The app supports multiple payment methods, including credit cards and digital wallets.',
  tou_section_cancellation_title: 'Cancellation policy',
  tou_section_cancellation_body:
    'Orders may be cancelled within 10 minutes after being placed.',
  tou_section_feedback_title: 'Feedback and ratings',
  tou_section_feedback_body:
    'Users are encouraged to share feedback about their delivery experience.',
  tou_section_promotions_title: 'Promotions and offers',
  tou_section_promotions_body:
    'The app may offer promotions and discounts that are subject to specific conditions.',
  tou_section_contact_title: 'Contact us',
  tou_section_contact_body:
    'If you have any questions, please feel free to contact us:',
  tou_contact_email: 'Email: contact@fooddelivery.com',
  tou_contact_address: 'Address: Doha, Qatar',
  rider_chat_title: 'Chat with Rider',
  rider_chat_subtitle: 'Live delivery updates',
  rider_chat_status_online: 'Online now',
  rider_chat_eta_label: '{{minutes}} min away',
  rider_chat_order_label: 'Order {{orderCode}}',
  rider_chat_help_text: 'Share pickup notes or ask for an arrival call.',
  rider_chat_message_rider_intro: 'Hi! I am on the way with your order.',
  rider_chat_message_user_reply: 'Perfect. Please call me when you arrive at the gate.',
  rider_chat_message_rider_eta: 'Sure, I will call you. See you in about {{minutes}} minutes.',
  rider_chat_quick_reply_gate: 'Call at gate',
  rider_chat_quick_reply_thanks: 'Thanks!',
  rider_chat_quick_reply_here: 'I’m here',
  rider_chat_quick_reply_hello: 'Hello',
  rider_chat_quick_reply_call_arrive: 'Call me when you arrive',
  rider_chat_quick_reply_where: 'Where are you?',
  rider_chat_quick_reply_eta: 'How long will you take?',
  rider_chat_input_placeholder: 'Enter your concern...',
  rider_chat_auto_message: 'How can we help you?',
  rider_chat_auto_time: '8:29 pm',
  rider_chat_send: 'Send',
  rider_chat_send_error: 'Could not send message.',
  rider_chat_missing_session_error: 'Please log in before sending a message.',
  rider_chat_missing_receiver_error: 'Receiver is missing for this chat.',
  rider_chat_attachment_permission_title: 'Permission needed',
  rider_chat_attachment_permission_message: 'Please allow photo library access to add an attachment.',
  rider_chat_attachment_selected_title: 'Attachment selected',
  rider_chat_attachment_selected_message: '{{fileName}} is ready to attach.',
  rider_chat_add_attachment: 'Add attachment',
  rider_chat_send_message: 'Send message',
  rider_chat_call_action: 'Call rider',
  support_title: 'Support',
  support_guest_name: 'there',
  support_greeting: 'Hi {{name}}!',
  support_headline: 'What do you need help with today?',
  support_active_order_title: 'Help with your active order',
  support_active_order_eyebrow: 'Live order',
  support_active_order_track: 'Track and get help',
  support_active_order_accessibility: '{{store}}, {{status}}. Track order and get help.',
  support_chat_now_title: 'Get help now',
  support_chat_now_description: 'Message the support team for a fast, personal response.',
  support_chat_now_action_description: 'Continue a conversation or start a new one.',
  support_browse_topics: 'Browse help topics',
  support_topic_faq: 'Frequently asked questions',
  support_topic_faq_description: 'Find quick answers about orders, delivery, and your account.',
  support_topic_conversations: 'My conversations',
  support_topic_conversations_description: 'Continue recent chats with the support team.',
  support_topic_tickets: 'My Tickets',
  support_topic_tickets_description: 'Review reported issues and their resolution status.',
  support_issue_prompt: 'Didn’t find what you need?',
  support_issue_select_title: 'Please choose an option.',
  support_issue_placeholder: 'Select an issue type',
  support_report_issue_cta: 'Report an issue',
  support_retry: 'Try again',
  support_error_title: 'We couldn’t load this right now',
  support_error_description: 'Check your connection and try again. Your support history is safe.',
  support_conversations_empty_title: 'Your support chats will appear here',
  support_conversations_empty_description: 'Start a conversation whenever you need help with an order or your account.',
  support_conversations_empty_action: 'Start a conversation',
  support_conversations_no_results_title: 'No matching conversations',
  support_tickets_empty_title: 'No reported issues',
  support_tickets_empty_description: 'When you report an issue, its progress and replies will appear here.',
  support_tickets_empty_action: 'Report an issue',
  support_chat_closed_title: 'This conversation is closed',
  support_chat_closed_description: 'You can review the messages above or start a new support request.',
  support_issue_order: 'I already have a business account and need support',
  support_issue_payment: 'I’m interested in joining Food delivery as a business',
  support_issue_delivery: 'I booked an order with a business on Food delivery',
  support_issue_account: 'I need help with something else',
  support_issue_business_support: 'I already have a business account and need support',
  support_issue_joining_as_a_business: 'I’m interested in joining Food delivery as a business',
  support_issue_appointment_support: 'I booked an order with a business on Food delivery',
  support_call_action: 'Call support',
  support_back_action: 'Go back',
  support_header_action: 'Header action',
  support_close_action: 'Close support form',
  support_search_action: 'Search conversations',
  support_tickets_search_action: 'Search tickets',
  support_tickets_search_placeholder: 'Search tickets',
  support_tickets_no_results_title: 'No matching tickets',
  support_tickets_no_results_description: 'Try a different order number, status, or keyword.',
  support_form_how_help_label: 'How can we help?',
  support_form_email_label: 'Email',
  support_form_email_helper: 'If you have a Food delivery account, enter the email address you log in with',
  support_form_full_name_label: 'Full name',
  support_form_full_name_placeholder: 'Enter your name',
  support_form_country_region_label: 'Country / Region',
  support_form_country_region_placeholder: 'Please select',
  support_form_mobile_number_label: 'Mobile number',
  support_form_mobile_number_placeholder: '+61 333 000 0000',
  support_form_business_name_label: 'Business name',
  support_form_business_type_label: 'Business type',
  support_form_business_type_placeholder: 'Please select',
  support_form_team_size_label: 'Team size',
  support_form_team_size_placeholder: 'Please select',
  support_form_business_description_label: 'Is there anything in particular you want to know about Food delivery?',
  support_form_reason_label: 'Reason for contact',
  support_form_reason_placeholder: 'Please select',
  support_form_reason_account_setup: 'Account setup',
  support_form_reason_add_on_integrations: 'Add-ons and integrations',
  support_form_reason_addons_integrations: 'Add-ons and integrations',
  support_form_reason_using_the_app: 'Using the app',
  support_form_reason_payments_and_payouts: 'Payments and payouts',
  support_form_reason_technical_issues: 'Technical issues',
  support_form_reason_my_orders: 'My orders',
  support_form_reason_payments_and_purchases: 'Payments and purchases',
  support_form_reason_reviews: 'Reviews',
  support_form_reason_emails_and_notifications: 'Emails and notifications',
  support_form_reason_delete_my_account: 'Delete my account',
  support_form_reason_billing_fees: 'Billing and fees',
  support_form_reason_payments_payouts: 'Payments and payouts',
  support_form_reason_technical_support: 'Technical support',
  support_form_reason_other: 'Other',
  support_form_country_united_states: 'United States',
  support_form_country_canada: 'Canada',
  support_form_country_united_kingdom: 'United Kingdom',
  support_form_country_australia: 'Australia',
  support_form_country_france: 'France',
  support_form_business_type_burger_joint: 'Burger Joint',
  support_form_business_type_pizza_place: 'Pizza Place',
  support_form_business_type_taco_stand: 'Taco Stand',
  support_form_business_type_sandwich_shop: 'Sandwich Shop',
  support_form_business_type_ice_cream_parlor: 'Ice Cream Parlor',
  support_form_business_type_fried_chicken_spot: 'Fried Chicken Spot',
  support_form_business_type_food_truck: 'Food Truck',
  support_form_business_type_hot_dog_stand: 'Hot Dog Stand',
  support_form_business_type_other_fast_food: 'Other Fast Food',
  support_form_team_size_just_me: 'Just me',
  support_form_team_size_2_5: '2 - 5',
  support_form_team_size_6_10: '6 - 10',
  support_form_team_size_11_plus: '11+',
  support_form_description_label: 'Describe what you need help with',
  support_form_description_placeholder: 'Enter a description...',
  support_form_attach_title: 'Attach screenshots',
  support_form_attach_description: 'Drop your files here',
  support_form_attach_cta: 'Choose a file',
  support_form_send_email: 'Send email',
  support_form_submit_success_title: 'Ticket created',
  support_form_submit_success_message: 'Your support ticket was submitted successfully.',
  support_form_submit_error_title: 'Ticket failed',
  support_form_submit_error_message: 'We could not submit your support ticket. Check your connection and try again.',
  support_form_attachment_upload_error: 'One or more attachments could not be uploaded. Check your connection and try again.',
  support_chat_attachment_invalid_title: 'Attachment not added',
  support_chat_attachment_too_large_message: 'Each attachment must be 5 MB or smaller.',
  support_chat_agent_name: 'Jhon Smith',
  support_chat_auto_message: 'How can we help you?',
  support_chat_auto_time: '8:29 pm',
  support_chat_quick_reply_here: 'I’m here',
  support_chat_quick_reply_hello: 'Hello',
  support_chat_quick_reply_call_arrive: 'Call me when you arrive',
  support_chat_quick_reply_where: 'Where are you?',
  support_chat_quick_reply_eta: 'How long will you take?',
  support_chat_input_placeholder: 'Enter your concern...',
  support_chat_add_attachment: 'Add attachment',
  support_chat_send_message: 'Send message',
  support_chat_send_error_title: 'Message failed',
  support_chat_send_error_message: 'Could not send your support message.',
  support_chat_missing_session_error: 'Please log in before sending a message.',
  support_chat_missing_receiver_error: 'Support chat is not ready yet. Please open an existing conversation first.',
  support_chat_loading: 'Loading conversation...',
  support_chat_empty: 'No support conversation found yet.',
  support_chat_empty_message: 'Start a conversation with support.',
  support_chat_attachment_permission_title: 'Permission needed',
  support_chat_attachment_permission_message: 'Please allow photo library access to add an attachment.',
  support_chat_attachment_selected_title: 'Attachment selected',
  support_chat_attachment_selected_message: '{{fileName}} is ready to attach.',
  support_admin_picker_title: 'Choose support person',
  support_admin_picker_subtitle: 'Select an available admin to start your conversation.',
  support_admin_picker_loading: 'Loading support team...',
  support_admin_picker_empty: 'No support admins available right now.',
  support_admin_picker_row_subtitle: 'Tap to start conversation',
  support_conversations_title: 'My conversations',
  support_conversations_recent: 'Recent',
  support_conversations_past: 'Past',
  support_conversations_name_barbarella_inova: 'Barbarella Inova',
  support_conversations_name_barbarella_nova: 'Barbarella Nova',
  support_conversations_preview_let_me_check: 'Let me check.',
  support_conversations_preview_take_a_look: 'I’ll take a look.',
  support_conversations_time_5m: '5 min ago',
  support_conversations_time_1h: '1 hr ago',
  support_conversations_time_oct_2: '2 Oct',
  support_conversations_delete_action: 'Delete conversation',
  support_conversations_delete_title: 'Delete {{name}}’s chat?',
  support_conversations_delete_description: 'Are you sure you want to permanently delete this chat?',
  support_conversations_delete_cancel: 'Cancel',
  support_conversations_delete_confirm: 'Yes, Delete',
  support_conversations_loading: 'Loading conversations...',
  support_conversations_empty: 'No conversations yet.',
  support_conversations_search_placeholder: 'Search by name or message',
  support_conversations_no_results: 'No conversations match your search.',
  support_tickets_title: 'My Tickets',
  support_tickets_heading: 'All Tickets',
  support_tickets_loading: 'Loading tickets...',
  support_tickets_empty: 'No tickets found yet.',
  support_tickets_day_fri: 'FRI',
  support_tickets_title_how_to_order: 'How to Order',
  support_tickets_preview_how_to_order: 'Ordering on Food Delivery is quick and simple...',
  support_tickets_order_id: 'Order ID: {{orderId}}',
  support_tickets_status_open: 'Open',
  support_tickets_status_closed: 'Closed',
  support_tickets_status_pending: 'Pending',
  support_faq_title: 'General order questions',
  support_faq_header_title: 'Help articles',
  support_faq_subtitle: 'Clear answers for the most common ordering and delivery questions.',
  support_faq_place_order: 'How to place an order',
  support_faq_schedule_delivery: 'How to schedule your deliveries in advance',
  support_faq_change_delivery: 'Changing your deliveries',
  support_faq_order_history: 'How to view your order history',
  support_faq_ordering_for_others: 'Ordering for others and sending confirmations to different addresses',
  support_faq_still_need_help: 'Still need some help?',
  support_faq_feedback_prompt: 'Was this helpful?',
  support_faq_feedback_yes: 'Yes',
  support_faq_feedback_no: 'No',
  support_faq_feedback_thanks: 'Thanks — your feedback helps us improve support.',
  support_faq_place_order_body_1: 'Placing an order is quick and simple. Open the deliveries app and browse nearby restaurants, stores, or categories that match what you need.',
  support_faq_place_order_body_2: 'Tap a store to explore its menu, then add the items you want to your cart. You can review quantities, add notes, and remove anything before checkout.',
  support_faq_place_order_body_3: 'When you are ready, continue to checkout to confirm your delivery address, apply any promo codes, and choose your preferred payment method.',
  support_faq_place_order_body_4: 'After you place the order, you can track its progress in real time and stay updated until it arrives at your door.',
  support_faq_schedule_delivery_body_1: 'If a store supports scheduled orders, you can choose a delivery time before you complete checkout.',
  support_faq_schedule_delivery_body_2: 'Add your items to the cart and proceed to checkout. Look for the delivery timing section before confirming your order.',
  support_faq_schedule_delivery_body_3: 'Select a date and time slot that works for you, then review the order details to make sure everything looks right.',
  support_faq_schedule_delivery_body_4: 'Once confirmed, we will keep your scheduled delivery in your orders tab so you can review it again later.',
  support_faq_change_delivery_body_1: 'You may be able to update parts of your order before the store starts preparing it.',
  support_faq_change_delivery_body_2: 'Open your active order and check whether editing is still available. Some stores allow small updates while others may lock changes once preparation begins.',
  support_faq_change_delivery_body_3: 'If editing is unavailable, the fastest option is usually to contact support from the help section or start a chat with a person.',
  support_faq_change_delivery_body_4: 'We recommend checking your cart carefully before placing the order so you can avoid last-minute changes.',
  support_faq_order_history_body_1: 'Your previous and active deliveries are available from the orders section in the app.',
  support_faq_order_history_body_2: 'Open the order you want to review to see its items, payment details, delivery address, and current or past status.',
  support_faq_order_history_body_3: 'This is also the best place to reorder items quickly when you want the same delivery again.',
  support_faq_ordering_for_others_body_1: 'You can place an order for someone else by selecting or entering the correct delivery address before checkout.',
  support_faq_ordering_for_others_body_2: 'Make sure the recipient name, phone number, and any delivery instructions are accurate so the courier can reach the right person.',
  support_faq_ordering_for_others_body_3: 'If you need to send updates to a different contact, review the available contact details during checkout and before confirming the order.',
  support_faq_ordering_for_others_body_4: 'For the smoothest experience, let the recipient know a delivery is on the way and share any timing details with them.',
  support_faq_still_need_help_body_1: 'If your question is not covered here, open the chat option at the bottom of the screen and reach out to our support team.',
  support_faq_still_need_help_body_2: 'Include key details such as the store name, order number, and a short explanation of the issue so we can help faster.',
  support_faq_still_need_help_body_3: 'Our team will guide you through the next steps and help resolve delivery, payment, or account-related concerns.',
  support_chat_cta: 'Chat with a person',
  searching_near: 'Searching near',
  products: 'Products',
  stores: 'Stores',
  see_all: 'See All',
  filter_title: 'Filter',
  filter_close_label: 'Close filters',
  filter_apply_results: 'Apply filters',
  filter_category_title: 'Category',
  filter_price_title: 'Price',
  filter_address_title: 'Nearby address',
  filter_stock_title: 'Stock',
  filter_sort_title: 'Sort by',
  generic_list_error_title: 'Unable to load results',
  generic_list_error_description: 'Pull to refresh or try again.',
  generic_list_retry: 'Retry',
  generic_list_empty_title: 'No results found',
  generic_list_empty_description: 'Try a different search or adjust your filters.',
  generic_list_search_placeholder: 'Search',
  see_all_map_loading_title: 'Finding {{title}}',
  see_all_map_loading_description: 'This may take a few moments. Please stay on this screen.',
  see_all_map_sheet_title: 'Restaurant',
  see_all_map_cta: 'View Restaurant',
  // Change password flow
  change_password_title: 'Change Password',
  change_password_new_title: 'New Password',
  change_password_email_heading: 'Change password?',
  change_password_email_description: 'Enter your email address and we\'ll send you a verification code.',
  change_password_email_placeholder: 'your@email.com',
  change_password_continue: 'Continue',
  change_password_verify_heading: 'Verify Your Email',
  change_password_verify_description: 'Enter the 4-digit code sent to {{email}}',
  change_password_verify_button: 'Verify OTP',
  change_password_new_heading: 'Create your new password',
  change_password_new_description: 'Your new password must be different from your previous password.',
  change_password_new_placeholder: 'New password',
  change_password_confirm_placeholder: 'Confirm new password',
  change_password_set_new: 'Set new password',
  change_password_mismatch: 'Passwords do not match.',
  change_password_error_title: 'Error',
  change_password_send_otp_error: 'Failed to send verification code.',
  change_password_verify_otp_error: 'Invalid or expired code.',
  change_password_update_error: 'Failed to update password.',
  change_password_success_title: 'Success',
  change_password_success_message: 'Your password has been updated.',
  change_password_otp_resent_title: 'Code sent',
  change_password_otp_resent_message: 'A new verification code has been sent.',
  // Delete account flow
  delete_account_step_label: 'Delete my account',
  delete_account_sorry_heading: "We'll be sorry to see you go",
  delete_account_sorry_subtext: 'Can we change your mind? Drop a line at',
  delete_account_contact_email: 'hello@enategadelivery.com',
  delete_account_reason_heading: 'Why do you wish to leave Food delivery?',
  delete_account_reason_subtext: 'Please let us know the reason for deleting your account:',
  delete_account_reason_mistake: 'I created this account by mistake',
  delete_account_reason_no_longer: 'I do not want to use Food delivery anymore',
  delete_account_reason_no_venues: "I can't find the venues or services I want",
  delete_account_reason_other: 'Other',
  delete_account_confirm_heading: 'Delete your Food delivery account',
  delete_account_confirm_description: 'This action will delete your account and you won\'t be able to retrieve it. Please confirm you understand by ticking the below statements:',
  delete_account_confirm_item_orders: 'I know I won\'t be able to access my orders.',
  delete_account_confirm_item_marketplace: 'I know I will no longer be able to book orders via Food delivery marketplace.',
  delete_account_final_heading: 'Confirm you are happy to proceed',
  delete_account_final_description: 'Please note this is permanent and can\'t be undone. To confirm deleting your account, please review your email below:',
  delete_account_email_label: 'Email',
  delete_account_email_placeholder: 'your@email.com',
  delete_account_cta_continue: 'Continue',
  delete_account_cta_delete: 'Delete account',
  delete_account_close: 'Close',
  delete_account_alert_title: 'Delete account',
  delete_account_alert_message: 'Are you sure you want to permanently delete your account? This action cannot be undone.',
  delete_account_alert_cancel: 'Cancel',
  delete_account_alert_confirm: 'Delete',
  delete_account_error_title: 'Error',
  delete_account_error: 'Failed to delete account. Please try again.',
  // Color mode screen
  color_mode_title: 'App color mode',
  color_mode_section_label: 'Select app color mode',
  color_mode_system: 'Default System',
  color_mode_light: 'Light',
  color_mode_dark: 'Dark',
  // Language screen
  language_title: 'App languages',
  language_section_label: 'Select language',
  language_english: 'English',
  language_french: 'French',
  popular: 'Popular',
  ingredients: 'Ingredients',
  usage: 'Usage',
  nutrition_facts: 'Nutrition facts',
  amount_per: 'Amount per',
  energy: 'Energy',
  fat: 'Fat',
  carbohydrates: 'Carbohydrates',
  protein: 'Protein',
  sugar: 'Sugar',
  choose_size: 'Choose Size',
  choose_variation: 'Choose Variation',
  select_one: 'Select one',
  required_label: 'Required',
  optional_label: 'Optional',
  product_option_choose_at_least: 'Choose at least {{count}}',
  product_option_choose_range: 'Choose {{min}}–{{max}}',
  product_option_choose_up_to: 'Choose up to {{count}}',
  product_option_required_error: 'Choose the required options to continue.',
  small: 'Small',
  medium: 'Medium',
  large: 'Large',
  choose_your_flavour: 'Choose your Flavour',
  choose_your_addons: 'Choose your Addons',
  add_to_cart: 'Add to Cart',
  cart_title: 'Cart',
  cart_store_fallback: 'Your store',
  cart_return_to_store: 'Return to {{store}}',
  cart_delivery_time: '{{time}} min delivery',
  cart_items_title: 'Your items',
  cart_add_more: 'Add More',
  cart_recommended_title: 'Recommended for you',
  cart_checkout: 'Go to checkout',
  cart_checkout_short: 'Checkout',
  cart_order_summary: 'Order summary',
  cart_promo_title: 'Promo code',
  cart_promo_subtitle: 'Choose a code for this order',
  cart_promo_applied: 'Selected for checkout',
  cart_promo_add: 'Add',
  cart_promo_change: 'Change',
  cart_fees_at_checkout: 'Delivery and service fees are confirmed at checkout',
  cart_minimum_remaining: '{{amount}} away from the minimum order',
  cart_minimum_reached: 'Minimum order reached',
  cart_minimum_progress_accessibility: '{{current}} of {{minimum}} minimum order',
  cart_item_unavailable: 'Unavailable',
  cart_recommendation_accessibility: 'View {{product}}',
  cart_fee_modal_current_subtotal: 'Current subtotal',
  cart_fee_modal_minimum_order: 'Minimum order',
  cart_fee_modal_base_delivery: 'Base delivery fee',
  cart_fee_modal_checkout_notice: 'Final delivery and service fees are calculated for your address at checkout.',
  checkout_title: 'Checkout',
  checkout_order_from: 'Ordering from',
  checkout_item_count: '{{count}} items',
  checkout_fulfillment_title: 'How would you like it?',
  checkout_fulfillment_delivery: 'Delivery',
  checkout_fulfillment_pickup: 'Pickup',
  checkout_delivery_details_title: 'Delivery details',
  checkout_pickup_details_title: 'Pickup details',
  checkout_address_title: 'Choose a delivery address',
  checkout_address_subtitle: 'Tap here to continue',
  checkout_address_selected_subtitle: 'Tap here to change',
  checkout_pickup_title: 'Pickup location',
  checkout_pickup_subtitle: 'Collect your order from the store',
  checkout_leave_at_door_title: 'Leave at the door',
  checkout_leave_at_door_subtitle: 'A contact-free handoff',
  checkout_notes_title: 'Order notes',
  checkout_message_restaurant_title: 'Add a message for the restaurant',
  checkout_message_restaurant_subtitle: 'Special requests, allergies, dietary restrictions?',
  checkout_message_restaurant_editor_title: 'Instructions for the restaurant',
  checkout_message_restaurant_editor_description: 'Special requests, allergies, dietary restrictions?',
  checkout_message_restaurant_placeholder: 'Add special requests (optional)',
  checkout_message_courier_title: 'Add a message for the courier',
  checkout_message_courier_subtitle: 'Add any important instructions, landmarks or special requests.',
  checkout_message_courier_editor_title: 'Instructions for the courier',
  checkout_message_courier_editor_description: 'Add any important instructions, landmarks or special requests.',
  checkout_message_courier_placeholder: 'Add delivery instructions (optional)',
  checkout_message_done: 'Done',
  checkout_delivery_time_title: 'Delivery Time',
  checkout_collection_time_title: 'Collection Time',
  checkout_delivery_time_standard: 'Standard',
  checkout_delivery_time_standard_eta: '10-20 min',
  checkout_delivery_time_schedule: 'Schedule',
  checkout_delivery_time_schedule_hint: 'Choose a delivery time',
  checkout_schedule_title: 'Schedule delivery time',
  checkout_schedule_heading: 'Choose a time that works for you',
  checkout_schedule_description: 'Available times are kept current for this store.',
  checkout_schedule_available_times: 'Available times',
  checkout_schedule_today: 'Today',
  checkout_schedule_tomorrow: 'Tomorrow',
  checkout_schedule_asap: 'As soon as possible',
  checkout_schedule_confirm: 'Confirm',
  checkout_schedule_empty_title: 'No schedule slots available',
  checkout_schedule_empty_message: 'Try another day or continue with standard delivery.',
  checkout_schedule_error_title: 'Unable to load schedule slots',
  checkout_schedule_error_message: 'Please try again to fetch the available time slots.',
  checkout_schedule_slot_expired: 'That time slot is no longer available. Please choose another one.',
  checkout_schedule_unavailable_note: 'Pre-order not available on Sundays & holidays.',
  checkout_payment_title: 'Payment',
  checkout_payment_selector_title: 'Payment method',
  checkout_payment_close: 'Close payment methods',
  checkout_payment_selector_heading: 'Choose a payment method',
  checkout_payment_selector_description: 'Select how you want to pay for this order.',
  checkout_payment_selector_confirm: 'Confirm payment method',
  checkout_payment_cash_title: 'Cash',
  checkout_payment_cash_subtitle: 'Pay with cash when your order arrives',
  checkout_payment_card_title: 'Card',
  checkout_payment_card_subtitle: 'Pay securely online with your card',
  checkout_payment_card_saved_subtitle: '{{brand}} (•••• {{last4}})',
  checkout_payment_option_cash_description: 'Pay on delivery or pickup.',
  checkout_payment_option_card_description: 'You will complete payment in secure Stripe checkout.',
  checkout_payment_add_card_required: 'Add a card in wallet to use card payment.',
  checkout_payment_cash_unavailable: 'Cash on delivery is unavailable for this store',
  checkout_payment_card_unavailable: 'Card payment is unavailable for this store',
  checkout_payment_cod_unavailable_error: 'This store does not allow cash on delivery.',
  checkout_payment_card_unavailable_error: 'This store does not allow card payments.',
  checkout_payment_webview_title: 'Complete payment',
  checkout_payment_processing_title: 'Confirming your payment',
  checkout_payment_processing_message: 'Please wait while we verify your payment and create your order.',
  checkout_payment_processing_error: 'We are still checking your payment. Please wait a moment.',
  checkout_payment_cancelled: 'Payment was cancelled.',
  checkout_payment_failed: 'Payment failed. Please try again with another method.',
  checkout_payment_card_redirecting: 'Complete your payment in the browser to finish this order.',
  checkout_payment_card_redirect_error: 'Unable to open secure checkout right now.',
  checkout_leave_at_door_card_required: 'Leave at the door requires card payment. Please switch to card to continue.',
  checkout_leave_at_door_switched_to_card: 'Payment method switched to card for leave-at-door delivery.',
  checkout_promo_title: 'Promo code',
  checkout_promo_subtitle: 'Tap here to continue',
  checkout_promo_tap_to_change: 'Tap here to change',
  checkout_promo_remove: 'Remove',
  checkout_promo_removed: 'Promo code removed',
  checkout_tip_title: 'Tip your courier',
  checkout_tip_description: 'The tip will be paid full to the courier.',
  checkout_tip_custom: 'Custom',
  checkout_tip_none: 'No tip',
  checkout_tip_custom_title: 'Add a custom tip',
  checkout_tip_custom_placeholder: '0.00',
  checkout_tip_custom_done: 'Done',
  checkout_summary_title: 'Summary',
  checkout_summary_hint: 'incl. taxes (if applicable)',
  checkout_summary_subtotal: 'Subtotal',
  checkout_summary_discount: 'Discount',
  checkout_summary_delivery_fee: 'Delivery fee',
  checkout_summary_packing_charges: 'Packing charges',
  checkout_summary_tax: 'Taxes',
  checkout_summary_tip: 'Courier tip',
  checkout_summary_total: 'Total',
  checkout_summary_free: 'Free',
  checkout_place_order: 'Place order',
  checkout_place_order_pending: 'Place order will be available in the next step.',
  checkout_place_order_success: 'Order placed successfully.',
  checkout_place_order_error: 'Unable to place your order right now.',
  order_confirmation_title: 'Order confirmed',
  order_confirmation_number: 'Order #{{number}}',
  order_confirmation_message: '{{store}} has received your order. We’ll keep you updated as it moves.',
  order_confirmation_store_fallback: 'Your store',
  order_confirmation_step_confirmed: 'Confirmed',
  order_confirmation_step_store: 'With the store',
  order_confirmation_step_preparing: 'Preparing',
  order_confirmation_step_scheduled: 'Scheduled',
  order_confirmation_step_delivery: 'Delivery',
  order_confirmation_step_pickup: 'Pickup',
  order_confirmation_eta_label: 'Estimated arrival',
  order_confirmation_ready_label: 'Estimated ready time',
  order_confirmation_eta_pending: 'Updating shortly',
  order_confirmation_minutes: '{{estimate}} min',
  order_confirmation_order_from: 'Order from',
  order_confirmation_track: 'Track order',
  order_confirmation_receipt: 'View receipt',
  order_confirmation_help: 'Get help',
  order_confirmation_done: 'Close confirmation',
  checkout_address_required: 'Please choose a delivery address first.',
  checkout_promo_pending: 'Promo code support will be added in the next step.',
  checkout_preview_error_title: 'Unable to load checkout',
  checkout_preview_error_message: 'Please try again in a moment.',
  checkout_preview_updating: 'Updating your total…',
  checkout_store_closed_title: 'Store is closed',
  checkout_store_closed_message:
    'This store is currently closed. Please try again during its opening hours.',
  checkout_payment_wallet_title: 'Wallet',
  checkout_payment_wallet_subtitle: 'Pay using your wallet balance',
  checkout_payment_option_wallet_description:
    'Pay securely using your wallet balance.',
  checkout_payment_wallet_insufficient_balance:
    'Insufficient wallet balance for this order.',
  checkout_payment_wallet_balance: 'Wallet balance: {{currency}} {{amount}}',


  cart_empty_title: 'Your cart is empty',
  cart_empty_message: 'When you add items from a store, your order will be right here so you can make changes whenever you want.',
  cart_start_shopping: 'Start shopping',
  cart_error_title: 'Could not load your cart',
  cart_error_message: 'Please try again in a moment.',
  cart_remove_item: 'Remove item',
  cart_decrement_item: 'Decrease quantity',
  cart_increment_item: 'Increase quantity',
  cart_info_label: 'Order fees and minimum spend',
  cart_low_order_fee_applies_prefix: 'A ',
  cart_low_order_fee_applies_suffix: ' low-order fee applies',
  cart_fee_modal_title: 'Order fees & minimum spend',
  cart_fee_modal_description_prefix: 'The minimum spend is ',
  cart_fee_modal_description_suffix: ' total cart value.',
  cart_fee_modal_total_cart_value: 'Total cart value',
  cart_fee_modal_service_fee: 'Service fee',
  cart_fee_modal_above: '& above',
  cart_fee_modal_no_fee: 'No Fee',
  cart_fee_modal_note_prefix: '* For orders less than ',
  cart_fee_modal_note_middle: ' a small order fee of ',
  cart_fee_modal_note_suffix: ' applies',
  cart_store_conflict_title: 'Replace your current cart?',
  cart_store_conflict_message:
    'Your cart already has items from another store. Replace it to add items from {{incomingStore}}.',
  cart_store_conflict_message_with_product:
    'Your cart already has items from another store. Replace it to add {{product}} from {{incomingStore}}.',
  cart_store_conflict_keep_cart: 'Keep current cart',
  cart_store_conflict_replace_cart: 'Replace cart',
  cart_store_conflict_store_fallback: 'this store',
  cart_action_loading_options_title: 'Preparing options',
  cart_action_loading_options_message:
    'Please wait while we load the available customizations for this item.',
  cart_action_customization_required_title: 'Choose your options first',
  cart_action_customization_required_message:
    'Please review the product options before adding this item to your cart.',
  cart_action_out_of_stock_title: 'Item unavailable',
  cart_action_out_of_stock_message:
    'This item is currently out of stock. Please try another item.',
  cart_network_error_title: 'Connection issue',
  cart_network_error_message:
    'Please check your internet connection and try again.',
  cart_add_success_title: 'Added to cart',
  cart_add_success_message: '{{quantity}} × {{product}} is ready in your cart.',
  cart_add_success_go_to_cart: 'Go to cart',
  cart_add_success_continue_shopping: 'Continue shopping',
  cart_add_error_title: 'Could not add item',
  cart_add_error_message: 'Please try again in a moment.',
  cart_update_success_title: 'Cart updated',
  cart_update_success_message: 'Your cart quantity has been updated.',
  cart_update_error_title: 'Could not update cart',
  cart_update_error_message: 'Please try updating your cart again.',
  cart_remove_success_title: 'Item removed',
  cart_remove_success_message: 'The item has been removed from your cart.',
  cart_remove_error_title: 'Could not remove item',
  cart_remove_error_message: 'Please try removing the item again.',
  cart_clear_action: 'Clear cart',
  cart_clear_popup_title: 'Clear your cart?',
  cart_clear_popup_message:
    'This will remove all items from your current cart so you can start fresh.',
  cart_clear_popup_confirm: 'Clear cart',
  cart_clear_popup_cancel: 'Cancel',
  cart_clear_error_title: 'Could not replace cart',
  cart_clear_error_message: 'Please try again in a moment.',
  free: 'Free',
  store_card_new: 'New',
  store_card_delivery_fee_unavailable: '{{currency}} —',
  store_card_delivery_time_unavailable: 'ETA —',
  store_card_distance_unavailable: '— km',
  product_info_back: 'Back',
  product_info_share: 'Share product',
  product_info_unavailable: 'Currently unavailable',
  product_info_error_title: "Couldn't load product",
  orders_tab_active: 'Active',
  orders_tab_history: 'Past',
  orders_tab_scheduled: 'Scheduled',
  orders_history_active_heading: 'Active orders',
  orders_empty_active_title: 'No active orders yet',
  orders_empty_active_subtitle: 'Your active orders will appear here once you place one.',
  orders_empty_history_title: 'No orders yet',
  orders_empty_history_subtitle: 'You haven’t made any order. It will show here when you made one.',
  orders_empty_history_cta: 'Start shopping',
  orders_empty_scheduled_title: 'No schedule deliveries yet',
  orders_empty_scheduled_subtitle: 'You haven’t schedule any order.',
  orders_history_ongoing_heading: 'Ongoing order',
  orders_history_past_heading: 'Past orders',
  orders_history_scheduled_heading: 'Scheduled orders',
  orders_list_load_more: 'Load more',
  orders_list_no_more_items: 'No more items',
  orders_list_error: 'Unable to load scheduled deliveries right now.',
  orders_list_retry: 'Try again',
  orders_status_upcoming: 'Upcoming',
  orders_status_ongoing: 'Ongoing',
  orders_status_scheduled: 'Scheduled',
  orders_status_received: 'Order received',
  orders_status_confirmed: 'Confirmed',
  orders_status_preparing: 'Preparing your order',
  orders_status_ready: 'Ready for pickup',
  orders_status_courier_assigned: 'Courier assigned',
  orders_status_on_the_way: 'On the way',
  orders_status_arrived: 'Courier arrived',
  orders_status_delayed: 'Delivery delayed',
  orders_status_delivered: 'Order Delivered',
  orders_status_cancelled: 'Order Cancelled',
  orders_status_rejected: 'Order declined',
  orders_status_failed: 'Order could not be completed',
  orders_screen_title: 'Orders',
  orders_screen_subtitle: 'Follow what is in motion or revisit a past delivery.',
  orders_view_details: 'View details',
  order_cancel_title: 'Cancel order?',
  order_cancel_message: 'Paid orders will be refunded to your wallet.',
  order_cancel_keep: 'Keep order',
  order_cancel_confirm: 'Cancel order',
  order_cancel_failed: 'Unable to cancel order',
  order_details_title: 'Order details',
  order_details_error_title: 'Unable to load this order right now.',
  order_details_status: 'Order status',
  order_details_progress: 'Delivery progress',
  order_details_scheduled_for: 'Scheduled for',
  order_details_items: 'Order items',
  order_details_summary: 'Order summary',
  order_details_payment_details: 'Payment details',
  order_details_payment_method: 'Payment method',
  order_details_paid: 'Paid',
  order_details_unavailable: 'Unavailable',
  order_details_reference: 'Order #{{number}}',
  order_details_get_help: 'Get help',
  order_details_order_number: 'Order number',
  order_details_delivery_address: 'Delivery address',
  order_details_item_subtotal: 'Item subtotal',
  order_details_discount: 'Discount',
  order_details_tax: 'Tax',
  order_details_packing_charges: 'Packing charges',
  order_details_delivery_fee: 'Delivery',
  order_details_courier_tip: 'Courier tip',
  order_details_total_amount: 'Total amount',
  order_details_rate_order: 'Rate the order',
  order_details_view_rating: 'View your rating',
  order_details_increase_tip: 'Increase the tip',
  order_details_track_progress: 'Track progress',
  order_details_order_again: 'Order again',
  order_details_notes: 'Notes',
  order_details_restaurant_note: 'Restaurant note',
  order_details_courier_note: 'Courier note',
  order_again_error_title: 'Could not reorder items',
  order_again_error_message: 'Please try ordering these items again in a moment.',
  order_again_partial_title: 'Some items need attention',
  order_details_tip_done: 'Done',
  order_details_tip_placeholder: '0.00',
  order_details_empty_items: 'No items',
  order_details_quantity_one: 'Qty {{count}}',
  order_tracking_title: 'Your order',
  order_tracking_help: 'Order tracking help',
  order_tracking_eta_label: 'Estimated delivery time',
  order_tracking_eta_pending: 'Updating shortly',
  order_tracking_eta_short_confirming: 'Confirm',
  order_tracking_eta_short_preparing: 'Prep',
  order_tracking_eta_short_on_way: 'On way',
  order_tracking_eta_short_nearby: 'Near',
  order_tracking_eta_short_delivered: 'Done',
  order_tracking_eta_short_ended: 'Ended',
  order_tracking_eta_short_updating: 'Soon',
  order_tracking_until_delivered: 'until delivered',
  order_tracking_eta_remaining: 'remaining',
  order_tracking_estimated_arrival: 'Estimated arrival {{time}}',
  order_tracking_close: 'Close order tracking',
  order_tracking_recenter_map: 'Recenter map',
  order_tracking_route_loading: 'Finding the best route…',
  order_tracking_route_unavailable: 'Live route unavailable',
  order_tracking_route_unavailable_description: 'Live locations remain visible while the road route updates.',
  order_tracking_route_pending: 'Route updates will appear here',
  order_tracking_route_pending_description: 'The route will draw as soon as both locations are available.',
  order_tracking_location_unavailable: 'Live map unavailable',
  order_tracking_location_unavailable_description: 'Your order updates are still available below.',
  order_tracking_progress: 'Delivery progress',
  order_tracking_next_step: 'Next: {{step}}',
  order_tracking_no_next_step: 'No further steps',
  order_tracking_delay_next: 'We’ll keep you updated',
  order_tracking_order_items: 'Order items',
  order_tracking_courier_role: 'Your courier',
  order_tracking_courier_pending: 'Courier details are updating',
  order_tracking_message_courier: 'Message courier',
  order_tracking_delivered_title: 'Delivered',
  order_tracking_delivered_message_line_one: 'Your order has been delivered.',
  order_tracking_delivered_message_line_two: 'Enjoy your meal!',
  order_tracking_error_title: 'Unable to load tracking right now.',
  order_tracking_delivery_details: 'Delivery details',
  order_tracking_collection_details: 'Collection details',
  order_tracking_contact_title: 'Contact your courier',
  order_tracking_contact_subtitle: 'Ask for contactless delivery',
  order_tracking_courier_fallback: 'Courier',
  order_tracking_summary: 'Summary',
  order_tracking_summary_note: 'incl. taxes (if applicable)',
  order_tracking_unavailable_title: 'Order not confirmed',
  order_tracking_unavailable_description:
    'The store was unable to confirm your order, so it has been cancelled. You can place it again or choose another store nearby.',
  order_tracking_unavailable_cancelled_description:
    'This order has been cancelled, so there is nothing left to track. You can place it again or choose another store nearby.',
  order_tracking_unavailable_action: 'Back to home',
  // Wallet
  wallet_title: 'Wallet',
  wallet_balance_label: 'Wallet balance',
  wallet_loyalty_total_points: 'Total loyalty points earned',
  wallet_loyalty_rate: '{{points}} points = {{currency}} 1',
  wallet_loyalty_amount: 'Wallet balance earned from loyalty',
  wallet_convert_points_title: 'Convert loyalty points',
  wallet_points_available: '{{points}} points available',
  wallet_points_input: 'Points to convert',
  wallet_points_receive: 'You will receive {{currency}} {{amount}}',
  wallet_convert_points_action: 'Add to wallet',
  wallet_points_converted_title: 'Points converted',
  wallet_points_converted_message: '{{currency}} {{amount}} was added to your wallet.',
  wallet_points_convert_error: 'Unable to convert points',
  wallet_cards_title: 'Cards',
  wallet_secure: 'Secure',
  wallet_default_card: 'Default',
  wallet_add_card: 'Add debit/credit card',
  wallet_topup_title: 'Add money',
  wallet_topup_amount: 'Enter amount',
  wallet_topup_action: 'Add to wallet',
  wallet_topup_card_required: 'Add a card before topping up',
  wallet_topup_success: 'Payment successful',
  wallet_topup_pending: 'Your wallet balance will update after payment confirmation.',
  wallet_topup_error: 'Unable to add money',
  wallet_recent_transactions: 'Recent Transactions',
  wallet_transactions_empty_title: 'No transactions yet',
  wallet_transactions_empty_description: 'Your wallet activity will appear here once you make a payment or refund.',
  wallet_transactions_error: 'We could not load your wallet activity. Tap to try again.',
  wallet_see_all: 'See all',
  wallet_add_card_title: 'Add card',
  wallet_name_on_card: 'Name on card',
  wallet_name_placeholder: 'Add card holder full name',
  wallet_card_number_label: 'Card number',
  wallet_card_secure_title: 'Your card details stay protected',
  wallet_card_secure_description: 'Payment details are encrypted and handled securely by Stripe.',
  wallet_card_number_placeholder: 'Credit or debit card number',
  wallet_expiry_label: 'Expiry date',
  wallet_security_code_label: 'Security code',
  wallet_pay_securely: 'Pay securely with',
  wallet_save_card: 'Save',
  wallet_no_saved_cards: 'No saved cards yet',
  wallet_cards_error: 'Unable to load saved cards. Tap to try again.',
  wallet_add_card_error: 'Unable to save card',
  wallet_setup_intent_success_title: 'Card setup started',
  wallet_setup_intent_success_message:
    'Setup intent created. Complete the card confirmation flow with Stripe SDK.',
  wallet_stripe_publishable_key_missing: 'Stripe publishable key is missing.',
  wallet_card_incomplete: 'Please complete card details.',
  wallet_card_saved_success_title: 'Card saved',
  wallet_card_saved_success_message: 'Your card was added successfully.',
  off: 'off',
};

export default en;
