const es = {
  "shop_type_grocery": "Supermercado",
  "shop_type_restaurant": "Restaurante",
  "shop_type_browse_action": "Explorar",
  "shop_type_browse_accessibility": "Explorar {{name}}",
  "promotional_banner": "banner promocional",
  "store_menu_all_categories": "Todas las categorías",
  "store_menu_page_error": "No podía cargar estos elementos. Revise su conexión e intente de nuevo.",
  "store_menu_refresh_error": "No podía refrescar el menú. Sus artículos actuales todavía están disponibles.",
  "store_menu_search_hint": "Escribe al menos 2 caracteres para buscar en este restaurante.",
  "store_menu_search_loading": "Buscando este restaurante...",
  "store_menu_search_empty": "No hay artículos iguales. Prueba otro nombre o ingrediente.",
  "store_menu_search_error": "La búsqueda no podía cargar. Revise su conexión e intente de nuevo.",
  "store_menu_no_section_items": "Actualmente no hay artículos disponibles en esta sección.",
  "label": "Entrega",
  "description": "Ordenar desde tiendas o vendedores.",
  "header_title": "Entrega",
  "header_subtitle": "Elija un tipo de entrega",
  "hero_badge": "Experiencia de demostración",
  "hero_subtitle": "Cambiar entre los modelos de entrega y previsualizar la experiencia completa bellamente.",
  "hero_pill_fast": "Cambio de modo rápido",
  "hero_pill_flexible": "Prueba todos los flujos de entrega",
  "section_title": "Elija su modo",
  "single_vendor_title": "Vendedor único",
  "single_vendor_desc": "Orden de tu tienda preferida.",
  "single_vendor_chip": "Tienda curada",
  "single_vendor_stat": "Una tienda enfocada",
  "multi_vendor_title": "Múltiples tiendas",
  "multi_vendor_desc": "Examinar y ordenar desde múltiples tiendas.",
  "multi_vendor_chip": "Mercado",
  "multi_vendor_stat": "Muchos proveedores en un solo lugar",
  "chain_title": "Cadena",
  "chain_desc": "Orden de tus cadenas favoritas.",
  "chain_chip": "Red de marcas",
  "chain_stat": "Menús de cadena y ubicaciones",
  "explore_button": "Explorar",
  "details_title": "Detalles de entrega",
  "single_vendor_categories_title": "Categorías",
  "single_vendor_category_products_empty": "No se han encontrado productos para esta categoría.",
  "single_vendor_home_subtitle": "Tu tienda preferida",
  "single_vendor_home_body": "Explora proveedores y servicios aquí.",
  "single_vendor_tab_home": "Inicio",
  "single_vendor_tab_search": "Búsqueda",
  "single_vendor_tab_orders": "Órdenes",
  "single_vendor_tab_profile": "Perfil",
  "single_vendor_tab_search_placeholder": "Los resultados de búsqueda y las herramientas de descubrimiento aparecerán aquí pronto.",
  "single_vendor_tab_orders_placeholder": "Sus órdenes de un solo vendedor aparecerán aquí pronto.",
  "single_vendor_logout_error_title": "Error",
  "single_vendor_logout_error_message": "Incapaz de salir ahora mismo.",
  "multi_vendor_home_subtitle": "Navegar múltiples tiendas",
  "multi_vendor_home_body": "Descubrir y ordenar desde múltiples proveedores.",
  "multi_vendor_home_greeting_morning": "Buenos días ‹",
  "multi_vendor_home_greeting_afternoon": "Buenas tardes ‹",
  "multi_vendor_home_greeting_evening": "Buenas tardes",
  "delivery_home_greeting_morning": "Buenos días.",
  "delivery_home_greeting_afternoon": "Buenas tardes.",
  "delivery_home_greeting_evening": "Buenas noches.",
  "delivery_home_title": "Todo lo que necesitas, entregado.",
  "delivery_home_subtitle": "Explore tiendas cercanas, comidas frescas y elementos esenciales cotidianos.",
  "delivery_home_search_placeholder": "Buscar tiendas o comida",
  "multi_vendor_tab_home": "Inicio",
  "multi_vendor_tab_search": "Búsqueda",
  "multi_vendor_tab_orders": "Órdenes",
  "multi_vendor_tab_profile": "Perfil",
  "chain_tab_home": "Inicio",
  "chain_tab_search": "Búsqueda",
  "chain_tab_orders": "Órdenes",
  "chain_tab_profile": "Perfil",
  "chain_logout_error_title": "Error",
  "chain_logout_error_message": "Incapaz de salir ahora mismo.",
  "chain_categories_title": "Categorías",
  "chain_category_products_empty": "No se han encontrado productos para esta categoría.",
  "chain_menu_template_selector_label": "Seleccionar menú de cadena",
  "chain_menu_template_loading": "Cargando menús",
  "chain_menu_template_empty": "Sin menús",
  "chain_menu_template_unavailable": "Menú no disponible",
  "delivery_address_title": "Dirección de entrega",
  "delivery_address_empty_state": "Añadir una dirección para empezar a pedir desde esta tienda.",
  "logout": "A ver.",
  "multi_vendor_address_label": "Seleccionar dirección",
  "delivery_header_deliver_to": "Entrega",
  "multi_vendor_shop_types_title": "Tipos de tienda",
  "home_all_stores": "Todas las tiendas",
  "home_store_count": "{{count}} tiendas para explorar",
  "home_store_count_one": "{{count}} tienda para explorar",
  "home_store_count_other": "{{count}} tiendas para explorar",
  "home_store_list_subtitle": "Encuentra algo bueno cerca.",
  "home_no_nearby_stores_title": "Tu barrio está creciendo",
  "home_no_nearby_stores_message": "Explore todas las tiendas mientras encontremos más cerca de esta dirección.",
  "home_no_deals_title": "Las ofertas frescas están en camino",
  "home_no_deals_message": "Revise pronto para algo que valga la pena descubrir.",
  "home_no_shop_type_stores_title": "No hay tiendas en esta colección todavía",
  "deals_page_title": "Buen hallazgo, mejores precios.",
  "deals_page_description": "Explora ofertas sobre las cosas que amas.",
  "deals_page_empty_title": "No hay ofertas aquí todavía",
  "deals_page_empty_description": "Pruebe otra búsqueda o revise pronto para ofertas frescas.",
  "multi_vendor_main_shop_types_title": "Envíos",
  "multi_vendor_categories_title": "Categorías",
  "multi_vendor_top_brands_title": "Marcas destacadas",
  "multi_vendor_all_brands_title": "Todas las marcas",
  "multi_vendor_search_brands_placeholder": "Marcas de búsqueda",
  "multi_vendor_nearby_store_title": "Tiendas cercanas",
  "multi_vendor_home_quick_browse": "Todas las tiendas",
  "multi_vendor_home_quick_deals": "Tratos",
  "multi_vendor_home_quick_orders": "Orden de nuevo",
  "multi_vendor_home_quick_favourites": "Favoritos",
  "multi_vendor_deals_title": "Tratos",
  "multi_vendor_recommended_restaurants_title": "Restaurantes recomendados",
  "deals_see_all_tab_all": "Todos",
  "deals_see_all_tab_limited": "Ofertas de tiempo limitado",
  "deals_see_all_tab_weekly": "Tratos semanales",
  "deals_see_all_ends_in": "Finales en",
  "deals_see_all_section_title": "Explore todas las ofertas",
  "deals_see_all_section_title_limited": "Terminará pronto",
  "deals_see_all_section_title_weekly": "Ofertas de esta semana",
  "deals_see_all_badge_percentage": "{{value}} % de descuento",
  "deals_see_all_badge_fixed": "{{value}} apagado",
  "multi_vendor_order_again_title": "Orden de nuevo 😋",
  "main see all": "Ver todo",
  "multi_vendor_see_all": "Ver todo",
  "multi_vendor_order_again_add_item": "Añadir artículo",
  "multi_vendor_order_again_price_unavailable": "Precio no disponible",
  "multi_vendor_nearby_store_name_hardees": "Hardee's - Z Block",
  "multi_vendor_nearby_store_name_subway": "Subway - Z Block",
  "multi_vendor_nearby_store_category_fast_food": "Comida rápida",
  "multi_vendor_nearby_store_category_pure_veg": "Puro veg",
  "multi_vendor_nearby_store_review_count": "(5000+)",
  "multi_vendor_nearby_store_delivery_fee": "$2",
  "multi_vendor_nearby_store_delivery_time": "30 minutos",
  "multi_vendor_nearby_store_distance": "1,7 km",
  "multi_vendor_sponsored_label": "Patrocinado",
  "multi_vendor_cart_label": "Carrito",
  "multi_vendor_shop_type_gift": "Entrega de regalos",
  "multi_vendor_shop_type_milk": "Entrega de leche",
  "multi_vendor_shop_type_flower": "Entrega de flores",
  "multi_vendor_shop_type_liquor": "Entrega de bebidas",
  "multi_vendor_shop_type_products_empty": "No hay productos encontrados para este tipo de tienda.",
  "multi_vendor_shop_type_stores_empty": "No hay tiendas encontradas para este tipo de tienda.",
  "multi_vendor_shop_types_empty": "No hay tipos de tiendas de reparto disponibles ahora mismo.",
  "multi_vendor_location_stores_empty": "No hay tiendas disponibles para esta ubicación.",
  "multi_vendor_shop_type_products_error": "Incapaz de cargar productos ahora mismo.",
  "multi_vendor_shop_type_stores_error": "Incapaz de cargar tiendas ahora mismo.",
  "multi_vendor_home_section_empty_title": "No hay coincidencias ahora mismo",
  "multi_vendor_home_section_empty_message": "Recetas frescas y ofertas de tiempo limitado aparecerán aquí tan pronto como estén disponibles.",
  "multi_vendor_home_section_error_title": "Incapaz de cargar elementos",
  "multi_vendor_home_section_error_message": "Por favor, intente de nuevo en un momento.",
  "multi_vendor_home_section_empty_order_again": "Sus recientes elecciones aparecerán aquí después de su primer pedido.",
  "multi_vendor_home_empty_order_again_title": "¿Listo para un nuevo favorito?",
  "multi_vendor_home_empty_explore_action": "Explore tiendas",
  "multi_vendor_home_empty_order_action": "Explora ahora",
  "store_details_search_placeholder": "Menú de búsqueda...",
  "store_details_hero_title": "Hacer A\nComida.",
  "store_details_store_name": "Subway @ Ciudad Vieja, Nuevo México",
  "store_details_store_phone": "555-0123",
  "store_details_store_email": "support@subway.com",
  "store_details_store_hours": "9 AM a 6 PM",
  "store_details_call_label": "Llámanos",
  "store_details_email_label": "o correo electrónico",
  "store_details_tab_pizza": "Pizza",
  "store_details_tab_burgers": "Hamburguesas",
  "store_details_tab_pasta": "Pasta",
  "store_details_tab_sushi": "Sushi",
  "store_details_subcategory_italian_classic": "Clásico italiano",
  "store_details_subcategory_american_style": "Estilo americano",
  "store_details_subcategory_pepperoni": "Pepperoni",
  "store_details_subcategory_bbq_chicken": "Pollo BBQ",
  "store_details_subcategory_thin_crust": "Masa fina",
  "store_details_all_offered_items": "Todos los artículos ofrecidos",
  "store_details_no_items": "Todavía no hay elementos que coincidan con este filtro.",
  "store_details_load_error": "Incapaz de cargar detalles de la tienda ahora mismo.",
  "store_details_hours_unavailable": "Horas no disponibles",
  "store_details_store_missing": "Los detalles de la tienda no están disponibles.",
  "store_details_action_info": "Información de la tienda",
  "store_details_action_favorite": "Añadir tienda a favoritos",
  "store_details_action_remove_favorite": "Quitar la tienda de favoritos",
  "store_details_action_share": "Compartir tienda",
  "store_details_action_back": "Vuelve.",
  "store_details_about_title": "Sobre nosotros",
  "store_details_about_fallback": "La descripción de la tienda no está disponible ahora mismo.",
  "store_details_closed_store_title": "{{storeName}} está actualmente cerrado",
  "store_details_closed_store_description": "{{storeName}} actualmente no está abierto. Por favor, intente de nuevo más tarde.",
  "store_details_closed_store_fallback_name": "Esta tienda",
  "store_closed_modal_title": "{{storeName}} está actualmente cerrado",
  "store_closed_see_menu": "Ver menú",
  "store_status_closed": "Cerrado",
  "store_status_open": "Abierto",
  "store_details_delivery_minutes": "{{minutes}} min",
  "store_details_minimum_order": "Mín. {{amount}}",
  "store_details_close": "Cerca",
  "store_details_info_address": "Dirección: {{address}}",
  "store_details_info_phone": "Teléfono: {{phone}}",
  "store_details_info_email": "Correo electrónico: {{email}}",
  "store_details_view_cart": "Ver carrito",
  "store_details_cart_summary": "{{count}} artículos · {{amount}}",
  "store_details_add_product": "Añadir {{item}}",
  "store_details_badge_deal": "Trato hecho",
  "store_details_badge_ten_percent_off": "10% de descuento",
  "store_details_item_chicken_fajita": "Fajita de pollo",
  "store_details_item_chicken_teriyaki": "Pollo teriyaki",
  "store_details_item_burger": "Hamburguesa",
  "store_details_item_sushi": "Sushi",
  "store_details_item_alfredo_pasta": "Pasta Alfredo",
  "store_details_item_veggie_delight": "Delicia vegetariana",
  "chain_home_subtitle": "Cadenas favoritas",
  "chain_home_body": "Orden de tus cadenas favoritas.",
  "type_single_vendor_title": "Tienda de un solo vendedor",
  "type_single_vendor_desc": "Vendedores premium a mano sólo",
  "type_marketplace_title": "Mercado",
  "type_marketplace_desc": "Amplia comunidad de proveedores locales",
  "type_chain_title": "Cadenas de tiendas",
  "type_chain_desc": "Compra tus cadenas favoritas",
  "profile_personal_account": "Cuenta personal",
  "profile_wallet_balance": "Saldo de cartera",
  "profile_view_wallet": "Ver cartera",
  "profile_menu_profile": "Perfil",
  "profile_menu_notifications": "Notificaciones",
  "profile_menu_favorites": "Favoritos",
  "profile_menu_coupons": "Cupones",
  "profile_menu_settings": "Ajustes",
  "profile_menu_support": "Apoyo",
  "profile_menu_color_mode": "Aplicación modo de color",
  "profile_menu_language": "Inglés",
  "profile_menu_logout": "A ver.",
  "coupon_title": "Cupones",
  "coupon_active": "Activo",
  "coupon_claim_label": "Añadir un código de promo",
  "coupon_description": "Si tiene un código promocional de entrega de alimentos, código de referencia o tarjeta de regalo, ingrese aquí para reclamar sus beneficios.",
  "coupon_input_placeholder": "Introduzca el código",
  "coupon_use": "Uso",
  "coupon_off": "Fuera.",
  "coupon_valid_until": "Válido: {{date}}",
  "coupon_claim": "Reclamación",
  "coupon_claim_success_title": "Cupón añadido",
  "coupon_claim_error_title": "Incapaz de reclamar cupón",
  "coupon_claim_error_fallback": "Por favor, introduzca un código válido e inténtelo de nuevo.",
  "coupon_list_error_fallback": "Incapaz de cargar cupones reclamados ahora mismo.",
  "coupon_used": "Usado",
  "coupon_use_success_title": "Cupón activado",
  "coupon_use_success_message": "Ahora puedes usar esto.",
  "coupon_use_error_title": "Incapaz de activar el cupón",
  "coupon_use_error_fallback": "Por favor, inténtalo de nuevo.",
  "coupon_deactivate": "Desactivar",
  "coupon_deactivate_success_title": "Coupon desactivado",
  "coupon_deactivate_success_message": "Este promo ya no está activo.",
  "coupon_deactivate_error_title": "No se puede desactivar el cupón",
  "coupon_deactivate_error_fallback": "Por favor, inténtalo de nuevo.",
  "coupon_status_expired": "Gastos",
  "coupon_min_order": "Pedido mín. {{currency}} {{value}}",
  "coupon_store_fallback": "Tienda asociada",
  "coupon_store_with_more": "{{store}} y {{count}} más",
  "coupon_claimed_state_title": "¡Tienes el Cupón!",
  "coupon_claimed_state_body_line_one": "¡Hurra! Tu código promo se ha aplicado.",
  "coupon_claimed_state_body_line_two": "El descuento aparecerá automáticamente en el checkout.",
  "coupon_empty_title": "No hay cupones todavía",
  "coupon_empty_description": "No tienes cupones ahora mismo. Ingrese un código de promoción arriba para encontrar ofertas.",
  "my_profile_title": "Mi perfil",
  "my_profile_edit": "Editar",
  "my_profile_full_name": "Nombre completo",
  "my_profile_date_of_birth": "Fecha de nacimiento",
  "my_profile_mobile_number": "Número de móvil",
  "my_profile_email": "Correo electrónico",
  "my_profile_my_addresses": "Mis direcciones",
  "my_profile_add_address": "Agregar dirección",
  "my_profile_address_home": "Inicio",
  "my_profile_address_apartment": "Apartamento",
  "my_profile_address_work": "Trabajo",
  "my_profile_address_other": "Otros",
  "photo_modal_title": "Perfil Foto",
  "photo_modal_description": "Elige cómo quieres actualizar tu foto de perfil",
  "photo_take_photo": "Tomar foto",
  "photo_choose_gallery": "Elija de la galería",
  "photo_cancel": "Cancelar",
  "photo_permission_title": "Permiso requerido",
  "photo_permission_camera": "El acceso a la cámara es necesario para tomar una foto.",
  "photo_permission_gallery": "El acceso a la galería es necesario para elegir una foto.",
  "photo_upload_error_title": "Subir Failed",
  "photo_upload_failed": "No podía actualizar la foto del perfil.",
  "edit_profile_title": "Perfil de edición",
  "edit_profile_name": "Nombre",
  "edit_profile_date_of_birth": "Fecha de nacimiento",
  "edit_profile_day": "Día",
  "edit_profile_month": "Mes",
  "edit_profile_year": "Año",
  "edit_profile_gender": "Género",
  "edit_profile_gender_placeholder": "Seleccione la opción",
  "edit_profile_save": "Guardar",
  "edit_profile_success": "El éxito",
  "edit_profile_success_message": "Perfil actualizado con éxito.",
  "edit_profile_error": "Error",
  "edit_profile_name_required": "Se requiere nombre.",
  "edit_profile_failed": "No podía actualizar el perfil.",
  "address_list_title": "Mis direcciones",
  "address_add_title": "Agregar dirección",
  "address_edit_title": "Dirección de edición",
  "address_search_placeholder": "Buscar una dirección",
  "address_choose_on_map": "Elija en el mapa",
  "address_recent_searches": "Búsquedas recientes",
  "address_no_results": "No se han encontrado resultados",
  "address_confirm_location": "Confirme ubicación",
  "address_locating": "Localizando...",
  "address_selected_location": "Ubicación seleccionada",
  "address_location_name_placeholder": "Nombre de ubicación (por ejemplo, mi casa)",
  "address_details_label": "Detalles de la dirección",
  "address_location_type_label": "Tipo de ubicación",
  "address_location_details_label": "Detalles de la ubicación",
  "address_detail_house_placeholder": "Casa",
  "address_detail_apartment_placeholder": "Apartamento / Apartamento",
  "address_detail_office_placeholder": "Oficina / Edificio",
  "address_detail_place_placeholder": "Lugar",
  "address_detail_society_placeholder": "Urbanización",
  "address_detail_floor_placeholder": "Planta / Torre",
  "address_detail_department_placeholder": "Departamento / Planta",
  "address_detail_area_placeholder": "Zona / calle",
  "address_detail_landmark_placeholder": "Punto de referencia",
  "address_optional_suffix": "(opcional)",
  "address_type_home": "Inicio",
  "address_type_apartment": "Apartamento",
  "address_type_office": "Oficina",
  "address_type_other": "Otros",
  "address_save": "Guardar la dirección",
  "address_update": "Dirección de actualización",
  "address_delete": "Suprimir",
  "address_delete_confirm_title": "Suprímase la dirección",
  "address_delete_confirm_message": "¿Estás seguro de que quieres borrar esta dirección?",
  "address_delete_cancel": "Cancelar",
  "address_delete_confirm": "Suprimir",
  "address_save_error": "No podía salvar la dirección.",
  "address_select_error": "No podía seleccionar la dirección.",
  "address_delete_error": "No podía borrar la dirección.",
  "address_save_success": "Dirección guardada con éxito.",
  "address_update_success": "Dirección actualizada con éxito.",
  "address_delete_success": "Dirección eliminada con éxito.",
  "address_selector_title": "Ubicación",
  "address_selector_close": "Buscador de ubicación cercana",
  "address_selector_use_current_location": "Use mi ubicación actual",
  "address_selector_add_new": "Agregar nueva dirección",
  "favourites_title": "Tus Favoritos",
  "favourites_subtitle": "Tus tiendas salvas, listas cuando estés.",
  "favourites_empty_title": "Todavía no hay favoritos",
  "favourites_empty_subtitle": "Toca el corazón en cualquier tienda para mantenerlo cerca la próxima vez.",
  "favourites_error_title": "No podía cargar favoritos",
  "favourites_error": "Revise su conexión e intente de nuevo.",
  "favourites_retry": "Inténtalo de nuevo.",
  "favourites_free_delivery": "Entrega gratuita",
  "favourites_remove": "Quitar de los favoritos",
  "favourites_add": "Añadir a favoritos",
  "favourites_toggle_added": "Añadido a los favoritos",
  "favourites_toggle_removed": "Retirado de favoritos",
  "favourites_toggle_error": "Failed to update favorites",
  "rate_order_title": "Vota tu orden",
  "rate_order_heading": "¿Cómo fue tu comida?",
  "rate_order_subheading": "Su opinión nos ayuda a mejorar nuestra entrega.",
  "rate_order_comment_placeholder": "Escribe tu experiencia aquí...",
  "rate_order_submit": "Enviar",
  "rate_order_submitted_heading": "¡Gracias por tu calificación!",
  "rate_order_submitted_subheading": "Ya has calificado esta orden. Su opinión nos ayuda a mejorar nuestra entrega.",
  "rate_order_submitted_no_comment": "No se añadió ningún comentario a esta valoración.",
  "rate_order_success_title": "¡Gracias!",
  "rate_order_success_message": "Su revisión ha sido presentada.",
  "rate_order_error_title": "La comunicación falló",
  "settings_title": "Ajustes",
  "settings_notifications": "Ajustes de notificación",
  "settings_change_password": "Cambiar contraseña",
  "settings_privacy_policy": "Política de privacidad",
  "settings_terms_of_service": "Términos de servicio",
  "settings_terms_of_use": "Términos de uso",
  "settings_delete_account": "Suprimir la Cuenta",
  "settings_app_version": "Versión 1.0.0",
  "notif_settings_title": "Ajustes de notificación",
  "notif_settings_food_delivery": "Entrega de alimentos",
  "notif_settings_marketing": "Marketing",
  "notif_settings_email": "Correo electrónico",
  "notif_settings_sms": "SMS",
  "notif_settings_whatsapp": "WhatsApp",
  "notif_settings_success_title": "Guardado",
  "notif_settings_success_message": "Preferencia de notificación actualizada.",
  "notif_settings_error_title": "Error",
  "privacy_title": "Política de privacidad",
  "privacy_last_updated": "Última actualización hace 2 meses",
  "privacy_intro": "Esta política de privacidad explica cómo manejamos su información personal mientras utilizamos la aplicación de entrega de alimentos. Al registrar o acceder a la aplicación, usted acepta las prácticas descritas en esta política.",
  "privacy_section_app_title": "Política de privacidad para la aplicación",
  "privacy_section_app_body": "La aplicación de entrega de alimentos está comprometida a proteger y gestionar sus datos y pedidos personales de forma segura. Está autorizado a utilizar la aplicación para fines personales y empresariales, con sujeción al cumplimiento de esta política y de todas las leyes aplicables.",
  "privacy_section_responsibilities_title": "Responsabilidades del usuario",
  "privacy_section_responsibilities_body": "Los usuarios son responsables de mantener sus direcciones de entrega e información de pago precisa. Es importante mantener actualizada esta información para evitar problemas durante el proceso de pedido.",
  "privacy_section_data_title": "Recopilación de datos",
  "privacy_section_data_body": "La aplicación de entrega de alimentos recopila datos esenciales para mejorar su experiencia, incluyendo su ubicación, historial de pedidos y preferencias.",
  "privacy_section_modifications_title": "Modificaciones de pedidos",
  "privacy_section_modifications_body": "Puede modificar o cancelar sus pedidos a través de la aplicación antes de que sean procesados. Una vez confirmada la orden, los cambios pueden ya no ser posibles.",
  "privacy_section_payment_title": "Garantía de pago",
  "privacy_section_payment_body": "Priorizamos la seguridad de su información de pago. Todas las transacciones realizadas a través de la aplicación se procesan utilizando la tecnología de cifrado estándar.",
  "privacy_section_contact_title": "Contacta con nosotros",
  "privacy_section_contact_body": "Si tiene alguna pregunta sobre estos términos, no dude en ponerse en contacto con nosotros:",
  "privacy_contact_email": "Correo electrónico: contact@fooddelivery.com",
  "privacy_contact_address": "Dirección: Doha, Catar",
  "tos_title": "Términos de servicio",
  "tos_last_updated": "Última actualización hace 2 meses",
  "tos_intro": "Estos términos de servicio definen su acceso a la aplicación de suministro de alimentos y su uso.",
  "tos_section_usage_title": "Uso del servicio",
  "tos_section_usage_body": "La aplicación de entrega de alimentos proporciona una plataforma confiable para hacer pedidos y gestionar sus entregas de comida.",
  "tos_section_orders_title": "Gestión de pedidos",
  "tos_section_orders_body": "La aplicación le permite seguir sus pedidos fácilmente, modificar detalles o cancelarlos dentro del plazo permitido.",
  "tos_section_payment_title": "Garantía de pago",
  "tos_section_payment_body": "Los pagos realizados a través de la aplicación se procesan de forma segura utilizando la tecnología de cifrado.",
  "tos_section_delivery_title": "Políticas de envío",
  "tos_section_delivery_body": "Se alienta a los usuarios a proporcionar direcciones de entrega precisas para apoyar un servicio rápido y eficiente.",
  "tos_section_support_title": "Atención al cliente",
  "tos_section_support_body": "La aplicación proporciona un sistema de soporte robusto para abordar cualquier pregunta o problema.",
  "tos_section_contact_title": "Contacta con nosotros",
  "tos_section_contact_body": "Si tiene alguna pregunta sobre estos términos, no dude en ponerse en contacto con nosotros:",
  "tos_contact_email": "Correo electrónico: contact@fooddelivery.com",
  "tos_contact_address": "Dirección: Doha, Catar",
  "tou_title": "Términos de uso",
  "tou_last_updated": "Actualizado hace 2 meses",
  "tou_intro": "Estos términos de uso definen sus derechos y responsabilidades al utilizar la aplicación.",
  "tou_section_guidelines_title": "Directrices de uso",
  "tou_section_guidelines_body": "La aplicación proporciona una gestión segura de sus pedidos y datos del cliente.",
  "tou_section_etiquette_title": "Etiqueta de entrega",
  "tou_section_etiquette_body": "Los usuarios deben permanecer respetuosos y cortés hacia el personal de entrega.",
  "tou_section_payment_title": "Métodos de pago",
  "tou_section_payment_body": "La aplicación soporta múltiples métodos de pago, incluyendo tarjetas de crédito y carteras digitales.",
  "tou_section_cancellation_title": "Política de cancelación",
  "tou_section_cancellation_body": "Las órdenes pueden ser canceladas dentro de 10 minutos después de ser colocadas.",
  "tou_section_feedback_title": "Opiniones y valoraciones",
  "tou_section_feedback_body": "Se alienta a los usuarios a compartir comentarios sobre su experiencia de entrega.",
  "tou_section_promotions_title": "Ofertas y promociones",
  "tou_section_promotions_body": "La aplicación puede ofrecer promociones y descuentos que están sujetos a condiciones específicas.",
  "tou_section_contact_title": "Contacta con nosotros",
  "tou_section_contact_body": "Si tiene alguna pregunta, no dude en ponerse en contacto con nosotros:",
  "tou_contact_email": "Correo electrónico: contact@fooddelivery.com",
  "tou_contact_address": "Dirección: Doha, Catar",
  "rider_chat_title": "Chat con Rider",
  "rider_chat_subtitle": "Actualizaciones de entrega en vivo",
  "rider_chat_status_online": "Online ahora",
  "rider_chat_eta_label": "{{minutes}} min de distancia",
  "rider_chat_order_label": "Orden {{orderCode}}",
  "rider_chat_help_text": "Compartir notas de recogida o pedir una llamada de llegada.",
  "rider_chat_message_rider_intro": "¡Hola! Estoy en camino con tu orden.",
  "rider_chat_message_user_reply": "Perfecto. Por favor llámame cuando llegues a la puerta.",
  "rider_chat_message_rider_eta": "Claro, te llamaré. Nos vemos en unos minutos de {{minutes}}.",
  "rider_chat_quick_reply_gate": "Llama a la puerta",
  "rider_chat_quick_reply_thanks": "¡Gracias!",
  "rider_chat_quick_reply_here": "Estoy aquí",
  "rider_chat_quick_reply_hello": "Hola.",
  "rider_chat_quick_reply_call_arrive": "Llámame cuando llegues.",
  "rider_chat_quick_reply_where": "¿Dónde estás?",
  "rider_chat_quick_reply_eta": "¿Cuánto tardarás?",
  "rider_chat_input_placeholder": "Entra en tu preocupación...",
  "rider_chat_auto_message": "¿Cómo podemos ayudarle?",
  "rider_chat_auto_time": "8:29 pm",
  "rider_chat_send": "Enviar",
  "rider_chat_send_error": "No podía enviar mensaje.",
  "rider_chat_missing_session_error": "Por favor inicie sesión antes de enviar un mensaje.",
  "rider_chat_missing_receiver_error": "Receptor falta para esta charla.",
  "rider_chat_attachment_permission_title": "Permiso necesario",
  "rider_chat_attachment_permission_message": "Por favor, permita el acceso a la biblioteca de fotos para añadir un accesorio.",
  "rider_chat_attachment_selected_title": "Adjunto seleccionado",
  "rider_chat_attachment_selected_message": "{{fileName}} está listo para adjuntar.",
  "rider_chat_add_attachment": "Añadir adjunto",
  "rider_chat_send_message": "Enviar mensaje",
  "rider_chat_call_action": "Llamar al repartidor",
  "support_title": "Apoyo",
  "support_active_order_eyebrow": "Orden en vivo",
  "support_active_order_track": "Pista y consiga ayuda",
  "support_active_order_accessibility": "{{store}}, {{status}}. Haz un seguimiento y consigue ayuda.",
  "support_topic_faq": "Preguntas frecuentes",
  "support_topic_faq_description": "Encuentre respuestas rápidas sobre pedidos, entrega y su cuenta.",
  "support_issue_prompt": "¿No encontró lo que necesita?",
  "support_issue_select_title": "Por favor elija una opción.",
  "support_issue_placeholder": "Seleccione un tipo de problema",
  "support_retry": "Inténtalo de nuevo.",
  "support_error_title": "No podíamos cargar esto ahora mismo",
  "support_error_description": "Revise su conexión e intente de nuevo. Tu historial de apoyo es seguro.",
  "support_tickets_empty_title": "No not reported issues",
  "support_tickets_empty_description": "Cuando usted reporte un problema, su progreso y respuestas aparecerán aquí.",
  "support_chat_closed_title": "Esta conversación está cerrada.",
  "support_chat_closed_description": "Puede revisar los mensajes anteriores o iniciar una nueva solicitud de soporte.",
  "support_issue_order": "Ya tengo una cuenta de negocio y necesito apoyo",
  "support_issue_payment": "Estoy interesado en unirse a la entrega de alimentos como un negocio",
  "support_issue_delivery": "He reservado un pedido con un negocio en la entrega de alimentos",
  "support_issue_account": "Necesito ayuda con otra cosa.",
  "support_issue_business_support": "Ya tengo una cuenta de negocio y necesito apoyo",
  "support_issue_joining_as_a_business": "Estoy interesado en unirse a la entrega de alimentos como un negocio",
  "support_issue_appointment_support": "He reservado un pedido con un negocio en la entrega de alimentos",
  "support_call_action": "Apoyo de llamada",
  "support_back_action": "Vuelve.",
  "support_header_action": "Acción del encabezado",
  "support_close_action": "Formulario de apoyo cercano",
  "support_tickets_search_action": "Buscar entradas",
  "support_tickets_search_placeholder": "Buscar entradas",
  "support_tickets_no_results_title": "No hay boletos de coincidencia",
  "support_tickets_no_results_description": "Prueba un número de orden diferente, estado o palabra clave.",
  "support_form_how_help_label": "¿Cómo podemos ayudar?",
  "support_form_email_label": "Correo electrónico",
  "support_form_email_helper": "Si tiene una cuenta de entrega de alimentos, ingrese la dirección de correo electrónico con la que inicie sesión",
  "support_form_full_name_label": "Nombre completo",
  "support_form_full_name_placeholder": "Introduzca su nombre",
  "support_form_country_region_label": "País / Región",
  "support_form_country_region_placeholder": "Seleccione",
  "support_form_mobile_number_label": "Número de móvil",
  "support_form_mobile_number_placeholder": "+61 333 000 0000",
  "support_form_business_name_label": "Nombre del negocio",
  "support_form_business_type_label": "Tipo de negocio",
  "support_form_business_type_placeholder": "Seleccione",
  "support_form_team_size_label": "Tamaño del equipo",
  "support_form_team_size_placeholder": "Seleccione",
  "support_form_business_description_label": "¿Hay algo en particular que quieras saber sobre la entrega de alimentos?",
  "support_form_reason_label": "Motivo de contacto",
  "support_form_reason_placeholder": "Seleccione",
  "support_form_reason_account_setup": "Configuración de la cuenta",
  "support_form_reason_add_on_integrations": "Complementos e integraciones",
  "support_form_reason_addons_integrations": "Complementos e integraciones",
  "support_form_reason_using_the_app": "Usando la aplicación",
  "support_form_reason_payments_and_payouts": "Pagos y pagos",
  "support_form_reason_technical_issues": "Cuestiones técnicas",
  "support_form_reason_my_orders": "Mis órdenes.",
  "support_form_reason_payments_and_purchases": "Pagos y compras",
  "support_form_reason_reviews": "Reseñas",
  "support_form_reason_emails_and_notifications": "Correos electrónicos y notificaciones",
  "support_form_reason_delete_my_account": "Suprimir mi cuenta",
  "support_form_reason_billing_fees": "Facturación y honorarios",
  "support_form_reason_payments_payouts": "Pagos y pagos",
  "support_form_reason_technical_support": "Apoyo técnico",
  "support_form_reason_other": "Otros",
  "support_form_country_united_states": "Estados Unidos",
  "support_form_country_canada": "Canadá",
  "support_form_country_united_kingdom": "Reino Unido",
  "support_form_country_australia": "Australia",
  "support_form_country_france": "Francia",
  "support_form_business_type_burger_joint": "Hamburguesería",
  "support_form_business_type_pizza_place": "Pizzería",
  "support_form_business_type_taco_stand": "Puesto de tacos",
  "support_form_business_type_sandwich_shop": "Tienda de sándwiches",
  "support_form_business_type_ice_cream_parlor": "Heladería",
  "support_form_business_type_fried_chicken_spot": "Restaurante de pollo frito",
  "support_form_business_type_food_truck": "Camión de alimentos",
  "support_form_business_type_hot_dog_stand": "Puesto de perritos calientes",
  "support_form_business_type_other_fast_food": "Otros alimentos rápidos",
  "support_form_team_size_just_me": "Sólo yo",
  "support_form_team_size_2_5": "2 - 5",
  "support_form_team_size_6_10": "6 - 10",
  "support_form_team_size_11_plus": "11+",
  "support_form_description_label": "Describe con qué necesitas ayuda",
  "support_form_description_placeholder": "Introduzca una descripción...",
  "support_form_attach_title": "Capturas de pantalla adjunto",
  "support_form_attach_description": "Deja tus archivos aquí",
  "support_form_attach_cta": "Elija un archivo",
  "support_form_send_email": "Enviar correo electrónico",
  "support_form_submit_success_title": "Ticket creado",
  "support_form_submit_success_message": "Su billete de apoyo se presentó con éxito.",
  "support_form_submit_error_title": "El billete falló",
  "support_form_submit_error_message": "No podíamos enviar tu billete de apoyo. Revise su conexión e intente de nuevo.",
  "support_form_attachment_upload_error": "Uno o más archivos adjuntos no se pueden cargar. Revise su conexión e intente de nuevo.",
  "support_chat_attachment_invalid_title": "Adjunto no añadido",
  "support_chat_attachment_too_large_message": "Cada apego debe ser de 5 MB o menor.",
  "support_chat_auto_message": "¿Cómo podemos ayudarle?",
  "support_chat_auto_time": "8:29 pm",
  "support_chat_quick_reply_here": "Estoy aquí",
  "support_chat_quick_reply_hello": "Hola.",
  "support_chat_quick_reply_call_arrive": "Llámame cuando llegues.",
  "support_chat_quick_reply_where": "¿Dónde estás?",
  "support_chat_quick_reply_eta": "¿Cuánto tardarás?",
  "support_chat_input_placeholder": "Entra en tu preocupación...",
  "support_chat_add_attachment": "Añadir adjunto",
  "support_chat_send_message": "Enviar mensaje",
  "support_chat_send_error_title": "El mensaje falló",
  "support_chat_send_error_message": "No podía enviar su mensaje de apoyo.",
  "support_chat_missing_session_error": "Por favor inicie sesión antes de enviar un mensaje.",
  "support_chat_missing_receiver_error": "El chat de soporte no está listo todavía. Por favor, abra una conversación existente primero.",
  "support_chat_loading": "Cargando conversaciones...",
  "support_chat_attachment_permission_title": "Permiso necesario",
  "support_chat_attachment_permission_message": "Por favor, permita el acceso a la biblioteca de fotos para añadir un accesorio.",
  "support_chat_attachment_selected_title": "Adjunto seleccionado",
  "support_chat_attachment_selected_message": "{{fileName}} está listo para adjuntar.",
  "support_tickets_title": "Mis entradas",
  "support_new_ticket": "Nuevo billete",
  "support_tickets_subtitle": "Seguimiento de sus peticiones y seguimiento con nuestro equipo en cada uno.",
  "support_tickets_filter_all": "Todos",
  "support_tickets_filter_active": "Activo",
  "support_tickets_filter_closed": "Resolver / cerrar",
  "support_tickets_search_clear": "Búsqueda clara",
  "support_tickets_empty": "Todavía no hay entradas.",
  "support_tickets_order_id": "ID del pedido: {{orderId}}",
  "support_faq_title": "Cuestiones de orden general",
  "support_faq_header_title": "Ayuda artículos",
  "support_faq_subtitle": "Respuestas claras para las preguntas de pedido y entrega más comunes.",
  "support_faq_place_order": "Cómo hacer un pedido",
  "support_faq_schedule_delivery": "Cómo programar sus entregas con antelación",
  "support_faq_change_delivery": "Cambiar tus entregas",
  "support_faq_order_history": "Cómo ver su historial de pedidos",
  "support_faq_ordering_for_others": "Ordenar por otros y enviar confirmaciones a diferentes direcciones",
  "support_faq_still_need_help": "¿Todavía necesitas ayuda?",
  "support_faq_feedback_prompt": "¿Fue útil?",
  "support_faq_feedback_yes": "Sí.",
  "support_faq_feedback_no": "No",
  "support_faq_feedback_thanks": "Gracias — su opinión nos ayuda a mejorar el apoyo.",
  "support_faq_place_order_body_1": "Hacer un pedido es rápido y sencillo. Abra la aplicación de entregas y busque restaurantes, tiendas o categorías cercanos que coincidan con lo que necesite.",
  "support_faq_place_order_body_2": "Toque una tienda para explorar su menú, a continuación, agregue los elementos que desee a su carrito. Usted puede revisar las cantidades, añadir notas, y eliminar cualquier cosa antes del checkout.",
  "support_faq_place_order_body_3": "Cuando esté listo, continúe el checkout para confirmar su dirección de entrega, aplique cualquier código de promo y elija su método de pago preferido.",
  "support_faq_place_order_body_4": "Después de realizar el pedido, puede seguir su progreso en tiempo real y mantenerse actualizado hasta que llegue a su puerta.",
  "support_faq_schedule_delivery_body_1": "Si una tienda admite pedidos programados, puede elegir un tiempo de entrega antes de completar el checkout.",
  "support_faq_schedule_delivery_body_2": "Añadir sus artículos al carrito y proceder a la compra. Busque la sección de tiempo de entrega antes de confirmar su pedido.",
  "support_faq_schedule_delivery_body_3": "Seleccione una fecha y una ranura de tiempo que funciona para usted, luego revise los detalles del pedido para asegurarse de que todo se ve bien.",
  "support_faq_schedule_delivery_body_4": "Una vez confirmado, mantendremos su entrega programada en su ficha de pedidos para que pueda volver a revisarla más tarde.",
  "support_faq_change_delivery_body_1": "Usted puede ser capaz de actualizar partes de su pedido antes de que la tienda comience a prepararlo.",
  "support_faq_change_delivery_body_2": "Abra su orden activo y compruebe si la edición sigue disponible. Algunas tiendas permiten pequeñas actualizaciones mientras que otras pueden bloquear cambios una vez que comience la preparación.",
  "support_faq_change_delivery_body_3": "Si la edición no está disponible, la opción más rápida es por lo general contactar con soporte desde la sección de ayuda o iniciar un chat con una persona.",
  "support_faq_change_delivery_body_4": "Recomendamos revisar su carrito cuidadosamente antes de hacer el pedido para que pueda evitar cambios de último minuto.",
  "support_faq_order_history_body_1": "Sus entregas anteriores y activas están disponibles en la sección de pedidos de la aplicación.",
  "support_faq_order_history_body_2": "Abra el orden que desea revisar para ver sus artículos, detalles de pago, dirección de entrega, y estado actual o pasado.",
  "support_faq_order_history_body_3": "Este es también el mejor lugar para reordenar los artículos rápidamente cuando desea la misma entrega de nuevo.",
  "support_faq_ordering_for_others_body_1": "Usted puede hacer un pedido para otra persona seleccionando o ingresando la dirección de entrega correcta antes de la salida.",
  "support_faq_ordering_for_others_body_2": "Asegúrese de que el nombre del destinatario, el número de teléfono y las instrucciones de entrega son exactas para que el mensajero pueda llegar a la persona correcta.",
  "support_faq_ordering_for_others_body_3": "Si necesita enviar actualizaciones a un contacto diferente, revise los datos de contacto disponibles durante el checkout y antes de confirmar el pedido.",
  "support_faq_ordering_for_others_body_4": "Para la experiencia más suave, haga que el destinatario sepa que una entrega está en camino y comparta cualquier detalle de tiempo con ellos.",
  "support_faq_still_need_help_body_1": "Si su pregunta no está cubierta aquí, abra la opción de chat en la parte inferior de la pantalla y llegue a nuestro equipo de soporte.",
  "support_faq_still_need_help_body_2": "Incluye detalles clave como el nombre de la tienda, el número de pedido y una breve explicación del problema para que podamos ayudar más rápido.",
  "support_faq_still_need_help_body_3": "Nuestro equipo le guiará a través de los próximos pasos y ayudará a resolver problemas relacionados con la entrega, el pago o la cuenta.",
  "searching_near": "Búsqueda cerca",
  "products": "Productos",
  "stores": "Tiendas",
  "see_all": "Ver todo",
  "filter_title": "Filtro",
  "filter_close_label": "Cerrar filtros",
  "filter_apply_results": "Aplicar filtros",
  "filter_category_title": "Categoría",
  "filter_price_title": "Precio",
  "filter_address_title": "Dirección cercana",
  "filter_stock_title": "Existencias",
  "filter_sort_title": "Ordenar por",
  "generic_list_error_title": "Incapaz de cargar resultados",
  "generic_list_error_description": "Trae para refrescar o probar de nuevo.",
  "generic_list_retry": "Entrada",
  "generic_list_empty_title": "No se han encontrado resultados",
  "generic_list_empty_description": "Pruebe una búsqueda diferente o ajuste sus filtros.",
  "generic_list_search_placeholder": "Búsqueda",
  "see_all_map_loading_title": "Encontrar {{title}}",
  "see_all_map_loading_description": "Esto puede tomar unos momentos. Por favor, quédate en esta pantalla.",
  "see_all_map_sheet_title": "Restaurante",
  "see_all_map_cta": "Ver Restaurante",
  "change_password_title": "Cambiar contraseña",
  "change_password_new_title": "Nueva contraseña",
  "change_password_email_heading": "¿Cambiar contraseña?",
  "change_password_email_description": "Introduzca su dirección de correo electrónico y le enviaremos un código de verificación.",
  "change_password_email_placeholder": "your@email.com",
  "change_password_continue": "Continuar",
  "change_password_verify_heading": "Verificar su correo electrónico",
  "change_password_verify_description": "Introduzca el código de 4 dígitos enviado a {{email}}",
  "change_password_verify_button": "Verificar OTP",
  "change_password_new_heading": "Crea tu nueva contraseña",
  "change_password_new_description": "Su nueva contraseña debe ser diferente de su contraseña anterior.",
  "change_password_new_placeholder": "Nueva contraseña",
  "change_password_confirm_placeholder": "Confirme nueva contraseña",
  "change_password_set_new": "Establecer nueva contraseña",
  "change_password_mismatch": "Las contraseñas no coinciden.",
  "change_password_error_title": "Error",
  "change_password_send_otp_error": "No ha enviado código de verificación.",
  "change_password_verify_otp_error": "Código inválido o vencido.",
  "change_password_update_error": "No ha actualizado la contraseña.",
  "change_password_success_title": "El éxito",
  "change_password_success_message": "Su contraseña ha sido actualizada.",
  "change_password_otp_resent_title": "Código enviado",
  "change_password_otp_resent_message": "Se ha enviado un nuevo código de verificación.",
  "delete_account_step_label": "Suprimir mi cuenta",
  "delete_account_sorry_heading": "Sentimos verte ir.",
  "delete_account_sorry_subtext": "¿Podemos cambiar de opinión? Suelta una línea",
  "delete_account_contact_email": "hello@enategadelivery.com",
  "delete_account_reason_heading": "¿Por qué desea dejar la entrega de alimentos?",
  "delete_account_reason_subtext": "Por favor háganos saber la razón para borrar su cuenta:",
  "delete_account_reason_mistake": "He creado esta cuenta por error",
  "delete_account_reason_no_longer": "No quiero usar la entrega de alimentos más",
  "delete_account_reason_no_venues": "No puedo encontrar los lugares o servicios que quiero",
  "delete_account_reason_other": "Otros",
  "delete_account_confirm_heading": "Su cuenta de entrega de alimentos",
  "delete_account_confirm_description": "Esta acción eliminará tu cuenta y no podrás recuperarla. Por favor, confirme que entiende haciendo las siguientes declaraciones:",
  "delete_account_confirm_item_orders": "Sé que no podré acceder a mis órdenes.",
  "delete_account_confirm_item_marketplace": "Sé que ya no podré reservar pedidos a través del mercado de entrega de alimentos.",
  "delete_account_final_heading": "Confirme que está feliz de proceder",
  "delete_account_final_description": "Tenga en cuenta que esto es permanente y no se puede deshacer. Para confirmar la eliminación de su cuenta, revise su correo electrónico a continuación:",
  "delete_account_email_label": "Correo electrónico",
  "delete_account_email_placeholder": "your@email.com",
  "delete_account_cta_continue": "Continuar",
  "delete_account_cta_delete": "Suprimir la cuenta",
  "delete_account_close": "Cerca",
  "delete_account_alert_title": "Suprimir la cuenta",
  "delete_account_alert_message": "¿Estás seguro de que quieres eliminar permanentemente tu cuenta? Esta acción no puede ser aprobada.",
  "delete_account_alert_cancel": "Cancelar",
  "delete_account_alert_confirm": "Suprimir",
  "delete_account_error_title": "Error",
  "delete_account_error": "Failed to delete account. Por favor, inténtalo de nuevo.",
  "color_mode_title": "Aplicación modo de color",
  "color_mode_section_label": "Seleccione el modo de color de la aplicación",
  "color_mode_system": "Sistema predeterminado",
  "color_mode_light": "Luz",
  "color_mode_dark": "Oscuro",
  "language_title": "Idiomas de la aplicación",
  "language_section_label": "Seleccionar idioma",
  "language_english": "Inglés",
  "language_german": "Alemán",
  "language_spanish": "Español",
  "language_arabic": "Árabe",
  "language_french": "Francés",
  "popular": "Popular",
  "ingredients": "Ingredientes",
  "usage": "Uso",
  "nutrition_facts": "Datos nutricionales",
  "amount_per": "Cuantía",
  "energy": "Energía",
  "fat": "Gordo",
  "carbohydrates": "Carbohidratos",
  "protein": "Proteína",
  "sugar": "Azúcar",
  "choose_size": "Elija tamaño",
  "choose_variation": "Elija Variación",
  "select_one": "Seleccione uno",
  "required_label": "Se requiere",
  "optional_label": "Facultativo",
  "product_option_choose_at_least": "Elija al menos {{count}}",
  "product_option_choose_range": "Elija {{min}}–{{max}}",
  "product_option_choose_up_to": "Elija hasta {{count}}",
  "product_option_required_error": "Elija las opciones necesarias para continuar.",
  "small": "Pequeña",
  "medium": "Mediana",
  "large": "Grande",
  "choose_your_flavour": "Elige tu favorito",
  "choose_your_addons": "Elige tus Addons",
  "add_to_cart": "Añadir al carrito",
  "cart_title": "Carrito",
  "cart_store_fallback": "Tu tienda",
  "cart_return_to_store": "Volver a {{store}}",
  "cart_delivery_time": "Entrega en {{time}} min",
  "cart_items_title": "Sus artículos",
  "cart_add_more": "Añadir más",
  "cart_recommended_title": "Recomendado para usted",
  "cart_checkout": "Ir a la salida",
  "cart_checkout_short": "Pagar",
  "cart_order_summary": "Resumen",
  "cart_promo_title": "Código Promo",
  "cart_promo_subtitle": "Elija un código para este pedido",
  "cart_promo_applied": "Seleccionado para el checkout",
  "cart_promo_add": "Añadir",
  "cart_promo_change": "Cambio",
  "cart_fees_at_checkout": "Los gastos de envío y servicio se confirman al realizar el registro de salida",
  "cart_minimum_remaining": "{{amount}} lejos del orden mínimo",
  "cart_minimum_reached": "Orden mínima alcanzada",
  "cart_minimum_progress_accessibility": "{{current}} de {{minimum}} pedido mínimo",
  "cart_item_unavailable": "No disponible",
  "cart_recommendation_accessibility": "Ver {{product}}",
  "cart_fee_modal_current_subtotal": "Subtotal actual",
  "cart_fee_modal_minimum_order": "Orden mínima",
  "cart_fee_modal_base_delivery": "Tasa de prestación básica",
  "cart_fee_modal_checkout_notice": "La entrega final y las tarifas de servicio se calculan para su dirección al checkout.",
  "checkout_title": "Pago",
  "checkout_order_from": "Ordenar desde",
  "checkout_item_count": "Artículos de {{count}}",
  "checkout_fulfillment_title": "¿Te gustaría?",
  "checkout_fulfillment_delivery": "Entrega",
  "checkout_fulfillment_pickup": "Recogida",
  "checkout_delivery_details_title": "Detalles de la entrega",
  "checkout_pickup_details_title": "Detalles de recogida",
  "checkout_address_title": "Elija una dirección de entrega",
  "checkout_address_subtitle": "Pulse aquí para continuar",
  "checkout_address_selected_subtitle": "Toca aquí para cambiar",
  "checkout_pickup_title": "Ubicación de recogida",
  "checkout_pickup_subtitle": "Recoger su pedido de la tienda",
  "checkout_leave_at_door_title": "Vete a la puerta.",
  "checkout_leave_at_door_subtitle": "Un desvío sin contacto",
  "checkout_notes_title": "Notas de orden",
  "checkout_message_restaurant_title": "Añadir un mensaje para el restaurante",
  "checkout_message_restaurant_subtitle": "Solicitudes especiales, alergias, restricciones dietéticas?",
  "checkout_message_restaurant_editor_title": "Instrucciones para el restaurante",
  "checkout_message_restaurant_editor_description": "Solicitudes especiales, alergias, restricciones dietéticas?",
  "checkout_message_restaurant_placeholder": "Agregar solicitudes especiales (opcional)",
  "checkout_message_courier_title": "Añadir un mensaje para el mensajero",
  "checkout_message_courier_subtitle": "Añada instrucciones importantes, hitos o peticiones especiales.",
  "checkout_message_courier_editor_title": "Instrucciones para el mensajero",
  "checkout_message_courier_editor_description": "Añada instrucciones importantes, hitos o peticiones especiales.",
  "checkout_message_courier_placeholder": "Añadir instrucciones de entrega (opcional)",
  "checkout_message_done": "Hecho",
  "checkout_delivery_time_title": "Tiempo de entrega",
  "checkout_collection_time_title": "Tiempo de recogida",
  "checkout_delivery_time_standard": "Estándar",
  "checkout_delivery_time_standard_eta": "10-20 min",
  "checkout_delivery_time_schedule": "Cuadro",
  "checkout_delivery_time_schedule_hint": "Elija un tiempo de entrega",
  "checkout_schedule_title": "Tiempo de entrega programado",
  "checkout_schedule_heading": "Elige un tiempo que funcione para ti",
  "checkout_schedule_description": "Los tiempos disponibles se mantienen actualizados para esta tienda.",
  "checkout_schedule_available_times": "Tiempos disponibles",
  "checkout_schedule_today": "Hoy",
  "checkout_schedule_tomorrow": "Mañana",
  "checkout_schedule_asap": "Tan pronto como sea posible",
  "checkout_schedule_confirm": "Confirmación",
  "checkout_schedule_empty_title": "No hay horarios disponibles",
  "checkout_schedule_empty_message": "Pruebe otro día o continúe con la entrega estándar.",
  "checkout_schedule_error_title": "No se puede cargar ranuras programadas",
  "checkout_schedule_error_message": "Pruebe de nuevo para buscar las ranuras de tiempo disponibles.",
  "checkout_schedule_slot_expired": "Esa ranura de tiempo ya no está disponible. Por favor elige otro.",
  "checkout_schedule_unavailable_note": "Orden previa no disponible los domingos &amp; vacaciones.",
  "checkout_payment_title": "Pago",
  "checkout_payment_selector_title": "Método de pago",
  "checkout_payment_close": "Métodos de pago cercanos",
  "checkout_payment_selector_heading": "Elija un método de pago",
  "checkout_payment_selector_description": "Seleccione cómo desea pagar por este pedido.",
  "checkout_payment_selector_confirm": "Método de confirmación",
  "checkout_payment_cash_title": "Efectivo",
  "checkout_payment_cash_subtitle": "Paga con efectivo cuando llegue su pedido",
  "checkout_payment_card_title": "Tarjeta",
  "checkout_payment_card_subtitle": "Pagar seguro en línea con su tarjeta",
  "checkout_payment_card_saved_subtitle": "{{brand}} (•••• {{last4}})",
  "checkout_payment_option_cash_description": "Paga en la entrega o recoger.",
  "checkout_payment_option_card_description": "Usted completará el pago en el pago seguro de Stripe.",
  "checkout_payment_add_card_required": "Añadir una tarjeta en la cartera para usar el pago de la tarjeta.",
  "checkout_payment_cash_unavailable": "El efectivo en la entrega no está disponible para esta tienda",
  "checkout_payment_card_unavailable": "El pago de la tarjeta no está disponible para esta tienda",
  "checkout_payment_cod_unavailable_error": "Esta tienda no permite efectivo en la entrega.",
  "checkout_payment_card_unavailable_error": "Esta tienda no permite pagos de tarjetas.",
  "checkout_payment_webview_title": "Pago completo",
  "checkout_payment_processing_title": "Confirmando su pago",
  "checkout_payment_processing_message": "Por favor, espere mientras verifique su pago y cree su pedido.",
  "checkout_payment_processing_error": "Todavía estamos revisando su pago. Por favor, espera un momento.",
  "checkout_payment_cancelled": "El pago fue cancelado.",
  "checkout_payment_failed": "El pago falló. Por favor, intente de nuevo con otro método.",
  "checkout_payment_confirmation_delayed": "El pago de su tarjeta puede ser procesado. Revisa tus órdenes antes de intentarlo de nuevo.",
  "checkout_payment_card_redirecting": "Complete su pago en el navegador para terminar este pedido.",
  "checkout_payment_card_redirect_error": "Incapaz de abrir una salida segura ahora mismo.",
  "checkout_leave_at_door_card_required": "Dejar en la puerta requiere pago de tarjeta. Por favor, cambie a la tarjeta para continuar.",
  "checkout_leave_at_door_switched_to_card": "El método de pago se cambió a la tarjeta para la entrega de permiso a puerta.",
  "checkout_promo_title": "Código Promo",
  "checkout_promo_subtitle": "Pulse aquí para continuar",
  "checkout_promo_tap_to_change": "Toca aquí para cambiar",
  "checkout_promo_remove": "Retirar",
  "checkout_promo_removed": "Código Promo eliminado",
  "checkout_tip_title": "Propina para tu repartidor",
  "checkout_tip_description": "La propina se pagará llena al mensajero.",
  "checkout_tip_custom": "Aduanas",
  "checkout_tip_none": "No hay propina",
  "checkout_tip_custom_title": "Añadir una propina personalizada",
  "checkout_tip_custom_placeholder": "0.00",
  "checkout_tip_custom_done": "Hecho",
  "checkout_summary_title": "Resumen",
  "checkout_summary_hint": "IVA (si procede)",
  "checkout_summary_subtotal": "Subtotal",
  "checkout_summary_discount": "Descuento",
  "checkout_summary_delivery_fee": "Tasa de entrega",
  "checkout_summary_packing_charges": "Cargos de embalaje",
  "checkout_summary_tax": "Impuestos",
  "checkout_summary_tip": "Punta del mensajero",
  "checkout_summary_total": "Total",
  "checkout_summary_free": "Gratis",
  "checkout_place_order": "Orden de lugar",
  "checkout_place_order_pending": "El orden del lugar estará disponible en el siguiente paso.",
  "checkout_place_order_success": "Orden con éxito.",
  "checkout_place_order_error": "Incapaz de hacer su pedido ahora mismo.",
  "order_confirmation_title": "Orden confirmada",
  "order_confirmation_number": "Orden #{{number}}",
  "order_confirmation_message": "{{store}} ha recibido su pedido. Te mantendremos actualizado mientras se mueve.",
  "order_confirmation_store_fallback": "Tu tienda",
  "order_confirmation_step_confirmed": "Confirmado",
  "order_confirmation_step_store": "Con la tienda",
  "order_confirmation_step_preparing": "Preparación",
  "order_confirmation_step_scheduled": "Programado",
  "order_confirmation_step_delivery": "Entrega",
  "order_confirmation_step_pickup": "Recogida",
  "order_confirmation_eta_label": "Fecha estimada de llegada",
  "order_confirmation_ready_label": "Tiempo de preparación estimado",
  "order_confirmation_eta_pending": "Actualizar en breve",
  "order_confirmation_minutes": "{{estimate}} min",
  "order_confirmation_order_from": "Orden de",
  "order_confirmation_track": "Orden de seguimiento",
  "order_confirmation_receipt": "Ver el recibo",
  "order_confirmation_help": "Obtener ayuda",
  "order_confirmation_done": "Confirmación cercana",
  "checkout_address_required": "Por favor, elija una dirección de entrega primero.",
  "checkout_promo_pending": "El soporte de código Promo se añadirá en el siguiente paso.",
  "checkout_preview_error_title": "No se puede cargar el checkout",
  "checkout_preview_error_message": "Por favor, intente de nuevo en un momento.",
  "checkout_preview_updating": "Actualizando tu total...",
  "checkout_store_closed_title": "La tienda está cerrada",
  "checkout_store_closed_message": "Esta tienda está actualmente cerrada. Inténtelo de nuevo durante las horas de apertura.",
  "checkout_address_outside_delivery_area_title": "Zona de distribución exterior",
  "checkout_address_outside_delivery_area_message": "Esta tienda no puede entregar a la dirección seleccionada. Por favor, elija una dirección de entrega diferente.",
  "checkout_change_address": "Dirección de cambio",
  "checkout_insufficient_wallet_balance_title": "Equilibrio de cartera insuficiente",
  "checkout_insufficient_wallet_balance_message": "Su saldo de la cartera de {{balance}} no es suficiente para cubrir el total de este pedido de {{total}}. Añade fondos a tu billetera o elige otro método de pago.",
  "checkout_insufficient_wallet_balance_add_funds": "Añadir fondos a la cartera",
  "checkout_insufficient_wallet_balance_choose_payment": "Elija otro método de pago",
  "checkout_payment_wallet_title": "Monedero",
  "checkout_payment_wallet_subtitle": "Paga usando el saldo de tu billetera",
  "checkout_payment_option_wallet_description": "Pagar con seguridad usando el saldo de tu billetera.",
  "checkout_payment_wallet_insufficient_balance": "Equilibrio de cartera insuficiente para este pedido.",
  "checkout_payment_wallet_balance": "Saldo de bolsillo: {{currency}} {{amount}}",
  "cart_empty_title": "Su carrito está vacío",
  "cart_empty_message": "Cuando agregue artículos de una tienda, su pedido estará aquí para que pueda hacer cambios cuando quiera.",
  "cart_start_shopping": "Empieza a comprar",
  "cart_error_title": "No podía cargar su carrito",
  "cart_error_message": "Por favor, intente de nuevo en un momento.",
  "cart_remove_item": "Quitar artículo",
  "cart_decrement_item": "Reducción de la cantidad",
  "cart_increment_item": "Aumento de la cantidad",
  "cart_info_label": "Honorarios y gastos mínimos",
  "cart_low_order_fee_applies_prefix": "A",
  "cart_low_order_fee_applies_suffix": "tarifa de bajo pedido se aplica",
  "cart_fee_modal_title": "Gastos de pedido &quot; gasto mínimo &quot;",
  "cart_fee_modal_description_prefix": "El gasto mínimo es",
  "cart_fee_modal_description_suffix": "valor total del carrito.",
  "cart_fee_modal_total_cart_value": "Valor total del carrito",
  "cart_fee_modal_service_fee": "Tasa de servicio",
  "cart_fee_modal_above": "arriba",
  "cart_fee_modal_no_fee": "No Fee",
  "cart_fee_modal_note_prefix": "* Para pedidos inferiores a",
  "cart_fee_modal_note_middle": "una pequeña cuota de pedido",
  "cart_fee_modal_note_suffix": "aplicable",
  "cart_store_conflict_title": "¿Reemplazar su carrito actual?",
  "cart_store_conflict_message": "Su carrito ya tiene artículos de otra tienda. Reemplazarlo para añadir elementos de {{incomingStore}}.",
  "cart_store_conflict_message_with_product": "Su carrito ya tiene artículos de otra tienda. Reemplazarlo para añadir {{product}} de {{incomingStore}}.",
  "cart_store_conflict_keep_cart": "Mantenga el carro actual",
  "cart_store_conflict_replace_cart": "Carrito de repuesto",
  "cart_store_conflict_store_fallback": "esta tienda",
  "cart_action_loading_options_title": "Opciones de preparación",
  "cart_action_loading_options_message": "Por favor, espere mientras cargamos las personalizaciones disponibles para este artículo.",
  "cart_action_customization_required_title": "Elige tus opciones primero",
  "cart_action_customization_required_message": "Por favor, revise las opciones de producto antes de añadir este artículo a su carrito.",
  "cart_action_out_of_stock_title": "Tema no disponible",
  "cart_action_out_of_stock_message": "Este artículo está actualmente agotado. Por favor, prueba otro artículo.",
  "cart_network_error_title": "Cuestión de conexión",
  "cart_network_error_message": "Por favor, compruebe su conexión a Internet e inténtelo de nuevo.",
  "cart_add_success_title": "Añadido al carrito",
  "cart_add_success_message": "{{quantity}} × {{product}} está listo en su carrito.",
  "cart_add_success_go_to_cart": "Ir al carro",
  "cart_add_success_continue_shopping": "Continuar comprando",
  "cart_add_error_title": "No se puede añadir el artículo",
  "cart_add_error_message": "Por favor, intente de nuevo en un momento.",
  "cart_store_closed_title": "{{storeName}} está cerrado",
  "cart_store_closed_description": "Esta tienda no acepta órdenes ahora mismo. Por favor, revisa una vez que vuelva.",
  "cart_update_success_title": "Carrito actualizado",
  "cart_update_success_message": "Su cantidad de carrito ha sido actualizada.",
  "cart_update_error_title": "No se puede actualizar el carrito",
  "cart_update_error_message": "Por favor, intenta actualizar tu carrito de nuevo.",
  "cart_remove_success_title": "Tema eliminado",
  "cart_remove_success_message": "El artículo ha sido eliminado de su carrito.",
  "cart_remove_error_title": "No se puede quitar el elemento",
  "cart_remove_error_message": "Por favor, intenta quitar el artículo de nuevo.",
  "cart_clear_action": "Carrito transparente",
  "cart_clear_popup_title": "¿Despejar tu carrito?",
  "cart_clear_popup_message": "Esto eliminará todos los artículos de su carrito actual para que pueda empezar de nuevo.",
  "cart_clear_popup_confirm": "Carrito transparente",
  "cart_clear_popup_cancel": "Cancelar",
  "cart_clear_error_title": "No se puede reemplazar el carrito",
  "cart_clear_error_message": "Por favor, intente de nuevo en un momento.",
  "free": "Gratis",
  "store_card_new": "Nuevo",
  "store_card_delivery_fee_unavailable": "{{currency}} —",
  "store_card_delivery_time_unavailable": "ETA –",
  "store_card_distance_unavailable": "km",
  "product_info_back": "Atrás",
  "product_info_share": "Producto compartido",
  "product_info_unavailable": "Actualmente no disponible",
  "product_info_error_title": "No se puede cargar el producto",
  "orders_tab_active": "Activo",
  "orders_tab_history": "Pasado",
  "orders_tab_scheduled": "Programado",
  "orders_history_active_heading": "Órdenes activas",
  "orders_empty_active_title": "No hay órdenes activas todavía",
  "orders_empty_active_subtitle": "Sus órdenes activas aparecerán aquí una vez que coloque uno.",
  "orders_empty_history_title": "No hay órdenes todavía",
  "orders_empty_history_subtitle": "No has hecho ninguna orden. Se mostrará aquí cuando hayas hecho uno.",
  "orders_empty_history_cta": "Empieza a comprar",
  "orders_empty_scheduled_title": "No hay entregas programadas todavía",
  "orders_empty_scheduled_subtitle": "No has programado ningún pedido.",
  "orders_history_ongoing_heading": "Orden en curso",
  "orders_history_past_heading": "Órdenes anteriores",
  "orders_history_scheduled_heading": "Órdenes programadas",
  "orders_list_load_more": "Cargar más",
  "orders_list_no_more_items": "No más artículos",
  "orders_list_error": "Incapaz de cargar las entregas programadas ahora mismo.",
  "orders_list_retry": "Inténtalo de nuevo.",
  "orders_status_upcoming": "Subiendo",
  "orders_status_ongoing": "Continuando",
  "orders_status_scheduled": "Programado",
  "orders_status_received": "Orden recibida",
  "orders_status_confirmed": "Confirmado",
  "orders_status_preparing": "Preparando su orden",
  "orders_status_ready": "Listo para recoger",
  "orders_status_courier_assigned": "Mensaje asignado",
  "orders_status_on_the_way": "En camino",
  "orders_status_arrived": "Courier llegó",
  "orders_status_delayed": "Entrega retrasada",
  "orders_status_delivered": "Orden entregada",
  "orders_status_cancelled": "Orden cancelada",
  "orders_status_rejected": "Orden declinado",
  "orders_status_failed": "La orden no puede completarse",
  "orders_screen_title": "Órdenes",
  "orders_screen_subtitle": "Siga lo que está en movimiento o revise una entrega pasada.",
  "orders_view_details": "Ver detalles",
  "order_cancel_title": "¿Cancelar pedido?",
  "order_cancel_message": "Los pedidos pagados serán devueltos a su cartera.",
  "order_cancel_keep": "Mantén orden",
  "order_cancel_confirm": "Cancelar pedido",
  "order_cancel_failed": "Incapaz de cancelar el pedido",
  "order_details_title": "Detalles del pedido",
  "order_details_error_title": "Incapaz de cargar este pedido ahora mismo.",
  "order_details_status": "Estado del orden",
  "order_details_progress": "Progresos en la ejecución",
  "order_details_scheduled_for": "Programado",
  "order_details_items": "Artículos de orden",
  "order_details_summary": "Resumen",
  "order_details_payment_details": "Detalles del pago",
  "order_details_payment_method": "Método de pago",
  "order_details_paid": "Pagado",
  "order_details_unavailable": "No disponible",
  "order_details_reference": "Orden #{{number}}",
  "order_details_get_help": "Obtener ayuda",
  "order_details_order_number": "Número de pedido",
  "order_details_delivery_address": "Dirección de entrega",
  "order_details_item_subtotal": "Tema",
  "order_details_discount": "Descuento",
  "order_details_tax": "Impuestos",
  "order_details_packing_charges": "Cargos de embalaje",
  "order_details_delivery_fee": "Entrega",
  "order_details_courier_tip": "Punta del mensajero",
  "order_details_total_amount": "Cantidad total",
  "order_details_rate_order": "Tasar el orden",
  "order_details_view_rating": "Ver tu valoración",
  "order_details_increase_tip": "Aumentar la punta",
  "order_details_track_progress": "Seguimiento de los progresos realizados",
  "order_details_order_again": "Orden de nuevo",
  "order_details_notes": "Notas",
  "order_details_restaurant_note": "Nota de restaurante",
  "order_details_courier_note": "Nota de valor",
  "order_again_error_title": "No se pueden reordenar objetos",
  "order_again_error_message": "Por favor, intente ordenar estos artículos de nuevo en un momento.",
  "order_again_partial_title": "Algunos temas necesitan atención",
  "order_details_tip_done": "Hecho",
  "order_details_tip_placeholder": "0.00",
  "order_details_empty_items": "No hay elementos",
  "order_details_quantity_one": "Cant. {{count}}",
  "order_tracking_title": "Su orden",
  "order_tracking_help": "Ayuda de rastreo de pedidos",
  "order_tracking_eta_label": "Tiempo estimado de entrega",
  "order_tracking_eta_pending": "Actualizar en breve",
  "order_tracking_eta_short_confirming": "Confirmación",
  "order_tracking_eta_short_preparing": "Preparando",
  "order_tracking_eta_short_on_way": "En camino",
  "order_tracking_eta_short_nearby": "Cerca",
  "order_tracking_eta_short_delivered": "Hecho",
  "order_tracking_eta_short_ended": "Finalizado",
  "order_tracking_eta_short_updating": "Pronto.",
  "order_tracking_until_delivered": "hasta la entrega",
  "order_tracking_eta_remaining": "restantes",
  "order_tracking_estimated_arrival": "Llegada estimada {{time}}",
  "order_tracking_close": "Seguimiento de pedidos cercanos",
  "order_tracking_recenter_map": "Mapa más reciente",
  "order_tracking_route_loading": "Encontrar la mejor ruta...",
  "order_tracking_route_unavailable": "Ruta en vivo no disponible",
  "order_tracking_route_unavailable_description": "Las ubicaciones en vivo siguen siendo visibles mientras las actualizaciones de la ruta por carretera.",
  "order_tracking_route_pending": "Las actualizaciones de la ruta aparecerán aquí",
  "order_tracking_route_pending_description": "La ruta se dibujará tan pronto como ambos lugares estén disponibles.",
  "order_tracking_location_unavailable": "Mapa en vivo no disponible",
  "order_tracking_location_unavailable_description": "Sus actualizaciones de pedidos todavía están disponibles a continuación.",
  "order_tracking_progress": "Progresos en la ejecución",
  "order_tracking_next_step": "Siguiente: {{step}}",
  "order_tracking_no_next_step": "No se han adoptado nuevas medidas",
  "order_tracking_delay_next": "Te mantendremos actualizado",
  "order_tracking_order_items": "Artículos de orden",
  "order_tracking_courier_role": "Tu correo",
  "order_tracking_courier_pending": "Los detalles del mensaje están actualizando",
  "order_tracking_message_courier": "Mensaje de correo",
  "order_tracking_delivered_title": "Entrega",
  "order_tracking_delivered_message_line_one": "Tu pedido ha sido entregado.",
  "order_tracking_delivered_message_line_two": "¡Disfruta de tu comida!",
  "order_tracking_error_title": "Incapaz de cargar rastreo ahora mismo.",
  "order_tracking_delivery_details": "Detalles de la entrega",
  "order_tracking_collection_details": "Detalles de la colección",
  "order_tracking_contact_title": "Contacta con tu correo",
  "order_tracking_contact_subtitle": "Solicitar entrega sin contacto",
  "order_tracking_courier_fallback": "Repartidor",
  "order_tracking_summary": "Resumen",
  "order_tracking_summary_note": "IVA (si procede)",
  "order_tracking_unavailable_title": "Orden no confirmada",
  "order_tracking_unavailable_description": "La tienda no pudo confirmar su pedido, así que se ha cancelado. Puedes colocarla de nuevo o elegir otra tienda cercana.",
  "order_tracking_unavailable_cancelled_description": "Esta orden ha sido cancelada, así que no queda nada por rastrear. Puedes colocarla de nuevo o elegir otra tienda cercana.",
  "order_tracking_unavailable_action": "Volver a casa",
  "wallet_title": "Monedero",
  "wallet_balance_label": "Saldo de bolsillo",
  "wallet_hide_balance": "Ocultar el saldo de la cartera",
  "wallet_show_balance": "Mostrar saldo de la cartera",
  "wallet_action_convert": "Convertir puntos",
  "wallet_action_cards": "Gestionar tarjetas",
  "wallet_loyalty_available_points": "Puntos disponibles",
  "wallet_loyalty_zero_state": "Aún no hay puntos para convertir. Tus puntos aparecerán aquí cuando los ganes.",
  "wallet_loyalty_receive_label": "Usted recibirá",
  "wallet_loyalty_details": "Mostrar detalles de fidelidad",
  "wallet_loyalty_hide_details": "Ocultar detalles de lealtad",
  "wallet_points_max": "Max",
  "wallet_convert_sheet_description": "Convierta sus puntos de fidelidad en equilibrio de cartera.",
  "wallet_loyalty_total_points": "Total de puntos de fidelidad ganado",
  "wallet_loyalty_rate": "{{points}} puntos = {{currency}} 1",
  "wallet_loyalty_amount": "Saldo de bolsillo ganado por lealtad",
  "wallet_convert_points_title": "Convertir puntos de fidelidad",
  "wallet_points_available": "{{points}} puntos disponibles",
  "wallet_points_input": "Puntos para convertir",
  "wallet_points_receive": "Usted recibirá {{currency}} {{amount}}",
  "wallet_convert_points_action": "Añadir a la cartera",
  "wallet_points_converted_title": "Puntos convertidos",
  "wallet_points_converted_message": "{{currency}} {{amount}} fue añadido a su cartera.",
  "wallet_points_convert_error": "Incapaz de convertir puntos",
  "wallet_cards_title": "Tarjetas",
  "wallet_payment_methods_title": "Métodos de pago",
  "wallet_cards_sheet_description": "Administra tus tarjetas guardadas.",
  "wallet_cards_secure_note": "Los detalles de la tarjeta son manejados de forma segura por Stripe.",
  "wallet_saved_card_accessibility": "{{brand}} tarjeta {{name}}, {{last4}}",
  "wallet_done": "Hecho",
  "wallet_close": "Cerca",
  "wallet_view_transactions": "Ver transacciones",
  "wallet_secure": "Seguro",
  "wallet_default_card": "Predeterminada",
  "wallet_add_card": "Añadir tarjeta de débito/crédito",
  "wallet_topup_title": "Añadir dinero",
  "wallet_topup_sheet_description": "Sube tu billetera para pagos más rápidos y fáciles.",
  "wallet_select_payment_method": "Seleccionar método de pago",
  "wallet_choose_payment_method": "Elija el método de pago",
  "wallet_clear_amount": "Cantidad clara",
  "wallet_topup_amount": "Entrada",
  "wallet_topup_action": "Añadir a la cartera",
  "wallet_topup_action_amount": "Añadir {{amount}} a la cartera",
  "wallet_cover_order": "Arriba {{amount}} para este pedido",
  "wallet_topup_minimum": "Subtítulos mínimos: {{amount}}",
  "wallet_add_card_continue": "Añadir una tarjeta para continuar",
  "wallet_topup_card_required": "Añadir una tarjeta antes de subir",
  "wallet_topup_success": "Pago con éxito",
  "wallet_topup_success_title": "Pago confirmado",
  "wallet_topup_success_message": "{{amount}} se pagó con éxito. Su saldo de la cartera se actualizará en breve.",
  "wallet_topup_processing": "Proceso de pago",
  "wallet_topup_pending": "Su saldo de la cartera se actualizará después de la confirmación del pago.",
  "wallet_topup_error": "Incapaz de añadir dinero",
  "wallet_recent_transactions": "Transacciones recientes",
  "wallet_balance_load_error": "No podía cargar su equilibrio. Toca para volver a entrar.",
  "wallet_statement_today": "Hoy",
  "wallet_statement_yesterday": "Ayer",
  "wallet_statement_title": "Declaración de Wallet",
  "wallet_statement_balance": "Saldo actual",
  "wallet_statement_all": "Toda actividad",
  "wallet_statement_money_in": "Dinero en",
  "wallet_statement_money_out": "Dinero",
  "wallet_statement_no_filtered_activity": "No hay actividad en esta categoría todavía",
  "wallet_statement_details": "Detalles de la transacción",
  "wallet_statement_reason": "Razón",
  "wallet_statement_direction": "Dirección",
  "wallet_statement_date": "Fecha y hora",
  "wallet_statement_status": "Situación",
  "wallet_statement_reference": "Referencia de pago o pedido",
  "wallet_statement_transaction_id": "ID de transacción de Wallet",
  "wallet_statement_view_order": "Ver pedido",
  "wallet_statement_completed": "Completado",
  "wallet_statement_approved": "Aprobado",
  "wallet_statement_pending": "Pendiente",
  "wallet_statement_rejected": "Rechazado",
  "wallet_statement_unknown_status": "Grabado",
  "wallet_statement_unknown_direction": "Dirección no disponible",
  "wallet_statement_card_topup": "Añadido dinero a billetera",
  "wallet_statement_card_topup_description": "Pagado con una tarjeta guardada",
  "wallet_statement_order_payment": "Pagado por un pedido",
  "wallet_statement_order_payment_description": "Pagado de tu billetera",
  "wallet_statement_order_refund": "Reembolso del pedido",
  "wallet_statement_order_refund_description": "Dinero devuelto a tu cartera",
  "wallet_statement_loyalty_conversion": "Puntos de fidelidad convertidos",
  "wallet_statement_loyalty_conversion_description": "Añadido desde tus puntos de fidelidad",
  "wallet_statement_opening_balance": "Saldo inicial",
  "wallet_statement_opening_balance_description": "Traido de su cartera anterior",
  "wallet_statement_credit": "Dinero añadido a la cartera",
  "wallet_statement_credit_description": "Fuente no registrada",
  "wallet_statement_debit": "Dinero extraído de la cartera",
  "wallet_statement_debit_description": "La razón no se registró",
  "wallet_statement_withdrawal": "Retirada",
  "wallet_statement_withdrawal_description": "Dinero retirado de su cartera",
  "wallet_statement_unknown": "Transmisión de cartera",
  "wallet_statement_unknown_description": "No se registraron detalles de transacción",
  "wallet_transactions_empty_title": "Aún no hay transacciones",
  "wallet_transactions_empty_description": "Su actividad de cartera aparecerá aquí una vez que realice un pago o reembolso.",
  "wallet_transactions_error": "No podíamos cargar tu actividad de cartera. Pulsa para intentarlo de nuevo.",
  "wallet_see_all": "Ver todo",
  "wallet_view_details": "Ver detalles",
  "wallet_add_card_title": "Añadir tarjeta",
  "wallet_name_on_card": "Nombre en la tarjeta",
  "wallet_name_placeholder": "Añada el nombre completo titular de la tarjeta",
  "wallet_card_number_label": "Número de tarjeta",
  "wallet_card_secure_title": "Sus datos de la tarjeta están protegidos",
  "wallet_card_secure_description": "Los datos de pago son cifrados y manejados de forma segura por Stripe.",
  "wallet_card_number_placeholder": "Número de tarjeta de crédito o débito",
  "wallet_expiry_label": "Fecha de expulsión",
  "wallet_security_code_label": "Código de seguridad",
  "wallet_pay_securely": "Pagar con seguridad",
  "wallet_save_card": "Guardar",
  "wallet_no_saved_cards": "Sin tarjetas guardadas todavía",
  "wallet_cards_error": "Incapaz de cargar tarjetas guardadas. Pulsa para intentarlo de nuevo.",
  "wallet_add_card_error": "Incapaz de guardar la tarjeta",
  "wallet_setup_intent_success_title": "La configuración de la tarjeta comenzó",
  "wallet_setup_intent_success_message": "La intención de configuración creada. Complete el flujo de confirmación de la tarjeta con Stripe SDK.",
  "wallet_stripe_publishable_key_missing": "La llave publicable Stripe falta.",
  "wallet_card_incomplete": "Por favor, complete los detalles de la tarjeta.",
  "wallet_card_saved_success_title": "Tarjeta guardada",
  "wallet_card_saved_success_message": "Tu tarjeta fue agregada con éxito.",
  "off": "apagado",
  "checkout_phone_verify_title": "Verifica tu teléfono para hacer un pedido",
  "checkout_phone_verify_description": "Confirma un número de móvil antes de pagar para que podamos contactarte sobre tu pedido.",
  "checkout_phone_code_sent": "Introduce el código de cuatro dígitos enviado a {{phone}}.",
  "checkout_phone_code_error": "Revisa el código e inténtalo de nuevo.",
  "checkout_phone_send_error": "No se pudo enviar el código. Inténtalo de nuevo.",
  "checkout_phone_send": "Enviar código de verificación",
  "checkout_phone_confirm": "Verificar teléfono",
  "checkout_phone_change": "Cambiar número",
  "checkout_phone_profile_error": "No pudimos comprobar los datos de tu cuenta.",
  "chat_photo_accessibility": "Foto del chat",
  "chat_photo_permission": "Permite el acceso a las fotos para adjuntar una imagen.",
  "chat_photo_invalid": "Elige una foto JPEG, PNG o HEIC.",
  "chat_photo_too_large": "Elige una foto de menos de 10 MB.",
  "chat_photo_upload_failed": "No se pudo enviar la foto. Inténtalo de nuevo.",
  "support_chat_missing_conversation": "El chat de este ticket aún no está disponible. Inténtalo más tarde.",
  "browse_city_title": "Elige una ubicación",
  "browse_city_saved_addresses": "Direcciones guardadas",
  "browse_city_address": "Dirección",
  "browse_city_selected_address": "Dirección seleccionada",
  "browse_city_addresses_error": "No se pudieron cargar las direcciones guardadas.",
  "browse_city_add_address": "Añadir una dirección",
  "browse_city_choose_address": "Elige una dirección",
  "browse_city_continue": "Continuar",
  "browse_city_close": "Cerrar el selector de ubicación",
  "browse_city_header": "Explorando",
  "browse_city_change": "Cambiar ubicación. Explorando ahora {{city}}",
  "multi_vendor_special_offers_title": "Ofertas especiales",
  "home_deals_limited_time": "Tiempo limitado",
  "home_deals_featured_title": "Las mejores ofertas para ti",
  "home_deals_featured_description": "Ofertas por tiempo limitado de tiendas cercanas",
  "store_details_out_of_stock": "Agotado",
  "order_confirmation_placed_title": "Pedido realizado",
  "order_confirmation_step_placed": "Realizado",
  "order_tracking_chat_with_rider": "Chatear con el repartidor",
  "order_tracking_chat_unread": "Chatear con el repartidor, {{count}} mensajes sin leer",
  "favourite_foods_browse": "Explorar comidas favoritas",
  "favourite_foods_loading": "Cargando comidas favoritas",
  "favourite_foods_retry": "No se pudieron cargar las comidas favoritas. Toca para reintentar.",
  "favourite_foods_open": "Explorar productos de {{name}}",
  "favourite_foods_empty_title": "Aún no hay productos aquí",
  "favourite_foods_empty_description": "Prueba con otra comida favorita u otra ubicación."
};

export default es;
