const fr = {
  label: 'Livraisons',
  description: 'Commandez auprès de magasins ou de vendeurs.',
  header_title: 'Livraisons',
  header_subtitle: 'Choisissez un type de livraison',
  hero_badge: 'Experience demo',
  hero_subtitle:
    "Passez d'un modele de livraison a l'autre et previsualisez l'experience complete.",
  hero_pill_fast: 'Changement rapide',
  hero_pill_flexible: 'Tester tous les flux',
  section_title: 'Choisissez votre mode',
  single_vendor_title: 'Vendeur Unique',
  single_vendor_desc: 'Commandez auprès de votre magasin préféré.',
  single_vendor_chip: 'Boutique selectionnee',
  single_vendor_stat: 'Une boutique ciblee',
  multi_vendor_title: 'Multi Vendeurs',
  multi_vendor_desc: 'Parcourez et commandez auprès de plusieurs magasins.',
  multi_vendor_chip: 'Marketplace',
  multi_vendor_stat: 'Plusieurs vendeurs ensemble',
  chain_title: 'Chaîne',
  chain_desc: 'Commandez auprès de vos chaînes préférées.',
  chain_chip: 'Reseau de marques',
  chain_stat: 'Menus et emplacements de chaine',
  explore_button: 'Explorer',
  details_title: 'Détails de Livraison',
  single_vendor_categories_title: 'Catégories',
  single_vendor_category_products_empty: 'Aucun produit trouvé pour cette catégorie.',
  single_vendor_home_subtitle: 'Votre magasin préféré',
  single_vendor_home_body: 'Explorez les vendeurs et services ici.',
  single_vendor_tab_home: 'Accueil',
  single_vendor_tab_search: 'Recherche',
  single_vendor_tab_orders: 'Commandes',
  single_vendor_tab_profile: 'Profil',
  single_vendor_tab_search_placeholder: 'Les résultats de recherche et les outils de découverte apparaîtront bientôt ici.',
  single_vendor_tab_orders_placeholder: 'Vos commandes vendeur unique apparaîtront bientôt ici.',
  single_vendor_logout_error_title: 'Erreur',
  single_vendor_logout_error_message: 'Impossible de vous déconnecter pour le moment.',
  multi_vendor_home_subtitle: 'Parcourez plusieurs magasins',
  multi_vendor_home_body: 'Découvrez et commandez auprès de plusieurs vendeurs.',
  multi_vendor_home_greeting_morning: 'Bonjour 👋',
  multi_vendor_home_greeting_afternoon: 'Bon après-midi 👋',
  multi_vendor_home_greeting_evening: 'Bonsoir 👋',
  delivery_home_greeting_morning: 'Bonjour',
  delivery_home_greeting_afternoon: 'Bon après-midi',
  delivery_home_greeting_evening: 'Bonsoir',
  delivery_home_title: 'Tout ce qu’il vous faut, livré.',
  delivery_home_subtitle: 'Découvrez les commerces, plats frais et essentiels à proximité.',
  delivery_home_search_placeholder: 'Rechercher commerces, plats et essentiels',
  multi_vendor_tab_home: 'Accueil',
  multi_vendor_tab_search: 'Recherche',
  multi_vendor_tab_orders: 'Commandes',
  multi_vendor_tab_profile: 'Profil',
  chain_tab_home: 'Accueil',
  chain_tab_search: 'Recherche',
  chain_tab_orders: 'Commandes',
  chain_tab_profile: 'Profil',
  chain_logout_error_title: 'Erreur',
  chain_logout_error_message: 'Impossible de vous déconnecter pour le moment.',
  chain_categories_title: 'Catégories',
  chain_category_products_empty: 'Aucun produit trouvé pour cette catégorie.',
  chain_menu_template_selector_label: 'Sélectionner le menu de la chaîne',
  chain_menu_template_loading: 'Chargement des menus',
  chain_menu_template_empty: 'Aucun menu',
  chain_menu_template_unavailable: 'Menu indisponible',
  delivery_address_title: 'Adresse de livraison',
  delivery_address_empty_state:
    "Ajoutez une adresse pour commencer à commander dans ce magasin.",
  logout: 'Se déconnecter',
  multi_vendor_address_label: 'Sélectionner une adresse',
  delivery_header_deliver_to: 'Livrer à',
  multi_vendor_shop_types_title: 'Types de boutiques',
  multi_vendor_main_shop_types_title: 'Catégories de livraisons',
  multi_vendor_categories_title: 'Catégories',
  multi_vendor_top_brands_title: 'Marques populaires',
  multi_vendor_all_brands_title: 'Toutes les marques',
  multi_vendor_nearby_store_title: 'Magasins à proximité',
  multi_vendor_home_quick_browse: 'Tous les magasins',
  multi_vendor_home_quick_deals: 'Offres',
  multi_vendor_home_quick_orders: 'Commander à nouveau',
  multi_vendor_home_quick_favourites: 'Favoris',
  multi_vendor_deals_title: 'Offres',
  multi_vendor_recommended_restaurants_title: 'Restaurants recommandés',
  deals_see_all_tab_all: 'Tout',
  deals_see_all_tab_limited: 'Offres limitees',
  deals_see_all_tab_weekly: 'Offres hebdomadaires',
  deals_see_all_ends_in: 'Se termine dans',
  deals_see_all_section_title: 'Tous les articles proposes',
  deals_see_all_section_title_limited: 'Offres a duree limitee',
  deals_see_all_section_title_weekly: 'Offres hebdomadaires',
  deals_see_all_badge_percentage: '{{value}} % de reduction',
  deals_see_all_badge_fixed: '{{value}} de reduction',
  multi_vendor_order_again_title: 'Commander a nouveau 😋',
  'main see all': 'Voir principal',
  multi_vendor_see_all: 'Voir tout',
  multi_vendor_order_again_add_item: 'Ajouter un article',
  multi_vendor_order_again_price_unavailable: 'Prix indisponible',
  multi_vendor_nearby_store_name_hardees: "Hardee's - Bloc Z",
  multi_vendor_nearby_store_name_subway: 'Subway - Bloc Z',
  multi_vendor_nearby_store_category_fast_food: 'Restauration rapide',
  multi_vendor_nearby_store_category_pure_veg: 'Vegetarien',
  multi_vendor_nearby_store_review_count: '(5000+)',
  multi_vendor_nearby_store_delivery_fee: '$2',
  multi_vendor_nearby_store_delivery_time: '30 min',
  multi_vendor_nearby_store_distance: '1.7 km',
  multi_vendor_sponsored_label: 'Sponsorisé',
  multi_vendor_cart_label: 'Panier',
  multi_vendor_shop_type_gift: 'Livraison de cadeaux',
  multi_vendor_shop_type_milk: 'Livraison de lait',
  multi_vendor_shop_type_flower: 'Livraison de fleurs',
  multi_vendor_shop_type_liquor: "Livraison d'alcool",
  multi_vendor_shop_type_products_empty: 'Aucun produit trouve pour ce type de boutique.',
  multi_vendor_shop_type_stores_empty: 'Aucun magasin trouve pour ce type de boutique.',
  multi_vendor_shop_types_empty: 'Aucun type de boutique de livraison n’est disponible pour le moment.',
  multi_vendor_location_stores_empty: 'Aucun magasin n’est disponible pour cet emplacement.',
  multi_vendor_shop_type_products_error: 'Impossible de charger les produits pour le moment.',
  multi_vendor_shop_type_stores_error: 'Impossible de charger les magasins pour le moment.',
  multi_vendor_home_section_empty_title: 'Aucun résultat pour le moment',
  multi_vendor_home_section_empty_message: 'Les nouveautés et les offres limitées apparaîtront ici dès qu’elles seront disponibles.',
  multi_vendor_home_section_error_title: 'Impossible de charger les articles',
  multi_vendor_home_section_error_message: 'Veuillez réessayer dans un instant.',
  multi_vendor_home_section_empty_order_again: 'Vos choix récents apparaîtront ici après votre première commande.',
  multi_vendor_home_empty_order_again_title: 'Prêt pour un nouveau favori ?',
  multi_vendor_home_empty_explore_action: 'Explorer les magasins',
  multi_vendor_home_empty_order_action: 'Explorer maintenant',
  store_details_search_placeholder: 'Rechercher dans le menu…',
  store_details_hero_title: 'Composez\nvotre repas.',
  store_details_store_name: 'Subway @ Old Town, Nouveau-Mexique',
  store_details_store_phone: '555-0123',
  store_details_store_email: 'support@subway.com',
  store_details_store_hours: '9 h a 18 h',
  store_details_call_label: 'Appelez-nous au',
  store_details_email_label: 'ou ecrivez a',
  store_details_tab_offers: 'Offres',
  store_details_tab_pizza: 'Pizza',
  store_details_tab_burgers: 'Burgers',
  store_details_tab_pasta: 'Pasta',
  store_details_tab_sushi: 'Sushi',
  store_details_subcategory_italian_classic: 'Classique italien',
  store_details_subcategory_american_style: 'Style americain',
  store_details_subcategory_pepperoni: 'Pepperoni',
  store_details_subcategory_bbq_chicken: 'Poulet BBQ',
  store_details_subcategory_thin_crust: 'Pate fine',
  store_details_all_offered_items: 'Tous les articles en offre',
  store_details_no_items: 'Aucun article ne correspond encore a ce filtre.',
  store_details_load_error: 'Impossible de charger les details du magasin pour le moment.',
  store_details_hours_unavailable: 'Horaires indisponibles',
  store_details_store_missing: 'Les details du magasin ne sont pas disponibles.',
  store_details_action_info: 'Infos du magasin',
  store_details_action_favorite: 'Ajouter le magasin aux favoris',
  store_details_action_remove_favorite: 'Retirer le magasin des favoris',
  store_details_action_share: 'Partager le magasin',
  store_details_action_back: 'Retour',
  store_details_about_title: 'A propos de nous',
  store_details_about_fallback: 'La description du magasin n est pas disponible pour le moment.',
  store_details_closed_store_title: '{{storeName}} est actuellement fermé',
  store_details_closed_store_description:
    '{{storeName}} est actuellement fermé. Veuillez réessayer plus tard.',
  store_details_closed_store_fallback_name: 'Ce magasin',
  store_closed_modal_title: '{{storeName}} est actuellement fermé',
  store_closed_see_menu: 'Voir le menu',
  store_status_closed: 'Fermé',
  store_status_open: 'Ouvert',
  store_details_delivery_minutes: '{{minutes}} min',
  store_details_minimum_order: 'Min. {{amount}}',
  store_details_close: 'Fermer',
  store_details_info_address: 'Adresse : {{address}}',
  store_details_info_phone: 'Téléphone : {{phone}}',
  store_details_info_email: 'E-mail : {{email}}',
  store_details_view_cart: 'Voir le panier',
  store_details_cart_summary: '{{count}} articles · {{amount}}',
  store_details_add_product: 'Ajouter {{item}}',
  store_details_badge_deal: 'Offre',
  store_details_badge_ten_percent_off: '10 % de reduction',
  store_details_item_chicken_fajita: 'Poulet fajita',
  store_details_item_chicken_teriyaki: 'Poulet teriyaki',
  store_details_item_burger: 'Burger',
  store_details_item_sushi: 'Sushi',
  store_details_item_alfredo_pasta: 'Pasta Alfredo',
  store_details_item_veggie_delight: 'Veggie Delight',
  chain_home_subtitle: 'Chaînes favorites',
  chain_home_body: 'Commandez auprès de vos chaînes préférées.',
  type_single_vendor_title: 'Magasin Vendeur Unique',
  type_single_vendor_desc: 'Uniquement des vendeurs premium sélectionnés',
  type_marketplace_title: 'Marketplace',
  type_marketplace_desc: 'Nombreux prestataires locaux',
  type_chain_title: 'Magasins de Chaîne',
  type_chain_desc: 'Achetez vos chaînes préférées',
  // Profile screen
  profile_personal_account: 'Compte personnel',
  profile_wallet_balance: 'Solde du portefeuille',
  profile_view_wallet: 'Voir le portefeuille',
  profile_menu_profile: 'Profil',
  profile_menu_notifications: 'Notifications',
  profile_menu_favorites: 'Favoris',
  profile_menu_coupons: 'Coupons',
  profile_menu_settings: 'Paramètres',
  profile_menu_support: 'Assistance',
  profile_menu_color_mode: 'Mode couleur',
  profile_menu_language: 'Français',
  profile_menu_logout: 'Se déconnecter',
  // Coupons screen
  coupon_title: 'Coupons',
  coupon_description:
    "Si vous avez un code promo Livraison, un code de parrainage ou une carte cadeau, saisissez-le ici pour obtenir vos avantages.",
  coupon_input_placeholder: 'Entrer le code',
  coupon_use: 'Utiliser',
  coupon_off: 'Off',
  coupon_valid_until: 'Valide : {{date}}',
  coupon_claim: 'Réclamer',
  coupon_claim_success_title: 'Coupon réclamé',
  coupon_claim_error_title: 'Impossible de réclamer le coupon',
  coupon_claim_error_fallback: 'Veuillez saisir un code valide et réessayer.',
  coupon_list_error_fallback: 'Impossible de charger les coupons réclamés pour le moment.',
  coupon_used: 'Utilisé',
  coupon_use_success_title: 'Coupon activé',
  coupon_use_success_message: 'Vous pouvez maintenant l’utiliser.',
  coupon_use_error_title: "Impossible d'activer le coupon",
  coupon_use_error_fallback: 'Veuillez réessayer.',
  coupon_deactivate: 'Désactiver',
  coupon_deactivate_success_title: 'Coupon désactivé',
  coupon_deactivate_success_message: "Ce code promo n'est plus actif.",
  coupon_deactivate_error_title: 'Impossible de désactiver le coupon',
  coupon_deactivate_error_fallback: 'Veuillez réessayer.',
  coupon_status_expired: 'Expiré',
  coupon_min_order: 'Min. commande €{{value}}',
  coupon_store_fallback: 'Magasin partenaire',
  coupon_store_with_more: '{{store}} et {{count}} autre(s)',
  coupon_claimed_state_title: 'Vous venez de recevoir le coupon !',
  coupon_claimed_state_body_line_one: 'Super ! Votre code promo a été appliqué.',
  coupon_claimed_state_body_line_two: 'La réduction apparaîtra automatiquement au paiement.',
  coupon_empty_title: 'Aucun coupon pour le moment',
  coupon_empty_description:
    "Vous n'avez aucun coupon pour le moment. Saisissez un code promo ci-dessus pour trouver des offres.",
  // My Profile screen
  my_profile_title: 'Mon profil',
  my_profile_edit: 'Modifier',
  my_profile_full_name: 'Nom complet',
  my_profile_date_of_birth: 'Date de naissance',
  my_profile_mobile_number: 'Numéro de téléphone',
  my_profile_email: 'E-mail',
  my_profile_my_addresses: 'Mes adresses',
  my_profile_add_address: 'Ajouter une adresse',
  my_profile_address_home: 'Domicile',
  my_profile_address_apartment: 'Appartement',
  my_profile_address_work: 'Travail',
  my_profile_address_other: 'Autre',
  // Profile photo modal
  photo_modal_title: 'Photo de profil',
  photo_modal_description: 'Choisissez comment mettre à jour votre photo de profil',
  photo_take_photo: 'Prendre une photo',
  photo_choose_gallery: 'Choisir dans la galerie',
  photo_cancel: 'Annuler',
  photo_permission_title: 'Autorisation requise',
  photo_permission_camera: "L'accès à la caméra est nécessaire pour prendre une photo.",
  photo_permission_gallery: "L'accès à la galerie est nécessaire pour choisir une photo.",
  photo_upload_error_title: 'Échec du téléchargement',
  photo_upload_failed: 'Impossible de mettre à jour la photo de profil.',
  // Edit Profile screen
  edit_profile_title: 'Modifier le profil',
  edit_profile_name: 'Nom',
  edit_profile_date_of_birth: 'Date de naissance',
  edit_profile_day: 'Jour',
  edit_profile_month: 'Mois',
  edit_profile_year: 'Année',
  edit_profile_gender: 'Genre',
  edit_profile_gender_placeholder: 'Sélectionner une option',
  edit_profile_save: 'Enregistrer',
  edit_profile_success: 'Succès',
  edit_profile_success_message: 'Profil mis à jour avec succès.',
  edit_profile_error: 'Erreur',
  edit_profile_name_required: 'Le nom est requis.',
  edit_profile_failed: 'Impossible de mettre à jour le profil.',
  // Address screens
  address_list_title: 'Mes adresses',
  address_add_title: 'Ajouter une adresse',
  address_edit_title: "Modifier l'adresse",
  address_search_placeholder: 'Rechercher une adresse',
  address_choose_on_map: 'Choisir sur la carte',
  address_recent_searches: 'Recherches récentes',
  address_no_results: 'Aucun résultat trouvé',
  address_confirm_location: "Confirmer l'emplacement",
  address_locating: 'Localisation…',
  address_selected_location: 'Emplacement sélectionné',
  address_location_name_placeholder: 'Nom du lieu (ex. Ma maison)',
  address_details_label: "Détails de l'adresse",
  address_location_type_label: 'Type de lieu',
  address_location_details_label: 'Détails du lieu',
  address_detail_house_placeholder: 'Maison',
  address_detail_apartment_placeholder: 'Appartement / Flat',
  address_detail_office_placeholder: 'Bureau / Immeuble',
  address_detail_place_placeholder: 'Lieu',
  address_detail_society_placeholder: 'Société / Résidence',
  address_detail_floor_placeholder: 'Étage / Tour',
  address_detail_department_placeholder: 'Service / Étage',
  address_detail_area_placeholder: 'Zone / Rue',
  address_detail_landmark_placeholder: 'Repère',
  address_optional_suffix: '(facultatif)',
  address_type_home: 'Domicile',
  address_type_apartment: 'Appartement',
  address_type_office: 'Bureau',
  address_type_other: 'Autre',
  address_save: "Enregistrer l'adresse",
  address_update: "Mettre à jour l'adresse",
  address_delete: 'Supprimer',
  address_delete_confirm_title: "Supprimer l'adresse",
  address_delete_confirm_message: 'Êtes-vous sûr de vouloir supprimer cette adresse ?',
  address_delete_cancel: 'Annuler',
  address_delete_confirm: 'Supprimer',
  address_save_error: "Impossible d'enregistrer l'adresse.",
  address_select_error: "Impossible de sélectionner l'adresse.",
  address_delete_error: "Impossible de supprimer l'adresse.",
  address_save_success: 'Adresse enregistrée avec succès.',
  address_update_success: 'Adresse mise à jour avec succès.',
  address_delete_success: 'Adresse supprimée avec succès.',
  address_selector_title: 'Emplacement',
  address_selector_close: "Fermer le sélecteur d'emplacement",
  address_selector_use_current_location: 'Utiliser ma position actuelle',
  address_selector_add_new: 'Ajouter une nouvelle adresse',
  // Favourites screen
  favourites_title: 'Vos Favoris',
  favourites_empty_title: "Aucun favori pour l'instant",
  favourites_empty_subtitle: 'Les magasins que vous aimez apparaîtront ici.',
  favourites_error: 'Impossible de charger les favoris. Tirez vers le bas pour réessayer.',
  favourites_free_delivery: 'Livraison gratuite',
  favourites_remove: 'Retirer des favoris',
  favourites_add: 'Ajouter aux favoris',
  favourites_toggle_added: 'Ajouté aux favoris',
  favourites_toggle_removed: 'Retiré des favoris',
  favourites_toggle_error: 'Échec de la mise à jour des favoris',
  // Rate order screen
  rate_order_title: 'Évaluer votre commande',
  rate_order_heading: 'Comment était votre repas ?',
  rate_order_subheading: 'Vos commentaires nous aident à améliorer notre livraison.',
  rate_order_comment_placeholder: 'Écrivez votre expérience ici...',
  rate_order_submit: 'Soumettre',
  rate_order_submitted_heading: 'Merci pour votre évaluation !',
  rate_order_submitted_subheading:
    'Vous avez déjà évalué cette commande. Vos commentaires nous aident à améliorer notre service de livraison.',
  rate_order_submitted_no_comment:
    "Aucun commentaire n'a été ajouté à cette évaluation.",
  rate_order_success_title: 'Merci !',
  rate_order_success_message: 'Votre avis a été soumis.',
  rate_order_error_title: 'Échec de la soumission',
  // Settings screen
  settings_title: 'Paramètres',
  settings_notifications: 'Paramètres de notifications',
  settings_change_password: 'Changer le mot de passe',
  settings_privacy_policy: 'Politique de confidentialité',
  settings_terms_of_service: "Conditions d'utilisation",
  settings_terms_of_use: "Conditions d'usage",
  settings_delete_account: 'Supprimer le compte',
  settings_app_version: "Version de l'application 1.0.0",
  // Notification settings screen
  notif_settings_title: 'Paramètres de notifications',
  notif_settings_food_delivery: 'Livraison de nourriture',
  notif_settings_marketing: 'Marketing',
  notif_settings_email: 'E-mail',
  notif_settings_sms: 'SMS',
  notif_settings_whatsapp: 'WhatsApp',
  notif_settings_success_title: 'Enregistré',
  notif_settings_success_message: 'Préférence de notification mise à jour.',
  notif_settings_error_title: 'Erreur',
  // Privacy Policy screen
  privacy_screen_header: 'Politique de confidentialité',
  privacy_title: 'Politique de confidentialité',
  privacy_last_updated: 'Dernière mise à jour il y a 2 mois',
  privacy_intro:
    "Cette politique de confidentialité explique comment nous traitons vos informations personnelles lors de l'utilisation de l'application de livraison de nourriture. En vous inscrivant ou en accédant à l'application, vous consentez aux pratiques décrites dans cette politique.",
  privacy_section_app_title: "Politique de confidentialité pour l'application",
  privacy_section_app_body:
    "L'application de livraison de nourriture s'engage à protéger et gérer vos données personnelles et commandes en toute sécurité. Vous êtes autorisé à utiliser l'application à des fins personnelles et commerciales, sous réserve de respecter cette politique et toutes les lois applicables.",
  privacy_section_responsibilities_title: 'Responsabilités des utilisateurs',
  privacy_section_responsibilities_body:
    "Les utilisateurs sont responsables de l'exactitude de leurs adresses de livraison et de leurs informations de paiement. Il est important de maintenir ces informations à jour pour éviter tout problème lors du processus de commande.",
  privacy_section_data_title: 'Collecte de données',
  privacy_section_data_body:
    "L'application de livraison de nourriture collecte des données essentielles pour améliorer votre expérience, notamment votre localisation, l'historique de vos commandes et vos préférences.",
  privacy_section_modifications_title: 'Modifications de commande',
  privacy_section_modifications_body:
    "Vous pouvez modifier ou annuler vos commandes via l'application avant qu'elles ne soient traitées. Une fois une commande confirmée, les modifications peuvent ne pas être possibles.",
  privacy_section_payment_title: 'Sécurité des paiements',
  privacy_section_payment_body:
    "Nous accordons la priorité à la sécurité de vos informations de paiement. Toutes les transactions effectuées via l'application sont traitées à l'aide d'une technologie de chiffrement standard.",
  privacy_section_contact_title: 'Nous contacter',
  privacy_section_contact_body: 'Si vous avez des questions sur ces conditions, n\'hésitez pas à nous contacter :',
  privacy_contact_email: 'E-mail : contact@fooddelivery.com',
  privacy_contact_address: 'Adresse : Doha, Qatar',
  // Terms of Service screen
  tos_screen_header: "Conditions d'utilisation",
  tos_title: "Conditions d'utilisation",
  tos_last_updated: 'dernière mise à jour il y a 2 mois',
  tos_intro:
    "Ces conditions d'utilisation définissent votre accès et votre utilisation de l'application de livraison de nourriture.",
  tos_section_usage_title: 'Utilisation du service',
  tos_section_usage_body:
    "L'application de livraison de nourriture fournit une plateforme fiable pour commander et gérer vos livraisons de repas.",
  tos_section_orders_title: 'Gestion des commandes',
  tos_section_orders_body:
    "L'application vous permet de suivre facilement vos commandes, de modifier les détails ou de les annuler dans le délai imparti.",
  tos_section_payment_title: 'Sécurité des paiements',
  tos_section_payment_body:
    "Les paiements via l'application sont traités de manière sécurisée avec une technologie de chiffrement.",
  tos_section_delivery_title: 'Politiques de livraison',
  tos_section_delivery_body:
    'Les utilisateurs sont encouragés à fournir des adresses de livraison précises pour faciliter un service rapide et efficace.',
  tos_section_support_title: 'Service client',
  tos_section_support_body:
    "L'application fournit un système d'assistance robuste pour répondre à toutes les questions ou problèmes.",
  tos_section_contact_title: 'Nous contacter',
  tos_section_contact_body: 'Si vous avez des questions sur ces conditions, n\'hésitez pas à nous contacter :',
  tos_contact_email: 'E-mail : contact@fooddelivery.com',
  tos_contact_address: 'Adresse : Doha, Qatar',
  // Terms of Use screen
  tou_screen_header: "Conditions d'usage",
  tou_title: "Conditions d'usage",
  tou_last_updated: 'mise à jour il y a 2 mois',
  tou_intro:
    "Ces conditions d'utilisation définissent vos droits et responsabilités lors de l'utilisation de l'application.",
  tou_section_guidelines_title: "Directives d'utilisation",
  tou_section_guidelines_body:
    "L'application fournit une gestion sécurisée de vos commandes et données client.",
  tou_section_etiquette_title: 'Étiquette de livraison',
  tou_section_etiquette_body:
    'Les utilisateurs doivent maintenir le respect et la courtoisie envers le personnel de livraison.',
  tou_section_payment_title: 'Méthodes de paiement',
  tou_section_payment_body:
    "L'application prend en charge plusieurs méthodes de paiement, notamment les cartes de crédit et les portefeuilles numériques.",
  tou_section_cancellation_title: "Politique d'annulation",
  tou_section_cancellation_body:
    'Les commandes peuvent être annulées dans un délai de 10 minutes après leur passation.',
  tou_section_feedback_title: 'Commentaires et évaluations',
  tou_section_feedback_body:
    "Les utilisateurs sont encouragés à donner leur avis sur leur expérience de livraison.",
  tou_section_promotions_title: 'Promotions et offres',
  tou_section_promotions_body:
    "L'application peut proposer des promotions et des réductions soumises à des conditions spécifiques.",
  tou_section_contact_title: 'Nous contacter',
  tou_section_contact_body: 'Si vous avez des questions, n\'hésitez pas à nous contacter :',
  tou_contact_email: 'E-mail : contact@fooddelivery.com',
  tou_contact_address: 'Adresse : Doha, Qatar',
  // Search / map
  products: 'Produits',
  stores: 'Magasins',
  see_all: 'Voir tout',
  filter_title: 'Filtrer',
  filter_close_label: 'Fermer les filtres',
  filter_apply_results: 'Appliquer les filtres',
  filter_category_title: 'Catégorie',
  filter_price_title: 'Prix',
  filter_address_title: 'Adresse à proximité',
  filter_stock_title: 'Stock',
  filter_sort_title: 'Trier par',
  generic_list_error_title: 'Impossible de charger les résultats',
  generic_list_error_description: 'Actualisez ou réessayez.',
  generic_list_retry: 'Réessayer',
  generic_list_empty_title: 'Aucun résultat trouvé',
  generic_list_empty_description: 'Essayez une autre recherche ou modifiez vos filtres.',
  generic_list_search_placeholder: 'Recherche',
  see_all_map_loading_title: 'Recherche de {{title}}',
  see_all_map_loading_description: 'Cela peut prendre quelques instants. Veuillez rester sur cet écran.',
  see_all_map_sheet_title: 'Restaurant',
  see_all_map_cta: 'Voir le restaurant',
  // Change password flow
  change_password_title: 'Changer le mot de passe',
  change_password_new_title: 'Nouveau mot de passe',
  change_password_email_heading: 'Changer le mot de passe ?',
  change_password_email_description:
    'Entrez votre adresse e-mail et nous vous enverrons un code de vérification.',
  change_password_email_placeholder: 'votre@email.com',
  change_password_continue: 'Continuer',
  change_password_verify_heading: 'Vérifiez votre e-mail',
  change_password_verify_description: 'Entrez le code à 4 chiffres envoyé à {{email}}',
  change_password_verify_button: 'Vérifier le code',
  change_password_new_heading: 'Créez votre nouveau mot de passe',
  change_password_new_description: "Votre nouveau mot de passe doit être différent de l'ancien.",
  change_password_new_placeholder: 'Nouveau mot de passe',
  change_password_confirm_placeholder: 'Confirmer le mot de passe',
  change_password_set_new: 'Définir le nouveau mot de passe',
  change_password_mismatch: 'Les mots de passe ne correspondent pas.',
  change_password_error_title: 'Erreur',
  change_password_send_otp_error: "Échec de l'envoi du code de vérification.",
  change_password_verify_otp_error: 'Code invalide ou expiré.',
  change_password_update_error: 'Échec de la mise à jour du mot de passe.',
  change_password_success_title: 'Succès',
  change_password_success_message: 'Votre mot de passe a été mis à jour.',
  change_password_otp_resent_title: 'Code envoyé',
  change_password_otp_resent_message: 'Un nouveau code de vérification a été envoyé.',
  // Delete account flow
  delete_account_step_label: 'Supprimer mon compte',
  delete_account_sorry_heading: 'Nous serons désolés de vous voir partir',
  delete_account_sorry_subtext: 'Pouvons-nous vous faire changer d\'avis ? Contactez-nous à',
  delete_account_contact_email: 'hello@enategadelivery.com',
  delete_account_reason_heading: 'Pourquoi souhaitez-vous quitter Food delivery ?',
  delete_account_reason_subtext: 'Veuillez nous indiquer la raison de la suppression de votre compte :',
  delete_account_reason_mistake: 'J\'ai créé ce compte par erreur',
  delete_account_reason_no_longer: 'Je ne veux plus utiliser Food delivery',
  delete_account_reason_no_venues: 'Je ne trouve pas les établissements ou services que je veux',
  delete_account_reason_other: 'Autre',
  delete_account_confirm_heading: 'Supprimer votre compte Food delivery',
  delete_account_confirm_description: 'Cette action supprimera votre compte et vous ne pourrez pas le récupérer. Veuillez confirmer que vous comprenez en cochant les déclarations ci-dessous :',
  delete_account_confirm_item_orders: 'Je sais que je ne pourrai plus accéder à mes commandes.',
  delete_account_confirm_item_marketplace: 'Je sais que je ne pourrai plus passer de commandes via la marketplace Food delivery.',
  delete_account_final_heading: 'Confirmez que vous souhaitez continuer',
  delete_account_final_description: 'Veuillez noter que cette action est permanente et ne peut pas être annulée. Pour confirmer la suppression de votre compte, veuillez vérifier votre e-mail ci-dessous :',
  delete_account_email_label: 'E-mail',
  delete_account_email_placeholder: 'votre@email.com',
  delete_account_cta_continue: 'Continuer',
  delete_account_cta_delete: 'Supprimer le compte',
  delete_account_close: 'Fermer',
  delete_account_alert_title: 'Supprimer le compte',
  delete_account_alert_message: 'Êtes-vous sûr de vouloir supprimer définitivement votre compte ? Cette action est irréversible.',
  delete_account_alert_cancel: 'Annuler',
  delete_account_alert_confirm: 'Supprimer',
  delete_account_error_title: 'Erreur',
  delete_account_error: 'Échec de la suppression du compte. Veuillez réessayer.',
  // Color mode screen
  color_mode_title: 'Mode couleur',
  color_mode_section_label: 'Sélectionner le mode couleur',
  color_mode_system: 'Système par défaut',
  color_mode_light: 'Clair',
  color_mode_dark: 'Sombre',
  // Language screen
  language_title: 'Langues de l\'application',
  language_section_label: 'Sélectionner la langue',
  language_english: 'Anglais',
  language_french: 'Français',
  popular: 'Populaire',
  ingredients: 'Ingrédients',
  usage: 'Utilisation',
  nutrition_facts: 'Valeurs nutritionnelles',
  amount_per: 'Quantité pour',
  energy: 'Énergie',
  fat: 'Matières grasses',
  carbohydrates: 'Glucides',
  protein: 'Protéines',
  sugar: 'Sucre',
  choose_size: 'Choisir la taille',
  choose_variation: 'Choisir la variation',
  select_one: 'Sélectionnez-en un',
  required_label: 'Obligatoire',
  optional_label: 'Optionnel',
  small: 'Petit',
  medium: 'Moyen',
  large: 'Grand',
  choose_your_flavour: 'Choisissez votre saveur',
  choose_your_addons: 'Choisissez vos suppléments',
  add_to_cart: 'Ajouter au panier',
  cart_title: 'Panier',
  cart_items_title: 'Vos articles',
  cart_add_more: 'Ajouter plus',
  cart_recommended_title: 'Recommandé pour vous',
  cart_checkout: 'Passer au paiement',
  checkout_title: 'Paiement',
  checkout_fulfillment_delivery: 'Livraison',
  checkout_fulfillment_pickup: 'Retrait',
  checkout_address_title: 'Choisissez une adresse de livraison',
  checkout_address_subtitle: 'Touchez ici pour continuer',
  checkout_address_selected_subtitle: 'Touchez ici pour modifier',
  checkout_pickup_title: 'Lieu de retrait',
  checkout_pickup_subtitle: 'Récupérez votre commande au magasin',
  checkout_leave_at_door_title: 'Laisser à la porte',
  checkout_message_restaurant_title: 'Ajouter un message pour le restaurant',
  checkout_message_restaurant_subtitle: 'Demandes spéciales, allergies, restrictions alimentaires ?',
  checkout_message_restaurant_editor_title: 'Instructions pour le restaurant',
  checkout_message_restaurant_editor_description: 'Demandes spéciales, allergies, restrictions alimentaires ?',
  checkout_message_restaurant_placeholder: 'Ajoutez des demandes spéciales (facultatif)',
  checkout_message_courier_title: 'Ajouter un message pour le livreur',
  checkout_message_courier_subtitle: 'Ajoutez toute instruction importante, repère ou demande spéciale.',
  checkout_message_courier_editor_title: 'Instructions pour le livreur',
  checkout_message_courier_editor_description: 'Ajoutez toute instruction importante, repère ou demande spéciale.',
  checkout_message_courier_placeholder: 'Ajoutez des instructions de livraison (facultatif)',
  checkout_message_done: 'Terminé',
  checkout_delivery_time_title: 'Heure de livraison',
  checkout_collection_time_title: 'Heure de retrait',
  checkout_delivery_time_standard: 'Standard',
  checkout_delivery_time_standard_eta: '10-20 min',
  checkout_delivery_time_schedule: 'Planifier',
  checkout_delivery_time_schedule_hint: 'Choisissez une heure de livraison',
  checkout_schedule_title: 'Planifier l’heure de livraison',
  checkout_schedule_today: 'Aujourd’hui',
  checkout_schedule_tomorrow: 'Demain',
  checkout_schedule_asap: 'Dès que possible',
  checkout_schedule_confirm: 'Confirmer',
  checkout_schedule_empty_title: 'Aucun créneau disponible',
  checkout_schedule_empty_message: 'Essayez un autre jour ou continuez avec la livraison standard.',
  checkout_schedule_error_title: 'Impossible de charger les créneaux',
  checkout_schedule_error_message: 'Veuillez réessayer pour récupérer les créneaux disponibles.',
  checkout_schedule_slot_expired: 'Ce créneau n’est plus disponible. Veuillez en choisir un autre.',
  checkout_schedule_unavailable_note: 'La précommande n’est pas disponible les dimanches et jours fériés.',
  checkout_payment_title: 'Paiement',
  checkout_payment_selector_title: 'Mode de paiement',
  checkout_payment_selector_heading: 'Choisissez un mode de paiement',
  checkout_payment_selector_description: 'Selectionnez comment vous souhaitez payer cette commande.',
  checkout_payment_selector_confirm: 'Confirmer le mode de paiement',
  checkout_payment_cash_title: 'Espèces',
  checkout_payment_cash_subtitle: 'Payez en espèces à la livraison ou au retrait',
  checkout_payment_card_title: 'Carte',
  checkout_payment_card_subtitle: 'Payez en ligne de manière sécurisée avec votre carte',
  checkout_payment_wallet_title: 'Portefeuille',
  checkout_payment_wallet_subtitle: 'Payez avec le solde de votre portefeuille',
  checkout_payment_option_wallet_description: 'Payez avec le solde de votre portefeuille.',
  checkout_payment_wallet_insufficient_balance: 'Solde du portefeuille insuffisant pour cette commande.',
  checkout_payment_wallet_balance: 'Solde du portefeuille : {{currency}} {{amount}}',
  checkout_payment_card_saved_subtitle: '{{brand}} (•••• {{last4}})',
  checkout_payment_option_cash_description: 'Payez à la livraison ou au retrait.',
  checkout_payment_option_card_description: 'Vous terminerez le paiement dans le parcours sécurisé Stripe.',
  checkout_payment_add_card_required: 'Ajoutez une carte dans le portefeuille pour payer par carte.',
  checkout_payment_cash_unavailable: 'Le paiement en espèces à la livraison n’est pas disponible pour ce magasin',
  checkout_payment_card_unavailable: 'Le paiement par carte n’est pas disponible pour ce magasin',
  checkout_payment_cod_unavailable_error: 'Ce magasin n’autorise pas le paiement en espèces à la livraison.',
  checkout_payment_card_unavailable_error: 'Ce magasin n’autorise pas les paiements par carte.',
  checkout_payment_webview_title: 'Finaliser le paiement',
  checkout_payment_processing_title: 'Confirmation de votre paiement',
  checkout_payment_processing_message: 'Veuillez patienter pendant que nous verifions votre paiement et creons votre commande.',
  checkout_payment_processing_error: 'Nous verifions encore votre paiement. Veuillez patienter un instant.',
  checkout_payment_cancelled: 'Le paiement a ete annule.',
  checkout_payment_failed: 'Le paiement a echoue. Veuillez reessayer avec un autre mode.',
  checkout_payment_card_redirecting: 'Terminez votre paiement dans le navigateur pour finaliser cette commande.',
  checkout_payment_card_redirect_error: 'Impossible d’ouvrir le paiement sécurisé pour le moment.',
  checkout_leave_at_door_card_required: 'L’option \"Laisser à la porte\" nécessite un paiement par carte. Veuillez choisir la carte pour continuer.',
  checkout_leave_at_door_switched_to_card: 'Le mode de paiement a été basculé sur carte pour la livraison sans contact.',
  checkout_promo_title: 'Code promo',
  checkout_promo_subtitle: 'Touchez ici pour continuer',
  checkout_promo_tap_to_change: 'Touchez ici pour modifier',
  checkout_promo_remove: 'Retirer',
  checkout_promo_removed: 'Code promo retiré',
  checkout_tip_title: 'Donnez un pourboire à votre livreur',
  checkout_tip_description: 'Le pourboire sera versé intégralement au livreur.',
  checkout_tip_custom: 'Personnalisé',
  checkout_tip_custom_title: 'Ajouter un pourboire personnalisé',
  checkout_tip_custom_placeholder: '0.00',
  checkout_tip_custom_done: 'Terminé',
  checkout_summary_title: 'Résumé',
  checkout_summary_hint: 'taxes incluses (si applicables)',
  checkout_summary_subtotal: 'Sous-total',
  checkout_summary_discount: 'Remise',
  checkout_summary_delivery_fee: 'Frais de livraison',
  checkout_summary_packing_charges: 'Frais d’emballage',
  checkout_summary_tax: 'Taxes',
  checkout_summary_tip: 'Pourboire du livreur',
  checkout_summary_total: 'Total',
  checkout_summary_free: 'Gratuit',
  checkout_place_order: 'Passer la commande',
  checkout_place_order_pending: 'La validation de commande sera disponible à l’étape suivante.',
  checkout_place_order_success: 'Commande passée avec succès.',
  checkout_place_order_error: 'Impossible de passer votre commande pour le moment.',
  checkout_address_required: 'Veuillez d’abord choisir une adresse de livraison.',
  checkout_promo_pending: 'La prise en charge des codes promo sera ajoutée à l’étape suivante.',
  checkout_preview_error_title: 'Impossible de charger le paiement',
  checkout_preview_error_message: 'Veuillez réessayer dans un instant.',
  checkout_store_closed_title: 'La boutique est fermée',
  checkout_store_closed_message:
    'Cette boutique est actuellement fermée. Veuillez réessayer pendant ses heures d’ouverture.',
  checkout_payment_wallet_title: 'Portefeuille',
  checkout_payment_wallet_subtitle:
    'Payez avec le solde de votre portefeuille',
  checkout_payment_option_wallet_description:
    'Payez avec le solde de votre portefeuille.',
  checkout_payment_wallet_insufficient_balance:
    'Solde insuffisant pour cette commande.',
  checkout_payment_wallet_balance:
    'Solde du portefeuille : {{currency}} {{amount}}',
  cart_empty_title: 'Votre panier est vide',
  cart_empty_message: 'Lorsque vous ajoutez des articles depuis une boutique, votre commande apparaîtra ici pour que vous puissiez la modifier quand vous le souhaitez.',
  cart_start_shopping: 'Commencer vos achats',
  cart_error_title: 'Impossible de charger votre panier',
  cart_error_message: 'Veuillez réessayer dans un instant.',
  cart_remove_item: 'Retirer l’article',
  cart_decrement_item: 'Diminuer la quantité',
  cart_increment_item: 'Augmenter la quantité',
  cart_info_label: 'Frais de commande et minimum',
  cart_low_order_fee_applies_prefix: 'Des frais de petite commande de ',
  cart_low_order_fee_applies_suffix: ' s’appliquent',
  cart_fee_modal_title: 'Frais de commande et minimum',
  cart_fee_modal_description_prefix: 'Le montant minimum du panier est de ',
  cart_fee_modal_description_suffix: '.',
  cart_fee_modal_total_cart_value: 'Valeur totale du panier',
  cart_fee_modal_service_fee: 'Frais de service',
  cart_fee_modal_above: 'et plus',
  cart_fee_modal_no_fee: 'Aucun frais',
  cart_fee_modal_note_prefix: '* Pour les commandes inférieures à ',
  cart_fee_modal_note_middle: ', des frais de petite commande de ',
  cart_fee_modal_note_suffix: ' s’appliquent',
  cart_store_conflict_title: 'Remplacer votre panier actuel ?',
  cart_store_conflict_message:
    "Votre panier contient deja des articles d'une autre boutique. Remplacez-le pour ajouter des articles de {{incomingStore}}.",
  cart_store_conflict_message_with_product:
    "Votre panier contient deja des articles d'une autre boutique. Remplacez-le pour ajouter {{product}} depuis {{incomingStore}}.",
  cart_store_conflict_keep_cart: 'Garder le panier actuel',
  cart_store_conflict_replace_cart: 'Remplacer le panier',
  cart_store_conflict_store_fallback: 'cette boutique',
  cart_action_loading_options_title: 'Preparation des options',
  cart_action_loading_options_message:
    'Veuillez patienter pendant le chargement des personnalisations disponibles pour cet article.',
  cart_action_customization_required_title: 'Choisissez d’abord vos options',
  cart_action_customization_required_message:
    'Veuillez verifier les options du produit avant d’ajouter cet article a votre panier.',
  cart_action_out_of_stock_title: 'Article indisponible',
  cart_action_out_of_stock_message:
    'Cet article est actuellement en rupture de stock. Veuillez essayer un autre article.',
  cart_network_error_title: 'Probleme de connexion',
  cart_network_error_message:
    'Veuillez verifier votre connexion internet puis reessayer.',
  cart_add_success_title: 'Ajoute au panier',
  cart_add_success_message: '{{quantity}} x {{product}} ont ete ajoutes a votre panier.',
  cart_add_error_title: "Impossible d'ajouter l'article",
  cart_add_error_message: 'Veuillez reessayer dans un instant.',
  cart_update_success_title: 'Panier mis a jour',
  cart_update_success_message: 'La quantite de votre panier a ete mise a jour.',
  cart_update_error_title: 'Impossible de mettre a jour le panier',
  cart_update_error_message: 'Veuillez reessayer de mettre a jour votre panier.',
  cart_remove_success_title: 'Article retire',
  cart_remove_success_message: 'L’article a ete retire de votre panier.',
  cart_remove_error_title: "Impossible de retirer l'article",
  cart_remove_error_message: "Veuillez reessayer de retirer l'article.",
  cart_clear_action: 'Vider le panier',
  cart_clear_popup_title: 'Vider votre panier ?',
  cart_clear_popup_message:
    'Cela supprimera tous les articles de votre panier actuel afin que vous puissiez recommencer.',
  cart_clear_popup_confirm: 'Vider le panier',
  cart_clear_popup_cancel: 'Annuler',
  cart_clear_error_title: 'Impossible de remplacer le panier',
  cart_clear_error_message: 'Veuillez reessayer dans un instant.',
  free: 'Gratuit',
  product_info_error_title: 'Impossible de charger le produit',
  rider_chat_title: 'Chat avec le livreur',
  rider_chat_subtitle: 'Mises à jour de livraison en direct',
  rider_chat_status_online: 'En ligne',
  rider_chat_eta_label: 'Arrive dans {{minutes}} min',
  rider_chat_order_label: 'Commande {{orderCode}}',
  rider_chat_help_text: 'Partagez des consignes ou demandez un appel à l’arrivée.',
  rider_chat_message_rider_intro: 'Bonjour ! Je suis en route avec votre commande.',
  rider_chat_message_user_reply: 'Parfait. Merci de m’appeler quand vous arrivez au portail.',
  rider_chat_message_rider_eta: 'Bien sûr, je vous appelle. À tout de suite dans environ {{minutes}} minutes.',
  rider_chat_quick_reply_gate: 'Appeler au portail',
  rider_chat_quick_reply_thanks: 'Merci !',
  rider_chat_quick_reply_here: 'Je suis là',
  rider_chat_quick_reply_hello: 'Bonjour',
  rider_chat_quick_reply_call_arrive: 'Appelez-moi à l’arrivée',
  rider_chat_quick_reply_where: 'Où êtes-vous ?',
  rider_chat_quick_reply_eta: 'Dans combien de temps ?',
  rider_chat_input_placeholder: 'Entrez votre message...',
  rider_chat_auto_message: 'Comment pouvons-nous vous aider ?\n[Message automatique]',
  rider_chat_auto_time: '20:29',
  rider_chat_send: 'Envoyer',
  rider_chat_send_error: 'Impossible d’envoyer le message.',
  rider_chat_missing_session_error: 'Connectez-vous avant d’envoyer un message.',
  rider_chat_missing_receiver_error: 'Le destinataire est manquant pour ce chat.',
  rider_chat_attachment_permission_title: 'Autorisation requise',
  rider_chat_attachment_permission_message: 'Veuillez autoriser l’accès à la photothèque pour ajouter une pièce jointe.',
  rider_chat_attachment_selected_title: 'Pièce jointe sélectionnée',
  rider_chat_attachment_selected_message: '{{fileName}} est prêt à être joint.',
  rider_chat_add_attachment: 'Ajouter une pièce jointe',
  rider_chat_send_message: 'Envoyer le message',
  rider_chat_call_action: 'Appeler le livreur',
  support_title: 'Assistance',
  support_guest_name: 'ici',
  support_greeting: 'Bonjour {{name}} !',
  support_headline: 'De quoi avez-vous besoin aujourd’hui ?',
  support_browse_topics: 'Parcourir les rubriques d’aide',
  support_topic_faq: 'Questions fréquentes',
  support_topic_conversations: 'Mes conversations',
  support_topic_tickets: 'Mes tickets',
  support_issue_prompt: 'Vous n’avez pas trouvé ce dont vous avez besoin ?',
  support_issue_select_title: 'Veuillez choisir une option.',
  support_issue_placeholder: 'Sélectionnez un type de problème',
  support_issue_order: 'J’ai deja un compte professionnel et j’ai besoin d’assistance',
  support_issue_payment: 'Je souhaite rejoindre Food delivery en tant qu’entreprise',
  support_issue_delivery: 'J’ai passe une commande avec une entreprise sur Food delivery',
  support_issue_account: 'J’ai besoin d’aide pour autre chose',
  support_issue_business_support: 'J’ai deja un compte professionnel et j’ai besoin d’assistance',
  support_issue_joining_as_a_business: 'Je souhaite rejoindre Food delivery en tant qu’entreprise',
  support_issue_appointment_support: 'J’ai passe une commande avec une entreprise sur Food delivery',
  support_call_action: 'Appeler l’assistance',
  support_back_action: 'Retour',
  support_header_action: 'Action de l’en-tete',
  support_close_action: 'Fermer le formulaire d’assistance',
  support_search_action: 'Rechercher dans les conversations',
  support_tickets_search_action: 'Rechercher des tickets',
  support_form_how_help_label: 'Comment pouvons-nous vous aider ?',
  support_form_email_label: 'Email',
  support_form_email_helper: 'Si vous avez un compte Food delivery, entrez l’adresse email utilisee pour vous connecter',
  support_form_full_name_label: 'Nom complet',
  support_form_full_name_placeholder: 'Entrez votre nom',
  support_form_country_region_label: 'Pays / Region',
  support_form_country_region_placeholder: 'Veuillez selectionner',
  support_form_mobile_number_label: 'Numero de telephone',
  support_form_mobile_number_placeholder: '+61 333 000 0000',
  support_form_business_name_label: 'Nom de l’entreprise',
  support_form_business_type_label: 'Type d’entreprise',
  support_form_business_type_placeholder: 'Veuillez selectionner',
  support_form_team_size_label: 'Taille de l’equipe',
  support_form_team_size_placeholder: 'Veuillez selectionner',
  support_form_business_description_label: 'Y a-t-il quelque chose en particulier que vous souhaitez savoir sur Food delivery ?',
  support_form_reason_label: 'Raison du contact',
  support_form_reason_placeholder: 'Veuillez selectionner',
  support_form_reason_account_setup: 'Configuration du compte',
  support_form_reason_add_on_integrations: 'Modules et integrations',
  support_form_reason_addons_integrations: 'Modules et integrations',
  support_form_reason_using_the_app: 'Utilisation de l’application',
  support_form_reason_payments_and_payouts: 'Paiements et versements',
  support_form_reason_technical_issues: 'Problemes techniques',
  support_form_reason_my_orders: 'Mes commandes',
  support_form_reason_payments_and_purchases: 'Paiements et achats',
  support_form_reason_reviews: 'Avis',
  support_form_reason_emails_and_notifications: 'Emails et notifications',
  support_form_reason_delete_my_account: 'Supprimer mon compte',
  support_form_reason_billing_fees: 'Facturation et frais',
  support_form_reason_payments_payouts: 'Paiements et versements',
  support_form_reason_technical_support: 'Support technique',
  support_form_reason_other: 'Autre',
  support_form_country_united_states: 'Etats-Unis',
  support_form_country_canada: 'Canada',
  support_form_country_united_kingdom: 'Royaume-Uni',
  support_form_country_australia: 'Australie',
  support_form_country_france: 'France',
  support_form_business_type_burger_joint: 'Burger',
  support_form_business_type_pizza_place: 'Pizzeria',
  support_form_business_type_taco_stand: 'Stand de tacos',
  support_form_business_type_sandwich_shop: 'Sandwicherie',
  support_form_business_type_ice_cream_parlor: 'Glacier',
  support_form_business_type_fried_chicken_spot: 'Poulet frit',
  support_form_business_type_food_truck: 'Food truck',
  support_form_business_type_hot_dog_stand: 'Stand de hot-dogs',
  support_form_business_type_other_fast_food: 'Autre restauration rapide',
  support_form_team_size_just_me: 'Juste moi',
  support_form_team_size_2_5: '2 - 5',
  support_form_team_size_6_10: '6 - 10',
  support_form_team_size_11_plus: '11+',
  support_form_description_label: 'Decrivez ce pour quoi vous avez besoin d’aide',
  support_form_description_placeholder: 'Entrez une description...',
  support_form_attach_title: 'Joindre des captures d’ecran',
  support_form_attach_description: 'Deposez vos fichiers ici',
  support_form_attach_cta: 'Choisir un fichier',
  support_form_send_email: 'Envoyer un email',
  support_form_submit_success_title: 'Ticket cree',
  support_form_submit_success_message: 'Votre ticket de support a ete envoye avec succes.',
  support_form_submit_error_title: 'Echec du ticket',
  support_chat_agent_name: 'Jhon Smith',
  support_chat_auto_message: 'Comment pouvons-nous vous aider ?\n[Message automatique]',
  support_chat_auto_time: '20:29',
  support_chat_quick_reply_here: 'Je suis la',
  support_chat_quick_reply_hello: 'Bonjour',
  support_chat_quick_reply_call_arrive: 'Appelez-moi quand vous arrivez',
  support_chat_quick_reply_where: 'Ou etes-vous ?',
  support_chat_quick_reply_eta: 'Dans combien de temps ?',
  support_chat_input_placeholder: 'Entrez votre message...',
  support_chat_add_attachment: 'Ajouter une piece jointe',
  support_chat_send_message: 'Envoyer le message',
  support_chat_send_error_title: 'Echec de l’envoi',
  support_chat_send_error_message: 'Impossible d’envoyer votre message au support.',
  support_chat_missing_session_error: 'Connectez-vous avant d’envoyer un message.',
  support_chat_missing_receiver_error: 'Le chat support n’est pas encore pret. Ouvrez d’abord une conversation existante.',
  support_chat_loading: 'Chargement de la conversation...',
  support_chat_empty: 'Aucune conversation de support trouvee.',
  support_chat_empty_message: 'Commencez une conversation avec le support.',
  support_chat_attachment_permission_title: 'Autorisation requise',
  support_chat_attachment_permission_message: 'Veuillez autoriser l’acces a la phototheque pour ajouter une piece jointe.',
  support_chat_attachment_selected_title: 'Piece jointe selectionnee',
  support_chat_attachment_selected_message: '{{fileName}} est pret a etre joint.',
  support_admin_picker_title: 'Choisir une personne du support',
  support_admin_picker_subtitle: 'Selectionnez un administrateur disponible pour commencer la conversation.',
  support_admin_picker_loading: 'Chargement de l’equipe support...',
  support_admin_picker_empty: 'Aucun administrateur support disponible pour le moment.',
  support_admin_picker_row_subtitle: 'Touchez pour commencer la conversation',
  support_conversations_title: 'Mes conversations',
  support_conversations_recent: 'Récentes',
  support_conversations_past: 'Anciennes',
  support_conversations_name_barbarella_inova: 'Barbarella Inova',
  support_conversations_name_barbarella_nova: 'Barbarella Nova',
  support_conversations_preview_let_me_check: 'Je verifie.',
  support_conversations_preview_take_a_look: 'Je vais regarder.',
  support_conversations_time_5m: 'Il y a 5 min',
  support_conversations_time_1h: 'Il y a 1 h',
  support_conversations_time_oct_2: '2 Oct',
  support_conversations_delete_action: 'Supprimer la conversation',
  support_conversations_delete_title: 'Supprimer le chat de {{name}} ?',
  support_conversations_delete_description: 'Voulez-vous vraiment supprimer definitivement cette conversation ?',
  support_conversations_delete_cancel: 'Annuler',
  support_conversations_delete_confirm: 'Oui, supprimer',
  support_conversations_loading: 'Chargement des conversations...',
  support_conversations_empty: 'Aucune conversation pour le moment.',
  support_conversations_search_placeholder: 'Rechercher par nom ou message',
  support_conversations_no_results: 'Aucune conversation ne correspond a votre recherche.',
  support_tickets_title: 'Mes tickets',
  support_tickets_heading: 'Tous les tickets',
  support_tickets_loading: 'Chargement des tickets...',
  support_tickets_empty: 'Aucun ticket trouve pour le moment.',
  support_tickets_day_fri: 'VEN',
  support_tickets_title_how_to_order: 'Comment commander',
  support_tickets_preview_how_to_order: 'Commander sur Food Delivery est rapide et simple...',
  support_tickets_order_id: 'ID de commande : {{orderId}}',
  support_tickets_status_open: 'Ouvert',
  support_tickets_status_closed: 'Ferme',
  support_tickets_status_pending: 'En attente',
  support_faq_title: 'Questions generales sur les commandes',
  support_faq_place_order: 'Comment passer une commande',
  support_faq_schedule_delivery: 'Comment planifier vos livraisons à l’avance',
  support_faq_change_delivery: 'Modifier vos livraisons',
  support_faq_order_history: 'Comment consulter votre historique de commandes',
  support_faq_ordering_for_others: 'Commander pour d’autres et envoyer les confirmations à différentes adresses',
  support_faq_still_need_help: 'Vous avez encore besoin d’aide ?',
  support_faq_feedback_prompt: 'Cela vous a-t-il aide ?',
  support_faq_feedback_yes: 'Oui',
  support_faq_feedback_no: 'Non',
  support_faq_place_order_body_1: 'Passer une commande est simple et rapide. Ouvrez l’application de livraisons et parcourez les restaurants, boutiques ou categories autour de vous.',
  support_faq_place_order_body_2: 'Touchez une boutique pour voir son menu, puis ajoutez les articles souhaites a votre panier. Vous pouvez verifier les quantites, ajouter des notes et retirer des articles avant le paiement.',
  support_faq_place_order_body_3: 'Quand tout est pret, passez au paiement pour confirmer l’adresse de livraison, appliquer un code promo et choisir votre mode de paiement prefere.',
  support_faq_place_order_body_4: 'Apres validation, vous pouvez suivre votre commande en temps reel jusqu’a son arrivee.',
  support_faq_schedule_delivery_body_1: 'Si la boutique accepte les commandes programmees, vous pouvez choisir une heure de livraison avant de confirmer votre commande.',
  support_faq_schedule_delivery_body_2: 'Ajoutez vos articles au panier puis passez au paiement. Recherchez la section du moment de livraison avant de confirmer.',
  support_faq_schedule_delivery_body_3: 'Choisissez une date et un creneau qui vous conviennent, puis verifiez les details de la commande.',
  support_faq_schedule_delivery_body_4: 'Une fois confirmee, la livraison programmee restera visible dans votre onglet des commandes.',
  support_faq_change_delivery_body_1: 'Vous pouvez parfois modifier certains elements de la commande avant que la boutique commence la preparation.',
  support_faq_change_delivery_body_2: 'Ouvrez votre commande en cours pour voir si la modification est encore disponible. Certaines boutiques autorisent de petits changements, d’autres verrouillent rapidement la commande.',
  support_faq_change_delivery_body_3: 'Si la modification n’est plus possible, le plus rapide est de contacter l’assistance depuis l’aide ou d’ouvrir le chat avec une personne.',
  support_faq_change_delivery_body_4: 'Nous vous conseillons de verifier attentivement votre panier avant de confirmer la commande.',
  support_faq_order_history_body_1: 'Vos livraisons en cours et passees sont disponibles dans la section des commandes de l’application.',
  support_faq_order_history_body_2: 'Ouvrez la commande voulue pour voir les articles, les details de paiement, l’adresse de livraison et son statut.',
  support_faq_order_history_body_3: 'C’est aussi le meilleur endroit pour recommander rapidement les memes articles.',
  support_faq_ordering_for_others_body_1: 'Vous pouvez commander pour quelqu’un d’autre en selectionnant ou en ajoutant la bonne adresse de livraison avant le paiement.',
  support_faq_ordering_for_others_body_2: 'Verifiez que le nom du destinataire, le numero de telephone et les instructions de livraison sont corrects afin que le livreur puisse joindre la bonne personne.',
  support_faq_ordering_for_others_body_3: 'Si vous devez envoyer les mises a jour a un autre contact, relisez les informations de contact pendant le paiement avant de confirmer.',
  support_faq_ordering_for_others_body_4: 'Pour que tout se passe bien, prevenez le destinataire qu’une livraison est en route et partagez les informations utiles.',
  support_faq_still_need_help_body_1: 'Si votre question n’est pas traitee ici, utilisez l’option de chat en bas de l’ecran pour contacter notre equipe d’assistance.',
  support_faq_still_need_help_body_2: 'Ajoutez les informations utiles comme le nom de la boutique, le numero de commande et un court resume du probleme pour accelerer l’aide.',
  support_faq_still_need_help_body_3: 'Notre equipe vous guidera pour la suite et vous aidera a resoudre les problemes de livraison, paiement ou compte.',
  support_chat_cta: 'Discuter avec une personne',
  orders_tab_active: 'Actives',
  orders_tab_history: 'Passées',
  orders_tab_scheduled: 'Planifiées',
  orders_history_active_heading: 'Commandes actives',
  orders_empty_active_title: 'Aucune commande active pour le moment',
  orders_empty_active_subtitle: 'Vos commandes actives apparaîtront ici une fois passées.',
  orders_empty_history_title: 'Aucune commande pour le moment',
  orders_empty_history_subtitle: 'Vous n’avez encore passé aucune commande. Elle apparaîtra ici dès que vous en ferez une.',
  orders_empty_history_cta: 'Commencer vos achats',
  orders_empty_scheduled_title: 'Aucune livraison planifiée pour le moment',
  orders_empty_scheduled_subtitle: 'Vous n’avez planifié aucune commande.',
  orders_history_ongoing_heading: 'Commande en cours',
  orders_history_past_heading: 'Commandes passées',
  orders_history_scheduled_heading: 'Commandes planifiées',
  orders_list_load_more: 'Charger plus',
  orders_list_no_more_items: 'Plus aucun élément',
  orders_list_error: 'Impossible de charger les livraisons planifiées pour le moment.',
  orders_list_retry: 'Réessayer',
  orders_status_upcoming: 'À venir',
  orders_status_ongoing: 'En cours',
  orders_status_delivered: 'Commande livrée',
  orders_status_cancelled: 'Commande annulée',
  order_cancel_title: 'Annuler la commande ?',
  order_cancel_message: 'Les commandes payées seront remboursées dans votre portefeuille.',
  order_cancel_keep: 'Garder la commande',
  order_cancel_confirm: 'Annuler la commande',
  order_details_title: 'Détails de la commande',
  order_details_error_title: 'Impossible de charger cette commande pour le moment.',
  order_details_status: 'Statut de la commande',
  order_details_scheduled_for: 'Prévue pour',
  order_details_items: 'Articles de la commande',
  order_details_summary: 'Résumé de la commande',
  order_details_payment_details: 'Détails du paiement',
  order_details_order_number: 'Numéro de commande',
  order_details_delivery_address: 'Adresse de livraison',
  order_details_item_subtotal: 'Sous-total des articles',
  order_details_discount: 'Réduction',
  order_details_tax: 'Taxe',
  order_details_packing_charges: 'Frais d’emballage',
  order_details_delivery_fee: 'Livraison',
  order_details_courier_tip: 'Pourboire du livreur',
  order_details_total_amount: 'Montant total',
  order_details_rate_order: 'Évaluer la commande',
  order_details_view_rating: 'Voir votre évaluation',
  order_details_increase_tip: 'Augmenter le pourboire',
  order_details_track_progress: 'Suivre la progression',
  order_details_order_again: 'Commandez à nouveau',
  order_details_notes: 'Notes',
  order_details_restaurant_note: 'Note pour le restaurant',
  order_details_courier_note: 'Note pour le livreur',
  order_again_error_title: 'Impossible de recommander ces articles',
  order_again_error_message: 'Veuillez réessayer de commander ces articles dans un instant.',
  order_again_partial_title: 'Certains articles nécessitent votre attention',
  order_details_tip_done: 'Terminé',
  order_details_tip_placeholder: '0.00',
  order_details_empty_items: 'Aucun article',
  order_details_quantity_one: 'Qté {{count}}',
  order_tracking_title: 'Votre commande',
  order_tracking_help: 'Aide au suivi de commande',
  order_tracking_eta_label: 'Temps de livraison estimé',
  order_tracking_delivered_title: 'Livrée',
  order_tracking_delivered_message_line_one: 'Votre commande a été livrée.',
  order_tracking_delivered_message_line_two: 'Bon appétit !',
  order_tracking_error_title: 'Impossible de charger le suivi pour le moment.',
  order_tracking_delivery_details: 'Détails de livraison',
  order_tracking_collection_details: 'Détails du retrait',
  order_tracking_contact_title: 'Contacter votre livreur',
  order_tracking_contact_subtitle: 'Demander une livraison sans contact',
  order_tracking_courier_fallback: 'Livreur',
  order_tracking_summary: 'Résumé',
  order_tracking_summary_note: 'taxes incluses (si applicable)',
  order_tracking_unavailable_title: 'Commande non confirmée',
  order_tracking_unavailable_description:
    "Le magasin n'a pas pu confirmer votre commande, elle a donc été annulée. Vous pouvez la passer à nouveau ou choisir un autre magasin à proximité.",
  order_tracking_unavailable_cancelled_description:
    "Cette commande a été annulée, il n'y a donc plus rien à suivre. Vous pouvez la passer à nouveau ou choisir un autre magasin à proximité.",
  order_tracking_unavailable_action: "Retour à l'accueil",
  // Wallet
  wallet_balance_label: 'Solde du portefeuille',
  wallet_loyalty_total_points: 'Total des points fidélité gagnés',
  wallet_loyalty_rate: '{{points}} points = {{currency}} 1',
  wallet_loyalty_amount: 'Solde du portefeuille issu de la fidélité',
  wallet_cards_title: 'Cartes',
  wallet_add_card: 'Ajouter une carte de débit/crédit',
  wallet_recent_transactions: 'Transactions récentes',
  wallet_transactions_empty_title: 'Aucune transaction pour le moment',
  wallet_transactions_empty_description:
    'L’activité de votre portefeuille apparaîtra ici après un paiement ou un remboursement.',
  wallet_see_all: 'Voir tout',
  wallet_add_card_title: 'Ajouter une carte',
  wallet_name_on_card: 'Nom sur la carte',
  wallet_name_placeholder: 'Nom complet du titulaire',
  wallet_card_number_label: 'Numéro de carte',
  wallet_card_number_placeholder: 'Numéro de carte de crédit ou débit',
  wallet_expiry_label: 'Date d\'expiration',
  wallet_security_code_label: 'Code de sécurité',
  wallet_pay_securely: 'Paiement sécurisé avec',
  wallet_save_card: 'Enregistrer',
  wallet_no_saved_cards: 'Aucune carte enregistrée',
  wallet_add_card_error: 'Impossible d’enregistrer la carte',
  wallet_setup_intent_success_title: 'Configuration de la carte démarrée',
  wallet_setup_intent_success_message:
    'Intent de configuration créé. Terminez la confirmation avec le SDK Stripe.',
  wallet_stripe_publishable_key_missing: 'La clé publique Stripe est manquante.',
  wallet_card_incomplete: 'Veuillez compléter les détails de la carte.',
  wallet_card_saved_success_title: 'Carte enregistrée',
  wallet_card_saved_success_message: 'Votre carte a été ajoutée avec succès.',
  off: 'désactivé'
};

export default fr;
