const en = {
  label: 'Home Visits',
  description: 'Schedule trusted visits.',
  header_title: 'Home Visits',
  header_subtitle: 'On-demand services',
  section_title: 'Pick your mode',
  single_vendor_title: 'Single Provider',
  single_vendor_desc: 'A focused experience for one provider.',
  single_vendor_chip: 'Primary flow',
  single_vendor_stat: 'Book with the current experience',
  single_vendor_categories_title: 'Categories',
  single_vendor_category_services_empty: 'No services found for this category.',
  single_vendor_home_subtitle: 'Schedule trusted home visits',
  single_vendor_home_section_empty_title: 'Nothing here yet',
  single_vendor_home_section_error_title: 'Unable to load items',
  single_vendor_home_section_error_message: 'Please try again in a moment.',
  multi_vendor_title: 'Multi Provider',
  multi_vendor_desc: 'Browse multiple home visit providers.',
  multi_vendor_chip: 'Nearby services',
  multi_vendor_stat: 'Browse providers around you',
  multi_vendor_main_services_title: 'Main services',
  multi_vendor_service_type_title: 'Service type',
  multi_vendor_service_type_categories_empty:
    'No categories found for this service type.',
  multi_vendor_top_centers_title: 'Top centers',
  multi_vendor_top_centers_empty: 'No top centers are available right now.',
  multi_vendor_deals_title: 'Deals',
  multi_vendor_deals_empty: 'No service deals are available right now.',
  multi_vendor_providers_title: 'Nearby providers',
  multi_vendor_service_providers_title: 'Service providers',
  multi_vendor_service_providers_empty: 'No service providers are available right now.',
  multi_vendor_nearby_services_title: 'Nearby services',
  multi_vendor_providers_empty: 'No providers are available for this service yet.',
  multi_vendor_nearby_services_empty: 'No nearby services are available right now.',
  multi_vendor_favorite_added: 'Added to favorites',
  multi_vendor_favorite_removed: 'Removed from favorites',
  multi_vendor_favorite_error: 'Unable to update favorites right now.',
  multi_vendor_center_info_title: 'Center information',
  multi_vendor_center_info_category: 'Category',
  multi_vendor_center_info_availability: 'Availability',
  multi_vendor_center_info_address: 'Address',
  multi_vendor_center_info_distance: 'Distance',
  multi_vendor_center_info_rating: 'Rating',
  multi_vendor_center_info_starting_price: 'Starting price',
  multi_vendor_center_info_fallback: 'No center information is available yet.',
  chain_title: 'Chain',
  chain_desc: 'A structured flow for service chains.',
  chain_chip: 'Future mode',
  chain_stat: 'Reserved for chain-based services',
  explore_button: 'Explore',
  single_vendor_tab_home: 'Home',
  single_vendor_tab_search: 'Search',
  single_vendor_tab_orders: 'Bookings',
  single_vendor_tab_profile: 'Profile',
  single_vendor_bookings_title: 'My Booking',
  single_vendor_bookings_tab_ongoing: 'Ongoing',
  single_vendor_bookings_tab_past: 'Past',
  single_vendor_bookings_view_details: 'View details',
  single_vendor_bookings_book_again: 'Book again',
  single_vendor_favorites_title: 'Favorites',
  single_vendor_favorites_empty: 'No items are currently in the favorites list.',
  single_vendor_favorites_error: 'Unable to load favorites right now.',
  single_vendor_bookings_item: 'item',
  single_vendor_bookings_items: 'items',
  single_vendor_bookings_retry: 'Try again',
  single_vendor_bookings_error_title: 'Unable to load bookings',
  single_vendor_bookings_empty_title_ongoing: 'No ongoing bookings',
  single_vendor_bookings_empty_subtitle_ongoing: 'Your active bookings will show up here.',
  single_vendor_bookings_empty_title_past: 'No past bookings',
  single_vendor_bookings_empty_subtitle_past: 'Your completed or cancelled bookings will show up here.',
  single_vendor_bookings_empty_generic_title: 'No bookings found',
  single_vendor_bookings_empty_generic_subtitle:
    'Your upcoming and past bookings will appear here once you place one.',
  single_vendor_booking_status_confirmed: 'Confirmed',
  single_vendor_booking_default_duration: '1 hr duration',
  single_vendor_booking_add_calendar_title: 'Add to calendar',
  single_vendor_booking_add_calendar_subtitle: 'Set yourself a reminder',
  single_vendor_booking_calendar_open_error: 'Unable to open calendar right now.',
  single_vendor_booking_manage_title: 'Manage appointment',
  single_vendor_booking_manage_subtitle: 'Reschedule or cancel your appointment',
  single_vendor_booking_cancel_subtitle: 'Cancel your appointment',
  single_vendor_booking_track_title: 'Track Worker',
  single_vendor_booking_track_subtitle: 'Track your worker',
  single_vendor_active_service_title: 'Service Started',
  single_vendor_active_service_default_title: 'Home Deep Cleaning',
  single_vendor_active_service_default_subtitle: 'Open your active service',
  single_vendor_track_worker_title: 'Your appointment',
  single_vendor_track_worker_estimated_service_label: 'Estimated service time',
  single_vendor_track_worker_eta_label: 'Estimated arrival time',
  single_vendor_track_worker_eta_10_15: '10-15 mins',
  single_vendor_track_worker_eta_15_25: '15-25 mins',
  single_vendor_track_worker_anytime_now: 'Anytime now',
  single_vendor_track_worker_preparing_subtitle:
    'Your order has been place and worker is preparing the equipments.',
  single_vendor_track_worker_on_the_way: 'Your worker is on the way!',
  single_vendor_track_worker_anytime_subtitle: 'Anytime now! Look out for your worker.',
  single_vendor_track_worker_service_started: 'Service has begun!',
  single_vendor_track_worker_started_subtitle: 'The service is now live!',
  single_vendor_track_worker_contact_title: 'Contact your worker',
  single_vendor_track_worker_contact_subtitle: 'Ask for contactless service',
  single_vendor_track_worker_contact_unavailable: 'Worker contact is not available right now.',
  single_vendor_track_worker_appointment_details: 'Appointment details',
  single_vendor_track_worker_booking_number: 'Booking number',
  single_vendor_track_worker_appointment_address: 'Appointment address',
  single_vendor_track_worker_address_fallback: 'Address not available',
  single_vendor_track_worker_around_corner_title:
    'Get ready, our worker is just around the corner.',
  single_vendor_track_worker_around_corner_subtitle: '',
  single_vendor_track_worker_view: 'View',
  single_vendor_track_worker_payment_title: 'Job Finished! Complete your transaction',
  single_vendor_track_worker_payment_subtitle:
    'Your service has been successfully completed. Please confirm the details in this final invoice and process your payment.',
  single_vendor_track_worker_payment_by: 'Payment by',
  single_vendor_track_worker_online_payment: 'Online Payment',
  single_vendor_track_worker_pay_now: 'Pay Now',
  single_vendor_track_worker_payment_failed: 'Payment failed',
  single_vendor_track_worker_payment_processing: 'Payment is processing',
  single_vendor_track_worker_waiting_payment_request:
    'Pay Now will be enabled once the worker requests payment.',
  single_vendor_track_worker_payment_confirmed: 'Payment confirmed',
  single_vendor_track_worker_saved_card_required_title: 'Saved card required',
  single_vendor_track_worker_saved_card_required_message:
    'Add a saved card in your Home Visits wallet before paying for this job.',
  single_vendor_track_worker_default_card_required_title: 'Default card required',
  single_vendor_track_worker_default_card_required_message:
    'Set a default saved card in your Home Visits wallet before paying for this job.',
  single_vendor_track_worker_feedback_title: 'How was your experience?',
  single_vendor_track_worker_feedback_subtitle: 'Your feedback helps us improve our services.',
  single_vendor_track_worker_feedback_placeholder: 'Write your experience here...',
  single_vendor_track_worker_submit: 'Submit',
  single_vendor_track_worker_feedback_success: 'Thanks for your feedback!',
  single_vendor_track_worker_cancelled: 'Appointment cancelled',
  single_vendor_track_worker_cancelled_subtitle: 'This appointment is no longer active.',
  single_vendor_track_worker_failed: 'Service could not be completed',
  single_vendor_track_worker_failed_subtitle: 'Please contact support for help.',
  single_vendor_booking_service_title: 'Service details',
  single_vendor_booking_service_subtitle: 'Prices may vary based on additional services',
  single_vendor_booking_price_summary_title: 'Price summary',
  single_vendor_booking_price_labor: 'Labor',
  single_vendor_booking_price_hourly_rate: 'Hourly Rate',
  single_vendor_booking_price_working_hours: 'Working Hours',
  single_vendor_booking_price_items_used: 'Items Used',
  single_vendor_booking_price_subtotal: 'Subtotal',
  single_vendor_booking_price_discount: 'Discount',
  single_vendor_booking_price_tax: 'Tax',
  single_vendor_booking_price_delivery_fee: 'Delivery Fee',
  single_vendor_booking_price_packing_charges: 'Packing Charges',
  single_vendor_booking_price_tip: 'Tip',
  single_vendor_booking_service_duration: '1 hr',
  single_vendor_booking_duration_job: '1 job',
  single_vendor_booking_duration_service: '1 service',
  single_vendor_booking_total: 'Total',
  single_vendor_booking_open_reviews: 'View reviews',
  single_vendor_booking_customer_note_title: 'Customer note',
  single_vendor_booking_address_title: 'Service address',
  single_vendor_booking_cancellation_title: 'Cancellation policy',
  single_vendor_booking_cancellation_body: 'Please cancel within 2 hours of your appointment',
  single_vendor_reviews_title: 'Reviews',
  single_vendor_reviews_filter_by: 'Filter by',
  single_vendor_reviews_sort_by: 'Sort by',
  single_vendor_reviews_latest: 'Latest',
  single_vendor_reviews_best: 'Best',
  single_vendor_reviews_worst: 'Worst',
  single_vendor_reviews_summary_label: '{{rating}} ({{count}})',
  single_vendor_reviews_total_label: '{{count}} reviews',
  single_vendor_reviews_empty_title: 'No reviews yet',
  single_vendor_reviews_empty_subtitle: 'Be the first to leave a review for this service.',
  single_vendor_reviews_service_home_cleaning: 'Home cleaning',
  single_vendor_reviews_service_plumber: 'Plumber',
  single_vendor_reviews_service_window_cleaning: 'Window Cleaning',
  single_vendor_reviews_service_electrician: 'Electrician',
  single_vendor_reviews_service_floor_cleaning: 'Floor Cleaning',
  single_vendor_reviews_service_washing: 'Washing',
  single_vendor_reviews_comment_1:
    "Great service! My home is spotless and smells amazing. I'll definitely book again.",
  single_vendor_reviews_comment_2:
    'Excellent cleaning! The team was punctual, friendly, and very detail-oriented.',
  single_vendor_reviews_comment_3:
    'The best service ever! My house looks brand new. I highly recommend this company.',
  single_vendor_reviews_comment_4:
    "I'm very happy with the service. The team was professional and did a fantastic job.",
  single_vendor_reviews_comment_5:
    'The team was efficient and thorough. My home has never been cleaner. Thank you!',
  single_vendor_reviews_comment_6:
    "I'm so glad I hired this company. They were on time and did an amazing job.",
  single_vendor_reviews_comment_7:
    "I'm very impressed with the quality of service. My home is now sparkling clean!",
  single_vendor_manage_appointment_title: 'Manage appointment',
  single_vendor_manage_appointment_reschedule: 'Reschedule appointment',
  single_vendor_manage_appointment_cancel: 'Cancel appointment',
  single_vendor_manage_appointment_empty_title: 'No appointments found',
  single_vendor_manage_appointment_empty_subtitle:
    'Your upcoming and past appointments will appear when you book',
  single_vendor_manage_appointment_search_service: 'Search service',
  single_vendor_cancel_appointment_heading: 'Are you sure you want to cancel appointment?',
  single_vendor_cancel_appointment_body_top:
    'If you want to change the appointment time, you can reschedule your appointment.',
  single_vendor_cancel_appointment_body_bottom:
    'Are you sure you want to cancel your appointment?',
  single_vendor_cancel_appointment_cta: 'Yes, cancel appointment',
  single_vendor_cancel_appointment_loading: 'Cancelling...',
  single_vendor_cancel_appointment_success_title: 'Appointment cancelled',
  single_vendor_cancel_appointment_success_message:
    'Your appointment has been cancelled successfully.',
  single_vendor_cancel_appointment_error_title: 'Unable to cancel appointment',
  single_vendor_cancel_appointment_started_message:
    'This job cannot be cancelled once it has started.',
  single_vendor_contract_details_title: 'Contract Details',
  single_vendor_contract_loading: 'Loading contract...',
  single_vendor_contract_overview_title: 'Overview',
  single_vendor_contract_assigned_team_title: 'Assigned team',
  single_vendor_contract_notes_title: 'Notes',
  single_vendor_contract_billing_title: 'Billing status',
  single_vendor_contract_invoices_title: 'Invoices',
  single_vendor_contract_schedule_title: 'Schedule',
  single_vendor_contract_plan_label: 'Plan',
  single_vendor_contract_status_label: 'Status',
  single_vendor_contract_team_label: 'Team',
  single_vendor_contract_daily_hours_label: 'Daily hours',
  single_vendor_contract_service_center_label: 'Service center',
  single_vendor_contract_visit_days_label: 'Visit days',
  single_vendor_contract_start_date_label: 'Start date',
  single_vendor_contract_end_date_label: 'End date',
  single_vendor_contract_supervisor_members_label: 'Supervisor & members',
  single_vendor_contract_lead_worker_label: 'Lead worker',
  single_vendor_contract_team_member_label: 'Team member',
  single_vendor_contract_job_description_label: 'Job description',
  single_vendor_contract_customer_note_label: 'Customer note',
  single_vendor_contract_saved_card_label: 'Saved card',
  single_vendor_contract_saved_card_available: 'Available',
  single_vendor_contract_saved_card_missing: 'Not added',
  single_vendor_contract_due_date_label: 'Due date',
  single_vendor_contract_visits_in_invoice_label: 'Visits in invoice',
  single_vendor_contract_paid_at_label: 'Paid at',
  single_vendor_contract_pay_invoice: 'Pay invoice',
  single_vendor_contract_pay_overdue_invoice: 'Pay overdue invoice',
  single_vendor_contract_schedule_coverage_label: 'Coverage',
  single_vendor_contract_schedule_delivery_label: 'Service delivery',
  single_vendor_contract_schedule_delivery_value:
    'Managed by the admin through monthly billing',
  single_vendor_contract_pending_status_label: 'Pending approval',
  single_vendor_contract_flexible: 'Flexible',
  single_vendor_contract_no_team: 'No team assigned yet',
  single_vendor_contract_worker_fallback: 'Worker',
  single_vendor_contract_individual: 'Individual',
  single_vendor_contract_team_value: 'Team ({{count}})',
  single_vendor_contract_daily_hours_value: '{{count}} hr',
  single_vendor_contract_contract_cancellation_title: 'Contract cancellation',
  single_vendor_contract_contract_cancellation_status_label: 'Cancellation status',
  single_vendor_contract_contract_cancellation_reason_label: 'Reason',
  single_vendor_contract_contract_cancellation_review_note_label: 'Admin note',
  single_vendor_contract_contract_cancellation_requested_at_label: 'Requested at',
  single_vendor_contract_contract_cancellation_reviewed_at_label: 'Reviewed at',
  single_vendor_contract_contract_cancellation_request_button: 'Request cancellation',
  single_vendor_contract_contract_cancellation_request_again_button:
    'Request cancellation again',
  single_vendor_contract_contract_cancellation_reason_placeholder:
    'Tell us why you want to cancel this contract.',
  single_vendor_contract_contract_cancellation_submit: 'Send request',
  single_vendor_contract_contract_cancellation_submitting: 'Sending...',
  single_vendor_contract_contract_cancellation_success_title: 'Request sent',
  single_vendor_contract_contract_cancellation_success_message:
    'Your cancellation request has been sent for admin review.',
  single_vendor_contract_contract_cancellation_error_title:
    'Unable to request cancellation',
  single_vendor_contract_contract_cancellation_status_none: 'No request',
  single_vendor_contract_contract_cancellation_status_requested:
    'Cancellation requested',
  single_vendor_contract_contract_cancellation_status_rejected:
    'Request rejected',
  single_vendor_contract_contract_cancellation_status_approved:
    'Cancelled',
  single_vendor_contract_invoice_paid_title: 'Invoice paid',
  single_vendor_contract_invoice_paid_message:
    'Your contract invoice has been paid successfully.',
  single_vendor_contract_invoice_processing_title: 'Payment processing',
  single_vendor_contract_invoice_payment_failed_title: 'Payment failed',
  single_vendor_contract_saved_card_required_title: 'Saved card required',
  single_vendor_contract_saved_card_required_message:
    'Add a saved card in your Home Visits wallet before paying this invoice.',
  single_vendor_contract_default_card_required_title: 'Default card required',
  single_vendor_contract_default_card_required_message:
    'Set a default saved card in your Home Visits wallet before paying this invoice.',
  single_vendor_contract_invoice_payment_failed_message:
    'We could not process the contract invoice payment.',
  single_vendor_home_body: 'Basic home screen placeholder for the single provider flow.',
  single_vendor_search_body: 'Basic search screen placeholder for the single provider flow.',
  single_vendor_orders_body: 'Basic bookings screen placeholder for the single provider flow.',
  single_vendor_profile_body: 'Basic profile screen placeholder for the single provider flow.',
  multi_vendor_home_body: 'Basic home screen placeholder for the multi provider flow.',
  chain_home_body: 'Basic home screen placeholder for the chain flow.',
  logout: 'Log out',
  logout_error_title: 'Error',
  logout_error_message: 'Unable to log out right now.',
  details_title: 'Visit Details',
  details_body: 'Visit details and provider info.',
  // Address related strings
  home_visits_address_label: 'Select service location',
  add_service_address: 'Add service address',
  address_select_error: 'Failed to select address. Please try again.',
  address_selector_title: 'Select Service Location',
  address_selector_close: 'Close',
  address_selector_use_current_location: 'Use current location',
  address_selector_add_new: 'Add new address',
  single_vendor_deals_title: 'Deals',
  single_vendor_nearby_location_title: 'Nearby your location',
  single_vendor_most_popular_services_title: 'Most Popular Services',
  single_vendor_nearby_location_select_address_message:
    'Select a service address to see nearby services.',
  single_vendor_see_all: 'See all',
  chain_categories_title: 'Categories',
  chain_category_services_empty: 'No services found for this category.',
  chain_menu_template_selector_label: 'Select chain menu',
  chain_menu_template_loading: 'Loading menus',
  chain_menu_template_empty: 'No menus',
  chain_menu_template_unavailable: 'Menu unavailable',
  offers: 'Offers',
  search: 'Search',
  closed: 'Closed',
  all_offered_items: 'All Offered Items',
  clear_all: 'Clear all',
  single_vendor_home_section_empty_message: 'Check back later for more.',
  home_visits_see_all_search_placeholder: 'Search services',
  home_visits_see_all_coming_soon_title: 'Coming soon',
  home_visits_see_all_coming_soon_description:
    'This See All screen will be available for this mode soon.',
  home_visits_filter_title: 'Filter',
  home_visits_filter_close: 'Close filters',
  home_visits_filter_stock_title: 'Stock',
  home_visits_filter_stock_all: 'All',
  home_visits_filter_stock_in_stock: 'In stock',
  home_visits_filter_price_tiers: 'Price tier',
  home_visits_filter_any_price: 'Any price',
  home_visits_filter_sort_by: 'Sort by',
  home_visits_filter_sort_recommended: 'Recommended',
  home_visits_filter_sort_delivery_time: 'Delivery time',
  home_visits_filter_sort_price_low_to_high: 'Price low to high',
  home_visits_filter_sort_name: 'Name',
  home_visits_filter_sort_rating: 'Highest rating',
  home_visits_filter_clear: 'Clear',
  home_visits_filter_apply: 'Apply',
  service_details_book_service: 'Book service',
  team_schedule_title: 'Team & Schedule',
  team_schedule_team_size_title: 'Team Size',
  team_schedule_team_size_helper: 'Pricing is calculated per worker and per hour.',
  team_schedule_working_hours_title: 'Working Hours',
  team_schedule_working_hours_helper: 'Each worker is charged at $12 per hour',
  team_schedule_working_hours_input_placeholder: 'Enter hours (1-12)',
  team_schedule_worker_type_title: 'Worker Type',
  team_schedule_worker_type_individual_title: 'Individual',
  team_schedule_worker_type_individual_description: 'Just for now',
  team_schedule_worker_type_team_title: 'Team',
  team_schedule_worker_type_team_description: 'Same team works daily. Managed by our admin.',
  team_schedule_service_mode_title: 'Service type',
  team_schedule_service_mode_one_time_title: 'One-time Service',
  team_schedule_service_mode_one_time_description: 'Just for now',
  team_schedule_service_mode_contract_title: 'Contract',
  team_schedule_service_mode_contract_description: 'Same team works daily. Managed by our admin.',
  team_schedule_contract_range_title: 'Enter time range',
  team_schedule_contract_range_helper: 'Select time range for the contract',
  team_schedule_contract_range_custom: 'Custom',
  team_schedule_contract_range_custom_placeholder: 'Choose days, such as 1 or 2.',
  team_schedule_contract_range_add: 'Add',
  team_schedule_continue: 'Continue',
  team_schedule_custom_title: 'Enter team members',
  team_schedule_custom_helper: 'You can select up to 12 workers',
  team_schedule_custom_field_placeholder: '1 worker',
  team_schedule_custom_add: 'Add',
  team_schedule_job_description_title: 'Job Description',
  team_schedule_job_description_placeholder: 'Add any notes about the work performed.',
  team_schedule_job_description_required: 'Please add a job description to continue.',
  team_schedule_date_time_title: 'Choose date and time',
  team_schedule_date_time_confirm: 'Confirm Date & Time',
  team_schedule_select_date_title: 'Select date',
  team_schedule_time_selected_day_title: 'Time on selected day',
  team_schedule_time_selected_days_title: 'Time on selected days',
  team_schedule_start_time_label: 'Start time',
  team_schedule_end_time_label: 'End time',
  team_schedule_selected_days_count: '{{count}} days selected',
  team_schedule_contract_section_title: 'Select contract type',
  team_schedule_contract_type_label: 'Contract type',
  team_schedule_contract_type_sheet_title: 'Contract type',
  team_schedule_contract_type_weekly: 'Weekly',
  team_schedule_contract_type_monthly: 'Monthly',
  team_schedule_contract_type_yearly: 'Yearly',
  team_schedule_working_hours_hour: 'hour',
  team_schedule_working_hours_hours: 'hours',
  team_schedule_repeat_label: 'Repeat every {{contractType}}',
  team_schedule_repeat_every_week: 'Repeat every week',
  team_schedule_repeat_weekly_description: 'Apply the same days each week',
  team_schedule_repeat_monthly_description: 'Apply the same days each month',
  team_schedule_repeat_yearly_description: 'Apply the same days each year',
  team_schedule_end_date_label: 'End Date',
  team_schedule_pick_date: 'Pick a date',
  team_schedule_picker_confirm: 'Confirm',
  team_schedule_start_time_picker_title: 'Select start time',
  team_schedule_end_time_picker_title: 'Select end time',
  team_schedule_end_date_picker_title: 'Select end date',
  team_schedule_one_time_info:
    'This is a one-time job. You can schedule consecutive days for up to 10 days only. If you need recurring visits weekly or monthly with the same team and fixed schedule, please select a Contract Job instead.',
  team_schedule_contract_info:
    'This is a {{contractType}} contract. The same team will arrive at this time on each scheduled visit, managed by FixRight admin.',
  team_schedule_start_date_future_error: 'Start date cannot be in the past.',
  team_schedule_start_time_future_error: 'Start time must be at least 30 minutes from now.',
  team_schedule_one_time_start_hint: 'Next available start time is at least 30 minutes from now.',
  team_schedule_weekly_select_day_error: 'Select at least one weekday for weekly contract.',
  team_schedule_yearly_select_month_error: 'Select at least one month for yearly contract.',
  team_schedule_end_date_after_start_error: 'Contract end date must be after start date.',
  team_schedule_no_upcoming_visits_error: 'No upcoming visits found. Adjust contract settings.',
  team_schedule_contract_min_days_error: 'Please select at least 7 consecutive days.',
  team_schedule_repeat_weekdays_label: 'Repeat on weekdays',
  team_schedule_day_of_month_label: 'Day of month',
  team_schedule_months_label: 'Months',
  team_schedule_advanced_recurrence_title: 'Advanced recurrence',
  team_schedule_yearly_range_helper:
    'Start date and contract end date determine the year range automatically.',
  team_schedule_summary_weekly_days: '{{count}} weekday(s) selected',
  team_schedule_summary_monthly_day: 'Runs on day {{day}} of each month',
  team_schedule_summary_yearly_months: '{{count}} month(s) selected, day {{day}}',
  team_schedule_upcoming_visits_preview: 'Upcoming visits: {{dates}}',
  team_schedule_no_upcoming_visits: 'No upcoming visits generated yet.',
  team_schedule_non_repeat_helper: 'Repeat is off. Select consecutive days (minimum 7).',
  team_schedule_non_repeat_mode_label: 'Schedule mode: Consecutive days',
  team_schedule_range_mode_hint: 'Range mode: select a start date, then select an end date (can be next month).',
  team_schedule_today: 'Today',
  team_worker_singular: 'worker',
  team_worker_plural: 'workers',
  team_schedule_hour_singular: 'hour',
  team_schedule_hour_plural: 'hours',
  team_schedule_day_singular: 'Day',
  team_schedule_day_plural: 'Days',
  review_confirm_title: 'Review & Confirm',
  review_confirm_home: 'Home',
  review_confirm_notes_title: 'Notes',
  review_confirm_optional: 'Optional',
  review_confirm_notes_placeholder: 'Any instructions for cleaner',
  review_confirm_schedule_for: 'Schedule for',
  review_confirm_appointment_time: 'Appointment Time',
  review_confirm_payment_section_title: 'Payment',
  review_confirm_payment_title: 'Cash',
  review_confirm_payment_card_label: '**** 9432',
  review_confirm_payment_subtitle: 'Tap here to change',
  review_confirm_choose_payment_method_title: 'Choose payment method',
  review_confirm_add_payment_method: 'Add payment method',
  review_confirm_discount_title: 'Discount code',
  review_confirm_discount_subtitle: 'Tap here to continue',
  review_confirm_discount_placeholder: 'Enter discount code',
  review_confirm_discount_use_code: 'Use promo code',
  review_confirm_discount_applied: 'Applied: {{code}}',
  review_confirm_cancellation_title: 'Cancellation policy',
  review_confirm_cancellation_body: 'Please cancel within 2 hours of your appointment',
  review_confirm_cancellation_notice_two_hours:
    'Please cancel at least 2 hours before your appointment.',
  review_confirm_cancellation_notice_thirty_minutes:
    'Please cancel at least 30 minutes before your appointment.',
  review_confirm_cancellation_notice_fifteen_minutes:
    'Please cancel at least 15 minutes before your appointment.',
  review_confirm_summary_title: 'Summary',
  review_confirm_summary_subtitle:
    'incl. taxes (if applicable) - Prices may vary based on additional services',
  review_confirm_contract_price_pending:
    'The admin will set the contract price after approval.',
  review_confirm_contract_price_footer_note:
    'The monthly fee will appear once the admin approves this contract.',
  review_confirm_footer_cta: 'Confirm',
  single_vendor_contract_pending_approval: 'Awaiting admin-set price',
  single_vendor_contract_monthly_fee: 'Monthly fee',
  single_vendor_contract_approved_at: 'Approved at',
  review_confirm_services_title: 'Selected Services',
  review_confirm_schedule_title: 'Team & Schedule',
  review_confirm_team_label: 'Team',
  review_confirm_hours_label: 'Hours',
  review_confirm_type_label: 'Type',
  review_confirm_date_time_label: 'Date & Time',
  review_confirm_cta: 'Confirm Booking',
  review_confirm_location_title: 'Service Location',
  review_confirm_location_label: 'Address',
  review_confirm_location_fallback: 'No address selected',
  review_confirm_price_title: 'Price Summary',
  review_confirm_price_services: 'Selected services',
  review_confirm_price_workers: 'Team & hours',
  review_confirm_price_tax: 'Tax',
  review_confirm_price_delivery_fee: 'Delivery Fee',
  review_confirm_price_packing_charges: 'Packing Charges',
  review_confirm_price_tip: 'Tip',
  review_confirm_price_total: 'Total',
  review_confirm_popup_title: 'Please Note',
  review_confirm_popup_line_two: "You'll only be charged after the service is completed.",
  review_confirm_popup_accept: 'Accept and confirm',
  review_confirm_success_title: 'Booked',
  review_confirm_success_body: 'Your booking request is ready to proceed.',
  review_confirm_appointment_confirmed: 'Appointment confirmed',
  review_confirm_place_order_error_title: 'Unable to Confirm Booking',
  review_confirm_place_order_error_description:
    'Please try again in a moment.',
  team_schedule_availability_unavailable_title: 'Scheduling Unavailable',
  team_schedule_availability_unavailable_description:
    'This service center is not accepting scheduled bookings for this date.',
  team_schedule_slot_not_available_title: 'Time Slot Not Available',
  team_schedule_slot_not_available_description:
    'Selected time is not available for your team size. Please choose another time.',
  team_schedule_availability_error_title: 'Unable to Check Availability',
  team_schedule_availability_error_description:
    'Please try again in a moment.',
  ok: 'Ok',
  service_details_service_singular: 'service',
  service_details_service_plural: 'services',
  service_details_service_type_fallback: 'Service Type',
  service_details_additional_services_fallback: 'Additional Services',
  service_details_favorite_action: 'Favorite',
  service_details_share_action: 'Share',
  Nothing_here_yet: 'Nothing here yet',
  Content_for_this_section_will_appear_once_items_are_available: 'Content for this section will appear once items are available.',
  home_visits_settings_body: 'Settings flow for home visits will be added next.',
  home_visits_support_body: 'Support flow for home visits will be added next.',
  home_visits_wallet_body: 'Wallet flow for home visits will be added next.',
  wallet_balance_label: 'Wallet balance',
  wallet_cards_title: 'Cards',
  wallet_add_card: 'Add debit/credit card',
  wallet_recent_transactions: 'Recent Transactions',
  wallet_transactions_empty_title: 'No transactions yet',
  wallet_transactions_empty_description: 'Your wallet activity will appear here once you make a payment or refund.',
  wallet_see_all: 'See all',
  wallet_add_card_title: 'Add card',
  wallet_name_on_card: 'Name on card',
  wallet_name_placeholder: 'Add card holder full name',
  wallet_card_number_label: 'Card number',
  wallet_pay_securely: 'Pay securely with Stripe',
  wallet_save_card: 'Save',
  wallet_no_saved_cards: 'No saved cards yet',
  wallet_add_card_error: 'Unable to save card',
  wallet_stripe_publishable_key_missing: 'Stripe publishable key is missing.',
  wallet_card_incomplete: 'Please complete card details.',
  wallet_card_saved_success_title: 'Card saved',
  wallet_card_saved_success_message: 'Your card was added successfully.',
  support_call_action: 'Call support',
  home_visits_support_back_action: 'Go back',
  home_visits_support_greeting: 'Hi {{name}}!',
  home_visits_support_guest_name: 'there',
  home_visits_support_headline: 'What do you need help with today?',
  home_visits_support_browse_topics: 'Browse help topics',
  home_visits_support_topic_faq: 'Frequently asked questions',
  home_visits_support_topic_conversations: 'My conversations',
  home_visits_support_topic_tickets: 'My tickets',
  home_visits_support_issue_prompt: 'Didn’t find what you need?',
  home_visits_support_issue_placeholder: 'Select an issue type',
  home_visits_support_issue_select_title: 'Select an issue',
  home_visits_support_issue_booking: 'Booking support',
  home_visits_support_issue_reschedule: 'Cancel or reschedule',
  home_visits_support_issue_payment: 'Payment issue',
  home_visits_support_issue_joining_as_a_business:
    'I’m interested in joining Home Services as a business',
  home_visits_support_issue_business_support:
    'I already have a business account and need support',
  home_visits_support_issue_appointment_support:
    'I booked an appointment with a business on Home Services',
  home_visits_support_close_action: 'Close support form',
  home_visits_support_form_how_help_label: 'How can we help?',
  home_visits_support_form_email_label: 'Email',
  home_visits_support_form_email_helper:
    'If you have a Home Services account, enter the email address you log in with',
  home_visits_support_form_full_name_label: 'Full name',
  home_visits_support_form_full_name_placeholder: 'Enter your name',
  home_visits_support_form_country_region_label: 'Country / Region',
  home_visits_support_form_country_region_placeholder: 'Please select',
  home_visits_support_form_mobile_number_label: 'Mobile number',
  home_visits_support_form_mobile_number_placeholder: '+61 333 000 0000',
  home_visits_support_form_business_name_label: 'Business name',
  home_visits_support_form_business_type_label: 'Business type',
  home_visits_support_form_business_type_placeholder: 'Please select',
  home_visits_support_form_team_size_label: 'Team size',
  home_visits_support_form_team_size_placeholder: 'Please select',
  home_visits_support_form_reason_label: 'Reason for contact',
  home_visits_support_form_reason_placeholder: 'Please select',
  home_visits_support_form_reason_account_setup: 'Account setup',
  home_visits_support_form_reason_add_on_integrations: 'Add-ons and integrations',
  home_visits_support_form_reason_addons_integrations: 'Add-ons and integrations',
  home_visits_support_form_reason_using_the_app: 'Using the app',
  home_visits_support_form_reason_payments_and_payouts: 'Payments and payouts',
  home_visits_support_form_reason_technical_issues: 'Technical issues',
  home_visits_support_form_reason_my_orders: 'My appointments',
  home_visits_support_form_reason_payments_and_purchases: 'Payments and purchases',
  home_visits_support_form_reason_reviews: 'Reviews',
  home_visits_support_form_reason_emails_and_notifications: 'Emails and notifications',
  home_visits_support_form_reason_delete_my_account: 'Delete my account',
  home_visits_support_form_reason_other: 'Other',
  home_visits_support_form_country_united_states: 'United States',
  home_visits_support_form_country_canada: 'Canada',
  home_visits_support_form_country_united_kingdom: 'United Kingdom',
  home_visits_support_form_country_australia: 'Australia',
  home_visits_support_form_country_france: 'France',
  home_visits_support_form_business_description_label:
    'Is there anything in particular you want to know about Home Services?',
  home_visits_support_form_appointment_description_label:
    'Please provide us with a description of your query, including your appointment reference or invoice number',
  home_visits_support_form_description_label: 'Describe what you need help with',
  home_visits_support_form_description_placeholder: 'Enter a description...',
  home_visits_support_form_attach_title: 'Attach screenshots',
  home_visits_support_form_attach_description: 'Drop your files here',
  home_visits_support_form_attach_cta: 'Choose a file',
  home_visits_support_form_send_email: 'Send email',
  home_visits_support_form_submit_success_title: 'Ticket created',
  home_visits_support_form_submit_success_message: 'Your support ticket was sent successfully.',
  home_visits_support_form_submit_error_title: 'Ticket failed',
  home_visits_support_chat_cta: 'Chat with a person',
  home_visits_support_admin_picker_title: 'Chat with support',
  home_visits_support_admin_picker_subtitle: 'Choose an available support admin',
  home_visits_support_admin_picker_loading: 'Loading support admins...',
  home_visits_support_admin_picker_empty: 'No support admins available right now.',
  home_visits_service_unavailable_booking:
    'This service is currently unavailable and cannot be booked.',
  home_visits_support_admin_picker_row_subtitle: 'Support admin',
  home_visits_support_faq_title: 'Frequently asked questions',
  home_visits_support_faq_item_1: 'How to book an appointment',
  home_visits_support_faq_item_2: 'How do I cancel or reschedule my appointment?',
  home_visits_support_faq_item_3: 'What payment methods are accepted?',
  home_visits_support_faq_item_4: 'Can I bring a friend to my appointment?',
  home_visits_support_faq_item_5: 'What is your cancellation policy?',
  home_visits_support_faq_item_6: 'Do you offer any discounts or promotions?',
  home_visits_support_conversations_title: 'My conversations',
  home_visits_support_conversations_loading: 'Loading conversations...',
  home_visits_support_conversations_empty: 'No conversations found yet.',
  home_visits_support_tickets_title: 'My tickets',
  home_visits_support_tickets_heading: 'My ticket',
  home_visits_support_tickets_search_action: 'Search tickets',
  home_visits_support_tickets_loading: 'Loading tickets...',
  home_visits_support_tickets_empty: 'No tickets found yet.',
  home_visits_support_tickets_order_id: 'Order ID: {{orderId}}',
  home_visits_support_ticket_fallback_title: 'Support ticket',
  home_visits_support_chat_agent_fallback: 'Support agent',
  home_visits_support_chat_empty_message: 'No messages yet',
  home_visits_support_chat_title: 'Salon Support',
  home_visits_support_chat_auto_message: 'How can we help you today?',
  home_visits_support_chat_auto_time: 'now',
  home_visits_support_chat_empty: 'No messages yet. Start by writing a message below.',
  home_visits_support_chat_input_placeholder: 'Enter your concern...',
  home_visits_support_chat_send_error_title: 'Unable to send',
  home_visits_support_chat_send_error_message:
    'We could not send your support message right now.',
  home_visits_support_chat_missing_session_error:
    'Your support session is not ready yet. Please try again in a moment.',
  home_visits_support_chat_quick_reply_help: 'I need help',
  home_visits_support_chat_quick_reply_booking: 'Booking issue',
  home_visits_support_chat_quick_reply_payment: 'Payment issue',
  home_visits_support_chat_quick_reply_provider: 'Provider issue',
  home_visits_support_chat_attachment_action: 'Attach image',
  home_visits_support_chat_send_action: 'Send message',
  home_visits_support_chat_attachment_permission_title: 'Permission required',
  home_visits_support_chat_attachment_permission_message:
    'Please allow photo library access to attach an image.',
  home_visits_support_chat_attachment_selected_title: 'Attachment selected',
  home_visits_support_chat_attachment_selected_message:
    '{{fileName}} is ready to send.',
  home_visits_support_call_unavailable: 'Call support is unavailable right now.',
  Unable_to_load_items: 'Unable to load items',
  Please_try_again_in_a_moment: 'Please try again in a moment.',
  // Search related translations
  services: 'Services',
  see_all: 'See all',
  off: 'off'
};

export default en;
