const fr = {
  label: 'Visites à Domicile',
  description: 'Planifiez des visites de confiance.',
  header_title: 'Visites à Domicile',
  header_subtitle: 'Services à la demande',
  section_title: 'Choisissez votre mode',
  single_vendor_title: 'Prestataire Unique',
  single_vendor_desc: 'Une expérience ciblée pour un seul prestataire.',
  single_vendor_chip: 'Flux principal',
  single_vendor_stat: "Reserve avec l'experience actuelle",
  single_vendor_categories_title: 'Catégories',
  single_vendor_category_services_empty: 'Aucun service trouvé pour cette catégorie.',
  multi_vendor_title: 'Multi Prestataires',
  multi_vendor_desc: 'Parcourez plusieurs prestataires de visites à domicile.',
  multi_vendor_chip: 'Services proches',
  multi_vendor_stat: 'Parcourez les prestataires autour de vous',
  multi_vendor_main_services_title: 'Services principaux',
  multi_vendor_service_type_title: 'Type de service',
  multi_vendor_service_type_categories_empty:
    'Aucune categorie trouvee pour ce type de service.',
  multi_vendor_top_centers_title: 'Meilleurs centres',
  multi_vendor_top_centers_empty: 'Aucun centre principal disponible pour le moment.',
  multi_vendor_deals_title: 'Offres',
  multi_vendor_deals_empty: 'Aucune offre de service disponible pour le moment.',
  multi_vendor_providers_title: 'Prestataires proches',
  multi_vendor_service_providers_title: 'Prestataires de service',
  multi_vendor_service_providers_empty: 'Aucun prestataire de service disponible pour le moment.',
  multi_vendor_nearby_services_title: 'Services proches',
  multi_vendor_providers_empty: 'Aucun prestataire disponible pour ce service pour le moment.',
  multi_vendor_nearby_services_empty: 'Aucun service proche disponible pour le moment.',
  multi_vendor_favorite_added: 'Ajoute aux favoris',
  multi_vendor_favorite_removed: 'Retire des favoris',
  multi_vendor_favorite_error: 'Impossible de mettre a jour les favoris pour le moment.',
  multi_vendor_center_info_title: 'Informations du centre',
  multi_vendor_center_info_category: 'Categorie',
  multi_vendor_center_info_availability: 'Disponibilite',
  multi_vendor_center_info_address: 'Adresse',
  multi_vendor_center_info_distance: 'Distance',
  multi_vendor_center_info_rating: 'Note',
  multi_vendor_center_info_starting_price: 'Prix de depart',
  multi_vendor_center_info_fallback: 'Aucune information de centre disponible pour le moment.',
  chain_title: 'Chaîne',
  chain_desc: 'Un flux structuré pour les chaînes de services.',
  chain_chip: 'Mode futur',
  chain_stat: 'Reserve aux services en chaine',
  explore_button: 'Explorer',
  single_vendor_tab_home: 'Accueil',
  single_vendor_tab_search: 'Recherche',
  single_vendor_tab_orders: 'Réservations',
  single_vendor_tab_profile: 'Profil',
  single_vendor_bookings_title: 'Ma réservation',
  single_vendor_bookings_tab_ongoing: 'En cours',
  single_vendor_bookings_tab_past: 'Passées',
  single_vendor_bookings_view_details: 'Voir les détails',
  single_vendor_bookings_book_again: 'Réserver à nouveau',
  single_vendor_favorites_title: 'Favoris',
  single_vendor_favorites_empty: 'Aucun élément n’est actuellement dans la liste des favoris.',
  single_vendor_favorites_error: 'Impossible de charger les favoris pour le moment.',
  single_vendor_bookings_item: 'article',
  single_vendor_bookings_items: 'articles',
  single_vendor_bookings_retry: 'Réessayer',
  single_vendor_bookings_error_title: 'Impossible de charger les réservations',
  single_vendor_bookings_empty_title_ongoing: 'Aucune réservation en cours',
  single_vendor_bookings_empty_subtitle_ongoing: 'Vos réservations actives apparaîtront ici.',
  single_vendor_bookings_empty_title_past: 'Aucune réservation passée',
  single_vendor_bookings_empty_subtitle_past: 'Vos réservations terminées ou annulées apparaîtront ici.',
  single_vendor_bookings_empty_generic_title: 'Aucune réservation trouvée',
  single_vendor_bookings_empty_generic_subtitle:
    'Vos réservations à venir et passées apparaîtront ici une fois effectuées.',
  single_vendor_booking_status_confirmed: 'Confirmée',
  single_vendor_booking_default_duration: 'Durée de 1 h',
  single_vendor_booking_add_calendar_title: 'Ajouter au calendrier',
  single_vendor_booking_add_calendar_subtitle: 'Définissez un rappel',
  single_vendor_booking_calendar_open_error: 'Impossible d’ouvrir le calendrier pour le moment.',
  single_vendor_booking_manage_title: 'Gérer le rendez-vous',
  single_vendor_booking_manage_subtitle: 'Reprogrammez ou annulez votre rendez-vous',
  single_vendor_booking_cancel_subtitle: 'Annuler votre rendez-vous',
  single_vendor_booking_track_title: 'Suivre le prestataire',
  single_vendor_booking_track_subtitle: 'Suivez votre prestataire',
  single_vendor_active_service_title: 'Service commence',
  single_vendor_active_service_default_title: 'Nettoyage maison',
  single_vendor_active_service_default_subtitle: 'Ouvrir votre service actif',
  single_vendor_track_worker_title: 'Votre rendez-vous',
  single_vendor_track_worker_estimated_service_label: 'Duree estimee du service',
  single_vendor_track_worker_eta_label: "Heure d'arrivee estimee",
  single_vendor_track_worker_eta_10_15: '10-15 min',
  single_vendor_track_worker_eta_15_25: '15-25 min',
  single_vendor_track_worker_anytime_now: "D'un moment a l'autre",
  single_vendor_track_worker_preparing_subtitle:
    "Votre commande est enregistree et le prestataire prepare l'equipement.",
  single_vendor_track_worker_on_the_way: 'Votre prestataire est en route !',
  single_vendor_track_worker_anytime_subtitle:
    'A tout moment ! Restez disponible pour votre prestataire.',
  single_vendor_track_worker_service_started: 'Le service a commence !',
  single_vendor_track_worker_started_subtitle: 'Le service est maintenant en cours !',
  single_vendor_track_worker_contact_title: 'Contacter votre prestataire',
  single_vendor_track_worker_contact_subtitle: 'Demandez un service sans contact',
  single_vendor_track_worker_contact_unavailable:
    "Le contact du prestataire n'est pas disponible pour le moment.",
  single_vendor_track_worker_appointment_details: 'Details du rendez-vous',
  single_vendor_track_worker_booking_number: 'Numero de reservation',
  single_vendor_track_worker_appointment_address: 'Adresse du rendez-vous',
  single_vendor_track_worker_address_fallback: 'Adresse non disponible',
  single_vendor_track_worker_around_corner_title:
    'Preparez-vous, notre prestataire est juste au coin de la rue.',
  single_vendor_track_worker_around_corner_subtitle: '',
  single_vendor_track_worker_view: 'Voir',
  single_vendor_track_worker_payment_title:
    'Travail termine ! Completez votre transaction',
  single_vendor_track_worker_payment_subtitle:
    'Votre service est termine avec succes. Veuillez verifier les details de cette facture finale et proceder au paiement.',
  single_vendor_track_worker_payment_by: 'Paiement par',
  single_vendor_track_worker_online_payment: 'Paiement en ligne',
  single_vendor_track_worker_pay_now: 'Payer maintenant',
  single_vendor_track_worker_payment_failed: 'Echec du paiement',
  single_vendor_track_worker_payment_processing: 'Le paiement est en cours',
  single_vendor_track_worker_waiting_payment_request:
    'Le paiement sera active une fois que le prestataire aura demande le paiement.',
  single_vendor_track_worker_payment_confirmed: 'Paiement confirme',
  single_vendor_track_worker_saved_card_required_title: 'Carte enregistree requise',
  single_vendor_track_worker_saved_card_required_message:
    'Ajoutez une carte enregistree dans votre portefeuille Home Visits avant de payer ce service.',
  single_vendor_track_worker_default_card_required_title: 'Carte par defaut requise',
  single_vendor_track_worker_default_card_required_message:
    'Definissez une carte enregistree par defaut dans votre portefeuille Home Visits avant de payer ce service.',
  single_vendor_track_worker_feedback_title: 'Comment etait votre experience ?',
  single_vendor_track_worker_feedback_subtitle:
    'Votre retour nous aide a ameliorer nos services.',
  single_vendor_track_worker_feedback_placeholder: 'Ecrivez votre experience ici...',
  single_vendor_track_worker_submit: 'Envoyer',
  single_vendor_track_worker_feedback_success: 'Merci pour votre retour !',
  single_vendor_track_worker_cancelled: 'Rendez-vous annule',
  single_vendor_track_worker_cancelled_subtitle: "Ce rendez-vous n'est plus actif.",
  single_vendor_track_worker_failed: "Le service n'a pas pu etre termine",
  single_vendor_track_worker_failed_subtitle: "Veuillez contacter l'assistance.",
  single_vendor_booking_service_title: 'Détails du service',
  single_vendor_booking_service_subtitle: 'Les prix peuvent varier selon les services supplémentaires',
  single_vendor_booking_price_summary_title: 'Résumé du prix',
  single_vendor_booking_price_labor: 'Main-d oeuvre',
  single_vendor_booking_price_hourly_rate: 'Taux horaire',
  single_vendor_booking_price_working_hours: 'Heures de travail',
  single_vendor_booking_price_items_used: 'Articles utilisés',
  single_vendor_booking_price_subtotal: 'Sous-total',
  single_vendor_booking_price_discount: 'Remise',
  single_vendor_booking_price_tax: 'Taxe',
  single_vendor_booking_price_delivery_fee: 'Frais de livraison',
  single_vendor_booking_price_packing_charges: 'Frais d emballage',
  single_vendor_booking_price_tip: 'Pourboire',
  single_vendor_booking_service_duration: '1 h',
  single_vendor_booking_duration_job: '1 tâche',
  single_vendor_booking_duration_service: '1 service',
  single_vendor_booking_total: 'Total',
  single_vendor_booking_open_reviews: 'Voir les avis',
  single_vendor_booking_customer_note_title: 'Note du client',
  single_vendor_booking_address_title: 'Adresse de service',
  single_vendor_booking_cancellation_title: 'Politique d’annulation',
  single_vendor_booking_cancellation_body: 'Veuillez annuler dans les 2 heures suivant votre rendez-vous',
  single_vendor_reviews_title: 'Avis',
  single_vendor_reviews_filter_by: 'Filtrer par',
  single_vendor_reviews_sort_by: 'Trier par',
  single_vendor_reviews_latest: 'Plus récents',
  single_vendor_reviews_best: 'Meilleurs',
  single_vendor_reviews_worst: 'Moins bons',
  single_vendor_reviews_summary_label: '{{rating}} ({{count}})',
  single_vendor_reviews_total_label: '{{count}} avis',
  single_vendor_reviews_empty_title: 'Aucun avis pour le moment',
  single_vendor_reviews_empty_subtitle: 'Soyez le premier a laisser un avis pour ce service.',
  single_vendor_reviews_service_home_cleaning: 'Nettoyage maison',
  single_vendor_reviews_service_plumber: 'Plomberie',
  single_vendor_reviews_service_window_cleaning: 'Nettoyage des fenêtres',
  single_vendor_reviews_service_electrician: 'Électricien',
  single_vendor_reviews_service_floor_cleaning: 'Nettoyage du sol',
  single_vendor_reviews_service_washing: 'Lavage',
  single_vendor_reviews_comment_1:
    "Super service ! Ma maison est impeccable et sent très bon. Je réserverai encore.",
  single_vendor_reviews_comment_2:
    "Excellent nettoyage ! L'équipe était ponctuelle, aimable et très minutieuse.",
  single_vendor_reviews_comment_3:
    "Le meilleur service ! Ma maison paraît neuve. Je recommande vivement cette entreprise.",
  single_vendor_reviews_comment_4:
    "Je suis très satisfaite du service. L'équipe était professionnelle et a fait un travail fantastique.",
  single_vendor_reviews_comment_5:
    "L'équipe a été efficace et appliquée. Ma maison n'a jamais été aussi propre. Merci !",
  single_vendor_reviews_comment_6:
    "Je suis ravie d'avoir choisi cette entreprise. Ils étaient à l'heure et ont fait un travail incroyable.",
  single_vendor_reviews_comment_7:
    "Je suis très impressionnée par la qualité du service. Ma maison est maintenant étincelante !",
  single_vendor_manage_appointment_title: 'Gérer le rendez-vous',
  single_vendor_manage_appointment_reschedule: 'Reprogrammer le rendez-vous',
  single_vendor_manage_appointment_cancel: 'Annuler le rendez-vous',
  single_vendor_manage_appointment_empty_title: 'Aucun rendez-vous trouvé',
  single_vendor_manage_appointment_empty_subtitle:
    'Vos rendez-vous à venir et passés apparaîtront lorsque vous réserverez',
  single_vendor_manage_appointment_search_service: 'Rechercher un service',
  single_vendor_cancel_appointment_heading: 'Êtes-vous sûr de vouloir annuler le rendez-vous ?',
  single_vendor_cancel_appointment_body_top:
    'Si vous souhaitez modifier l’heure du rendez-vous, vous pouvez le reprogrammer.',
  single_vendor_cancel_appointment_body_bottom:
    'Êtes-vous sûr de vouloir annuler votre rendez-vous ?',
  single_vendor_cancel_appointment_cta: 'Oui, annuler le rendez-vous',
  single_vendor_cancel_appointment_loading: 'Annulation...',
  single_vendor_cancel_appointment_success_title: 'Rendez-vous annulé',
  single_vendor_cancel_appointment_success_message:
    'Votre rendez-vous a été annulé avec succès.',
  single_vendor_cancel_appointment_error_title:
    'Impossible d’annuler le rendez-vous',
  single_vendor_cancel_appointment_started_message:
    'Cette intervention ne peut plus être annulée une fois commencée.',
  single_vendor_contract_details_title: 'Détails du contrat',
  single_vendor_contract_loading: 'Chargement du contrat...',
  single_vendor_contract_overview_title: 'Aperçu',
  single_vendor_contract_assigned_team_title: 'Équipe assignée',
  single_vendor_contract_notes_title: 'Notes',
  single_vendor_contract_billing_title: 'État de facturation',
  single_vendor_contract_invoices_title: 'Factures',
  single_vendor_contract_schedule_title: 'Planning',
  single_vendor_contract_plan_label: 'Forfait',
  single_vendor_contract_status_label: 'Statut',
  single_vendor_contract_team_label: 'Équipe',
  single_vendor_contract_daily_hours_label: 'Heures par jour',
  single_vendor_contract_service_center_label: 'Centre de service',
  single_vendor_contract_visit_days_label: 'Jours de visite',
  single_vendor_contract_start_date_label: 'Date de début',
  single_vendor_contract_end_date_label: 'Date de fin',
  single_vendor_contract_supervisor_members_label: 'Superviseur et membres',
  single_vendor_contract_lead_worker_label: 'Travailleur principal',
  single_vendor_contract_team_member_label: 'Membre de l’équipe',
  single_vendor_contract_job_description_label: 'Description du travail',
  single_vendor_contract_customer_note_label: 'Note du client',
  single_vendor_contract_saved_card_label: 'Carte enregistrée',
  single_vendor_contract_saved_card_available: 'Disponible',
  single_vendor_contract_saved_card_missing: 'Non ajoutée',
  single_vendor_contract_due_date_label: 'Date d’échéance',
  single_vendor_contract_visits_in_invoice_label: 'Visites dans la facture',
  single_vendor_contract_paid_at_label: 'Payée le',
  single_vendor_contract_pay_invoice: 'Payer la facture',
  single_vendor_contract_pay_overdue_invoice: 'Payer la facture en retard',
  single_vendor_contract_schedule_coverage_label: 'Couverture',
  single_vendor_contract_schedule_delivery_label: 'Prestation',
  single_vendor_contract_schedule_delivery_value:
    'Géré par l’administrateur avec facturation mensuelle',
  single_vendor_contract_pending_status_label: 'En attente d’approbation',
  single_vendor_contract_flexible: 'Flexible',
  single_vendor_contract_no_team: 'Aucune équipe assignée pour le moment',
  single_vendor_contract_worker_fallback: 'Travailleur',
  single_vendor_contract_individual: 'Individuel',
  single_vendor_contract_team_value: 'Équipe ({{count}})',
  single_vendor_contract_daily_hours_value: '{{count}} h',
  single_vendor_contract_contract_cancellation_title: 'Annulation du contrat',
  single_vendor_contract_contract_cancellation_status_label:
    'Statut de l’annulation',
  single_vendor_contract_contract_cancellation_reason_label: 'Raison',
  single_vendor_contract_contract_cancellation_review_note_label:
    'Note de l’administrateur',
  single_vendor_contract_contract_cancellation_requested_at_label:
    'Demandé le',
  single_vendor_contract_contract_cancellation_reviewed_at_label:
    'Examiné le',
  single_vendor_contract_contract_cancellation_request_button:
    'Demander l’annulation',
  single_vendor_contract_contract_cancellation_request_again_button:
    'Redemander l’annulation',
  single_vendor_contract_contract_cancellation_reason_placeholder:
    'Expliquez pourquoi vous souhaitez annuler ce contrat.',
  single_vendor_contract_contract_cancellation_submit: 'Envoyer la demande',
  single_vendor_contract_contract_cancellation_submitting: 'Envoi...',
  single_vendor_contract_contract_cancellation_success_title: 'Demande envoyée',
  single_vendor_contract_contract_cancellation_success_message:
    'Votre demande d’annulation a été envoyée pour validation par l’administrateur.',
  single_vendor_contract_contract_cancellation_error_title:
    'Impossible de demander l’annulation',
  single_vendor_contract_contract_cancellation_status_none: 'Aucune demande',
  single_vendor_contract_contract_cancellation_status_requested:
    'Annulation demandée',
  single_vendor_contract_contract_cancellation_status_rejected:
    'Demande refusée',
  single_vendor_contract_contract_cancellation_status_approved: 'Annulé',
  single_vendor_contract_invoice_paid_title: 'Facture payée',
  single_vendor_contract_invoice_paid_message:
    'Votre facture de contrat a été payée avec succès.',
  single_vendor_contract_invoice_processing_title: 'Paiement en cours',
  single_vendor_contract_invoice_payment_failed_title: 'Paiement échoué',
  single_vendor_contract_saved_card_required_title: 'Carte enregistrée requise',
  single_vendor_contract_saved_card_required_message:
    'Ajoutez une carte enregistrée dans votre portefeuille Home Visits avant de payer cette facture.',
  single_vendor_contract_default_card_required_title: 'Carte par défaut requise',
  single_vendor_contract_default_card_required_message:
    'Définissez une carte enregistrée par défaut dans votre portefeuille Home Visits avant de payer cette facture.',
  single_vendor_contract_invoice_payment_failed_message:
    'Nous n’avons pas pu traiter le paiement de la facture du contrat.',
  single_vendor_home_body: 'Écran d’accueil de base pour le flux à prestataire unique.',
  single_vendor_search_body: 'Écran de recherche de base pour le flux à prestataire unique.',
  single_vendor_orders_body: 'Écran de réservations de base pour le flux à prestataire unique.',
  single_vendor_profile_body: 'Écran de profil de base pour le flux à prestataire unique.',
  multi_vendor_home_body: 'Écran d’accueil de base pour le flux multi prestataires.',
  chain_home_body: 'Écran d’accueil de base pour le flux chaîne.',
  logout: 'Se déconnecter',
  logout_error_title: 'Erreur',
  logout_error_message: 'Impossible de vous déconnecter pour le moment.',
  details_title: 'Détails de la Visite',
  details_body: 'Détails de la visite et informations du prestataire.',
  // Address related strings
  single_vendor_home_subtitle: 'Planifiez des visites à domicile de confiance',
  single_vendor_home_section_empty_title: 'Rien à afficher pour le moment',
  single_vendor_home_section_error_title: 'Impossible de charger les éléments',
  single_vendor_home_section_error_message: 'Veuillez réessayer dans un instant.',
  home_visits_address_label: 'Sélectionner le lieu de service',
  add_service_address: 'Ajouter une adresse de service',
  address_select_error: 'Échec de la sélection de l\'adresse. Veuillez réessayer.',
  address_selector_title: 'Sélectionner le Lieu de Service',
  address_selector_close: 'Fermer',
  address_selector_use_current_location: 'Utiliser la position actuelle',
  address_selector_add_new: 'Ajouter une nouvelle adresse',
  single_vendor_deals_title:'accords',
  single_vendor_nearby_location_title: 'Pres de votre emplacement',
  single_vendor_most_popular_services_title: 'Services les plus populaires',
  single_vendor_nearby_location_select_address_message:
    'Selectionnez une adresse de service pour voir les services a proximite.',
  single_vendor_see_all: 'voir tout',
  chain_categories_title: 'Categories',
  chain_category_services_empty: 'Aucun service trouve pour cette categorie.',
  chain_menu_template_selector_label: 'Selectionner le menu de la chaine',
  chain_menu_template_loading: 'Chargement des menus',
  chain_menu_template_empty: 'Aucun menu',
  chain_menu_template_unavailable: 'Menu indisponible',
  offers: 'Offres',
  search: 'Rechercher',
  closed: 'Fermé',
  all_offered_items: 'Tous les articles proposes',
  clear_all: 'Tout effacer',
  single_vendor_home_section_empty_message: 'Revenez plus tard pour en savoir plus.',
  home_visits_see_all_search_placeholder: 'Rechercher des services',
  home_visits_see_all_coming_soon_title: 'Bientôt disponible',
  home_visits_see_all_coming_soon_description:
    'Cet écran Voir tout sera bientôt disponible pour ce mode.',
  home_visits_filter_title: 'Filtrer',
  home_visits_filter_close: 'Fermer les filtres',
  home_visits_filter_stock_title: 'Stock',
  home_visits_filter_stock_all: 'Tous',
  home_visits_filter_stock_in_stock: 'En stock',
  home_visits_filter_price_tiers: 'Niveau de prix',
  home_visits_filter_any_price: 'Tous les prix',
  home_visits_filter_sort_by: 'Trier par',
  home_visits_filter_sort_recommended: 'Recommandé',
  home_visits_filter_sort_delivery_time: 'Temps de livraison',
  home_visits_filter_sort_price_low_to_high: 'Prix croissant',
  home_visits_filter_sort_name: 'Nom',
  home_visits_filter_sort_rating: 'Meilleure note',
  home_visits_filter_clear: 'Effacer',
  home_visits_filter_apply: 'Appliquer',
  service_details_book_service: 'Reserver le service',
  team_schedule_title: 'Equipe et Planning',
  team_schedule_team_size_title: "Taille de l'equipe",
  team_schedule_team_size_helper: 'Le prix est calcule par travailleur et par heure.',
  team_schedule_working_hours_title: 'Heures de travail',
  team_schedule_working_hours_helper: 'Chaque travailleur est facture a 12 $ par heure',
  team_schedule_working_hours_input_placeholder: "Entrer le nombre d'heures (1-12)",
  team_schedule_worker_type_title: 'Type de travailleur',
  team_schedule_worker_type_individual_title: 'Individuel',
  team_schedule_worker_type_individual_description: 'Juste pour maintenant',
  team_schedule_worker_type_team_title: 'Equipe',
  team_schedule_worker_type_team_description: "La meme equipe travaille chaque jour. Gere par notre admin.",
  team_schedule_service_mode_title: 'Type de service',
  team_schedule_service_mode_one_time_title: 'Service ponctuel',
  team_schedule_service_mode_one_time_description: 'Juste pour maintenant',
  team_schedule_service_mode_contract_title: 'Contrat',
  team_schedule_service_mode_contract_description: "La meme equipe travaille chaque jour. Gere par notre admin.",
  team_schedule_contract_range_title: "Saisir la duree",
  team_schedule_contract_range_helper: 'Selectionnez la plage pour le contrat',
  team_schedule_contract_range_custom: 'Personnalise',
  team_schedule_contract_range_custom_placeholder: 'Choisissez des jours, comme 1 ou 2.',
  team_schedule_contract_range_add: 'Ajouter',
  team_schedule_continue: 'Continuer',
  team_schedule_custom_title: "Entrer les membres de l'equipe",
  team_schedule_custom_helper: 'Vous pouvez selectionner jusqu a 12 travailleurs',
  team_schedule_custom_field_placeholder: '1 travailleur',
  team_schedule_custom_add: 'Ajouter',
  team_schedule_job_description_title: 'Description du travail',
  team_schedule_job_description_placeholder: 'Ajoutez des notes sur le travail a effectuer.',
  team_schedule_job_description_required: 'Veuillez ajouter une description du travail pour continuer.',
  team_schedule_date_time_title: "Choisir la date et l'heure",
  team_schedule_date_time_confirm: "Confirmer la date et l'heure",
  team_schedule_select_date_title: 'Selectionnez la date',
  team_schedule_time_selected_day_title: 'Heure du jour selectionne',
  team_schedule_time_selected_days_title: 'Heure des jours selectionnes',
  team_schedule_start_time_label: 'Heure de debut',
  team_schedule_end_time_label: 'Heure de fin',
  team_schedule_selected_days_count: '{{count}} jours selectionnes',
  team_schedule_contract_section_title: 'Selectionnez le type de contrat',
  team_schedule_contract_type_label: 'Type de contrat',
  team_schedule_contract_type_sheet_title: 'Type de contrat',
  team_schedule_contract_type_weekly: 'Hebdomadaire',
  team_schedule_contract_type_monthly: 'Mensuel',
  team_schedule_contract_type_yearly: 'Annuel',
  team_schedule_working_hours_hour: 'heure',
  team_schedule_working_hours_hours: 'heures',
  team_schedule_repeat_label: 'Repeter chaque {{contractType}}',
  team_schedule_repeat_every_week: 'Repeter chaque semaine',
  team_schedule_repeat_weekly_description: 'Appliquer les memes jours chaque semaine',
  team_schedule_repeat_monthly_description: 'Appliquer les memes jours chaque mois',
  team_schedule_repeat_yearly_description: 'Appliquer les memes jours chaque annee',
  team_schedule_end_date_label: 'Date de fin',
  team_schedule_pick_date: 'Choisir une date',
  team_schedule_picker_confirm: 'Confirmer',
  team_schedule_start_time_picker_title: 'Selectionnez l heure de debut',
  team_schedule_end_time_picker_title: 'Selectionnez l heure de fin',
  team_schedule_end_date_picker_title: 'Selectionnez la date de fin',
  team_schedule_one_time_info:
    'Il s agit d un travail ponctuel. Vous pouvez planifier des jours consecutifs jusqu a 10 jours maximum. Pour des visites recurrentes hebdomadaires ou mensuelles avec la meme equipe et un horaire fixe, veuillez choisir un contrat.',
  team_schedule_contract_info:
    'Il s agit d un contrat {{contractType}}. La meme equipe arrivera a cette heure a chaque visite planifiee, geree par l admin FixRight.',
  team_schedule_start_date_future_error: 'La date de debut ne peut pas etre dans le passe.',
  team_schedule_start_time_future_error: 'L heure de debut doit etre au moins 30 minutes plus tard.',
  team_schedule_one_time_start_hint: 'La prochaine heure de debut disponible est dans au moins 30 minutes.',
  team_schedule_weekly_select_day_error: 'Selectionnez au moins un jour de la semaine pour le contrat hebdomadaire.',
  team_schedule_yearly_select_month_error: 'Selectionnez au moins un mois pour le contrat annuel.',
  team_schedule_end_date_after_start_error: 'La date de fin du contrat doit etre apres la date de debut.',
  team_schedule_no_upcoming_visits_error: 'Aucune visite a venir trouvee. Ajustez les parametres du contrat.',
  team_schedule_contract_min_days_error: 'Veuillez selectionner au moins 7 jours consecutifs.',
  team_schedule_repeat_weekdays_label: 'Repeter les jours de la semaine',
  team_schedule_day_of_month_label: 'Jour du mois',
  team_schedule_months_label: 'Mois',
  team_schedule_advanced_recurrence_title: 'Recurrence avancee',
  team_schedule_yearly_range_helper:
    'La date de debut et la date de fin du contrat determinent automatiquement la plage des annees.',
  team_schedule_summary_weekly_days: '{{count}} jour(s) de semaine selectionne(s)',
  team_schedule_summary_monthly_day: 'Execution le jour {{day}} de chaque mois',
  team_schedule_summary_yearly_months: '{{count}} mois selectionne(s), jour {{day}}',
  team_schedule_upcoming_visits_preview: 'Visites a venir : {{dates}}',
  team_schedule_no_upcoming_visits: 'Aucune visite a venir n est encore generee.',
  team_schedule_non_repeat_helper: 'La repetition est desactivee. Selectionnez des jours consecutifs (minimum 7).',
  team_schedule_non_repeat_mode_label: 'Mode de planification : jours consecutifs',
  team_schedule_range_mode_hint:
    'Mode plage : selectionnez une date de debut, puis une date de fin (possible le mois suivant).',
  team_schedule_today: "Aujourd'hui",
  team_worker_singular: 'travailleur',
  team_worker_plural: 'travailleurs',
  team_schedule_hour_singular: 'heure',
  team_schedule_hour_plural: 'heures',
  team_schedule_day_singular: 'Jour',
  team_schedule_day_plural: 'Jours',
  review_confirm_title: 'Verifier et confirmer',
  review_confirm_home: 'Domicile',
  review_confirm_notes_title: 'Notes',
  review_confirm_optional: 'Optionnel',
  review_confirm_notes_placeholder: 'Instructions pour le technicien',
  review_confirm_schedule_for: 'Planifie pour',
  review_confirm_appointment_time: 'Heure du rendez-vous',
  review_confirm_payment_section_title: 'Paiement',
  review_confirm_payment_title: 'Especes',
  review_confirm_payment_card_label: '**** 9432',
  review_confirm_payment_subtitle: 'Touchez pour changer',
  review_confirm_choose_payment_method_title: 'Choisir le mode de paiement',
  review_confirm_add_payment_method: 'Ajouter un mode de paiement',
  review_confirm_discount_title: 'Code promo',
  review_confirm_discount_subtitle: 'Touchez pour continuer',
  review_confirm_discount_placeholder: 'Entrer le code promo',
  review_confirm_discount_use_code: 'Utiliser le code promo',
  review_confirm_discount_applied: 'Applique : {{code}}',
  review_confirm_cancellation_title: "Politique d'annulation",
  review_confirm_cancellation_body: 'Veuillez annuler au moins 2 heures avant votre rendez-vous',
  review_confirm_cancellation_notice_two_hours:
    'Veuillez annuler au moins 2 heures avant votre rendez-vous.',
  review_confirm_cancellation_notice_thirty_minutes:
    'Veuillez annuler au moins 30 minutes avant votre rendez-vous.',
  review_confirm_cancellation_notice_fifteen_minutes:
    'Veuillez annuler au moins 15 minutes avant votre rendez-vous.',
  review_confirm_summary_title: 'Resume',
  review_confirm_summary_subtitle:
    'Taxes incluses (si applicables) • Les prix peuvent varier selon les services supplementaires',
  review_confirm_contract_price_pending:
    'L\'administrateur fixera le prix du contrat après approbation.',
  review_confirm_contract_price_footer_note:
    'Les frais mensuels apparaîtront une fois le contrat approuvé par l\'administrateur.',
  review_confirm_footer_cta: 'Confirmer',
  single_vendor_contract_pending_approval: 'En attente du tarif fixé par admin',
  single_vendor_contract_monthly_fee: 'Frais mensuels',
  single_vendor_contract_approved_at: 'Approuvé le',
  review_confirm_services_title: 'Services selectionnes',
  review_confirm_schedule_title: 'Equipe et planning',
  review_confirm_team_label: 'Equipe',
  review_confirm_hours_label: 'Heures',
  review_confirm_type_label: 'Type',
  review_confirm_date_time_label: 'Date et heure',
  review_confirm_cta: 'Confirmer la reservation',
  review_confirm_location_title: 'Lieu du service',
  review_confirm_location_label: 'Adresse',
  review_confirm_location_fallback: 'Aucune adresse selectionnee',
  review_confirm_price_title: 'Resume du prix',
  review_confirm_price_services: 'Services selectionnes',
  review_confirm_price_workers: 'Equipe et heures',
  review_confirm_price_tax: 'Taxe',
  review_confirm_price_delivery_fee: 'Frais de livraison',
  review_confirm_price_packing_charges: 'Frais d emballage',
  review_confirm_price_tip: 'Pourboire',
  review_confirm_price_total: 'Total',
  review_confirm_popup_title: 'Veuillez noter',
  review_confirm_popup_line_two: 'Vous serez facture uniquement apres la fin du service.',
  review_confirm_popup_accept: 'Accepter et confirmer',
  review_confirm_success_title: 'Reserve',
  review_confirm_success_body: 'Votre demande de reservation est prete.',
  review_confirm_appointment_confirmed: 'Rendez-vous confirme',
  review_confirm_place_order_error_title: 'Impossible de confirmer la reservation',
  review_confirm_place_order_error_description:
    'Veuillez reessayer dans un instant.',
  team_schedule_availability_unavailable_title: 'Planification indisponible',
  team_schedule_availability_unavailable_description:
    "Ce centre de service n'accepte pas de reservations planifiees pour cette date.",
  team_schedule_slot_not_available_title: 'Creneau indisponible',
  team_schedule_slot_not_available_description:
    "L'heure choisie n'est pas disponible pour la taille de votre equipe. Veuillez choisir une autre heure.",
  team_schedule_availability_error_title: "Impossible de verifier la disponibilite",
  team_schedule_availability_error_description:
    'Veuillez reessayer dans un instant.',
  ok: 'Ok',
  service_details_service_singular: 'service',
  service_details_service_plural: 'services',
  service_details_service_type_fallback: 'Type de service',
  service_details_additional_services_fallback: 'Services supplementaires',
  service_details_favorite_action: 'Favori',
  service_details_share_action: 'Partager',
  Nothing_here_yet: 'Rien ici encore',
  Content_for_this_section_will_appear_once_items_are_available: 'Le contenu de cette section apparaîtra dès que les articles seront disponibles.',
  home_visits_settings_body: 'Le flux des paramètres pour les visites à domicile sera ajouté ensuite.',
  home_visits_support_body: "Le flux d'assistance pour les visites à domicile sera ajouté ensuite.",
  home_visits_wallet_body: 'Le flux du portefeuille pour les visites à domicile sera ajouté ensuite.',
  wallet_balance_label: 'Solde du portefeuille',
  wallet_cards_title: 'Cartes',
  wallet_add_card: 'Ajouter une carte de debit/credit',
  wallet_recent_transactions: 'Transactions recentes',
  wallet_transactions_empty_title: 'Aucune transaction pour le moment',
  wallet_transactions_empty_description: 'L activite de votre portefeuille apparaitra ici apres un paiement ou un remboursement.',
  wallet_see_all: 'Voir tout',
  wallet_add_card_title: 'Ajouter une carte',
  wallet_name_on_card: 'Nom sur la carte',
  wallet_name_placeholder: 'Ajoutez le nom complet du titulaire',
  wallet_card_number_label: 'Numero de carte',
  wallet_pay_securely: 'Paiement securise avec Stripe',
  wallet_save_card: 'Enregistrer',
  wallet_no_saved_cards: 'Aucune carte enregistree',
  wallet_add_card_error: 'Impossible d enregistrer la carte',
  wallet_stripe_publishable_key_missing: 'La cle publique Stripe est manquante.',
  wallet_card_incomplete: 'Veuillez completer les details de la carte.',
  wallet_card_saved_success_title: 'Carte enregistree',
  wallet_card_saved_success_message: 'Votre carte a ete ajoutee avec succes.',
  support_call_action: 'Appeler l’assistance',
  home_visits_support_back_action: 'Retour',
  home_visits_support_greeting: 'Salut {{name}} !',
  home_visits_support_guest_name: 'vous',
  home_visits_support_headline: 'De quelle aide avez-vous besoin aujourd’hui ?',
  home_visits_support_browse_topics: 'Parcourir les sujets d’aide',
  home_visits_support_topic_faq: 'Questions fréquemment posées',
  home_visits_support_topic_conversations: 'Mes conversations',
  home_visits_support_topic_tickets: 'Mes tickets',
  home_visits_support_issue_prompt: 'Vous n’avez pas trouvé ce dont vous avez besoin ?',
  home_visits_support_issue_placeholder: 'Sélectionnez un type de problème',
  home_visits_support_issue_select_title: 'Sélectionner un problème',
  home_visits_support_issue_booking: 'Aide de réservation',
  home_visits_support_issue_reschedule: 'Annuler ou reprogrammer',
  home_visits_support_issue_payment: 'Problème de paiement',
  home_visits_support_issue_joining_as_a_business:
    'Je souhaite rejoindre Home Services en tant qu’entreprise',
  home_visits_support_issue_business_support:
    'J’ai deja un compte entreprise et j’ai besoin d’assistance',
  home_visits_support_issue_appointment_support:
    'J’ai reserve un rendez-vous avec une entreprise sur Home Services',
  home_visits_support_close_action: 'Fermer le formulaire d’assistance',
  home_visits_support_form_how_help_label: 'Comment pouvons-nous vous aider ?',
  home_visits_support_form_email_label: 'Email',
  home_visits_support_form_email_helper:
    'Si vous avez un compte Home Services, entrez l’adresse email utilisee pour vous connecter',
  home_visits_support_form_full_name_label: 'Nom complet',
  home_visits_support_form_full_name_placeholder: 'Entrez votre nom',
  home_visits_support_form_country_region_label: 'Pays / Region',
  home_visits_support_form_country_region_placeholder: 'Veuillez selectionner',
  home_visits_support_form_mobile_number_label: 'Numero de telephone',
  home_visits_support_form_mobile_number_placeholder: '+61 333 000 0000',
  home_visits_support_form_business_name_label: 'Nom de l’entreprise',
  home_visits_support_form_business_type_label: 'Type d’entreprise',
  home_visits_support_form_business_type_placeholder: 'Veuillez selectionner',
  home_visits_support_form_team_size_label: 'Taille de l’equipe',
  home_visits_support_form_team_size_placeholder: 'Veuillez selectionner',
  home_visits_support_form_reason_label: 'Raison du contact',
  home_visits_support_form_reason_placeholder: 'Veuillez selectionner',
  home_visits_support_form_reason_account_setup: 'Configuration du compte',
  home_visits_support_form_reason_add_on_integrations: 'Modules et integrations',
  home_visits_support_form_reason_addons_integrations: 'Modules et integrations',
  home_visits_support_form_reason_using_the_app: 'Utilisation de l’application',
  home_visits_support_form_reason_payments_and_payouts: 'Paiements et versements',
  home_visits_support_form_reason_technical_issues: 'Problemes techniques',
  home_visits_support_form_reason_my_orders: 'Mes rendez-vous',
  home_visits_support_form_reason_payments_and_purchases: 'Paiements et achats',
  home_visits_support_form_reason_reviews: 'Avis',
  home_visits_support_form_reason_emails_and_notifications: 'Emails et notifications',
  home_visits_support_form_reason_delete_my_account: 'Supprimer mon compte',
  home_visits_support_form_reason_other: 'Autre',
  home_visits_support_form_country_united_states: 'Etats-Unis',
  home_visits_support_form_country_canada: 'Canada',
  home_visits_support_form_country_united_kingdom: 'Royaume-Uni',
  home_visits_support_form_country_australia: 'Australie',
  home_visits_support_form_country_france: 'France',
  home_visits_support_form_business_description_label:
    'Y a-t-il quelque chose en particulier que vous souhaitez savoir sur Home Services ?',
  home_visits_support_form_appointment_description_label:
    'Veuillez fournir une description de votre demande, y compris votre reference de rendez-vous ou numero de facture',
  home_visits_support_form_description_label: 'Decrivez ce pour quoi vous avez besoin d’aide',
  home_visits_support_form_description_placeholder: 'Entrez une description...',
  home_visits_support_form_attach_title: 'Joindre des captures d’ecran',
  home_visits_support_form_attach_description: 'Deposez vos fichiers ici',
  home_visits_support_form_attach_cta: 'Choisir un fichier',
  home_visits_support_form_send_email: 'Envoyer un email',
  home_visits_support_form_submit_success_title: 'Ticket cree',
  home_visits_support_form_submit_success_message: 'Votre ticket de support a ete envoye avec succes.',
  home_visits_support_form_submit_error_title: 'Echec du ticket',
  home_visits_support_chat_cta: 'Discuter avec une personne',
  home_visits_support_admin_picker_title: 'Discuter avec l’assistance',
  home_visits_support_admin_picker_subtitle: 'Choisissez un agent de support disponible',
  home_visits_support_admin_picker_loading: 'Chargement des agents de support...',
  home_visits_support_admin_picker_empty: 'Aucun agent de support disponible pour le moment.',
  home_visits_service_unavailable_booking:
    'Ce service est actuellement indisponible et ne peut pas etre reserve.',
  home_visits_support_admin_picker_row_subtitle: 'Agent de support',
  home_visits_support_faq_title: 'Questions fréquemment posées',
  home_visits_support_faq_item_1: 'Comment réserver un rendez-vous',
  home_visits_support_faq_item_2: 'Comment annuler ou reprogrammer mon rendez-vous ?',
  home_visits_support_faq_item_3: 'Quels modes de paiement sont acceptés ?',
  home_visits_support_faq_item_4: 'Puis-je venir avec un ami à mon rendez-vous ?',
  home_visits_support_faq_item_5: 'Quelle est votre politique d’annulation ?',
  home_visits_support_faq_item_6: 'Proposez-vous des remises ou promotions ?',
  home_visits_support_conversations_title: 'Mes conversations',
  home_visits_support_conversations_loading: 'Chargement des conversations...',
  home_visits_support_conversations_empty: 'Aucune conversation trouvée pour le moment.',
  home_visits_support_tickets_title: 'Mes tickets',
  home_visits_support_tickets_heading: 'Mon ticket',
  home_visits_support_tickets_search_action: 'Rechercher des tickets',
  home_visits_support_tickets_loading: 'Chargement des tickets...',
  home_visits_support_tickets_empty: 'Aucun ticket trouve pour le moment.',
  home_visits_support_tickets_order_id: 'ID de commande : {{orderId}}',
  home_visits_support_ticket_fallback_title: 'Ticket de support',
  home_visits_support_chat_agent_fallback: 'Agent d’assistance',
  home_visits_support_chat_empty_message: 'Aucun message pour le moment',
  home_visits_support_chat_title: 'Assistance salon',
  home_visits_support_chat_auto_message: 'Comment pouvons-nous vous aider aujourd’hui ?',
  home_visits_support_chat_auto_time: 'maintenant',
  home_visits_support_chat_empty: 'Aucun message pour le moment. Commencez par écrire un message ci-dessous.',
  home_visits_support_chat_input_placeholder: 'Entrez votre problème...',
  home_visits_support_chat_send_error_title: 'Envoi impossible',
  home_visits_support_chat_send_error_message:
    'Nous n’avons pas pu envoyer votre message d’assistance pour le moment.',
  home_visits_support_chat_missing_session_error:
    'Votre session d’assistance n’est pas encore prête. Veuillez réessayer dans un instant.',
  home_visits_support_chat_quick_reply_help: 'J’ai besoin d’aide',
  home_visits_support_chat_quick_reply_booking: 'Problème de réservation',
  home_visits_support_chat_quick_reply_payment: 'Problème de paiement',
  home_visits_support_chat_quick_reply_provider: 'Problème avec le prestataire',
  home_visits_support_chat_attachment_action: 'Joindre une image',
  home_visits_support_chat_send_action: 'Envoyer le message',
  home_visits_support_chat_attachment_permission_title: 'Autorisation requise',
  home_visits_support_chat_attachment_permission_message:
    'Veuillez autoriser l’accès à la photothèque pour joindre une image.',
  home_visits_support_chat_attachment_selected_title: 'Pièce jointe sélectionnée',
  home_visits_support_chat_attachment_selected_message:
    '{{fileName}} est prêt à être envoyé.',
  home_visits_support_call_unavailable: 'L’appel au support est indisponible pour le moment.',
  Unable_to_load_items: 'Impossible de charger les articles',
  Please_try_again_in_a_moment: 'Veuillez réessayer dans un instant.',
  // Search related translations
  services: 'Services',
  see_all: 'Voir tout',
  off: 'désactivé' 
};

export default fr;
