const en = {
  label: 'Ride Sharing',
  description: 'Book rides in minutes.',
  header_title: 'Ride Sharing',
  header_subtitle: 'Get to your destination',
  home_body: 'Book a ride and track it in real time.',
  ride_home_offer_label: '10% off',
  ride_home_offer_title: 'Today’s Special',
  ride_home_offer_percent: '30%',
  ride_home_offer_body: 'Get a discount for every service order! Only valid for today!',
  ride_home_service_ride_title: 'Ride',
  ride_home_service_ride_subtitle: 'Book a ride!',
  ride_home_service_deliveries_title: 'Deliveries',
  ride_home_service_deliveries_subtitle: 'Food, groceries & more',
  ride_home_service_courier_title: 'Courier',
  ride_home_service_courier_subtitle: 'Send parcels securely',
  ride_home_service_home_visits_title: 'Home-Visits',
  ride_home_service_home_visits_subtitle: 'Book services at home',
  ride_options_title: 'Book a ride',
  ride_option_now_title: 'Ride',
  ride_option_now_desc: 'Request a nearby driver',
  ride_option_schedule_title: 'Scheduled',
  ride_option_schedule_desc: 'Plan a pickup in advance',
  ride_option_rental_title: 'Hourly',
  ride_option_rental_desc: 'Keep a car for hours',
  ride_option_courier_title: 'Courier',
  ride_option_courier_desc: 'Send parcels quickly',
  ride_option_women_title: 'Women Ride',
  ride_option_ac_title: 'Ride A/C',
  ride_option_premium_title: 'Premium',
  ride_search_placeholder: 'Where to & for how much?',
  ride_options_empty_destination: 'Search for the destination where you want to go!',
  ride_current_location: 'Current location',
  ride_types_error_title: 'Unable to load ride types',
  ride_types_error_description: 'Please refresh and try again. Ride options are temporarily unavailable.',
  ride_types_retry: 'Try again',
  ride_estimate_quote_error_title: 'Unable to load fare estimates',
  ride_estimate_quote_error_description: 'We could not load fare options for this route. Please try again.',
  ride_create_error_description: 'We could not create your ride request right now. Please try again.',
  ride_create_invalid_response_description: 'Your ride request was submitted, but the response was incomplete. Please refresh and check your active rides.',
  ride_estimate_route_error_title: 'Route preview unavailable',
  ride_estimate_route_error_description: 'We could not draw the route right now. Pickup and drop-off are still shown on the map.',
  ride_estimate_retry: 'Try again',
  ride_payment_choose_title: 'Choose payment method',
  ride_payment_add_method: 'Add payment method',
  ride_payment_card_number: 'Card number',
  ride_payment_expiry: 'Expiration date (MM / YY)',
  ride_payment_security_code: 'Security code',
  ride_payment_save: 'Save',
  ride_payment_wallet_balance: '{{currency}} 120.00',
  ride_offer_fare_title: 'Offer your fare',
  ride_offer_fare_field_label: 'You can change the recommended fare',
  ride_offer_fare_recommended: 'Recommended fare: {{fare}}',
  ride_offer_fare_validation: 'Fare cannot be lower than {{fare}}',
  ride_offer_fare_promo_code: 'Promo code',
  ride_offer_fare_current_trip: 'Your current trip',
  ride_offer_fare_tab_standard: 'Standard',
  ride_offer_fare_tab_hourly: 'Hourly',
  ride_offer_fare_next: 'Next',
  ride_offer_fare_hour_single: '{{count}} hour',
  ride_offer_fare_hour_plural: '{{count}} hours',
  ride_offer_fare_miles_included: '{{miles}} miles included',
  ride_offer_fare_promo_coming_soon: 'Promo codes coming soon',
  ride_finding_driver_offer_label: 'Driver offer',
  ride_finding_for_you_title: 'Recommended restaurant',
  ride_finding_for_you_cuisine_fallback: 'Fast food',
  ride_pickup_point_label: 'Pickup point',
  ride_pickup_point_value: 'New Jersey',
  delivery_services_title: 'Get anything delivered',
  delivery_service_food_title: 'Food Delivery',
  delivery_service_food_desc: 'Meals at your doorstep',
  delivery_service_grocery_title: 'Grocery Delivery',
  delivery_service_grocery_desc: 'Fresh items in minutes',
  delivery_service_gift_title: 'Gift Delivery',
  delivery_service_gift_desc: 'Send a surprise',
  delivery_service_medicine_title: 'Medicine Delivery',
  delivery_service_medicine_desc: 'Delivered to your door',
  delivery_service_package_title: 'Package courier',
  delivery_service_package_desc: 'Send parcels quickly',
  details_title: 'Ride Details',
  details_body: 'Ride details and driver information.',
  driver_profile_title: 'Driver Profile',
  driver_profile_button: 'Driver Profile',
  ride_profile_photo_unavailable: 'No profile photo available.',
  driver_profile_label_rides: 'Rides',
  driver_profile_label_joined_us: 'Joined us',
  driver_profile_label_rating: 'Rating',
  driver_profile_tab_reviews: 'Reviews',
  driver_profile_tab_info: 'Driver Information',
  driver_profile_top_reviews: 'Top reviews',
  driver_profile_total_reviews: '{{count}} total',
  driver_profile_reviews_based_on: 'Based on {{count}} reviews',
  driver_profile_view_all_reviews: 'View all {{count}} reviews',
  driver_profile_info_title: 'Driver Information',
  driver_profile_info_vehicle: 'Vehicle Info',
  driver_profile_info_member_since: 'Member Since',
  driver_profile_info_languages: 'Languages',
  driver_profile_info_languages_value: 'English, Spanish',
  driver_profile_info_background_check: 'Background Check',
  driver_profile_info_verified_passed: 'Verified · Passed',
  driver_profile_error_title: 'Failed to load profile',
  driver_profile_error_message: 'Something went wrong. Please try again.',
  driver_profile_retry: 'Retry',
  // Sidebar
  logout: 'Logout',
  // Sidebar menu items
  sidebar_lo_drive: 'Super App',
  sidebar_lo_drive_subtitle: 'Book and manage your regular rides with easy pickup and drop-off options.',
  sidebar_reservations: 'Reservations',
  sidebar_reservations_subtitle: 'View and manage your upcoming and past reservations in one place.',
  sidebar_ride_history: 'Ride & courier history',
  sidebar_ride_history_subtitle: 'Access your completed rides and courier deliveries with full details.',
  sidebar_payment_methods: 'Payment methods',
  sidebar_payment_methods_subtitle: 'Add or Update your saved payment methods.',
  sidebar_wallet: 'Wallet',
  sidebar_wallet_subtitle: 'View and manage your balance, transactions, and payments.',
  sidebar_support: 'Support and feedback',
  sidebar_support_subtitle: 'Reach out for help or give feedback on your experience.',
  sidebar_security: 'Security and settings',
  sidebar_security_subtitle: 'Update your password and change app preferences.',
  sidebar_notifications: 'Notifications',
  sidebar_notifications_subtitle: 'Stay updated with important alerts, ride updates, offers, and account activity.',
  ride_history_load_error: 'Unable to load ride history right now. Please try again.',
  ride_history_empty: 'No ride history yet',
  ride_history_status_completed: 'Completed',
  ride_history_status_cancelled: 'Cancelled',
  ride_history_status_ongoing: 'In progress',
  notifications_section_today: 'Today',
  notifications_section_past: 'Past',
  notifications_show_more: 'Show more',
  notifications_load_error: 'Unable to load notifications right now. Please try again.',
  notifications_empty_title: 'You are all up to date',
  notifications_empty_subtitle: 'No new notifications - come back soon',
  notification_detail_title: 'Notification',
  notification_detail_not_available: 'Notification details are not available.',
  // Profile
  personal_info_title: 'Personal info',
  personal_info_subtitle: 'Update your personal and contact details.',
  profile_photo_title: 'Profile photo',
  profile_photo_description: 'This is the photo you would like others to see.',
  update_photo_button: 'Update photo',
  cancel_button: 'Cancel',
  label_name: 'Full Name',
  label_name_short: 'Name',
  label_phone: 'Phone number',
  label_email: 'Email',
  label_first_name: 'First name',
  label_last_name: 'Last name',
  label_country_code: 'Country code',
  label_phone_number: 'Phone number',
  name_screen_title: 'Name',
  name_screen_description: 'This is the name you would like other people to use when referring you you.',
  phone_screen_title: 'Phone number',
  phone_screen_description: 'You\'ll use this number to get notifications, sign in, and recover your account.',
  phone_screen_subtitle: 'A verification code will be sent to this number',
  phone_update_otp_title: 'Verify OTP',
  phone_update_otp_description: 'Enter OTP sent to {{contact}}',
  phone_update_request_error: 'Failed to request phone update OTP.',
  phone_update_verify_error: 'Invalid or expired OTP.',
  phone_update_resend_success: 'A new verification code has been sent.',
  phone_update_resend_error: 'Failed to resend verification code.',
  phone_update_success: 'Phone number updated successfully.',
  update_button: 'Update',
  back_button: 'Back',
  // Settings
  settings_title: 'Security and settings',
  settings_subtitle: 'Update your password and change app preferences.',
  settings_update_password: 'Update Password',
  settings_current_password_label: 'Current password',
  settings_current_password_placeholder: 'Enter current password',
  settings_new_password_label: 'New password',
  settings_new_password_placeholder: 'Enter new password',
  settings_confirm_password_label: 'Confirm password',
  settings_confirm_password_placeholder: 'Re-enter new password',
  settings_language: 'Language',
  settings_language_en: 'English (US)',
  settings_language_fr: 'French',
  settings_theme: 'Appearance',
  settings_theme_system: 'Use device settings',
  settings_theme_light: 'Light mode',
  settings_theme_dark: 'Dark mode',
  settings_terms: 'Rules and terms',
  settings_privacy: 'Privacy policy',
  settings_terms_conditions: 'Terms and conditions',
  settings_licences: 'Licences',
  settings_lorem_ipsum: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
  settings_terms_conditions_subtitle: 'Please review and accept our legal terms.',
  password_min_length: 'Password must be at least 8 characters',
  password_uppercase: 'Password must contain at least one uppercase letter',
  password_lowercase: 'Password must contain at least one lowercase letter',
  password_number: 'Password must contain at least one number',
  password_special: 'Password must contain at least one special character',
  invalid_password: 'Invalid Password',
  settings_password_update_success: 'Password updated successfully',
  settings_password_update_error: 'Failed to update password. Please try again.',
  success: 'Success',
  error: 'Error',
  ok: 'OK',
  insufficient_wallet_balance: 'You do not have enough balance in your wallet for this ride.',
  wallet_top_up_prompt_title: 'Insufficient wallet balance',
  wallet_top_up_prompt_message: 'You do not have enough balance for this ride. Do you want to top up your wallet now?',
  wallet_top_up_prompt_confirm: 'Top up',
  ride_address_title: 'Your Route',
  ride_address_stop_title: 'Add stop',
  ride_address_close: 'Close',
  ride_address_from_placeholder: 'From',
  ride_address_stop_placeholder: 'Stop',
  ride_address_to_placeholder: 'To',
  ride_address_choose_on_map: 'Choose on map',
  ride_address_confirm_pickup: 'Confirm pick up',
  ride_address_confirm_dropoff: 'Confirm drop off',
  ride_address_map_locating: 'Locating address...',
  ride_address_map_selected_location: 'Selected location',
  ride_address_stop_duplicate_error: 'Stop must be different from pickup, drop-off, and existing stops.',
  ride_address_no_results_title: 'No addresses found',
  ride_address_no_results_description: 'Try a different street, building, or landmark name.',
  ride_address_recent_empty_title: 'No recent addresses yet',
  ride_address_recent_empty_description: 'Your recent pickup and drop-off selections will appear here.',
  ride_schedule_label: 'Schedule ride',
  ride_schedule_set_pickup_time: 'Set pick up time',
  ride_schedule_confirm_button: 'Schedule a ride',
  ride_schedule_remove: 'Remove schedule',
  ride_trip_points_title: 'Trip stops',
  ride_trip_points_origin: 'Origin',
  ride_trip_points_stop: 'Stop {{count}}',
  ride_trip_points_destination: 'Destination',
  ride_trip_points_view_all: 'View trip stops',
  ride_trip_points_more_stops: '+{{count}} more stops',
  ride_trip_points_remove_stop: 'Remove stop {{count}}',
  ride_courier_details_title: 'Add Courier Details',
  ride_courier_comment_label: 'Add comments for courier',
  ride_payment_cash: 'Cash',
  ride_find_button: 'Find a ride',
  ride_find_courier_button: 'Find a courier',
  ride_active_notice_searching_title: 'Ride request in progress',
  ride_active_notice_live_title: 'Active ride in progress',
  ride_active_driver_contact_unavailable: 'Driver contact unavailable',
  ride_active_dialer_unavailable: 'Unable to open dialer',
  ride_active_map_unavailable: 'Unable to open maps on this device.',
  ride_active_map_open_error: 'Unable to open directions right now.',
  ride_active_safety_coming_soon: 'Safety options coming soon',
  ride_active_share_coming_soon: 'Ride sharing coming soon',
  ride_active_emergency_coming_soon: 'Emergency actions coming soon',
  ride_active_waiting_notice: "Please don't be late, it may affect your rating",
  ride_active_waiting_acknowledge: "Ok, I'm coming",
  ride_active_waiting_acknowledge_error_title: 'Unable to notify driver',
  ride_active_waiting_acknowledge_error_message: 'We could not send your confirmation right now. Please try again.',
  ride_active_waiting_missing_ride_error: 'Ride details are not available right now.',
  ride_active_waiting_missing_customer_error: 'Customer details are not available for this ride.',
  ride_active_waiting_missing_driver_error: 'Driver details are not available for this ride.',
  ride_active_vehicle_assigned: 'Vehicle assigned',
  ride_active_driver_fallback: 'Driver',
  ride_active_contact_driver: 'Contact Driver',
  ride_active_contact_courier: 'Contact Courier',
  ride_chat_loading: 'Loading conversation...',
  ride_chat_auto_message: 'How can we help you?',
  ride_chat_auto_time: '8:29 pm',
  ride_chat_quick_reply_here: 'I’m here',
  ride_chat_quick_reply_hello: 'Hello',
  ride_chat_quick_reply_call_arrive: 'Call me when you arrive',
  ride_chat_quick_reply_where: 'Where are you?',
  ride_chat_quick_reply_eta: 'How long will you take?',
  ride_chat_input_placeholder: 'Enter your concern...',
  ride_chat_add_attachment: 'Add attachment',
  ride_chat_send_message: 'Send message',
  ride_chat_send_error_title: 'Unable to send',
  ride_chat_send_error_message: 'We could not send your message right now.',
  ride_chat_missing_session_error: 'Please sign in before sending a message.',
  ride_chat_missing_receiver_error: 'Driver details are not available for this chat yet.',
  ride_chat_attachment_permission_title: 'Permission required',
  ride_chat_attachment_permission_message: 'Allow photo library access to add an attachment.',
  ride_chat_attachment_selected_title: 'Attachment selected',
  ride_chat_attachment_selected_message: '{{fileName}} is ready to attach.',
  ride_chat_call_action: 'Call driver',
  ride_support_chat_title: 'Support',
  ride_support_chat_auto_message: 'How can we help you today?',
  ride_support_chat_input_placeholder: 'Enter your concern...',
  ride_support_chat_send_error_title: 'Unable to send',
  ride_support_chat_send_error_message: 'We could not send your support message right now.',
  ride_support_chat_missing_chat_box_error: 'Support chat is not ready yet. Please try again in a moment.',
  ride_support_chat_quick_reply_help: 'I need help',
  ride_support_chat_quick_reply_issue: 'I have an issue',
  ride_support_chat_quick_reply_payment: 'Payment issue',
  ride_support_chat_quick_reply_driver: 'Driver issue',
  ride_active_safety: 'Safety',
  ride_active_payment: 'Payment',
  ride_active_current_trip: 'Your current trip',
  ride_active_courier_route: 'Your courier route',
  ride_active_share_my_ride: 'Share my ride',
  ride_active_share_courier: 'Share courier',
  ride_active_call_emergency: 'Call emergency',
  ride_feedback_title: 'You have arrived!',
  ride_feedback_courier_title: 'Package delivered!',
  ride_feedback_rate_trip: 'Rate your trip',
  ride_feedback_rate_courier: 'Rate your trip',
  ride_feedback_tip_subtitle: 'You can thank your driver with a tip',
  ride_feedback_tag_good_music: 'Good music',
  ride_feedback_tag_clean_and_neat: 'Clean and neat',
  ride_feedback_tag_careful_driving: 'Careful driving',
  ride_feedback_tag_nice_car: 'Nice car',
  ride_feedback_tag_polite_driver: 'Polite driver',
  ride_feedback_tag_driver_arrived_quickly: 'Driver arrived quickly',
  ride_feedback_placeholder: 'Write your experience here...',
  ride_feedback_submit: 'Submit',
  ride_feedback_submit_success_title: 'Feedback submitted',
  ride_feedback_submit_success_message: 'Thanks for rating your trip.',
  ride_feedback_submit_error_title: 'Unable to submit feedback',
  ride_feedback_submit_error_message: 'We could not submit your rating right now. Please try again.',
  ride_finding_title: 'Finding a driver near you',
  ride_finding_driver_title: 'Finding a driver for you...',
  ride_finding_courier_title: 'Finding a courier for you...',
  ride_finding_accept_driver_offer_title: 'Accept an offer from a driver',
  ride_finding_accept_courier_offer_title: 'Accept an offer from a courier',
  ride_finding_description: 'We are matching your request with the nearest available drivers.',
  ride_finding_timeout_title: 'No driver accepted yet',
  ride_finding_timeout_description: 'Try increasing your fare to improve the chance of a quick match.',
  ride_finding_raise_fare: 'Update fare',
  ride_finding_keep_searching: 'Keep searching',
  ride_finding_cancel: 'Cancel ride',
  ride_finding_cancel_courier: 'Cancel courier',
  // Reservations
  reservations_title: 'Reservations',
  reservations_empty: 'No reservations yet',
  reservation_detail_title: 'Reservation detail',
  reservation_scheduled_for: 'Scheduled for',
  reservation_payment: 'Payment',
  reservation_route: 'Your ride route',
  reservation_status: 'Ride status',
  reservation_things_to_mind: 'Things to keep in mind',
  reservation_wait_time: 'Wait time',
  reservation_cancellation_policy: 'Cancellation policy',
  reservation_cancel_ride: 'Cancel the ride',
  reservation_confirm_cancel_title: 'Are you sure?',
  reservation_confirm_cancel_yes: 'Yes, cancel the ride',
  reservation_confirm_cancel_no: 'No, Continue the ride',
  reservation_cancel_success: 'Ride cancelled',
  reservation_cancel_success_message: 'Your ride has been cancelled successfully.',
  reservation_cancel_error: 'Cancellation failed',
  reservation_cancel_error_message: 'Could not cancel the ride. Please try again.',
  reservation_status_scheduled: 'Scheduled',
  reservation_status_completed: 'Completed',
  reservation_status_cancelled: 'Cancelled by you',
  reservation_status_in_progress: 'In progress',
  reservation_more_options: 'More options',
  reservation_not_found: 'Reservation not found',
  reservation_cash: 'Cash',
  reservation_card: 'Card',
  reservation_driver_details: 'Driver details',
  reservation_rides: 'rides',
  // Safety
  safety_screen_title: 'Safety features',
  safety_action_share_ride: 'Share my ride',
  safety_action_support: 'Support',
  safety_action_emergency_contacts: 'Emergency contacts',
  safety_call_emergency: 'Call',
  safety_driver_verifications: "Driver's verifications",
  safety_verification_license: 'Driver license validated',
  safety_verification_photo: 'Photocontrol completed',
  safety_verification_selfie: 'Selfie with driver license',
  safety_how_protected: "How you're protected",
  safety_protection_proactive: 'Proactive safety support',
  safety_protection_verification: 'Drivers verification',
  safety_protection_privacy: 'Protecting your privacy',
  safety_protection_safe_ride: 'Staying safe on every ride',
  safety_protection_accidents: 'Accidents: Steps to take',
  safety_support_coming_soon: 'Support coming soon',
  safety_emergency_contacts_coming_soon: 'Emergency contacts coming soon',
  // Wallet
  wallet_title: 'Wallet',
  wallet_subtitle: 'View and manage your balance and transactions.',
  wallet_your_balance: 'Your balance',
  wallet_add_funds: 'Add funds',
  wallet_transactions: 'Transactions',
  wallet_tab_all: 'All',
  wallet_tab_money_in: 'Money in',
  wallet_tab_money_out: 'Money out',
  wallet_add_funds_title: 'Add funds',
  wallet_add_funds_subtitle: 'Add a credit or debit card to quickly complete purchases.',
  wallet_offer_your_fare: 'Offer your fare',
  wallet_offer_fare_required: '*',
  wallet_offer_fare_hint: 'Enter an amount between {{currency}} 10.00 and {{currency}} 500',
  wallet_currency_prefix: '{{currency}}',
  wallet_amount_placeholder: '0.00',
  wallet_choose_payment_method: 'Choose payment method',
  wallet_add_payment_method: 'Add payment method',
  wallet_card_number: 'Card number',
  wallet_expiry: 'MM / YY',
  wallet_security_code: 'CVV',
  wallet_save: 'Save',
  wallet_topup_error_title: 'Unable to add funds',
  wallet_topup_error_message: 'We could not start the top-up checkout right now.',
  wallet_topup_checkout_error_message: 'We could not open the Stripe checkout page.',
};

export default en;
