const fr = {
  label: 'Covoiturage',
  description: 'Réservez des trajets en quelques minutes.',
  header_title: 'Covoiturage',
  header_subtitle: 'Atteignez votre destination',
  home_body: 'Réservez un trajet et suivez-le en temps réel.',
  ride_home_offer_label: '10 % de reduction',
  ride_home_offer_title: "L'offre du jour",
  ride_home_offer_percent: '30%',
  ride_home_offer_body: "Profitez d'une reduction sur chaque commande de service ! Valable uniquement aujourd'hui !",
  ride_home_service_ride_title: 'Trajet',
  ride_home_service_ride_subtitle: 'Réservez un trajet !',
  ride_home_service_deliveries_title: 'Livraisons',
  ride_home_service_deliveries_subtitle: 'Nourriture, courses et plus',
  ride_home_service_courier_title: 'Coursier',
  ride_home_service_courier_subtitle: 'Envoyez vos colis en securite',
  ride_home_service_home_visits_title: 'Services a domicile',
  ride_home_service_home_visits_subtitle: 'Reservez des services chez vous',
  ride_options_title: 'Allez partout',
  ride_option_now_title: 'Trajet',
  ride_option_now_desc: 'Trouvez un chauffeur proche',
  ride_option_schedule_title: 'Programmé',
  ride_option_schedule_desc: 'Réservez un départ à l’avance',
  ride_option_rental_title: 'Horaire',
  ride_option_rental_desc: 'Gardez une voiture plusieurs heures',
  ride_option_courier_title: 'Coursier',
  ride_option_courier_desc: 'Envoyez vos colis rapidement',
  ride_option_women_title: 'Trajet Femmes',
  ride_option_ac_title: 'Trajet A/C',
  ride_option_premium_title: 'Premium',
  ride_search_placeholder: 'Où aller & pour combien ?',
  ride_options_empty_destination: 'Recherchez la destination où vous souhaitez aller !',
  ride_current_location: 'Position actuelle',
  ride_types_error_title: 'Impossible de charger les types de trajet',
  ride_types_error_description: 'Veuillez actualiser et réessayer. Les options de trajet sont temporairement indisponibles.',
  ride_types_retry: 'Réessayer',
  ride_estimate_quote_error_title: 'Impossible de charger les estimations tarifaires',
  ride_estimate_quote_error_description: 'Nous n’avons pas pu charger les options tarifaires pour ce trajet. Veuillez réessayer.',
  ride_create_error_description: 'Nous n’avons pas pu creer votre demande de trajet pour le moment. Veuillez reessayer.',
  ride_create_invalid_response_description: 'Votre demande de trajet a ete envoyee, mais la reponse etait incomplete. Veuillez actualiser et verifier vos trajets actifs.',
  ride_estimate_route_error_title: 'Aperçu de l’itinéraire indisponible',
  ride_estimate_route_error_description: 'Nous n’avons pas pu tracer l’itinéraire pour le moment. Les points de départ et d’arrivée restent visibles sur la carte.',
  ride_estimate_retry: 'Réessayer',
  ride_payment_choose_title: 'Choisir un moyen de paiement',
  ride_payment_add_method: 'Ajouter un moyen de paiement',
  ride_payment_card_number: 'Numéro de carte',
  ride_payment_expiry: 'Date d’expiration (MM / AA)',
  ride_payment_security_code: 'Code de sécurité',
  ride_payment_save: 'Enregistrer',
  ride_payment_wallet_balance: '{{currency}} 120.00',
  ride_offer_fare_title: 'Proposez votre tarif',
  ride_offer_fare_field_label: 'Vous pouvez modifier le tarif recommandé',
  ride_offer_fare_recommended: 'Tarif recommandé : {{fare}}',
  ride_offer_fare_validation: 'Le tarif ne peut pas être inférieur à {{fare}}',
  ride_offer_fare_promo_code: 'Code promo',
  ride_offer_fare_current_trip: 'Votre trajet actuel',
  ride_offer_fare_tab_standard: 'Standard',
  ride_offer_fare_tab_hourly: 'Horaire',
  ride_offer_fare_next: 'Suivant',
  ride_offer_fare_hour_single: '{{count}} heure',
  ride_offer_fare_hour_plural: '{{count}} heures',
  ride_offer_fare_miles_included: '{{miles}} miles inclus',
  ride_offer_fare_promo_coming_soon: 'Les codes promo arrivent bientôt',
  ride_finding_driver_offer_label: 'Offre du chauffeur',
  ride_finding_for_you_title: 'Pour vous',
  ride_finding_for_you_cuisine_fallback: 'Restauration rapide',
  ride_pickup_point_label: 'Point de départ',
  ride_pickup_point_value: 'New Jersey',
  delivery_services_title: 'Faites tout livrer',
  delivery_service_food_title: 'Livraison de repas',
  delivery_service_food_desc: 'Des plats à votre porte',
  delivery_service_grocery_title: 'Livraison de courses',
  delivery_service_grocery_desc: 'Produits frais rapidement',
  delivery_service_gift_title: 'Livraison de cadeau',
  delivery_service_gift_desc: 'Envoyez une surprise',
  delivery_service_medicine_title: 'Livraison de médicaments',
  delivery_service_medicine_desc: 'Livré à votre porte',
  delivery_service_package_title: 'Colis express',
  delivery_service_package_desc: 'Envoyez vos colis rapidement',
  details_title: 'Détails du Trajet',
  details_body: 'Détails du trajet et informations sur le conducteur.',
  driver_profile_title: 'Profil du Conducteur',
  driver_profile_button: 'Profil du Conducteur',
  ride_profile_photo_unavailable: 'Aucune photo de profil disponible.',
  driver_profile_label_rides: 'Trajets',
  driver_profile_label_joined_us: 'Inscrit',
  driver_profile_label_rating: 'Note',
  driver_profile_tab_reviews: 'Avis',
  driver_profile_tab_info: 'Informations chauffeur',
  driver_profile_top_reviews: 'Meilleurs avis',
  driver_profile_total_reviews: '{{count}} au total',
  driver_profile_reviews_based_on: 'Basé sur {{count}} avis',
  driver_profile_view_all_reviews: 'Voir les {{count}} avis',
  driver_profile_info_title: 'Informations chauffeur',
  driver_profile_info_vehicle: 'Infos véhicule',
  driver_profile_info_member_since: 'Membre depuis',
  driver_profile_info_languages: 'Langues',
  driver_profile_info_languages_value: 'Anglais, Espagnol',
  driver_profile_info_background_check: 'Vérification des antécédents',
  driver_profile_info_verified_passed: 'Vérifié · Validé',
  driver_profile_error_title: 'Impossible de charger le profil',
  driver_profile_error_message: 'Une erreur est survenue. Veuillez réessayer.',
  driver_profile_retry: 'Réessayer',
  // Sidebar
  logout: 'Déconnexion',
  // Sidebar menu items
  sidebar_lo_drive: 'Super App',
  sidebar_lo_drive_subtitle: 'Réservez et gérez vos trajets réguliers avec des options de prise en charge et de dépôt faciles.',
  sidebar_reservations: 'Réservations',
  sidebar_reservations_subtitle: 'Consultez et gérez vos réservations à venir et passées en un seul endroit.',
  sidebar_ride_history: 'Historique des trajets et livraisons',
  sidebar_ride_history_subtitle: 'Accédez à vos trajets et livraisons terminés avec tous les détails.',
  sidebar_payment_methods: 'Moyens de paiement',
  sidebar_payment_methods_subtitle: 'Ajoutez ou mettez à jour vos moyens de paiement enregistrés.',
  sidebar_wallet: 'Portefeuille',
  sidebar_wallet_subtitle: 'Consultez et gérez votre solde, transactions et paiements.',
  sidebar_support: 'Support et feedback',
  sidebar_support_subtitle: 'Contactez-nous pour obtenir de l\'aide ou donnez votre avis sur votre expérience.',
  sidebar_security: 'Sécurité et paramètres',
  sidebar_security_subtitle: 'Mettez à jour votre mot de passe et modifiez les préférences de l\'application.',
  sidebar_notifications: 'Notifications',
  sidebar_notifications_subtitle: 'Restez informé des alertes importantes, mises à jour des trajets, offres et activité du compte.',
  ride_history_load_error: 'Impossible de charger l\'historique des trajets pour le moment. Veuillez réessayer.',
  ride_history_empty: 'Aucun historique de trajet pour le moment',
  ride_history_status_completed: 'Terminé',
  ride_history_status_cancelled: 'Annulé',
  ride_history_status_ongoing: 'En cours',
  notifications_section_today: "Aujourd'hui",
  notifications_section_past: 'Passées',
  notifications_show_more: 'Afficher plus',
  notifications_load_error: 'Impossible de charger les notifications pour le moment. Veuillez réessayer.',
  notifications_empty_title: 'Vous êtes à jour',
  notifications_empty_subtitle: 'Aucune nouvelle notification pour le moment',
  notification_detail_title: 'Notification',
  notification_detail_not_available: 'Les détails de la notification ne sont pas disponibles.',
  // Profile
  personal_info_title: 'Informations personnelles',
  personal_info_subtitle: 'Mettez à jour vos coordonnées personnelles et de contact.',
  profile_photo_title: 'Photo de profil',
  profile_photo_description: 'Ceci est la photo que vous souhaitez que les autres voient.',
  update_photo_button: 'Mettre à jour la photo',
  cancel_button: 'Annuler',
  label_name: 'Nom',
  label_name_short: 'Nom',
  label_phone: 'Numéro de téléphone',
  label_email: 'Email',
  label_first_name: 'Prénom',
  label_last_name: 'Nom',
  label_country_code: 'Indicatif pays',
  label_phone_number: 'Numéro de téléphone',
  name_screen_title: 'Nom',
  name_screen_description: 'Ceci est le nom que vous souhaitez que les autres personnes utilisent pour vous désigner.',
  phone_screen_title: 'Numéro de téléphone',
  phone_screen_description: 'Vous utiliserez ce numéro pour recevoir des notifications, vous connecter et récupérer votre compte.',
  phone_screen_subtitle: 'Un code de vérification sera envoyé à ce numéro',
  phone_update_otp_title: 'Vérifier OTP',
  phone_update_otp_description: 'Entrez le code OTP envoyé à {{contact}}',
  phone_update_request_error: "Échec de la demande du code OTP de mise à jour du téléphone.",
  phone_update_verify_error: 'Code OTP invalide ou expiré.',
  phone_update_resend_success: 'Un nouveau code de vérification a été envoyé.',
  phone_update_resend_error: "Échec du renvoi du code de vérification.",
  phone_update_success: 'Numéro de téléphone mis à jour avec succès.',
  update_button: 'Mettre à jour',
  back_button: 'Retour',
  error: 'Erreur',
  ok: 'OK',
  insufficient_wallet_balance: 'Vous n’avez pas assez de solde dans votre portefeuille pour ce trajet.',
  wallet_top_up_prompt_title: 'Solde du portefeuille insuffisant',
  wallet_top_up_prompt_message: 'Vous n’avez pas assez de solde pour ce trajet. Voulez-vous recharger votre portefeuille maintenant ?',
  wallet_top_up_prompt_confirm: 'Recharger',
  // Settings
  settings_title: 'Sécurité et paramètres',
  settings_subtitle: 'Mettez à jour votre mot de passe et modifiez les préférences.',
  settings_update_password: 'Mettre à jour le mot de passe',
  settings_current_password_label: 'Mot de passe actuel',
  settings_current_password_placeholder: 'Entrez le mot de passe actuel',
  settings_new_password_label: 'Nouveau mot de passe',
  settings_new_password_placeholder: 'Entrez le nouveau mot de passe',
  settings_confirm_password_label: 'Confirmer le mot de passe',
  settings_confirm_password_placeholder: 'Ressaisissez le nouveau mot de passe',
  settings_language: 'Langue',
  settings_language_en: 'Anglais (US)',
  settings_language_fr: 'Français',
  settings_theme: 'Apparence',
  settings_theme_system: 'Utiliser les paramètres de l\'appareil',
  settings_theme_light: 'Mode clair',
  settings_theme_dark: 'Mode sombre',
  settings_terms: 'Règles et conditions',
  settings_privacy: 'Politique de confidentialité',
  settings_terms_conditions: 'Termes et conditions',
  settings_licences: 'Licences',
  settings_lorem_ipsum: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
  settings_terms_conditions_subtitle: 'Veuillez consulter et accepter nos termes et conditions légaux.',
  ride_address_title: 'Votre trajet',
  ride_address_stop_title: 'Ajouter un arrêt',
  ride_address_close: 'Fermer',
  ride_address_from_placeholder: 'De',
  ride_address_stop_placeholder: 'Arrêt',
  ride_address_to_placeholder: 'À',
  ride_address_choose_on_map: 'Choisir sur la carte',
  ride_address_confirm_pickup: 'Confirmer le point de départ',
  ride_address_confirm_dropoff: 'Confirmer la destination',
  ride_address_map_locating: 'Recherche de l’adresse...',
  ride_address_map_selected_location: 'Emplacement sélectionné',
  ride_address_stop_duplicate_error: 'L’arrêt doit être différent du point de départ, de la destination et des autres arrêts.',
  ride_address_no_results_title: 'Aucune adresse trouvée',
  ride_address_no_results_description: 'Essayez un autre nom de rue, d’immeuble ou de lieu.',
  ride_address_recent_empty_title: 'Aucune adresse récente',
  ride_address_recent_empty_description: 'Vos derniers points de départ et destinations apparaîtront ici.',
  ride_schedule_label: 'Programmer le trajet',
  ride_schedule_set_pickup_time: 'Définir l’heure de départ',
  ride_schedule_confirm_button: 'Programmer un trajet',
  ride_schedule_remove: 'Retirer la programmation',
  ride_trip_points_title: 'Arrets du trajet',
  ride_trip_points_origin: 'Depart',
  ride_trip_points_stop: 'Arret {{count}}',
  ride_trip_points_destination: 'Destination',
  ride_trip_points_view_all: 'Voir les arrets du trajet',
  ride_trip_points_more_stops: '+{{count}} arrets de plus',
  ride_trip_points_remove_stop: 'Supprimer l’arret {{count}}',
  ride_courier_details_title: 'Ajouter les details du coursier',
  ride_courier_comment_label: 'Ajouter des commentaires pour le coursier',
  ride_payment_cash: 'Espèces',
  ride_find_button: 'Trouver un trajet',
  ride_find_courier_button: 'Trouver un coursier',
  ride_active_notice_searching_title: 'Demande de trajet en cours',
  ride_active_notice_live_title: 'Trajet actif en cours',
  ride_active_driver_contact_unavailable: 'Contact du chauffeur indisponible',
  ride_active_dialer_unavailable: 'Impossible d’ouvrir le composeur',
  ride_active_map_unavailable: 'Impossible d’ouvrir l’application de cartographie sur cet appareil.',
  ride_active_map_open_error: 'Impossible d’ouvrir l’itinéraire pour le moment.',
  ride_active_safety_coming_soon: 'Les options de sécurité arrivent bientôt',
  ride_active_share_coming_soon: 'Le partage du trajet arrive bientôt',
  ride_active_emergency_coming_soon: 'Les actions d’urgence arrivent bientôt',
  ride_active_waiting_notice: 'Merci de ne pas être en retard, cela peut affecter votre note',
  ride_active_waiting_acknowledge: 'D’accord, j’arrive',
  ride_active_waiting_acknowledge_error_title: 'Impossible de prévenir le chauffeur',
  ride_active_waiting_acknowledge_error_message: 'Nous n’avons pas pu envoyer votre confirmation pour le moment. Veuillez réessayer.',
  ride_active_waiting_missing_ride_error: 'Les détails du trajet ne sont pas disponibles pour le moment.',
  ride_active_waiting_missing_customer_error: 'Les informations du client ne sont pas disponibles pour ce trajet.',
  ride_active_waiting_missing_driver_error: 'Les informations du chauffeur ne sont pas disponibles pour ce trajet.',
  ride_active_vehicle_assigned: 'Véhicule attribué',
  ride_active_driver_fallback: 'Chauffeur',
  ride_active_contact_driver: 'Contacter le chauffeur',
  ride_active_contact_courier: 'Contacter le coursier',
  ride_chat_loading: 'Chargement de la conversation...',
  ride_chat_auto_message: 'Comment pouvons-nous vous aider ?\n[Message automatique]',
  ride_chat_auto_time: '20:29',
  ride_chat_quick_reply_here: 'Je suis là',
  ride_chat_quick_reply_hello: 'Bonjour',
  ride_chat_quick_reply_call_arrive: 'Appelez-moi quand vous arrivez',
  ride_chat_quick_reply_where: 'Où êtes-vous ?',
  ride_chat_quick_reply_eta: 'Dans combien de temps ?',
  ride_chat_input_placeholder: 'Entrez votre message...',
  ride_chat_add_attachment: 'Ajouter une pièce jointe',
  ride_chat_send_message: 'Envoyer le message',
  ride_chat_send_error_title: 'Envoi impossible',
  ride_chat_send_error_message: 'Nous n’avons pas pu envoyer votre message pour le moment.',
  ride_chat_missing_session_error: 'Connectez-vous avant d’envoyer un message.',
  ride_chat_missing_receiver_error: 'Les informations du chauffeur ne sont pas encore disponibles pour ce chat.',
  ride_chat_attachment_permission_title: 'Autorisation requise',
  ride_chat_attachment_permission_message: 'Veuillez autoriser l’accès à la photothèque pour ajouter une pièce jointe.',
  ride_chat_attachment_selected_title: 'Pièce jointe sélectionnée',
  ride_chat_attachment_selected_message: '{{fileName}} est prêt à être joint.',
  ride_chat_call_action: 'Appeler le chauffeur',
  ride_support_chat_title: 'Assistance',
  ride_support_chat_auto_message: 'Comment pouvons-nous vous aider aujourd’hui ?',
  ride_support_chat_input_placeholder: 'Entrez votre demande...',
  ride_support_chat_send_error_title: 'Envoi impossible',
  ride_support_chat_send_error_message: 'Nous n’avons pas pu envoyer votre message d’assistance pour le moment.',
  ride_support_chat_missing_chat_box_error: 'Le chat d’assistance n’est pas encore prêt. Veuillez réessayer dans un instant.',
  ride_support_chat_quick_reply_help: 'J’ai besoin d’aide',
  ride_support_chat_quick_reply_issue: 'J’ai un problème',
  ride_support_chat_quick_reply_payment: 'Problème de paiement',
  ride_support_chat_quick_reply_driver: 'Problème avec le chauffeur',
  ride_active_safety: 'Sécurité',
  ride_active_payment: 'Paiement',
  ride_active_current_trip: 'Votre trajet actuel',
  ride_active_courier_route: 'Votre itineraire de coursier',
  ride_active_share_my_ride: 'Partager mon trajet',
  ride_active_share_courier: 'Partager le coursier',
  ride_active_call_emergency: 'Appeler les urgences',
  ride_feedback_title: 'Vous êtes arrivé !',
  ride_feedback_courier_title: 'Colis livre !',
  ride_feedback_rate_trip: 'Notez votre trajet',
  ride_feedback_rate_courier: 'Notez votre trajet',
  ride_feedback_tip_subtitle: 'Vous pouvez remercier votre chauffeur avec un pourboire',
  ride_feedback_tag_good_music: 'Bonne musique',
  ride_feedback_tag_clean_and_neat: 'Propre et soigné',
  ride_feedback_tag_careful_driving: 'Conduite prudente',
  ride_feedback_tag_nice_car: 'Belle voiture',
  ride_feedback_tag_polite_driver: 'Chauffeur poli',
  ride_feedback_tag_driver_arrived_quickly: 'Chauffeur arrivé rapidement',
  ride_feedback_placeholder: 'Écrivez votre expérience ici...',
  ride_feedback_submit: 'Soumettre',
  ride_feedback_submit_success_title: 'Avis envoyé',
  ride_feedback_submit_success_message: 'Merci d’avoir évalué votre trajet.',
  ride_feedback_submit_error_title: 'Envoi impossible',
  ride_feedback_submit_error_message: 'Nous n’avons pas pu envoyer votre avis pour le moment. Veuillez réessayer.',
  // Reservations
  reservations_title: 'Réservations',
  reservations_empty: 'Aucune réservation',
  reservation_detail_title: 'Détails de la réservation',
  reservation_scheduled_for: 'Programmé pour',
  reservation_payment: 'Paiement',
  reservation_route: 'Votre itinéraire',
  reservation_status: 'Statut du trajet',
  reservation_things_to_mind: 'Choses à garder à l\'esprit',
  reservation_wait_time: 'Temps d\'attente',
  reservation_cancellation_policy: 'Politique d\'annulation',
  reservation_cancel_ride: 'Annuler le trajet',
  reservation_confirm_cancel_title: 'Êtes-vous sûr ?',
  reservation_confirm_cancel_yes: 'Oui, annuler le trajet',
  reservation_confirm_cancel_no: 'Non, continuer le trajet',
  reservation_cancel_success: 'Trajet annulé',
  reservation_cancel_success_message: 'Votre trajet a été annulé avec succès.',
  reservation_cancel_error: 'Échec de l\'annulation',
  reservation_cancel_error_message: 'Impossible d\'annuler le trajet. Veuillez réessayer.',
  reservation_status_scheduled: 'Programmé',
  reservation_status_completed: 'Terminé',
  reservation_status_cancelled: 'Annulé par vos soins',
  reservation_status_in_progress: 'En cours',
  reservation_more_options: 'Plus d\'options',
  reservation_not_found: 'Réservation non trouvée',
  reservation_cash: 'Espèces',
  reservation_card: 'Carte',
  reservation_driver_details: 'Détails du conducteur',
  reservation_rides: 'trajets',
  ride_finding_title: 'Recherche d’un chauffeur près de vous',
  ride_finding_driver_title: 'Recherche d’un chauffeur pour vous...',
  ride_finding_courier_title: 'Recherche d’un coursier pour vous...',
  ride_finding_accept_driver_offer_title: 'Accepter une offre d’un chauffeur',
  ride_finding_accept_courier_offer_title: 'Accepter une offre d’un coursier',
  ride_finding_description: 'Nous associons votre demande aux chauffeurs disponibles les plus proches.',
  ride_finding_timeout_title: 'Aucun chauffeur n’a encore accepté',
  ride_finding_timeout_description: 'Essayez d’augmenter votre tarif pour améliorer les chances d’une réponse rapide.',
  ride_finding_raise_fare: 'Augmenter le tarif',
  ride_finding_keep_searching: 'Continuer la recherche',
  ride_finding_cancel: 'Annuler le trajet',
  ride_finding_cancel_courier: 'Annuler le coursier',
  // Safety
  safety_screen_title: 'Fonctionnalités de sécurité',
  safety_action_share_ride: 'Partager mon trajet',
  safety_action_support: 'Assistance',
  safety_action_emergency_contacts: 'Contacts d\'urgence',
  safety_call_emergency: 'Appeler le 15',
  safety_driver_verifications: 'Vérifications du chauffeur',
  safety_verification_license: 'Permis de conduire validé',
  safety_verification_photo: 'Contrôle photo effectué',
  safety_verification_selfie: 'Selfie avec permis de conduire',
  safety_how_protected: 'Comment vous êtes protégé',
  safety_protection_proactive: 'Sécurité proactive',
  safety_protection_verification: 'Vérification des chauffeurs',
  safety_protection_privacy: 'Protection de votre vie privée',
  safety_protection_safe_ride: 'Sécurité à chaque trajet',
  safety_protection_accidents: 'Accidents : Que faire',
  safety_support_coming_soon: 'Assistance bientôt disponible',
  safety_emergency_contacts_coming_soon: 'Contacts d\'urgence bientôt disponibles',
  // Wallet
  wallet_title: 'Portefeuille',
  wallet_subtitle: 'Consultez et gérez votre solde et vos transactions.',
  wallet_your_balance: 'Votre solde',
  wallet_add_funds: 'Ajouter des fonds',
  wallet_transactions: 'Transactions',
  wallet_tab_all: 'Tout',
  wallet_tab_money_in: 'Entrées',
  wallet_tab_money_out: 'Sorties',
  wallet_add_funds_title: 'Ajouter des fonds',
  wallet_add_funds_subtitle: 'Ajoutez une carte de crédit ou de débit pour effectuer rapidement des achats.',
  wallet_offer_your_fare: 'Proposez votre tarif',
  wallet_offer_fare_required: '*',
  wallet_offer_fare_hint: 'Entrez un montant entre {{currency}} 10,00 et {{currency}} 500',
  wallet_currency_prefix: '{{currency}}',
  wallet_amount_placeholder: '0,00',
  wallet_choose_payment_method: 'Choisir le mode de paiement',
  wallet_add_payment_method: 'Ajouter un mode de paiement',
  wallet_card_number: 'Numéro de carte',
  wallet_expiry: 'MM / AA',
  wallet_security_code: 'CVV',
  wallet_save: 'Enregistrer',
  wallet_topup_error_title: 'Impossible d’ajouter des fonds',
  wallet_topup_error_message: 'Nous n’avons pas pu lancer le paiement de recharge pour le moment.',
  wallet_topup_checkout_error_message: 'Nous n’avons pas pu ouvrir la page de paiement Stripe.',
};

export default fr;
